<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/includes/loan-agreements.php';
requireAdmin();
$db = db(); loanAgreementEnsureSchema($db);
$loanId = (int)($_GET['loan_id'] ?? 0); $tab = (string)($_GET['tab'] ?? 'overview');
$previewEmployee = $tab === 'agreement' && ($_GET['preview'] ?? '') === 'employee';
$stmt = $db->prepare("SELECT l.*,CONCAT(e.first_name,' ',e.last_name) emp_name,e.first_name,e.last_name,e.emp_number,e.job_title,a.id agreement_id,a.version_no,a.status agreement_status,a.agreement_date,a.first_deduction_date,a.instalment_amount,a.number_of_instalments,a.final_instalment_amount,a.purpose,a.legal_notes,a.snapshot_json,a.document_hash,a.sent_at,a.employee_signed_at,a.owner_signed_at,a.fully_signed_at FROM loans l JOIN employees e ON e.id=l.employee_id LEFT JOIN loan_agreements a ON a.loan_id=l.id AND a.version_no=(SELECT MAX(x.version_no) FROM loan_agreements x WHERE x.loan_id=l.id) WHERE l.id=?");
$stmt->execute([$loanId]); $loan = $stmt->fetch(); if (!$loan) { http_response_code(404); exit('Loan not found.'); }
$schedule = $signatures = $events = [];
if ($loan['agreement_id']) {
    $q=$db->prepare("SELECT * FROM loan_repayment_schedule WHERE agreement_id=? ORDER BY instalment_no"); $q->execute([$loan['agreement_id']]); $schedule=$q->fetchAll();
    $q=$db->prepare("SELECT signer_role,signer_name,signed_at FROM loan_agreement_signatures WHERE agreement_id=? ORDER BY signed_at"); $q->execute([$loan['agreement_id']]); $signatures=$q->fetchAll();
    $q=$db->prepare("SELECT * FROM loan_agreement_events WHERE loan_id=? ORDER BY created_at DESC"); $q->execute([$loanId]); $events=$q->fetchAll();
}
$agreementData = $loan['agreement_id'] ? loanAgreementDocumentData($loan, $loan, $loan) : [];
$currentPage = 'loans.php';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Loan · <?=htmlspecialchars($loan['emp_name'])?></title><link rel="stylesheet" href="includes/styles.css"><link rel="stylesheet" href="includes/loan-agreement-document.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"></head><body>
<?php include __DIR__ . '/includes/sidebar.php'; ?>
<main class="main"><div class="topbar"><div><a href="loans.php" class="loan-back">← Loans &amp; Advances</a><div class="topbar-title"><?=htmlspecialchars($loan['emp_name'])?> · N$ <?=number_format((float)$loan['amount'],2)?></div></div></div><div class="content">
<?php if (($_GET['msg']??'')==='created'): ?><div class="toast"><i class="fa-solid fa-check"></i> Loan agreement draft created.</div><?php endif; ?>
<?php if (($_GET['msg']??'')==='sent'): ?><div class="toast"><i class="fa-solid fa-paper-plane"></i> Agreement sent to the employee for signature.</div><?php endif; ?>
<section class="card loan-summary"><div><small>Employee</small><b><?=htmlspecialchars($loan['emp_name'])?></b><span><?=htmlspecialchars($loan['emp_number'])?> · <?=htmlspecialchars($loan['job_title']??'Employee')?></span></div><div><small>Balance</small><b>N$ <?=number_format((float)$loan['balance'],2)?></b></div><div><small>Agreement</small><b><?=htmlspecialchars(loanAgreementStatusLabel((string)($loan['agreement_status']??'legacy_active')))?></b><span><?=$loan['agreement_id']?'LA-'.$loanId.'-V'.(int)$loan['version_no']:'Not created'?></span></div></section>
<nav class="loan-detail-tabs"><a class="<?=$tab==='overview'?'active':''?>" href="?loan_id=<?=$loanId?>&amp;tab=overview">Overview</a><a class="<?=$tab==='schedule'?'active':''?>" href="?loan_id=<?=$loanId?>&amp;tab=schedule">Repayment Schedule</a><a class="<?=$tab==='agreement'?'active':''?>" href="?loan_id=<?=$loanId?>&amp;tab=agreement">Loan Agreement</a><a class="<?=$tab==='history'?'active':''?>" href="?loan_id=<?=$loanId?>&amp;tab=history">History</a></nav>
<?php if ($tab==='overview'): ?><section class="card loan-pane"><h2>Loan overview</h2><dl><div><dt>Original amount</dt><dd>N$ <?=number_format((float)$loan['amount'],2)?></dd></div><div><dt>Monthly deduction</dt><dd>N$ <?=number_format((float)$loan['repayment_amount'],2)?></dd></div><div><dt>Loan date</dt><dd><?=date('d F Y',strtotime($loan['loan_date']))?></dd></div><div><dt>Status</dt><dd><?=htmlspecialchars(ucfirst($loan['status']))?></dd></div></dl></section><?php endif; ?>
<?php if ($tab==='schedule'): ?><section class="card loan-pane"><h2>Repayment schedule</h2><?php if (!$schedule): ?><p>No signed-agreement schedule is available yet.</p><?php else: ?><div class="hr-table-viewport"><table><thead><tr><th>Month</th><th>Expected</th><th>Actual</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php $balance=(float)$loan['amount']; foreach($schedule as $row): $balance=max(0,$balance-(float)$row['paid_amount']); ?><tr><td><?=date('F Y',strtotime($row['due_date']))?></td><td>N$ <?=number_format((float)$row['amount'],2)?></td><td>N$ <?=number_format((float)$row['paid_amount'],2)?></td><td>N$ <?=number_format($balance,2)?></td><td><?=htmlspecialchars(ucwords(str_replace('_',' ',$row['status'])))?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><?php endif; ?>
<?php if ($tab==='agreement'): ?>
<section class="card loan-pane loan-agreement-page"><div class="loan-pane-head"><div><span class="loan-eyebrow">Employee loan agreement</span><h2><?=htmlspecialchars(loanAgreementStatusLabel((string)($loan['agreement_status']??'legacy_active')))?></h2></div><?php if(!$loan['agreement_id']||$loan['agreement_status']==='legacy_active'): ?><form method="post" action="loans.php"><input type="hidden" name="loan_agreement_csrf" value="<?=htmlspecialchars(loanAgreementCsrfToken())?>"><input type="hidden" name="action" value="create_agreement"><input type="hidden" name="loan_id" value="<?=$loanId?>"><button class="btn btn-primary"><i class="fa-solid fa-file-circle-plus"></i> Create Loan Agreement</button></form><?php endif; ?></div>
<?php if ($loan['agreement_id']&&$loan['agreement_status']!=='legacy_active'): ?>
<?php if($previewEmployee): ?><div class="loan-preview-banner"><span><strong>Employee preview</strong> · This is the exact agreement the employee will see. No permissions or session have changed.</span><a href="?loan_id=<?=$loanId?>&amp;tab=agreement">Exit preview</a></div><?php endif; ?>
<?php loanAgreementRenderDocument($agreementData,$signatures,['document_hash'=>$loan['document_hash']]); ?>
<?php if(!$previewEmployee): ?><div class="loan-actions"><a class="btn btn-secondary" href="?loan_id=<?=$loanId?>&amp;tab=agreement&amp;preview=employee"><i class="fa-solid fa-eye"></i> Preview as Employee</a><?php if($loan['agreement_status']==='draft'): ?><button class="btn btn-primary" type="button" onclick="openSendAgreement()"><i class="fa-solid fa-paper-plane"></i> Send to Employee</button><?php endif; ?><?php if($loan['agreement_status']==='employee_signed'): ?><button class="btn btn-primary" type="button" onclick="openOwnerSignature()"><i class="fa-solid fa-signature"></i> Sign as Employer</button><?php endif; ?><?php if($loan['agreement_status']==='fully_signed'): ?><a class="btn btn-secondary" href="loan-agreement.php?loan_id=<?=$loanId?>&amp;download=1"><i class="fa-solid fa-file-pdf"></i> Download signed PDF</a><?php endif; ?></div><?php endif; ?>
<?php else: ?><p>This legacy loan has no digital agreement. Create a versioned draft to begin the controlled signature workflow.</p><?php endif; ?></section>
<?php if($loan['agreement_status']==='draft'): ?><div class="overlay" id="sendAgreementModal"><div class="modal" style="max-width:480px"><div class="modal-header"><div class="modal-title"><i class="fa-solid fa-paper-plane"></i> Send Loan Agreement</div><button class="modal-close" type="button" onclick="closeSendAgreement()"><i class="fa-solid fa-xmark"></i></button></div><form method="post" action="loans.php"><input type="hidden" name="loan_agreement_csrf" value="<?=htmlspecialchars(loanAgreementCsrfToken())?>"><input type="hidden" name="action" value="send_agreement"><input type="hidden" name="agreement_id" value="<?=$loan['agreement_id']?>"><input type="hidden" name="return_to_agreement" value="1"><div class="modal-body"><p>You are about to send <strong><?=htmlspecialchars($agreementData['agreement_number'])?></strong> to:</p><h3><?=htmlspecialchars($agreementData['employee_name'])?></h3><dl class="send-confirm-terms"><div><dt>Loan</dt><dd>N$ <?=number_format((float)$agreementData['loan_amount'],2)?></dd></div><div><dt>Instalment</dt><dd>N$ <?=number_format((float)$agreementData['instalment_amount'],2)?> × <?=(int)$agreementData['number_of_instalments']?> months</dd></div><div><dt>First deduction</dt><dd><?=loanAgreementFormatDate((string)$agreementData['first_deduction_date'])?></dd></div></dl><p>The employee will be asked to review and electronically sign this exact agreement version. Sending freezes this version and generates its verification hash.</p></div><div class="modal-footer"><button class="btn btn-secondary" type="button" onclick="closeSendAgreement()">Cancel</button><button class="btn btn-primary" type="submit"><i class="fa-solid fa-paper-plane"></i> Send Agreement</button></div></form></div></div><?php endif; ?>
<?php if($loan['agreement_status']==='employee_signed'): ?><div class="overlay" id="ownerSignatureModal"><div class="modal" style="max-width:460px"><div class="modal-header"><div class="modal-title"><i class="fa-solid fa-signature"></i> Employer Signature</div><button class="modal-close" type="button" onclick="closeOwnerSignature()"><i class="fa-solid fa-xmark"></i></button></div><form method="post" action="loans.php"><input type="hidden" name="loan_agreement_csrf" value="<?=htmlspecialchars(loanAgreementCsrfToken())?>"><input type="hidden" name="action" value="owner_sign"><input type="hidden" name="agreement_id" value="<?=$loan['agreement_id']?>"><div class="modal-body"><p>You are signing the exact frozen agreement <strong><?=htmlspecialchars($agreementData['agreement_number'])?></strong> already signed by <?=htmlspecialchars($agreementData['employee_name'])?>.</p><div class="form-group"><label class="form-label">Authorised Representative Full Name</label><input class="form-input" name="owner_name" required></div><div class="form-group"><label class="form-label">Electronic Signature</label><input class="form-input loan-owner-signature" name="owner_signature" required placeholder="Type your signature"></div></div><div class="modal-footer"><button class="btn btn-secondary" type="button" onclick="closeOwnerSignature()">Cancel</button><button class="btn btn-primary" type="submit"><i class="fa-solid fa-lock"></i> Sign Agreement</button></div></form></div></div><?php endif; ?>
<?php endif; ?>
<?php if($tab==='history'): ?><section class="card loan-pane"><h2>Agreement history</h2><?php if(!$events): ?><p>No agreement events recorded.</p><?php else: ?><ul class="loan-history"><?php foreach($events as $event): ?><li><b><?=htmlspecialchars(ucwords(str_replace('_',' ',$event['event_type'])))?></b><span><?=date('d M Y H:i',strtotime($event['created_at']))?></span></li><?php endforeach; ?></ul><?php endif; ?></section><?php endif; ?>
</div></main>
<style>.loan-back{display:block;margin-bottom:4px;color:var(--green);font-size:11px;text-decoration:none}.loan-summary{display:grid;grid-template-columns:2fr 1fr 1fr;gap:16px;padding:18px}.loan-summary div{display:grid;gap:3px}.loan-summary small,.loan-pane dt{font-size:9px;text-transform:uppercase;font-weight:700;color:var(--text-mid)}.loan-summary b{font-size:14px}.loan-summary span{font-size:10px;color:var(--text-mid)}.loan-detail-tabs{display:flex;gap:5px;margin:14px 0}.loan-detail-tabs a{padding:9px 12px;color:var(--text-mid);font-size:11px;font-weight:700;text-decoration:none;border-bottom:2px solid transparent}.loan-detail-tabs a.active{color:var(--green);border-color:var(--green)}.loan-pane{padding:20px}.loan-pane h2{font-size:17px;margin-bottom:14px}.loan-pane h3{font-size:13px;margin:18px 0 8px}.loan-pane p,.loan-pane li{font-size:12px;line-height:1.55}.loan-pane>dl{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.loan-pane>dl div{padding:11px;background:var(--bg);border-radius:8px}.loan-pane dd{font-size:12px;font-weight:700;margin-top:3px}.loan-pane-head{display:flex;justify-content:space-between;gap:15px}.loan-eyebrow{font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--green)}.loan-actions{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:8px;max-width:960px;margin:16px auto 0}.loan-history{list-style:none;padding:0}.loan-history li{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border)}.send-confirm-terms{display:grid;gap:0;margin:14px 0}.send-confirm-terms div{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border)}.send-confirm-terms dd{font-size:11px}.loan-agreement-page{background:transparent;border:0;box-shadow:none;padding:0}.loan-agreement-page>.loan-pane-head{max-width:960px;margin:0 auto 12px}@media(max-width:700px){.loan-summary,.loan-pane>dl{grid-template-columns:1fr}.loan-detail-tabs{overflow-x:auto}.loan-pane-head{flex-direction:column}.loan-actions{justify-content:stretch}.loan-actions .btn{justify-content:center;flex:1}}</style>
<script>function openSendAgreement(){document.getElementById('sendAgreementModal').classList.add('open')}function closeSendAgreement(){document.getElementById('sendAgreementModal').classList.remove('open')}function openOwnerSignature(){document.getElementById('ownerSignatureModal').classList.add('open')}function closeOwnerSignature(){document.getElementById('ownerSignatureModal').classList.remove('open')}document.querySelectorAll('.overlay').forEach(function(o){o.addEventListener('click',function(e){if(e.target===o)o.classList.remove('open')})});</script></body></html>
