<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/policy-system.php'; requireLogin();
$db=db();hrPolicyEnsureSchema($db);$u=currentUser();$v=hrPolicyVersion($db,(int)($_GET['id']??0));$isAdmin=$u['role']!=='employee';$eid=hrPolicyEmployeeId($u);
if(!$v||(!$isAdmin&&!in_array($v['status'],array('published','superseded'),true))){http_response_code(404);exit('Policy not found.');}
$ack=null;$legal='';if(!$isAdmin){$legal=hrPolicyLegalName($db,$eid);$s=$db->prepare("INSERT INTO hr_policy_acknowledgements (policy_id,version_id,employee_id,user_id,opened_at) VALUES (?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE opened_at=COALESCE(opened_at,NOW())");$s->execute(array($v['policy_id'],$v['id'],$eid,$u['id']));$s=$db->prepare("SELECT * FROM hr_policy_acknowledgements WHERE version_id=? AND employee_id=?");$s->execute(array($v['id'],$eid));$ack=$s->fetch(PDO::FETCH_ASSOC);hrPolicyAudit($db,'policy_opened',$v['policy_id'],$v['id'],$eid);}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($v['title'])?></title><link rel="stylesheet" href="includes/policies.css"></head><body class="viewer-body"><main class="viewer"><a href="policies.php" class="back-link">← Documents & Policies</a><header><span class="eyebrow">Company policy</span><h1><?=htmlspecialchars($v['title'])?></h1><div class="viewer-meta"><span>Version <b><?=htmlspecialchars($v['version_number'])?></b></span><span>Created <b><?=date('j F Y',strtotime($v['created_date']))?></b></span><span>Effective <b><?=date('j F Y',strtotime($v['effective_date']))?></b></span><span>Deadline <b><?=date('j F Y',strtotime($v['acknowledgement_deadline']))?></b></span></div><p class="status-pill"><?=htmlspecialchars(hrPolicyDisplayStatus($v))?></p></header>
<section class="document-panel"><div><h2>Authoritative policy document</h2><p>The original approved file is preserved unchanged. Open or download it to read the complete policy.</p><p class="hash">SHA-256 <?=htmlspecialchars($v['document_hash'])?></p></div><a class="primary-btn" target="_blank" href="policy-file.php?id=<?=$v['id']?>">Open original document</a></section>
<?php if(!$isAdmin&&$v['acknowledgement_required']):?><section class="ack-section" id="acknowledgement"><h2>Employee acknowledgement</h2><div class="ack-copy"><?=nl2br(htmlspecialchars(hrPolicyAcknowledgementText()))?></div><div class="question-box"><b>I have a question about this policy</b><p>Contact management before signing if any part of the policy is unclear.</p></div>
<?php if($ack&&!empty($ack['signed_at'])):?><div class="signed-state"><h3>Policy signed & acknowledged</h3><p>Signed by <?=htmlspecialchars($ack['legal_name'])?> on <?=date('j M Y H:i',strtotime($ack['signed_at']))?>.</p><a class="primary-btn" href="policy-receipt.php?id=<?=$ack['id']?>">View acknowledgement receipt</a></div>
<?php else:?><form method="post" action="policy-action.php" id="signatureForm"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="sign"><input type="hidden" name="version_id" value="<?=$v['id']?>"><input type="hidden" name="signature_method" id="signatureMethod" value="drawn"><input type="hidden" name="signature_data" id="signatureData">
<label class="check"><input type="checkbox" name="ack_confirm" required> I confirm that I have read and understood this policy.</label><label>Full Legal Name *<input name="legal_name" required value="<?=htmlspecialchars($legal)?>"></label>
<div class="signature-tabs"><button type="button" class="active" data-method="drawn">Draw signature</button><button type="button" data-method="typed">Typed fallback</button></div><div data-pane="drawn"><canvas id="signaturePad" width="720" height="220"></canvas><button type="button" class="secondary-btn" id="clearSignature">Clear signature</button></div><div data-pane="typed" hidden><p>By typing my full legal name below and selecting Sign & Acknowledge, I intend this electronic action to serve as my signature and acknowledgement of this policy.</p><label>Typed signature *<input name="typed_signature" value=""></label></div><button class="primary-btn" id="signButton" type="submit">Review & confirm signature</button></form><?php endif;?></section><?php endif;?></main>
<?php if(!$isAdmin&&!($ack&&!empty($ack['signed_at']))):?><script>window.hrPolicy={csrf:<?=json_encode(hrPolicyCsrf())?>,versionId:<?=$v['id']?>};</script><script src="includes/policy-signature.js"></script><?php endif;?></body></html>
