<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/policy-system.php'; requireLogin();
$db=db();hrPolicyEnsureSchema($db);$u=currentUser();$v=hrPolicyVersion($db,(int)($_GET['id']??0));$isAdmin=$u['role']!=='employee';$preview=$isAdmin&&($_GET['preview']??'')==='employee';$eid=hrPolicyEmployeeId($u);
if(!$v||(!$isAdmin&&!in_array($v['status'],array('published','superseded'),true))){http_response_code(404);exit('Policy not found.');}
if(empty($v['digital_html'])){http_response_code(409);exit('This policy version does not yet have a verified digital document.');}
$ack=null;$legal='';
if($preview){$legal='Preview Employee';}
elseif(!$isAdmin){
    $legal=hrPolicyLegalName($db,$eid);
    $s=$db->prepare("INSERT INTO hr_policy_acknowledgements (policy_id,version_id,employee_id,user_id,opened_at,last_opened_at) VALUES (?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE opened_at=COALESCE(opened_at,NOW()),last_opened_at=NOW()");
    $s->execute(array($v['policy_id'],$v['id'],$eid,$u['id']));
    $s=$db->prepare("SELECT * FROM hr_policy_acknowledgements WHERE version_id=? AND employee_id=?");$s->execute(array($v['id'],$eid));$ack=$s->fetch(PDO::FETCH_ASSOC);
    if(empty($ack['last_opened_at'])||strtotime($ack['last_opened_at'])<time()-300)hrPolicyAudit($db,'policy_opened',$v['policy_id'],$v['id'],$eid);
}
$toc=array();if(preg_match_all('/<h2 id="([^"]+)">(.*?)<\/h2>/s',$v['digital_html'],$matches,PREG_SET_ORDER))foreach($matches as $m)$toc[]=array('id'=>$m[1],'text'=>html_entity_decode(strip_tags($m[2]),ENT_QUOTES,'UTF-8'));
$signed=$ack&&!empty($ack['signed_at']);$readPercent=$ack?(float)$ack['reading_percent']:0;$employeeExperience=!$isAdmin||$preview;
$displayHtml=$v['digital_html'];if($employeeExperience)$displayHtml=preg_replace('/<h2[^>]*>\s*Portal acknowledgement record\s*<\/h2>.*$/is','',$displayHtml);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars($v['title'])?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="includes/policies.css?v=20260811-wide"></head>
<body class="viewer-body <?=$preview?'policy-preview-body':''?>"><div class="reading-progress" aria-hidden="true"><span id="readingProgressBar" style="width:<?=$readPercent?>%"></span></div><main class="viewer" id="policyViewer"><a href="policies.php" class="back-link" data-policy-exit>← Documents &amp; Policies</a>
<?php if($preview):?><div class="preview-banner"><b>PREVIEW MODE</b><span>Employee experience simulation — no acknowledgement record will be saved.</span></div><?php endif;?>
<header class="digital-policy-header"><span class="eyebrow">Company policy</span><h1><?=htmlspecialchars($v['title'])?></h1><div class="viewer-meta"><span>Version <b><?=htmlspecialchars($v['version_number'])?></b></span><span>Created <b><?=date('j F Y',strtotime($v['created_date']))?></b></span><span>Effective <b><?=date('j F Y',strtotime($v['effective_date']))?></b></span><span>Next review <b><?=htmlspecialchars($v['next_review']?:'Not scheduled')?></b></span></div><p class="status-pill"><?=htmlspecialchars(hrPolicyDisplayStatus($v))?></p><?php if($isAdmin&&!$preview):?><a class="secondary-btn preview-employee-btn" href="policy-view.php?id=<?=$v['id']?>&amp;preview=employee">Preview Employee Experience</a><?php endif;?><?php if($signed):?><div class="signed-policy-notice"><b>Signed &amp; Acknowledged</b><span><?=date('j M Y H:i',strtotime($ack['signed_at']))?></span><a href="policy-receipt.php?id=<?=$ack['id']?>">View acknowledgement</a><button type="button" onclick="window.print()">Print policy</button></div><?php endif;?></header>
<?php if($isAdmin&&!$preview):?><section class="document-panel compact"><div><h2>Original approved document</h2><p>The source file is preserved unchanged and linked to this digital version.</p><p class="hash">Document SHA-256 <?=htmlspecialchars($v['document_hash'])?><br>Digital SHA-256 <?=htmlspecialchars($v['digital_hash'])?></p></div><a class="secondary-btn" target="_blank" href="policy-file.php?id=<?=$v['id']?>">Open original</a></section><?php endif;?>
<div class="digital-policy-layout"><details class="policy-toc" aria-label="Policy contents" open><summary>Contents</summary><nav><?php foreach($toc as $item):?><a href="#<?=htmlspecialchars($item['id'])?>"><?=htmlspecialchars($item['text'])?></a><?php endforeach;?></nav></details><article class="policy-digital-content" id="policyDocument"><?=$displayHtml?></article></div>
<?php if($employeeExperience&&$v['acknowledgement_required']):?><section class="ack-section" id="acknowledgement"><h2>EMPLOYEE ACKNOWLEDGEMENT</h2><div class="ack-copy"><?=nl2br(htmlspecialchars(hrPolicyAcknowledgementText()))?></div><div class="ack-identity"><span><b>Employee</b><?=htmlspecialchars($legal)?></span><span><b>Employee ID</b><?=$preview?'PREVIEW':htmlspecialchars((string)$eid)?></span><span><b>Policy Version</b><?=htmlspecialchars($v['version_number'])?></span><span><b>Opened At</b><?=$preview?date('j F Y H:i'):htmlspecialchars(date('j F Y H:i',strtotime($ack['opened_at'])))?></span><span><b>Status</b><?=$signed?'Signed & Acknowledged':'Pending'?></span></div><div class="question-box"><b>I have a question about this policy</b><p>Contact management before signing if any part of the policy is unclear.</p></div>
<?php if($signed):?><div class="signed-state"><h3>SIGNED &amp; ACKNOWLEDGED</h3><p>Signed by <?=htmlspecialchars($ack['legal_name'])?> on <?=date('j M Y H:i',strtotime($ack['signed_at']))?>.</p><a class="primary-btn" href="policy-receipt.php?id=<?=$ack['id']?>">View Acknowledgement</a></div>
<?php else:?><div class="signature-gate" id="signatureGate">Continue reading to the acknowledgement section to enable signing.</div><form method="post" action="policy-action.php" id="signatureForm" aria-disabled="true"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="sign"><input type="hidden" name="ajax" value="1"><input type="hidden" name="version_id" value="<?=$v['id']?>"><input type="hidden" name="signature_method" id="signatureMethod" value="drawn"><input type="hidden" name="signature_data" id="signatureData"><fieldset id="signatureFields" disabled><label class="check"><input type="checkbox" name="ack_confirm" required> I confirm that I have read and understood this policy.</label><label>Full Legal Name *<input name="legal_name" required value="<?=htmlspecialchars($legal)?>"></label><div class="signature-tabs"><button type="button" class="active" data-method="drawn">Draw signature</button><button type="button" data-method="typed">Typed fallback</button></div><div data-pane="drawn"><canvas id="signaturePad" width="720" height="220"></canvas><button type="button" class="secondary-btn" id="clearSignature">Clear Signature</button></div><div data-pane="typed" hidden><p>By typing my full legal name below and selecting Sign &amp; Acknowledge, I intend this electronic action to serve as my signature and acknowledgement of this policy.</p><label>Typed signature *<input name="typed_signature" value=""></label></div><button class="primary-btn" id="signButton" type="submit">Sign &amp; Acknowledge</button></fieldset></form><div class="notice error" id="signatureError" hidden></div><?php endif;?></section><?php endif;?></main>
<?php if($employeeExperience&&!$signed):?><dialog id="exitWarning" class="exit-warning"><h2>POLICY ACKNOWLEDGEMENT NOT COMPLETED</h2><p>You have not yet completed your acknowledgement of:</p><p><b><?=htmlspecialchars($v['title'])?><br>Version <?=htmlspecialchars($v['version_number'])?></b></p><p>Acknowledgement is mandatory and must be completed by: <b><?=date('j F Y',strtotime($v['acknowledgement_deadline']))?></b></p><div><button class="primary-btn" type="button" data-continue-reading>Continue Reading</button><a class="secondary-btn" href="policies.php" data-leave-policy>Leave for Now</a></div></dialog><script>window.hrPolicy={csrf:<?=json_encode(hrPolicyCsrf())?>,versionId:<?=$v['id']?>,readingPercent:<?=$readPercent?>,readingPosition:<?=($ack?(int)$ack['reading_position']:0)?>,signed:false,preview:<?=$preview?'true':'false'?>};</script><script src="includes/policy-signature.js?v=20260811-preview"></script><?php endif;?>
<script>if(matchMedia('(max-width:850px)').matches)document.querySelector('.policy-toc')?.removeAttribute('open');</script></body></html>
