<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/policy-system.php'; requireLogin();
$db=db(); hrPolicyEnsureSchema($db); $user=currentUser(); $isAdmin=$user['role']!=='employee'; $eid=hrPolicyEmployeeId($user);
$success=$_SESSION['policy_success']??''; $error=$_SESSION['policy_error']??''; unset($_SESSION['policy_success'],$_SESSION['policy_error']);
$versions=$db->query("SELECT v.*,p.policy_type,p.current_version_id FROM hr_policy_versions v JOIN hr_policies p ON p.id=v.policy_id ".($isAdmin?'':"WHERE v.status IN ('published','superseded')")." ORDER BY v.policy_id,v.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);
$policies=$db->query("SELECT p.*,v.version_number FROM hr_policies p LEFT JOIN hr_policy_versions v ON v.id=p.current_version_id ORDER BY p.title")->fetchAll(PDO::FETCH_ASSOC);
$acks=array(); if(!$isAdmin&&$eid){$s=$db->prepare("SELECT * FROM hr_policy_acknowledgements WHERE employee_id=?");$s->execute(array($eid));foreach($s as $a)$acks[$a['version_id']]=$a;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Documents & Policies — Hambelela HR</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><link rel="stylesheet" href="includes/styles.css"><link rel="stylesheet" href="includes/policies.css"></head>
<body class="policy-shell"><?php include __DIR__.'/includes/'.($isAdmin?'sidebar.php':'emp-sidebar.php'); ?>
<main class="policy-main"><header class="policy-page-head"><div><span class="eyebrow">HR Portal</span><h1>Documents & Policies</h1><p>Company policies, version history and secure acknowledgements.</p></div><?php if($isAdmin):?><button class="primary-btn" type="button" data-open-draft><i class="fa-solid fa-plus"></i> Add policy version</button><?php endif;?></header>
<?php if($success):?><div class="notice success"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="notice error"><?=htmlspecialchars($error)?></div><?php endif;?>
<section><div class="section-head"><div><span class="eyebrow">Company Policies</span><h2>Policy library</h2></div></div>
<div class="policy-grid">
<?php if(!$versions):?><div class="empty-state"><i class="fa-solid fa-book-open"></i><h3>No policies published yet</h3><p>Published company policies will appear here.</p></div><?php endif;?>
<?php foreach($versions as $v): $ack=$acks[$v['id']]??null; $status=$isAdmin?hrPolicyDisplayStatus($v):hrPolicyAckStatus($v,$ack); ?>
<article class="policy-card"><div class="policy-card-top"><span class="type-pill"><?=htmlspecialchars(ucwords(str_replace('_',' ',$v['policy_type'])))?></span><span class="status-pill <?=strpos(strtolower($status),'overdue')!==false?'danger':''?>"><?=htmlspecialchars($status)?></span></div>
<h3><?=htmlspecialchars($v['title'])?></h3><div class="policy-meta"><span><b>Version</b> <?=htmlspecialchars($v['version_number'])?></span><span><b>Created</b> <?=date('j M Y',strtotime($v['created_date']))?></span><span><b>Effective</b> <?=date('j M Y',strtotime($v['effective_date']))?></span><span><b>Acknowledgement</b> <?=$v['acknowledgement_required']?'Required':'Not required'?></span></div>
<div class="policy-actions"><a class="primary-btn" href="policy-view.php?id=<?=$v['id']?>"><i class="fa-solid fa-book-open"></i> <?=(!$isAdmin&&$ack&&!empty($ack['signed_at']))?'View policy':'Read policy'?></a><?php if(!$isAdmin&&$ack&&!empty($ack['signed_at'])):?><a class="secondary-btn" href="policy-receipt.php?id=<?=$ack['id']?>">Receipt</a><?php endif;?><?php if($isAdmin&&$v['status']==='draft'):?><form method="post" action="policy-action.php" onsubmit="return confirm('Publish <?=htmlspecialchars(addslashes($v['title'].' Version '.$v['version_number']))?>? This will require applicable employees to read and digitally sign this version.')"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="publish"><input type="hidden" name="version_id" value="<?=$v['id']?>"><button class="primary-btn">Publish</button></form><?php endif;?><?php if($isAdmin&&$v['status']==='published'):?><a class="secondary-btn" href="policy-acknowledgements.php?id=<?=$v['id']?>">View acknowledgements</a><?php endif;?></div>
<?php if($isAdmin):?><div class="hash">SHA-256 <?=htmlspecialchars($v['document_hash'])?></div><?php endif;?></article><?php endforeach;?></div></section>
<?php if($isAdmin):?><dialog id="draftDialog" class="policy-dialog"><form method="post" action="policy-action.php" enctype="multipart/form-data"><button class="dialog-close" type="button" data-close-draft aria-label="Close">×</button><span class="eyebrow">New immutable version</span><h2>Add policy version</h2><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="save_draft">
<label>Existing policy (leave blank for new)<select name="policy_id"><option value="">New policy</option><?php foreach($policies as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['title'])?></option><?php endforeach;?></select></label>
<div class="form-grid"><label>Title *<input name="title" required value="Employee Handbook & HR Policy"></label><label>Policy type<select name="policy_type"><option value="general_document">General Document</option><option value="company_policy">Company Policy</option><option selected value="mandatory_policy">Mandatory Policy</option></select></label><label>Version *<input name="version_number" required value="1.0"></label><label>Created date *<input type="date" name="created_date" required value="2026-08-11"></label><label>Effective date *<input type="date" name="effective_date" required value="2026-09-01"></label><label>Acknowledgement deadline<input type="date" name="acknowledgement_deadline" value="2026-08-31"></label><label>Next formal review<input name="next_review" value="August 2027"></label><label>Approved DOCX file *<input type="file" name="policy_file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required><small>The DOCX is preserved unchanged and converted into the immutable digital viewer.</small></label></div>
<label class="check"><input type="checkbox" name="acknowledgement_required" value="1" checked> Employee acknowledgement required</label><label>Changes summary<textarea name="changes_summary">Initial Employee Handbook & HR Policy</textarea></label><button class="primary-btn" type="submit">Save draft</button></form></dialog><?php endif;?></main>
<script>const d=document.getElementById('draftDialog');document.querySelector('[data-open-draft]')?.addEventListener('click',()=>d.showModal());document.querySelector('[data-close-draft]')?.addEventListener('click',()=>d.close());</script></body></html>
