<?php
require_once __DIR__.'/config.php';require_once __DIR__.'/includes/policy-system.php';requireLogin();
$u=currentUser();$user=$u;if($u['role']==='employee'){http_response_code(403);exit('Owner or administrator access is required.');}
$db=db();hrPolicyEnsureSchema($db);$v=hrPolicyVersion($db,(int)($_GET['id']??0));
if(!$v){http_response_code(404);exit('Version not found.');}
$current=$v['status']==='published' && (int)$v['current_version_id']===(int)$v['id'] && $v['acknowledgement_required'];
$deliveryWarning=''; // Overview reads records; employee login/polling and explicit owner actions deliver assignments.
$s=$db->prepare("SELECT e.id,e.emp_number,e.start_date,e.job_title,TRIM(CONCAT(e.first_name,' ',e.last_name)) employee_name,
    s.id assignment_id,s.assigned_at,s.acknowledgement_deadline individual_deadline,COALESCE(s.acknowledgement_deadline,v.acknowledgement_deadline) deadline,
    a.id ack_id,a.opened_at,a.last_opened_at,a.reading_percent,a.reached_end_at,a.signed_at,
    pn.created_at notification_sent_at,pn.delivered_at notification_delivered_at
    FROM employees e JOIN hr_policy_versions v ON v.id=?
    LEFT JOIN hr_policy_assignments s ON s.employee_id=e.id AND s.version_id=v.id
    LEFT JOIN hr_policy_acknowledgements a ON a.employee_id=e.id AND a.version_id=v.id
    LEFT JOIN hr_policy_notifications pn ON pn.user_id=s.user_id AND pn.version_id=v.id
    WHERE e.status='active' ORDER BY e.first_name,e.last_name");
$s->execute(array($v['id']));$rows=$s->fetchAll(PDO::FETCH_ASSOC);$signed=0;$opened=0;$overdue=0;
foreach($rows as &$r){$r['status']=hrPolicyAssignmentStatus($r);if($r['signed_at'])$signed++;elseif($r['opened_at'])$opened++;if($r['status']==='Overdue')$overdue++;}unset($r);
$required=count($rows);$filter=(string)($_GET['filter']??'all');if(!in_array($filter,array('all','pending','opened','signed','overdue'),true))$filter='all';
$success=$_SESSION['policy_assignment_success']??'';$error=$_SESSION['policy_assignment_error']??'';unset($_SESSION['policy_assignment_success'],$_SESSION['policy_assignment_error']);
$settings=hrPolicySettings($db);
function policyOverviewEscape($value):string{return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
function policyOverviewDate($value):string{return $value?date('j M Y H:i',strtotime($value)):'—';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Policy acknowledgements</title><link rel="stylesheet" href="includes/styles.css"><link rel="stylesheet" href="includes/policies.css?v=<?=filemtime(__DIR__.'/includes/policies.css')?>">
<style>@font-face{font-family:Jost;src:url('/assets/fonts/jost-variable.woff2') format('woff2');font-display:swap}.policy-main,.policy-main button,.policy-main input{font-family:Jost,sans-serif}.policy-filters{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}.policy-filters a{padding:10px 16px;min-height:44px;box-sizing:border-box;border:1px solid #d3dac6;border-radius:8px;color:#52633f;text-decoration:none}.policy-filters a[aria-current=page]{background:#59694a;color:white}.assignment-form{display:flex;flex-wrap:wrap;gap:8px;align-items:end;min-width:230px;margin:12px 0}.assignment-form label{display:grid;gap:4px;font-size:12px}.assignment-form input,.assignment-form button{min-height:44px;border:1px solid #cbd2bf;border-radius:8px;padding:8px 12px;font-size:14px}.assignment-form button{background:#59694a;color:white;cursor:pointer}.assignment-form input{color:#303c27;background:white}.policy-main details summary{cursor:pointer;min-height:44px;display:flex;align-items:center;color:#52633f}.policy-main details dl{display:grid;grid-template-columns:auto 1fr;gap:8px;font-size:13px}.policy-main details dd{margin:0}.policy-main table td{vertical-align:top}.policy-main small{display:block}.policy-flash{padding:14px;background:#eef1e7;border:1px solid #d3dac6;border-radius:10px;margin:12px 0}.policy-flash.error{background:#fff1ed}.policy-main a:focus-visible,.policy-main button:focus-visible,.policy-main summary:focus-visible{outline:3px solid #adba8d;outline-offset:3px}@media(max-width:700px){.policy-main{min-width:0}.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.policy-main .table-wrap{max-width:100%;overflow-x:auto}.policy-main table{min-width:0}.policy-main thead{display:none}.policy-main tbody,.policy-main tr,.policy-main td{display:block;width:auto}.policy-main tr{border-bottom:1px solid #d3dac6;padding:12px}.policy-main td{border:0;padding:6px 0}.policy-main td[data-label]:before{content:attr(data-label) ': ';font-weight:600}.assignment-form{min-width:0}.assignment-form label{width:100%}.assignment-form input{box-sizing:border-box;width:100%}}</style>
</head><body class="policy-shell"><?php include __DIR__.'/includes/sidebar.php';?><main class="policy-main"><a href="policies.php" class="back-link">← Documents &amp; Policies</a>
<header class="policy-page-head"><div><span class="eyebrow">Employee Acknowledgements · Version <?=policyOverviewEscape($v['version_number'])?></span><h1><?=policyOverviewEscape($v['title'])?></h1><p><?=$current?'Current published policy':'Policy version history'?> · Individual deadlines and acknowledgement progress</p></div></header>
<?php if($success):?><p class="policy-flash" role="status"><?=policyOverviewEscape($success)?></p><?php endif;?>
<?php if($error||$deliveryWarning):?><p class="policy-flash error" role="alert"><?=policyOverviewEscape($error?:$deliveryWarning)?></p><?php endif;?>
<div class="summary-grid"><div><span>Employees required</span><b><?=$required?></b></div><div><span>Signed</span><b><?=$signed?></b></div><div><span>Pending</span><b><?=$required-$signed?></b></div><div><span>Opened · unsigned</span><b><?=$opened?></b></div><div><span>Overdue</span><b><?=$overdue?></b></div><div><span>Acknowledgement rate</span><b><?=$required?number_format($signed/$required*100,1):'0.0'?>%</b></div></div>
<nav class="policy-filters" aria-label="Acknowledgement filters"><?php foreach(array('all'=>'All','pending'=>'Pending','opened'=>'Opened','signed'=>'Signed','overdue'=>'Overdue') as $key=>$label):?><a href="?id=<?=(int)$v['id']?>&amp;filter=<?=$key?>" <?=$filter===$key?'aria-current="page"':''?>><?=$label?></a><?php endforeach;?></nav>
<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Assignment</th><th>Individual deadline</th><th>Status</th><th>Details &amp; actions</th></tr></thead><tbody>
<?php foreach($rows as $r):
if(($filter==='signed'&&!$r['signed_at'])||($filter==='pending'&&$r['signed_at'])||($filter==='opened'&&(!$r['opened_at']||$r['signed_at']))||($filter==='overdue'&&$r['status']!=='Overdue'))continue;
$date=$r['individual_deadline']?:hrPolicyDefaultDeadline((string)$r['start_date'],date('Y-m-d'),(int)$settings['policy_ack_days']);
?><tr data-employee="<?=(int)$r['id']?>"><td><b><?=policyOverviewEscape($r['employee_name'])?></b><small><?=policyOverviewEscape($r['emp_number'])?> · <?=policyOverviewEscape($r['job_title'])?></small></td><td data-label="Assigned"><?=policyOverviewDate($r['assigned_at'])?></td><td data-label="Deadline"><?=$r['assignment_id']||$r['signed_at']?($r['deadline']?date('j F Y',strtotime($r['deadline'])):'Not set'):'Select Date'?></td><td><span class="status-pill"><?=policyOverviewEscape($r['status'])?></span></td><td>
<details><summary>Acknowledgement details</summary><dl><dt>Assignment date</dt><dd><?=policyOverviewDate($r['assigned_at'])?></dd><dt>Opened</dt><dd><?=policyOverviewDate($r['opened_at'])?></dd><dt>Last opened</dt><dd><?=policyOverviewDate($r['last_opened_at'])?></dd><dt>Reading progress</dt><dd><?=number_format((float)$r['reading_percent'],0)?>%</dd><dt>Signed</dt><dd><?=policyOverviewDate($r['signed_at'])?></dd><dt>HR notification</dt><dd><?=policyOverviewDate($r['notification_sent_at'])?></dd></dl>
<?php $history=$db->prepare("SELECT action,details,created_at FROM hr_policy_audit WHERE subject_employee_id=? AND version_id=? AND action IN ('policy_assigned','policy_deadline_changed','policy_reminder_requested') ORDER BY id DESC LIMIT 10");$history->execute(array($r['id'],$v['id']));foreach($history->fetchAll(PDO::FETCH_ASSOC) as $event):$detail=json_decode($event['details']?:'{}',true);?><p><small><?=policyOverviewDate($event['created_at'])?> · <?=policyOverviewEscape(str_replace('_',' ',$event['action']))?><?=isset($detail['deadline'])?' · '.policyOverviewEscape($detail['previous_deadline']??'Not set').' → '.policyOverviewEscape($detail['deadline']):''?></small></p><?php endforeach;?></details>
<?php if($r['signed_at']&&$r['ack_id']):?><a href="policy-receipt.php?id=<?=(int)$r['ack_id']?>">View signed receipt</a>
<?php elseif($current):?><form method="post" action="policy-action.php" class="assignment-form"><input type="hidden" name="csrf" value="<?=policyOverviewEscape(hrPolicyCsrf())?>"><input type="hidden" name="version_id" value="<?=(int)$v['id']?>"><input type="hidden" name="employee_id" value="<?=(int)$r['id']?>"><label>Acknowledgement deadline<input type="date" name="deadline" required value="<?=policyOverviewEscape($date)?>"></label><button type="submit" name="action" value="assign_notify">Assign &amp; Notify</button><?php if($r['assignment_id']):?><button type="submit" name="action" value="change_deadline">Save Deadline</button><button type="submit" name="action" value="resend_reminder">Resend Reminder</button><?php endif;?></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></main></body></html>
