<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/policy-system.php'; requireLogin();
$db=db();hrPolicyEnsureSchema($db);$u=currentUser();$v=hrPolicyVersion($db,(int)($_GET['id']??0));$isAdmin=$u['role']!=='employee';$eid=hrPolicyEmployeeId($u);
if(!$v||(!$isAdmin&&!in_array($v['status'],array('published','superseded'),true))){http_response_code(404);exit('Policy not found.');}
if(empty($v['digital_html'])){http_response_code(409);exit('This policy version does not yet have a verified digital document.');}
$ack=null;$legal='';if(!$isAdmin){$legal=hrPolicyLegalName($db,$eid);$s=$db->prepare("INSERT INTO hr_policy_acknowledgements (policy_id,version_id,employee_id,user_id,opened_at,last_opened_at) VALUES (?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE opened_at=COALESCE(opened_at,NOW()),last_opened_at=NOW()");$s->execute(array($v['policy_id'],$v['id'],$eid,$u['id']));$s=$db->prepare("SELECT * FROM hr_policy_acknowledgements WHERE version_id=? AND employee_id=?");$s->execute(array($v['id'],$eid));$ack=$s->fetch(PDO::FETCH_ASSOC);if(empty($ack['last_opened_at'])||strtotime($ack['last_opened_at'])<time()-300)hrPolicyAudit($db,'policy_opened',$v['policy_id'],$v['id'],$eid);}
$toc=array();if(preg_match_all('/<h2 id="([^"]+)">(.*?)<\/h2>/s',$v['digital_html'],$matches,PREG_SET_ORDER))foreach($matches as $m)$toc[]=array('id'=>$m[1],'text'=>html_entity_decode(strip_tags($m[2]),ENT_QUOTES,'UTF-8'));
$signed=$ack&&!empty($ack['signed_at']);$readPercent=$ack?(float)$ack['reading_percent']:0;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars($v['title'])?></title><link rel="stylesheet" href="includes/policies.css"></head><body class="viewer-body"><div class="reading-progress" aria-hidden="true"><span id="readingProgressBar" style="width:<?=$readPercent?>%"></span></div><main class="viewer" id="policyViewer"><a href="policies.php" class="back-link" data-policy-exit>← Documents & Policies</a><header class="digital-policy-header"><span class="eyebrow">Company policy</span><h1><?=htmlspecialchars($v['title'])?></h1><div class="viewer-meta"><span>Version <b><?=htmlspecialchars($v['version_number'])?></b></span><span>Created <b><?=date('j F Y',strtotime($v['created_date']))?></b></span><span>Effective <b><?=date('j F Y',strtotime($v['effective_date']))?></b></span><span>Next review <b><?=htmlspecialchars($v['next_review']?:'Not scheduled')?></b></span></div><p class="status-pill"><?=htmlspecialchars(hrPolicyDisplayStatus($v))?></p><?php if($signed):?><div class="signed-policy-notice"><b>Signed & Acknowledged</b><span><?=date('j M Y H:i',strtotime($ack['signed_at']))?></span><a href="policy-receipt.php?id=<?=$ack['id']?>">View acknowledgement</a><button type="button" onclick="window.print()">Print policy</button></div><?php endif;?></header>
<section class="document-panel compact"><div><h2>Original approved document</h2><p>The source file is preserved unchanged and linked to this digital version.</p><p class="hash">Document SHA-256 <?=htmlspecialchars($v['document_hash'])?><br>Digital SHA-256 <?=htmlspecialchars($v['digital_hash'])?></p></div><a class="secondary-btn" target="_blank" href="policy-file.php?id=<?=$v['id']?>">Open original</a></section>
<div class="digital-policy-layout"><aside class="policy-toc" aria-label="Policy contents"><b>Contents</b><nav><?php foreach($toc as $item):?><a href="#<?=htmlspecialchars($item['id'])?>"><?=htmlspecialchars($item['text'])?></a><?php endforeach;?></nav></aside><article class="policy-digital-content" id="policyDocument"><?=$v['digital_html']?></article></div>
<?php if(!$isAdmin&&$v['acknowledgement_required']):?><section class="ack-section" id="acknowledgement"><h2>Employee acknowledgement</h2><div class="ack-copy"><?=nl2br(htmlspecialchars(hrPolicyAcknowledgementText()))?></div><div class="question-box"><b>I have a question about this policy</b><p>Contact management before signing if any part of the policy is unclear.</p></div>
<?php if($signed):?><div class="signed-state"><h3>Policy signed & acknowledged</h3><p>Signed by <?=htmlspecialchars($ack['legal_name'])?> on <?=date('j M Y H:i',strtotime($ack['signed_at']))?>.</p><a class="primary-btn" href="policy-receipt.php?id=<?=$ack['id']?>">View acknowledgement receipt</a></div>
<?php else:?><div class="signature-gate" id="signatureGate">Continue reading to the acknowledgement section to enable signing.</div><form method="post" action="policy-action.php" id="signatureForm" aria-disabled="true"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="sign"><input type="hidden" name="ajax" value="1"><input type="hidden" name="version_id" value="<?=$v['id']?>"><input type="hidden" name="signature_method" id="signatureMethod" value="drawn"><input type="hidden" name="signature_data" id="signatureData">
<fieldset id="signatureFields" disabled><label class="check"><input type="checkbox" name="ack_confirm" required> I confirm that I have read and understood this policy.</label><label>Full Legal Name *<input name="legal_name" required value="<?=htmlspecialchars($legal)?>"></label><div class="signature-tabs"><button type="button" class="active" data-method="drawn">Draw signature</button><button type="button" data-method="typed">Typed fallback</button></div><div data-pane="drawn"><canvas id="signaturePad" width="720" height="220"></canvas><button type="button" class="secondary-btn" id="clearSignature">Clear signature</button></div><div data-pane="typed" hidden><p>By typing my full legal name below and selecting Sign & Acknowledge, I intend this electronic action to serve as my signature and acknowledgement of this policy.</p><label>Typed signature *<input name="typed_signature" value=""></label></div><button class="primary-btn" id="signButton" type="submit">Review & confirm signature</button></fieldset></form><div class="notice error" id="signatureError" hidden></div><?php endif;?></section><?php endif;?></main>
<?php if(!$isAdmin&&!$signed):?><dialog id="exitWarning" class="exit-warning"><h2>Your acknowledgement is not complete</h2><p>Your reading progress has been saved. You will continue to receive a reminder until this policy is signed.</p><div><button class="primary-btn" type="button" data-continue-reading>Continue Reading</button><a class="secondary-btn" href="policies.php" data-leave-policy>Leave for Now</a></div></dialog><script>window.hrPolicy={csrf:<?=json_encode(hrPolicyCsrf())?>,versionId:<?=$v['id']?>,readingPercent:<?=$readPercent?>,readingPosition:<?=($ack?(int)$ack['reading_position']:0)?>,signed:false};</script><script src="includes/policy-signature.js"></script><?php endif;?></body></html>
