<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/includes/policy-system.php'; requireLogin();
$db=db(); hrPolicyEnsureSchema($db); $user=currentUser(); $isAdmin=$user['role']!=='employee'; $eid=hrPolicyEmployeeId($user);
$success=$_SESSION['policy_success']??''; $error=$_SESSION['policy_error']??''; unset($_SESSION['policy_success'],$_SESSION['policy_error']);
$versions=$db->query("SELECT v.*,p.policy_type,p.current_version_id FROM hr_policy_versions v JOIN hr_policies p ON p.id=v.policy_id ".($isAdmin?'':"WHERE v.status IN ('published','superseded')")." ORDER BY v.policy_id,v.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);
$policies=$db->query("SELECT p.*,v.version_number FROM hr_policies p LEFT JOIN hr_policy_versions v ON v.id=p.current_version_id ORDER BY p.title")->fetchAll(PDO::FETCH_ASSOC);
$activeEmployeeCount=$isAdmin?(int)$db->query("SELECT COUNT(*) FROM users u JOIN employees e ON e.id=u.employee_id WHERE e.status='active' AND u.role='employee'")->fetchColumn():0;
$acks=array(); if(!$isAdmin&&$eid){$s=$db->prepare("SELECT * FROM hr_policy_acknowledgements WHERE employee_id=?");$s->execute(array($eid));foreach($s as $a)$acks[$a['version_id']]=$a;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Documents & Policies — Hambelela HR</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><link rel="stylesheet" href="includes/styles.css"><link rel="stylesheet" href="includes/policies.css?v=20260811-ready"></head>
<body class="policy-shell"><?php include __DIR__.'/includes/'.($isAdmin?'sidebar.php':'emp-sidebar.php'); ?>
<main class="policy-main"><header class="policy-page-head"><div><span class="eyebrow">HR Portal</span><h1>Documents & Policies</h1><p>Company policies, version history and secure acknowledgements.</p></div><?php if($isAdmin):?><button class="primary-btn" type="button" data-open-draft><i class="fa-solid fa-plus"></i> Add policy version</button><?php endif;?></header>
<?php if($success):?><div class="notice success"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="notice error"><?=htmlspecialchars($error)?></div><?php endif;?>
<section><div class="section-head"><div><span class="eyebrow">Company Policies</span><h2>Policy library</h2></div><?php if($isAdmin&&$versions):?><a class="secondary-btn" href="policy-notification-preview.php?id=<?=(int)$versions[0]['id']?>">Preview Employee Notification</a><?php endif;?></div>
<div class="policy-grid">
<?php if(!$versions):?><div class="empty-state"><i class="fa-solid fa-book-open"></i><h3>No policies published yet</h3><p>Published company policies will appear here.</p></div><?php endif;?>
<?php foreach($versions as $v): $ack=$acks[$v['id']]??null; $status=$isAdmin?hrPolicyDisplayStatus($v):hrPolicyAckStatus($v,$ack); $metadataIssues=$isAdmin?hrPolicyMetadataMismatches($v):array(); ?>
<article class="policy-card"><div class="policy-card-top"><span class="type-pill"><?=htmlspecialchars(ucwords(str_replace('_',' ',$v['policy_type'])))?></span><span class="status-pill <?=strpos(strtolower($status),'overdue')!==false?'danger':''?>"><?=htmlspecialchars($status)?></span></div>
<h3><?=htmlspecialchars($v['title'])?></h3><div class="policy-meta"><span><b>Version</b> <?=htmlspecialchars($v['version_number'])?></span><span><b>Created</b> <?=date('j M Y',strtotime($v['created_date']))?></span><span><b>Effective</b> <?=date('j M Y',strtotime($v['effective_date']))?></span><span><b>Acknowledgement</b> <?=$v['acknowledgement_required']?'Required':'Not required'?></span></div>
<?php if($isAdmin&&$v['status']==='ready_to_publish'):?><div class="ready-panel"><strong>READY TO PUBLISH</strong><dl><dt>Version</dt><dd><?=htmlspecialchars($v['version_number'])?></dd><dt>Created</dt><dd><?=date('j F Y',strtotime($v['created_date']))?></dd><dt>Effective</dt><dd><?=date('j F Y',strtotime($v['effective_date']))?></dd><dt>Acknowledgement Deadline</dt><dd><?=$v['acknowledgement_deadline']?date('j F Y',strtotime($v['acknowledgement_deadline'])):'Not set'?></dd><dt>Employees to Notify</dt><dd><?=$activeEmployeeCount?></dd><dt>Acknowledgement Required</dt><dd><?=$v['acknowledgement_required']?'Yes':'No'?></dd></dl><?php if($metadataIssues):?><div class="metadata-warning"><b>Publication blocked — policy metadata requires review.</b><ul><?php foreach($metadataIssues as $issue):?><li><?=htmlspecialchars($issue)?></li><?php endforeach;?></ul></div><?php endif;?></div><?php endif;?>
<?php if($isAdmin&&$v['status']==='published'):?><div class="publication-receipt"><strong>POLICY PUBLISHED</strong><dl><dt>Version</dt><dd><?=htmlspecialchars($v['version_number'])?></dd><dt>Published</dt><dd><?=htmlspecialchars($v['published_at']?date('j F Y H:i',strtotime($v['published_at'])):'—')?></dd><dt>Published by</dt><dd><?=htmlspecialchars($v['published_by_name']?:'Owner/Admin')?></dd><dt>Effective</dt><dd><?=date('j F Y',strtotime($v['effective_date']))?></dd><dt>Employees assigned</dt><dd><?=htmlspecialchars((string)($v['employees_assigned']??0))?></dd><dt>Notifications created</dt><dd><?=htmlspecialchars((string)($v['notifications_created']??0))?></dd></dl></div><?php endif;?>
<div class="policy-actions"><a class="primary-btn" href="policy-view.php?id=<?=$v['id']?>"><i class="fa-solid fa-book-open"></i> <?=(!$isAdmin&&$ack&&!empty($ack['signed_at']))?'View policy':'Read policy'?></a><?php if(!$isAdmin&&$ack&&!empty($ack['signed_at'])):?><a class="secondary-btn" href="policy-receipt.php?id=<?=$ack['id']?>">Receipt</a><?php endif;?><?php if($isAdmin&&$v['status']==='draft'):?><form method="post" action="policy-action.php"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="mark_ready"><input type="hidden" name="version_id" value="<?=$v['id']?>"><button class="primary-btn">Mark Ready to Publish</button></form><?php endif;?><?php if($isAdmin&&$v['status']==='ready_to_publish'):?><button class="primary-btn" type="button" data-open-publish="<?=$v['id']?>">Publish &amp; Notify Employees</button><form method="post" action="policy-action.php"><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="return_draft"><input type="hidden" name="version_id" value="<?=$v['id']?>"><button class="secondary-btn">Return to Draft</button></form><?php endif;?><?php if($isAdmin&&$v['status']==='published'):?><a class="secondary-btn" href="policy-acknowledgements.php?id=<?=$v['id']?>">View Employee Acknowledgements</a><?php endif;?></div>
<?php if($isAdmin&&$v['status']==='ready_to_publish'):?><dialog class="policy-dialog publish-dialog" id="publishDialog<?=$v['id']?>"><form method="post" action="policy-action.php"><span class="eyebrow">Final owner confirmation</span><h2>PUBLISH EMPLOYEE HANDBOOK?</h2><p>You are about to publish:</p><h3><?=htmlspecialchars($v['title'])?><br>Version <?=htmlspecialchars($v['version_number'])?></h3><div class="confirmation-details"><b>Created:</b> <?=date('j F Y',strtotime($v['created_date']))?><br><b>Effective:</b> <?=date('j F Y',strtotime($v['effective_date']))?><br><b>Acknowledgement Deadline:</b> <?=$v['acknowledgement_deadline']?date('j F Y',strtotime($v['acknowledgement_deadline'])):'Not set'?></div><p>This action will freeze Version <?=htmlspecialchars($v['version_number'])?>, make it visible to active employees, create mandatory acknowledgement requirements, notify active employees, and preserve the published document and hash as immutable.</p><p><strong>Once published, Version <?=htmlspecialchars($v['version_number'])?> cannot be edited.</strong></p><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="publish"><input type="hidden" name="version_id" value="<?=$v['id']?>"><div class="confirm-actions"><button class="secondary-btn" type="button" data-close-publish>Cancel</button><button class="primary-btn" type="submit">Publish &amp; Notify Employees</button></div></form></dialog><?php endif;?>
<?php if($isAdmin):?><div class="hash">SHA-256 <?=htmlspecialchars($v['document_hash'])?></div><?php endif;?></article><?php endforeach;?></div></section>
<?php if($isAdmin):?><dialog id="draftDialog" class="policy-dialog"><form method="post" action="policy-action.php" enctype="multipart/form-data"><button class="dialog-close" type="button" data-close-draft aria-label="Close">×</button><span class="eyebrow">New immutable version</span><h2>Add policy version</h2><input type="hidden" name="csrf" value="<?=htmlspecialchars(hrPolicyCsrf())?>"><input type="hidden" name="action" value="save_draft">
<label>Existing policy (leave blank for new)<select name="policy_id"><option value="">New policy</option><?php foreach($policies as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['title'])?></option><?php endforeach;?></select></label>
<div class="form-grid"><label>Title *<input name="title" required value="Employee Handbook & HR Policy"></label><label>Policy type<select name="policy_type"><option value="general_document">General Document</option><option value="company_policy">Company Policy</option><option selected value="mandatory_policy">Mandatory Policy</option></select></label><label>Version *<input name="version_number" required value="1.0"></label><label>Created date *<input type="date" name="created_date" required value="2026-08-11"></label><label>Effective date *<input type="date" name="effective_date" required value="2026-09-01"></label><label>Acknowledgement deadline<input type="date" name="acknowledgement_deadline" value="2026-08-31"></label><label>Next formal review<input name="next_review" value="August 2027"></label><label>Approved DOCX file *<input type="file" name="policy_file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required><small>The DOCX is preserved unchanged and converted into the immutable digital viewer.</small></label></div>
<label class="check"><input type="checkbox" name="acknowledgement_required" value="1" checked> Employee acknowledgement required</label><label>Changes summary<textarea name="changes_summary">Initial Employee Handbook & HR Policy</textarea></label><button class="primary-btn" type="submit">Save draft</button></form></dialog><?php endif;?></main>
<script>const d=document.getElementById('draftDialog');document.querySelector('[data-open-draft]')?.addEventListener('click',()=>d.showModal());document.querySelector('[data-close-draft]')?.addEventListener('click',()=>d.close());document.querySelectorAll('[data-open-publish]').forEach(b=>b.addEventListener('click',()=>document.getElementById('publishDialog'+b.dataset.openPublish).showModal()));document.querySelectorAll('[data-close-publish]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));</script></body></html>
