<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/config.php';
require_once BASE_PATH . '/shared/auth.php';
require_once BASE_PATH . '/shared/database.php';
require_once BASE_PATH . '/shared/woocommerce.php';
require_once BASE_PATH . '/shared/cost-workbook.php';
require_once BASE_PATH . '/shared/cost-workbook-phase2.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

function cw_json(array $data, int $status = 200): void { http_response_code($status); echo json_encode($data, JSON_UNESCAPED_SLASHES); exit; }
function cw_body(): array { $raw=file_get_contents('php://input'); $data=json_decode($raw ?: '{}', true); return is_array($data)?$data:[]; }
function cw_money($v): ?string { $d=cw_decimal($v); return $d===null?null:number_format((float)$d,2,'.',''); }
function cw_sync_find(PDO $pdo, int $id): ?array { $st=$pdo->prepare('SELECT * FROM cw_sync_batches WHERE id=?');$st->execute([$id]);return $st->fetch() ?: null; }
function cw_sync_successful_id(PDO $pdo): ?int { $id=$pdo->query("SELECT id FROM cw_sync_batches WHERE is_successful_snapshot=1 AND status='completed' ORDER BY completed_at DESC,id DESC LIMIT 1")->fetchColumn();return $id===false?null:(int)$id; }
function cw_sync_fail(PDO $pdo, int $id, string $reason): void { $st=$pdo->prepare("UPDATE cw_sync_batches SET status='failed',failed_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP(),heartbeat_at=UTC_TIMESTAMP(),error_count=error_count+1,error_message=?,failure_reason=? WHERE id=? AND status IN ('queued','running')");$st->execute([$reason,$reason,$id]); }
function cw_snapshot_categories(PDO $pdo, int $batchId): array {
    $st=$pdo->prepare("SELECT DISTINCT category FROM cw_product_snapshots WHERE sync_batch_id=? AND category IS NOT NULL AND category<>''");
    $st->execute([$batchId]);$categories=[];
    foreach($st->fetchAll(PDO::FETCH_COLUMN) as $stored){foreach(preg_split('/\s*,\s*/',(string)$stored) as $category){$category=trim($category);if($category!=='')$categories[$category]=true;}}
    $categories=array_keys($categories);natcasesort($categories);return array_values($categories);
}

try {
    $pdo=db(); cw_install_schema($pdo); $action=(string)($_GET['action']??'summary'); $period=cw_request_period_bounds();
    if ($_SERVER['REQUEST_METHOD'] !== 'GET') cw_require_csrf();

    if ($action === 'summary') {
        $view=(string)($_GET['view']??'overview');
        $allowedViews=['overview','purchases','profitability','settings'];
        if(!in_array($view,$allowedViews,true))cw_json(['error'=>'Unknown Cost Workbook view.'],400);
        $counts=['active_invoices'=>0,'needs_review'=>0,'approved'=>0,'website_items'=>0,'shipments'=>0,'confirmed_calculations'=>0,'product_matches'=>0,'configured_settings'=>0];
        $dateWhere=$period?' AND COALESCE(invoice_date,DATE(uploaded_at))>=? AND COALESCE(invoice_date,DATE(uploaded_at))<?':'';$dateParams=$period?:[];
        $countQuery=static function(string $where)use($pdo,$dateWhere,$dateParams):int{$st=$pdo->prepare('SELECT COUNT(*) FROM cw_supplier_invoices WHERE '.$where.$dateWhere);$st->execute($dateParams);return(int)$st->fetchColumn();};
        if(in_array($view,['overview','purchases'],true)){
            $counts['active_invoices']=$countQuery("approval_status<>'archived'");
            $counts['needs_review']=$countQuery("approval_status='draft' AND review_status='needs_review'");
            $counts['approved']=$countQuery("approval_status='approved'");
        }
        if($view==='overview'){
            $shipmentWhere=$period?' AND shipment_date>=? AND shipment_date<?':'';
            $st=$pdo->prepare("SELECT COUNT(*) FROM cw_shipments WHERE status<>'archived'".$shipmentWhere);$st->execute($period?:[]);$counts['shipments']=(int)$st->fetchColumn();
            $periodJoin=$period?' AND s.shipment_date>=? AND s.shipment_date<?':'';
            $st=$pdo->prepare("SELECT COUNT(*) FROM cw_landed_calculation_versions v JOIN cw_landed_calculations c ON c.id=v.calculation_id JOIN cw_shipments s ON s.id=c.shipment_id WHERE v.status='confirmed'".$periodJoin);$st->execute($period?:[]);$counts['confirmed_calculations']=(int)$st->fetchColumn();
            $st=$pdo->prepare("SELECT COUNT(*) FROM cw_calculation_product_matches m JOIN cw_sale_size_costs ss ON ss.id=m.sale_size_cost_id JOIN cw_landed_calculation_lines l ON l.id=ss.calculation_line_id JOIN cw_landed_calculation_versions v ON v.id=l.calculation_version_id JOIN cw_landed_calculations c ON c.id=v.calculation_id JOIN cw_shipments s ON s.id=c.shipment_id WHERE 1=1".$periodJoin);$st->execute($period?:[]);$counts['product_matches']=(int)$st->fetchColumn();
            $counts['configured_settings']=(int)$pdo->query("SELECT COUNT(*) FROM cw_settings WHERE setting_value IS NOT NULL AND setting_value<>''")->fetchColumn();
        }
        $successfulId=in_array($view,['overview','profitability'],true)?cw_sync_successful_id($pdo):null;$snapshotStats=null;
        if($successfulId){$st=$pdo->prepare("SELECT SUM(variation_id=0 AND product_type='simple') simple_products,SUM(variation_id=0 AND product_type='variable') variable_parents,SUM(variation_id>0) variations,COUNT(*) total_records,SUM(sku IS NULL OR sku='') missing_skus,SUM(active_price_inc_vat IS NULL) missing_prices,SUM(stock_quantity IS NULL) missing_stock_quantity,SUM(manage_stock=0) unmanaged_stock FROM cw_product_snapshots WHERE sync_batch_id=?");$st->execute([$successfulId]);$snapshotStats=$st->fetch() ?: null;if($snapshotStats){$st=$pdo->prepare("SELECT COALESCE(SUM(duplicate_count),0) FROM (SELECT COUNT(*) duplicate_count FROM cw_product_snapshots WHERE sync_batch_id=? AND sku IS NOT NULL AND sku<>'' GROUP BY sku HAVING COUNT(*)>1) duplicates");$st->execute([$successfulId]);$snapshotStats['duplicate_skus']=(int)$st->fetchColumn();$counts['website_items']=(int)$snapshotStats['total_records'];}}
        $invoices=[];if($view==='purchases'){$invoiceStmt=$pdo->prepare("SELECT i.*, (SELECT COUNT(*) FROM cw_supplier_invoice_lines l WHERE l.supplier_invoice_id=i.id) line_count FROM cw_supplier_invoices i WHERE i.approval_status<>'archived'".($period?' AND COALESCE(i.invoice_date,DATE(i.uploaded_at))>=? AND COALESCE(i.invoice_date,DATE(i.uploaded_at))<?':'')." ORDER BY i.uploaded_at DESC LIMIT 100");$invoiceStmt->execute($period?:[]);$invoices=$invoiceStmt->fetchAll();}
        foreach($invoices as &$invoice){$invoice['approved_at_display']=cw2_windhoek_time($invoice['approved_at']??null);}unset($invoice);
        $settings=[];if(in_array($view,['purchases','settings'],true)){foreach($pdo->query('SELECT setting_key,setting_value FROM cw_settings')->fetchAll() as $r)$settings[$r['setting_key']]=$r['setting_value'];}
        $last=$successfulId?cw_sync_find($pdo,$successfulId):null;
        $current=$view==='profitability'?($pdo->query("SELECT * FROM cw_sync_batches ORDER BY id DESC LIMIT 1")->fetch() ?: null):null;
        $last=$last?cw_sync_public($last):null;$current=$current?cw_sync_public($current):null;
        cw_json(compact('counts','invoices','settings','last','current','snapshotStats'));
    }

    if ($action === 'upload') {
        cw_require_admin();
        if (empty($_FILES['invoice_files'])) throw new RuntimeException('Select at least one invoice file.');
        $allowed=['pdf'=>'application/pdf','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','xlsx'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','csv'=>['text/csv','text/plain','application/csv','application/vnd.ms-excel']];
        $max=15*1024*1024; $files=$_FILES['invoice_files']; $results=[]; $finfo=new finfo(FILEINFO_MIME_TYPE); $user=cw_user();
        $names=is_array($files['name'])?$files['name']:[$files['name']];
        foreach($names as $i=>$name){
            $tmp=is_array($files['tmp_name'])?$files['tmp_name'][$i]:$files['tmp_name']; $size=(int)(is_array($files['size'])?$files['size'][$i]:$files['size']); $error=(int)(is_array($files['error'])?$files['error'][$i]:$files['error']);
            try { if($error!==UPLOAD_ERR_OK) throw new RuntimeException('Upload error '.$error); if($size<=0||$size>$max) throw new RuntimeException('File must be 15 MB or smaller.');
                $ext=strtolower(pathinfo((string)$name,PATHINFO_EXTENSION)); if(!isset($allowed[$ext])) throw new RuntimeException('Unsupported file extension.');
                $mime=(string)$finfo->file($tmp); $mimes=(array)$allowed[$ext]; if(!in_array($mime,$mimes,true)) throw new RuntimeException('File content does not match its extension.');
                $dir=BASE_PATH.'/uploads/cost-workbook/'.date('Y/m'); if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir)) throw new RuntimeException('Secure upload folder is unavailable.');
                $stored=date('YmdHis').'-'.bin2hex(random_bytes(8)).'.'.$ext; $relative='uploads/cost-workbook/'.date('Y/m').'/'.$stored;
                if(!move_uploaded_file($tmp,BASE_PATH.'/'.$relative)) throw new RuntimeException('Could not store the uploaded file.');
                $stmt=$pdo->prepare('INSERT INTO cw_supplier_invoices (uploaded_by,uploaded_by_name,original_filename,stored_file,file_type,currency,extraction_status) VALUES (?,?,?,?,?,\'NAD\',\'manual_review\')');
                $stmt->execute([$user['id'],$user['name'],basename((string)$name),$relative,$mime]); $results[]=['name'=>$name,'ok'=>true,'id'=>(int)$pdo->lastInsertId()];
            } catch(Throwable $e){ $results[]=['name'=>$name,'ok'=>false,'error'=>$e->getMessage()]; }
        } cw_json(['results'=>$results]);
    }

    if ($action === 'invoice') {
        $id=(int)($_GET['id']??0); $st=$pdo->prepare('SELECT * FROM cw_supplier_invoices WHERE id=?'); $st->execute([$id]); $invoice=$st->fetch(); if(!$invoice) cw_json(['error'=>'Invoice not found.'],404);
        $st=$pdo->prepare('SELECT * FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=? ORDER BY id'); $st->execute([$id]); cw_json(['invoice'=>$invoice,'lines'=>$st->fetchAll()]);
    }

    if ($action === 'save-invoice') {
        cw_require_admin(); $b=cw_body(); $id=(int)($b['id']??0); $currency=strtoupper(trim((string)($b['currency']??''))); if(!preg_match('/^[A-Z]{3}$/',$currency)) throw new RuntimeException('Confirm a valid three-letter currency.');
        $vat=(string)($b['vat_treatment']??'unconfirmed'); if(!in_array($vat,['unconfirmed','inclusive','exclusive','exempt','mixed'],true)) $vat='unconfirmed';
        $pdo->beginTransaction();$invoice=$pdo->prepare('SELECT * FROM cw_supplier_invoices WHERE id=? FOR UPDATE');$invoice->execute([$id]);$existingInvoice=$invoice->fetch();
        if(!$existingInvoice)throw new RuntimeException('Invoice not found.');if($existingInvoice['approval_status']!=='draft')throw new RuntimeException('Approved or archived invoices cannot be edited.');
        $vatRate=(string)($pdo->query("SELECT setting_value FROM cw_settings WHERE setting_key='vat_rate'")->fetchColumn()?:'15');$allowedTypes=['unclassified','supplier_raw_material','website_product','website_variation','packaging','additional_cost'];$kept=[];$subtotalCents=0;$vatCents=0;$totalCents=0;$u=cw_user();
        $findLine=$pdo->prepare('SELECT * FROM cw_supplier_invoice_lines WHERE id=? AND supplier_invoice_id=? FOR UPDATE');
        $updateLine=$pdo->prepare('UPDATE cw_supplier_invoice_lines SET raw_description=?,product_description=?,supplier_sku=?,quantity=?,purchase_unit=?,pack_size=?,base_quantity=?,base_unit=?,unit_price=?,line_subtotal=?,vat_amount=?,line_total=?,discount=?,discount_type=?,discount_value=?,vat_rate=?,line_vat_treatment=?,calculated_vat_amount=?,vat_override_amount=?,vat_override_reason=?,vat_overridden_by=?,vat_overridden_by_name=?,vat_overridden_at=?,vat_source=?,purchase_cost_in_landed=?,base_unit_cost=?,item_type=?,review_status=?,owner_corrections=? WHERE id=? AND supplier_invoice_id=?');
        $insertLine=$pdo->prepare('INSERT INTO cw_supplier_invoice_lines (supplier_invoice_id,raw_description,product_description,supplier_sku,quantity,purchase_unit,pack_size,base_quantity,base_unit,unit_price,line_subtotal,vat_amount,line_total,discount,discount_type,discount_value,vat_rate,line_vat_treatment,calculated_vat_amount,vat_override_amount,vat_override_reason,vat_overridden_by,vat_overridden_by_name,vat_overridden_at,vat_source,purchase_cost_in_landed,base_unit_cost,item_type,review_status,owner_corrections) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
        foreach((array)($b['lines']??[]) as $line){
            [$base,$baseUnit,$warning]=cw_normalize_quantity($line['quantity']??null,(string)($line['purchase_unit']??''),$line['pack_size']??null);$amounts=cw2_invoice_line($line,$vat,$vatRate);
            $description=trim((string)($line['product_description']??''));$type=(string)($line['item_type']??'unclassified');if(!in_array($type,$allowedTypes,true))$type='unclassified';$valid=$warning===null&&$description!=='';
            $lineId=(int)($line['id']??0);$audit=[];$old=null;if($lineId>0){$findLine->execute([$lineId,$id]);$old=$findLine->fetch();if(!$old)throw new RuntimeException('An invoice line does not belong to the selected invoice.');$audit=json_decode((string)($old['owner_corrections']??'[]'),true);if(!is_array($audit))$audit=[];if(cw_money($old['discount']??0)!==$amounts['discount'])$audit[]=['field'=>'discount','from'=>cw_money($old['discount']??0),'to'=>$amounts['discount'],'changed_by'=>$u['id'],'changed_by_name'=>$u['name'],'changed_at'=>gmdate('c')];}
            $override=$amounts['vat_source']==='override';$baseUnitCost=$base&&((float)$base)>0?number_format((float)$amounts['line_subtotal']/(float)$base,6,'.',''):null;
            $values=[trim((string)($line['raw_description']??'')),$description,trim((string)($line['supplier_sku']??''))?:null,cw_decimal($line['quantity']??null),trim((string)($line['purchase_unit']??''))?:null,cw_decimal($line['pack_size']??null),$base,$baseUnit,cw_decimal($line['unit_price']??null),$amounts['line_subtotal'],$amounts['vat_amount'],$amounts['line_total'],$amounts['discount'],$amounts['discount_type'],$amounts['discount_value'],$amounts['vat_rate'],$amounts['vat_treatment'],$amounts['calculated_vat_amount'],$override?$amounts['vat_amount']:null,$override?trim((string)($line['vat_override_reason']??'')):null,$override?$u['id']:null,$override?$u['name']:null,$override?gmdate('Y-m-d H:i:s'):null,$amounts['vat_source'],$amounts['line_subtotal'],$baseUnitCost,$type,$valid?'valid':'invalid',json_encode($audit,JSON_UNESCAPED_SLASHES)];
            if($old){$updateLine->execute(array_merge($values,[$lineId,$id]));}else{$insertLine->execute(array_merge([$id],$values));$lineId=(int)$pdo->lastInsertId();}$kept[]=$lineId;$subtotalCents+=(int)round((float)$amounts['line_subtotal']*100);$vatCents+=(int)round((float)$amounts['vat_amount']*100);$totalCents+=(int)round((float)$amounts['line_total']*100);
        }
        if($kept){$placeholders=implode(',',array_fill(0,count($kept),'?'));$removed=$pdo->prepare("SELECT id FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=? AND id NOT IN ($placeholders)");$removed->execute(array_merge([$id],$kept));$removedIds=array_map('intval',$removed->fetchAll(PDO::FETCH_COLUMN));if($removedIds){$rp=implode(',',array_fill(0,count($removedIds),'?'));$pdo->prepare("DELETE FROM cw_product_matches WHERE supplier_invoice_line_id IN ($rp)")->execute($removedIds);$pdo->prepare("DELETE FROM cw_supplier_invoice_lines WHERE id IN ($rp)")->execute($removedIds);}}else{$removed=$pdo->prepare('SELECT id FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=?');$removed->execute([$id]);$removedIds=array_map('intval',$removed->fetchAll(PDO::FETCH_COLUMN));if($removedIds){$rp=implode(',',array_fill(0,count($removedIds),'?'));$pdo->prepare("DELETE FROM cw_product_matches WHERE supplier_invoice_line_id IN ($rp)")->execute($removedIds);}$pdo->prepare('DELETE FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=?')->execute([$id]);}
        $money=static function(int $cents):string{return number_format($cents/100,2,'.','');};$st=$pdo->prepare('UPDATE cw_supplier_invoices SET supplier_name=?,invoice_number=?,invoice_date=?,currency=?,exchange_rate=?,vat_treatment=?,subtotal=?,vat_amount=?,invoice_total=?,notes=?,review_status=\'reviewed\' WHERE id=? AND approval_status=\'draft\'');
        $st->execute([trim((string)($b['supplier_name']??'')),trim((string)($b['invoice_number']??''))?:null,($b['invoice_date']??'')?:null,$currency,cw_decimal($b['exchange_rate']??1),$vat,$money($subtotalCents),$money($vatCents),$money($totalCents),trim((string)($b['notes']??''))?:null,$id]);
        $dup=$pdo->prepare("SELECT id FROM cw_supplier_invoices WHERE id<>? AND supplier_name=? AND invoice_number=? AND invoice_date=? AND invoice_total<=>? AND approval_status<>'archived' LIMIT 1");
        $dup->execute([$id,trim((string)($b['supplier_name']??'')),trim((string)($b['invoice_number']??'')),($b['invoice_date']??'')?:null,$money($totalCents)]); $duplicateId=$dup->fetchColumn() ?: null;
        $pdo->commit(); cw_json(['ok'=>true,'duplicate_invoice_id'=>$duplicateId]);
    }

    if ($action === 'approve') {
        cw_require_admin(); $b=cw_body(); $id=(int)($b['id']??0); $st=$pdo->prepare('SELECT * FROM cw_supplier_invoices WHERE id=?');$st->execute([$id]);$inv=$st->fetch(); if(!$inv)throw new RuntimeException('Invoice not found.');
        if(trim($inv['supplier_name'])===''||empty($inv['invoice_number'])||empty($inv['invoice_date'])||$inv['vat_treatment']==='unconfirmed'||empty($inv['currency'])) throw new RuntimeException('Complete supplier, invoice number, date, currency and VAT treatment before approval.');
        $st=$pdo->prepare("SELECT COUNT(*) FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=? AND review_status<>'valid'");$st->execute([$id]); if((int)$st->fetchColumn()>0)throw new RuntimeException('Every invoice line must have a valid quantity, recognized unit and cost.');
        $st=$pdo->prepare('SELECT COUNT(*) FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=?');$st->execute([$id]);if((int)$st->fetchColumn()===0)throw new RuntimeException('Add at least one valid invoice line.');
        $u=cw_user();$pdo->prepare("UPDATE cw_supplier_invoices SET approval_status='approved',approved_by=?,approved_by_name=?,approved_at=UTC_TIMESTAMP() WHERE id=? AND approval_status='draft'")->execute([$u['id'],$u['name'],$id]);cw_json(['ok'=>true]);
    }

    if ($action === 'archive') { cw_require_admin();$b=cw_body();$pdo->prepare("UPDATE cw_supplier_invoices SET approval_status='archived',archived_at=NOW() WHERE id=?")->execute([(int)($b['id']??0)]);cw_json(['ok'=>true]); }
    if ($action === 'download') { $id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT original_filename,stored_file,file_type FROM cw_supplier_invoices WHERE id=?');$st->execute([$id]);$f=$st->fetch();$path=$f?BASE_PATH.'/'.$f['stored_file']:'';if(!$f||!is_file($path))throw new RuntimeException('Original file is unavailable.');header_remove('Content-Type');header('Content-Type: '.$f['file_type']);header('Content-Disposition: attachment; filename="'.rawurlencode($f['original_filename']).'"');header('X-Content-Type-Options: nosniff');readfile($path);exit; }

    if ($action === 'settings') { cw_require_admin();$b=cw_body();$allowed=['base_currency','vat_rate','retail_target_margin','wholesale_target_margin','reseller_target_margin','low_margin_threshold','default_allocation_method'];$u=cw_user();$st=$pdo->prepare('INSERT INTO cw_settings(setting_key,setting_value,updated_by,updated_by_name) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by),updated_by_name=VALUES(updated_by_name)');foreach($allowed as $k){if(array_key_exists($k,$b))$st->execute([$k,$b[$k]===''?null:(string)$b[$k],$u['id'],$u['name']]);}cw_json(['ok'=>true]); }

    if ($action === 'sync-status') { cw_require_admin();$id=(int)($_GET['batch_id']??0);$sync=$id?cw_sync_find($pdo,$id):($pdo->query('SELECT * FROM cw_sync_batches ORDER BY id DESC LIMIT 1')->fetch() ?: null);if(!$sync)cw_json(['sync'=>null]);cw_json(['sync'=>cw_sync_public($sync)]); }

    if ($action === 'sync-start') { cw_require_admin();$lock=cw_sync_acquire_lock($pdo,'lifecycle');try{$pdo->beginTransaction();$active=$pdo->query("SELECT * FROM cw_sync_batches WHERE status IN ('queued','running') ORDER BY id DESC LIMIT 1 FOR UPDATE")->fetch() ?: null;if($active&&!cw_sync_is_stale($active)){$pdo->commit();cw_json(['batch_id'=>(int)$active['id'],'sync'=>cw_sync_public($active),'restored'=>true]);}if($active){$reason='Heartbeat expired after '.CW_SYNC_STALE_SECONDS.' seconds; clean restart required.';$st=$pdo->prepare("UPDATE cw_sync_batches SET status='stale',recovered_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP(),failure_reason=?,recovery_reason=?,recovery_count=recovery_count+1 WHERE id=?");$st->execute([$reason,$reason,$active['id']]);}$u=cw_user();$previous=cw_sync_successful_id($pdo);$st=$pdo->prepare("INSERT INTO cw_sync_batches(sync_uuid,status,queued_at,started_at,heartbeat_at,updated_at,next_page,current_batch,current_offset,started_by,started_by_name,previous_successful_batch_id) VALUES(?,'running',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP(),1,0,0,?,?,?)");$st->execute([cw_sync_uuid(),$u['id'],$u['name'],$previous]);$id=(int)$pdo->lastInsertId();$pdo->commit();$sync=cw_sync_find($pdo,$id);cw_json(['batch_id'=>$id,'sync'=>cw_sync_public($sync),'restored'=>false,'recovered_previous'=>(bool)$active]);}finally{cw_sync_release_lock($pdo,$lock);} }

    if ($action === 'sync-recover') { cw_require_admin();$b=cw_body();$id=(int)($b['batch_id']??0);if($id<1)throw new RuntimeException('Select a sync attempt to recover.');$lock=cw_sync_acquire_lock($pdo,'lifecycle');try{$pdo->beginTransaction();$st=$pdo->prepare('SELECT * FROM cw_sync_batches WHERE id=? FOR UPDATE');$st->execute([$id]);$sync=$st->fetch();if(!$sync)throw new RuntimeException('Sync attempt not found.');if(in_array($sync['status'],['completed','cancelled','recovered'],true))throw new RuntimeException('This sync attempt is already terminal.');if(in_array($sync['status'],['queued','running'],true)&&!cw_sync_is_stale($sync))throw new RuntimeException('The sync heartbeat is still active.');$reason=trim((string)($b['reason']??'')) ?: 'Manual recovery after an interrupted or failed sync.';$reason=substr($reason,0,500);$u=cw_user();$st=$pdo->prepare("UPDATE cw_sync_batches SET status='recovered',recovered_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP(),recovery_count=recovery_count+1,recovery_reason=?,recovered_by=?,recovered_by_name=? WHERE id=?");$st->execute([$reason,$u['id'],$u['name'],$id]);$pdo->commit();$sync=cw_sync_find($pdo,$id);cw_json(['ok'=>true,'sync'=>cw_sync_public($sync)]);}finally{cw_sync_release_lock($pdo,$lock);} }

    if ($action === 'sync-batch') { cw_require_admin();$b=cw_body();$batch=(int)($b['batch_id']??0);if($batch<1)throw new RuntimeException('Invalid sync attempt.');$lock=cw_sync_acquire_lock($pdo,'batch-'.$batch,0);try{$pdo->beginTransaction();$st=$pdo->prepare('SELECT * FROM cw_sync_batches WHERE id=? FOR UPDATE');$st->execute([$batch]);$sync=$st->fetch();if(!$sync||$sync['status']!=='running')throw new RuntimeException('Sync attempt is not active.');if(cw_sync_is_stale($sync)){cw_sync_fail($pdo,$batch,'Sync heartbeat expired before the next batch.');$pdo->commit();throw new RuntimeException('Sync heartbeat expired; recover and restart safely.');}$page=(int)$sync['next_page'];$offset=($page-1)*CW_SYNC_BATCH_SIZE;$pdo->prepare('UPDATE cw_sync_batches SET heartbeat_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP(),last_batch_started_at=UTC_TIMESTAMP(),current_batch=?,current_offset=? WHERE id=?')->execute([$page,$offset,$batch]);$pdo->commit();
        try{$products=cw_sync_wc_get('products',['page'=>$page,'per_page'=>CW_SYNC_BATCH_SIZE,'status'=>'any','_fields'=>CW_SYNC_FIELDS]);if(!is_array($products))throw new RuntimeException('Website catalogue returned an invalid response.');$insert=$pdo->prepare('INSERT INTO cw_product_snapshots(product_id,variation_id,parent_product_id,product_name,variation_name,sku,category,product_type,attributes,regular_price_inc_vat,sale_price_inc_vat,active_price_inc_vat,stock_quantity,stock_status,manage_stock,website_status,permalink,sync_batch_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE sku=VALUES(sku),active_price_inc_vat=VALUES(active_price_inc_vat),stock_quantity=VALUES(stock_quantity),stock_status=VALUES(stock_status)');$count=0;
            foreach($products as $p){$cats=implode(', ',array_column((array)($p['categories']??[]),'name'));$rows=[[$p,0,'']];if(($p['type']??'')==='variable'){foreach(cw_sync_wc_get('products/'.(int)$p['id'].'/variations',['per_page'=>100,'status'=>'any','_fields'=>CW_SYNC_FIELDS]) as $v)$rows[]=[$v,(int)$v['id'],implode(' / ',array_column((array)($v['attributes']??[]),'option'))];}
                foreach($rows as [$x,$vid,$vname]){$insert->execute([(int)$p['id'],$vid,$vid?(int)$p['id']:null,(string)($p['name']??''),$vname,trim((string)($x['sku']??''))?:null,$cats,$vid?'variation':(string)($p['type']??'simple'),json_encode($x['attributes']??[]),cw_money($x['regular_price']??null),cw_money($x['sale_price']??null),cw_money($x['price']??null),isset($x['stock_quantity'])?cw_decimal($x['stock_quantity']):null,$x['stock_status']??null,!empty($x['manage_stock'])?1:0,$x['status']??null,$p['permalink']??null,$batch]);$count++;}}
            $done=count($products)<CW_SYNC_BATCH_SIZE;$pdo->beginTransaction();$st=$pdo->prepare('SELECT * FROM cw_sync_batches WHERE id=? FOR UPDATE');$st->execute([$batch]);$latest=$st->fetch();if(!$latest||$latest['status']!=='running')throw new RuntimeException('Sync attempt changed state during processing.');$processed=(int)$latest['processed_count']+$count;$catalogued=(int)$latest['total_products']+count($products);if($done){$pdo->exec('UPDATE cw_sync_batches SET is_successful_snapshot=0 WHERE is_successful_snapshot=1');$st=$pdo->prepare("UPDATE cw_sync_batches SET status='completed',completed_at=UTC_TIMESTAMP(),heartbeat_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP(),next_page=?,current_batch=?,current_offset=?,processed_count=?,success_count=?,total_products=?,expected_total=?,is_successful_snapshot=1,error_message=NULL,failure_reason=NULL WHERE id=?");$st->execute([$page+1,$page,$offset,$processed,$processed,$catalogued,$catalogued,$batch]);$pdo->prepare("UPDATE cw_settings SET setting_value=UTC_TIMESTAMP() WHERE setting_key='last_website_sync'")->execute();}else{$st=$pdo->prepare('UPDATE cw_sync_batches SET next_page=?,current_batch=?,current_offset=?,processed_count=?,success_count=?,total_products=?,heartbeat_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?');$st->execute([$page+1,$page,$offset,$processed,$processed,$catalogued,$batch]);}$pdo->commit();$public=cw_sync_public(cw_sync_find($pdo,$batch));cw_json(['done'=>$done,'page'=>$page,'items'=>$count,'sync'=>$public]);
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();cw_sync_fail($pdo,$batch,'Website catalogue read failed. The last successful snapshot was preserved.');throw new RuntimeException('Website catalogue read failed. The last successful snapshot was preserved.');}}finally{cw_sync_release_lock($pdo,$lock);} }

    if ($action === 'products') { $batchId=cw_sync_successful_id($pdo);if(!$batchId)cw_json(['products'=>[],'categories'=>[]]);$q=substr(trim((string)($_GET['q']??'')),0,100);$category=substr(trim((string)($_GET['category']??'')),0,100);$categories=cw_snapshot_categories($pdo,$batchId);if($category!==''&&!in_array($category,$categories,true))cw_json(['error'=>'Select a category from the successful website snapshot.'],422);$where=['s.sync_batch_id=?'];$params=[$batchId];if($q!==''){$like='%'.$q.'%';$where[]='(s.product_name LIKE ? OR s.variation_name LIKE ? OR s.sku LIKE ?)';array_push($params,$like,$like,$like);}if($category!==''){$where[]="FIND_IN_SET(?,REPLACE(COALESCE(s.category,''),', ',','))>0";$params[]=$category;}$sql="SELECT s.*,CASE WHEN s.sku IS NULL OR s.sku='' THEN 'Missing SKU' WHEN (SELECT COUNT(*) FROM cw_product_snapshots d WHERE d.sync_batch_id=s.sync_batch_id AND d.sku=s.sku)>1 THEN 'Duplicate SKU' WHEN s.active_price_inc_vat IS NULL THEN 'Missing website price' WHEN s.stock_quantity IS NULL THEN 'Missing stock quantity' ELSE 'Awaiting approved cost' END AS warning FROM cw_product_snapshots s WHERE ".implode(' AND ',$where).' ORDER BY s.product_name,s.variation_id LIMIT 200';$st=$pdo->prepare($sql);$st->execute($params);cw_json(['products'=>$st->fetchAll(),'categories'=>$categories]); }
    if ($action === 'match') { cw_require_admin();$b=cw_body();$line=(int)($b['line_id']??0);$invoiceId=(int)($b['invoice_id']??0);$type=(string)($b['item_type']??'unclassified');$valid=['supplier_raw_material','website_product','website_variation','packaging','additional_cost'];if(!in_array($type,$valid,true))throw new RuntimeException('Select a valid item classification.');$lineCheck=$pdo->prepare("SELECT l.id FROM cw_supplier_invoice_lines l JOIN cw_supplier_invoices i ON i.id=l.supplier_invoice_id WHERE l.id=? AND l.supplier_invoice_id=? AND i.approval_status='draft'");$lineCheck->execute([$line,$invoiceId]);if(!$lineCheck->fetchColumn())throw new RuntimeException('The selected line is not an editable line on this invoice.');$pid=isset($b['product_id'])?(int)$b['product_id']:null;$vid=isset($b['variation_id'])?(int)$b['variation_id']:null;if($pid){$snapshot=cw_sync_successful_id($pdo);$productCheck=$pdo->prepare('SELECT COUNT(*) FROM cw_product_snapshots WHERE sync_batch_id=? AND product_id=? AND variation_id=?');$productCheck->execute([$snapshot,$pid,$vid?:0]);if((int)$productCheck->fetchColumn()!==1)throw new RuntimeException('Select a product from the successful website snapshot.');}$u=cw_user();$pdo->beginTransaction();$pdo->prepare('UPDATE cw_supplier_invoice_lines SET item_type=?,woo_product_id=?,woo_variation_id=?,match_status=? WHERE id=? AND supplier_invoice_id=?')->execute([$type,$pid?:null,$vid?:null,$pid?'confirmed':'not_applicable',$line,$invoiceId]);$pdo->prepare('INSERT INTO cw_product_matches(supplier_invoice_line_id,woo_product_id,woo_variation_id,match_method,match_confidence,confirmed_by,confirmed_by_name) VALUES(?,?,?, ?,100,?,?)')->execute([$line,$pid?:null,$vid?:null,$pid?'manual':'classification',$u['id'],$u['name']]);$pdo->commit();cw_json(['ok'=>true]); }
    cw_json(['error'=>'Unknown action.'],404);
} catch(Throwable $e) { if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack(); cw_json(['error'=>$e->getMessage()],http_response_code()>=400?http_response_code():422); }
