<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/cost-workbook.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

function fc_reply(array $data,int $status=200):void{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function fc_body():array{$raw=file_get_contents('php://input');$data=json_decode((string)$raw,true);return is_array($data)?$data:$_POST;}
function fc_user():array{$u=current_user();return ['id'=>(int)($u['id']??0),'name'=>(string)($u['name']??$u['full_name']??'Owner')];}
function fc_json($value):string{return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
function fc_code(PDO $pdo):string{$next=(int)$pdo->query('SELECT COALESCE(MAX(id),0)+1 FROM cw_formulations')->fetchColumn();return 'FRM-'.str_pad((string)$next,3,'0',STR_PAD_LEFT);}
function fc_decode_row(array $row):array{foreach(['header_json','ingredients_json','production_json','batches_json','selling_sizes_json','totals_json']as$key)$row[$key]=json_decode((string)$row[$key],true)?:[];return$row;}
function fc_list(PDO $pdo):array{return $pdo->query("SELECT f.*,v.version_status,v.created_at version_created_at,v.totals_json FROM cw_formulations f LEFT JOIN cw_formulation_versions v ON v.formulation_id=f.id AND v.version_no=f.current_version ORDER BY f.active DESC,f.updated_at DESC,f.formulation_name")->fetchAll();}

try{
  $pdo=db();cw_install_schema($pdo);$action=(string)($_GET['action']??'bootstrap');
  if($_SERVER['REQUEST_METHOD']!=='GET')cw_require_csrf();
  if($action==='bootstrap'){
    $ingredients=$pdo->query("SELECT p.id product_id,p.product_name,p.short_code,p.product_category,c.costing_basis,c.base_unit,c.landed_cost_per_base,c.cost_date,s.supplier_name,CONCAT(s.supplier_name,' · ',COALESCE(i.invoice_number,s.manual_reference,'Manual'),' · ',c.cost_date) cost_source FROM cw_landed_product_costs c JOIN cw_cost_products p ON p.id=c.product_id JOIN cw_cost_product_sources s ON s.id=c.product_source_id LEFT JOIN cw_supplier_invoice_lines il ON il.id=c.supplier_invoice_line_id LEFT JOIN cw_supplier_invoices i ON i.id=il.supplier_invoice_id WHERE p.active=1 AND c.id=(SELECT c2.id FROM cw_landed_product_costs c2 WHERE c2.product_id=c.product_id ORDER BY c2.cost_date DESC,c2.id DESC LIMIT 1) ORDER BY p.product_name")->fetchAll();
    $sizes=$pdo->query("SELECT id,label,measurement_type,quantity,unit,base_value,base_unit FROM cw_size_conversions WHERE active=1 ORDER BY measurement_type,base_value")->fetchAll();
    $setups=$pdo->query("SELECT ps.id,ps.setup_name,ps.size_conversion_id,ps.scope_type,ps.scope_reference,ps.scope_label,COALESCE(SUM(pc.component_cost_ex),0) cost_ex_vat FROM cw_packaging_setups ps LEFT JOIN cw_packaging_setup_components pc ON pc.packaging_setup_id=ps.id WHERE ps.active=1 GROUP BY ps.id ORDER BY FIELD(ps.scope_type,'product','category','default'),ps.effective_date DESC,ps.id DESC")->fetchAll();
    $settings=[];$st=$pdo->query("SELECT setting_key,setting_value FROM cw_settings WHERE setting_key IN('formulation_margin_defaults','formulation_rounding_rule','formulation_vat_rate')");foreach($st->fetchAll()as$r)$settings[$r['setting_key']]=$r['setting_value'];
    fc_reply(['ok'=>true,'formulations'=>fc_list($pdo),'ingredients'=>$ingredients,'sizes'=>$sizes,'packaging_setups'=>$setups,'settings'=>$settings]);
  }
  if($action==='load'){$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT f.*,v.* FROM cw_formulations f JOIN cw_formulation_versions v ON v.formulation_id=f.id WHERE f.id=? ORDER BY v.version_no DESC LIMIT 1');$st->execute([$id]);$row=$st->fetch();if(!$row)throw new RuntimeException('Formulation not found.');$history=$pdo->prepare('SELECT id,version_no,version_status,effective_date,created_by_name,created_at FROM cw_formulation_versions WHERE formulation_id=? ORDER BY version_no DESC');$history->execute([$id]);fc_reply(['ok'=>true,'formulation'=>fc_decode_row($row),'history'=>$history->fetchAll()]);}
  if($action==='save'){
    $b=fc_body();$header=is_array($b['header']??null)?$b['header']:[];$name=trim((string)($header['formulation_name']??''));if($name==='')throw new RuntimeException('Formulation name is required.');
    $ingredients=is_array($b['ingredients']??null)?$b['ingredients']:[];if(!$ingredients)throw new RuntimeException('Add at least one ingredient.');
    foreach($ingredients as$i=>$row){if((int)($row['product_id']??0)<1||!is_numeric($row['quantity']??null)||(float)$row['quantity']<0)throw new RuntimeException('Complete ingredient row '.($i+1).'.');if(($header['formulation_type']??'weight')==='mixed'&&($row['requires_density']??false)&&(!is_numeric($row['density']??null)||(float)$row['density']<=0))throw new RuntimeException('A density conversion is required for mixed ingredient row '.($i+1).'.');}
    if(($header['mode_key']??'quantity')==='percentage'){$total=0;foreach($ingredients as$row)$total+=(float)($row['percentage']??0);if(abs($total-100)>0.01)throw new RuntimeException('Ingredient percentages must total 100%.');}
    $id=(int)($b['id']??0);$newVersion=!empty($b['new_version']);$duplicate=!empty($b['duplicate']);$u=fc_user();$pdo->beginTransaction();
    if($duplicate)$id=0;
    if($id){$lock=$pdo->prepare('SELECT * FROM cw_formulations WHERE id=? FOR UPDATE');$lock->execute([$id]);$current=$lock->fetch();if(!$current)throw new RuntimeException('Formulation not found.');if($current['status_key']==='active'&&!$newVersion)throw new RuntimeException('Approved formulations are immutable. Save a new version to make changes.');$version=$newVersion?((int)$current['current_version']+1):(int)$current['current_version'];$code=trim((string)($header['formulation_code']??$current['formulation_code']));$pdo->prepare('UPDATE cw_formulations SET formulation_name=?,formulation_code=?,category=?,formulation_type=?,status_key=?,current_version=?,effective_date=?,updated_by=?,updated_by_name=? WHERE id=?')->execute([$name,$code,(string)($header['category']??''),(string)($header['formulation_type']??'weight'),(string)($header['status_key']??'draft'),$version,($header['effective_date']??'')?:null,$u['id'],$u['name'],$id]);if($newVersion)$pdo->prepare("UPDATE cw_formulation_versions SET version_status='superseded' WHERE formulation_id=? AND version_status='approved'")->execute([$id]);}
    else{$code=$duplicate?'':trim((string)($header['formulation_code']??''));if($code==='')$code=fc_code($pdo);if($duplicate)$name.=' Copy';$pdo->prepare('INSERT INTO cw_formulations(formulation_name,formulation_code,category,formulation_type,status_key,effective_date,created_by,created_by_name,updated_by,updated_by_name) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$name,$code,(string)($header['category']??''),(string)($header['formulation_type']??'weight'),(string)($header['status_key']??'draft'),($header['effective_date']??'')?:null,$u['id'],$u['name'],$u['id'],$u['name']]);$id=(int)$pdo->lastInsertId();$version=1;}
    $status=(string)($header['status_key']??'draft')==='active'?'approved':'draft';$payload=[$id,$version,$status,($header['effective_date']??'')?:null,(string)($header['mode_key']??'quantity'),max(.000001,(float)($header['reference_batch_size']??1)),(string)($header['reference_batch_unit']??'kg'),max(.000001,(float)($header['expected_yield']??1)),(string)($header['yield_unit']??'kg'),max(0,(float)($header['loss_percent']??0)),(float)($header['vat_rate']??15),fc_json($header),fc_json($ingredients),fc_json($b['production']??[]),fc_json($b['batches']??[]),fc_json($b['selling_sizes']??[]),fc_json($b['totals']??[]),$u['id'],$u['name']];
    $pdo->prepare("INSERT INTO cw_formulation_versions(formulation_id,version_no,version_status,effective_date,mode_key,reference_batch_size,reference_batch_unit,expected_yield,yield_unit,loss_percent,vat_rate,header_json,ingredients_json,production_json,batches_json,selling_sizes_json,totals_json,created_by,created_by_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE version_status=VALUES(version_status),effective_date=VALUES(effective_date),mode_key=VALUES(mode_key),reference_batch_size=VALUES(reference_batch_size),reference_batch_unit=VALUES(reference_batch_unit),expected_yield=VALUES(expected_yield),yield_unit=VALUES(yield_unit),loss_percent=VALUES(loss_percent),vat_rate=VALUES(vat_rate),header_json=VALUES(header_json),ingredients_json=VALUES(ingredients_json),production_json=VALUES(production_json),batches_json=VALUES(batches_json),selling_sizes_json=VALUES(selling_sizes_json),totals_json=VALUES(totals_json),created_by=VALUES(created_by),created_by_name=VALUES(created_by_name),created_at=CURRENT_TIMESTAMP")->execute($payload);
    $pdo->prepare('INSERT INTO cw_formulation_audit(formulation_id,action_key,after_json,actor_id,actor_name) VALUES(?,?,?,?,?)')->execute([$id,$duplicate?'duplicated':($newVersion?'new_version':'saved'),fc_json(['version'=>$version,'status'=>$status]),$u['id'],$u['name']]);$pdo->commit();fc_reply(['ok'=>true,'id'=>$id,'version'=>$version,'code'=>$code,'message'=>$newVersion?'New formulation version saved.':'Formulation draft saved.']);
  }
  if($action==='archive'){$id=(int)(fc_body()['id']??0);$u=fc_user();$pdo->prepare("UPDATE cw_formulations SET active=0,status_key='archived',updated_by=?,updated_by_name=? WHERE id=?")->execute([$u['id'],$u['name'],$id]);$pdo->prepare("INSERT INTO cw_formulation_audit(formulation_id,action_key,actor_id,actor_name) VALUES(?,'archived',?,?)")->execute([$id,$u['id'],$u['name']]);fc_reply(['ok'=>true]);}
  throw new RuntimeException('Unsupported action.');
}catch(Throwable$e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Formulation costing: '.get_class($e).' '.$e->getMessage());fc_reply(['ok'=>false,'message'=>$e->getMessage()],400);}
