<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/cost-workbook.php';
require_once BASE_PATH.'/shared/openai-extractor.php';
require_once BASE_PATH.'/shared/pdf-extractor.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

function si_reply(array $data,int $status=200):void{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES);exit;}
function si_body():array{$value=json_decode((string)file_get_contents('php://input'),true);return is_array($value)?$value:[];}
function si_normalize(string $value):string{$value=function_exists('mb_strtolower')?mb_strtolower(trim($value),'UTF-8'):strtolower(trim($value));return preg_replace('/[^a-z0-9]+/','',$value);}
function si_date($value):?string{$value=trim((string)$value);if($value==='')return null;$date=DateTimeImmutable::createFromFormat('Y-m-d',$value);return $date&&$date->format('Y-m-d')===$value?$value:null;}
function si_decimal($value):?string{return cw_decimal($value);}
function si_categories():array{return ['Plant Butters','Carrier Oils','Essential Oils','Hydrosols','Dried Herbs','Powders','Active Ingredients','Preservatives','Emulsifiers','Surfactants','Proteins','Solvents','Waxes','Packaging','Equipment','Accessories','Other'];}
function si_types(bool $supplier=true):array{return $supplier?['Raw Materials','Packaging','Equipment & Accessories','Freight & Logistics','Services','Mixed','Uncategorised']:['Raw Materials','Packaging','Equipment & Accessories','Freight & Logistics','Services','Mixed'];}
function si_category(string $name):string{$n=function_exists('mb_strtolower')?mb_strtolower($name,'UTF-8'):strtolower($name);$map=['butter'=>'Plant Butters','essential'=>'Essential Oils','hydrosol'=>'Hydrosols','herb'=>'Dried Herbs','powder'=>'Powders','preserv'=>'Preservatives','emuls'=>'Emulsifiers','surfact'=>'Surfactants','protein'=>'Proteins','solvent'=>'Solvents','wax'=>'Waxes','bottle'=>'Packaging','jar'=>'Packaging','label'=>'Packaging','pouch'=>'Packaging','oil'=>'Carrier Oils'];foreach($map as $needle=>$category)if(strpos($n,$needle)!==false)return $category;return 'Other';}
function si_base(PDO $pdo,$quantity,$packSize,string $unit):array{$q=(float)($quantity?:0);$size=(float)($packSize?:0);if($q<=0)return[null,null,'Needs quantity'];if($size<=0)return[null,null,'Needs size'];$unit=trim($unit);$baseUnit=in_array($unit,['g','kg'],true)?'kg':(in_array($unit,['ml','L'],true)?'L':($unit==='unit'?'unit':null));if($baseUnit===null)return[null,null,'Needs size'];$factor=null;$st=$pdo->prepare('SELECT base_value,base_unit FROM cw_size_conversions WHERE active=1 AND unit=? AND ABS(quantity-?)<0.000001 LIMIT 1');$st->execute([$unit,$size]);$known=$st->fetch();if($known){$factor=(float)$known['base_value'];$baseUnit=(string)$known['base_unit'];}elseif($unit==='g')$factor=$size/1000;elseif($unit==='kg')$factor=$size;elseif($unit==='ml')$factor=$size/1000;elseif($unit==='L')$factor=$size;elseif($unit==='unit')$factor=$size;if($factor===null||$factor<=0)return[null,null,'Needs size'];return[number_format($q*$factor,6,'.',''),$baseUnit,null];}
function si_supplier(PDO $pdo,string $name,string $type='Uncategorised',bool $confirm=false):int{$normalized=si_normalize($name);if($normalized==='')return 0;$st=$pdo->prepare('SELECT id FROM cw_suppliers WHERE normalized_name=?');$st->execute([$normalized]);$id=(int)$st->fetchColumn();if($id){if($confirm)$pdo->prepare('UPDATE cw_suppliers SET name=?,supplier_type=?,type_confirmed=1 WHERE id=?')->execute([$name,$type,$id]);return$id;}$u=cw_user();$pdo->prepare('INSERT INTO cw_suppliers(name,normalized_name,supplier_type,type_confirmed,created_by) VALUES(?,?,?,?,?)')->execute([$name,$normalized,$type,$confirm?1:0,$u['id']]);return(int)$pdo->lastInsertId();}
function si_line_status(array $line):string{if((float)($line['quantity']??0)<=0)return'Needs quantity';if(empty($line['base_quantity']))return'Needs size';if(($line['match_status']??'unmatched')==='unmatched')return'Needs product match';return'Ready';}

try{
 $pdo=db();cw_install_schema($pdo);$action=(string)($_GET['action']??'list');if($_SERVER['REQUEST_METHOD']!=='GET')cw_require_csrf();
 if($action==='list'){
  $where=[];$params=[];$basis=($_GET['date_basis']??'invoice')==='upload'?'DATE(i.uploaded_at)':'i.invoice_date';$from=si_date($_GET['from']??'');$to=si_date($_GET['to']??'');if($from){$where[]="$basis>=?";$params[]=$from;}if($to){$where[]="$basis<=?";$params[]=$to;}
  foreach(['supplier_id'=>'i.supplier_id','supplier_type'=>'i.supplier_type','invoice_type'=>'i.invoice_type','category'=>'l.product_category'] as $key=>$column){$v=trim((string)($_GET[$key]??''));if($v!==''){$where[]="$column=?";$params[]=$v;}}
  $status=trim((string)($_GET['status']??''));if($status==='archived')$where[]="i.approval_status='archived'";elseif($status!==''){$where[]="i.approval_status<>'archived'";if($status==='ready')$where[]="l.review_status='valid'";elseif($status==='attention')$where[]="(l.review_status<>'valid' OR i.review_status='needs_review')";elseif($status==='extracting')$where[]="i.extraction_status='not_started'";elseif($status==='failed')$where[]="i.extraction_status='failed'";elseif($status==='duplicate')$where[]="i.extraction_message LIKE 'Possible duplicate%'";}else $where[]="i.approval_status<>'archived'";
  $q=trim((string)($_GET['q']??''));if($q!==''){$where[]='(i.supplier_name LIKE ? OR i.invoice_number LIKE ? OR l.product_description LIKE ? OR l.raw_description LIKE ? OR l.supplier_sku LIKE ?)';$like='%'.substr($q,0,100).'%';array_push($params,$like,$like,$like,$like,$like);}
  $page=max(1,(int)($_GET['page']??1));$size=(int)($_GET['page_size']??25);if(!in_array($size,[25,50,100],true))$size=25;$filter=$where?' WHERE '.implode(' AND ',$where):'';
  $count=$pdo->prepare('SELECT COUNT(*) FROM cw_supplier_invoice_lines l JOIN cw_supplier_invoices i ON i.id=l.supplier_invoice_id'.$filter);$count->execute($params);$total=(int)$count->fetchColumn();$offset=($page-1)*$size;
  $sql="SELECT l.*,i.supplier_id,i.supplier_name,i.supplier_type,i.invoice_type,i.invoice_number,i.invoice_date,i.uploaded_at,i.currency,i.exchange_rate,i.extraction_status,i.review_status invoice_review_status,i.approval_status,i.original_filename FROM cw_supplier_invoice_lines l JOIN cw_supplier_invoices i ON i.id=l.supplier_invoice_id{$filter} ORDER BY COALESCE(i.invoice_date,DATE(i.uploaded_at)) DESC,i.id DESC,l.id LIMIT {$size} OFFSET {$offset}";$st=$pdo->prepare($sql);$st->execute($params);$rows=$st->fetchAll();foreach($rows as &$row){$row['display_status']=si_line_status($row);$row['cost_per_base']=((float)$row['base_quantity']>0&&$row['line_subtotal']!==null)?number_format((float)$row['line_subtotal']/(float)$row['base_quantity'],2,'.',''):null;}unset($row);
  $summarySql="SELECT COUNT(DISTINCT i.id) invoices,COUNT(l.id) items,SUM(l.review_status<>'valid' OR i.review_status='needs_review') attention,COUNT(DISTINCT NULLIF(i.supplier_id,0)) suppliers FROM cw_supplier_invoices i LEFT JOIN cw_supplier_invoice_lines l ON l.supplier_invoice_id=i.id".($from?" WHERE $basis>=?" :'').($from&&$to?" AND $basis<=?":(!$from&&$to?" WHERE $basis<=?":''));$summaryParams=[];if($from)$summaryParams[]=$from;if($to)$summaryParams[]=$to;$summary=$pdo->prepare($summarySql);$summary->execute($summaryParams);
  $suppliers=$pdo->query("SELECT id,name,supplier_type FROM cw_suppliers WHERE active=1 ORDER BY name")->fetchAll();si_reply(['rows'=>$rows,'total'=>$total,'page'=>$page,'page_size'=>$size,'summary'=>$summary->fetch()?:[],'suppliers'=>$suppliers]);
 }
 if($action==='upload'){
  cw_require_admin();if(empty($_FILES['invoice_file'])||!is_uploaded_file((string)$_FILES['invoice_file']['tmp_name']))throw new RuntimeException('Select an invoice file.');$f=$_FILES['invoice_file'];if((int)$f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('The invoice did not upload successfully.');$size=(int)$f['size'];if($size<=0||$size>15*1024*1024)throw new RuntimeException('Invoice files must be 15 MB or smaller.');$ext=strtolower(pathinfo((string)$f['name'],PATHINFO_EXTENSION));$allowed=['pdf'=>'application/pdf','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png'];if(!isset($allowed[$ext]))throw new RuntimeException('Upload a supported PDF, JPG, JPEG or PNG invoice.');$mime=(string)(new finfo(FILEINFO_MIME_TYPE))->file((string)$f['tmp_name']);if($mime!==$allowed[$ext])throw new RuntimeException('The file content does not match its extension.');$hash=hash_file('sha256',(string)$f['tmp_name']);$dup=$pdo->prepare("SELECT id FROM cw_supplier_invoices WHERE file_hash=? AND approval_status<>'archived'");$dup->execute([$hash]);if($existing=(int)$dup->fetchColumn())si_reply(['error'=>'Possible duplicate: this exact invoice file already exists.','duplicate_id'=>$existing],409);
  $dir=BASE_PATH.'/uploads/cost-workbook/'.date('Y/m');if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Secure upload storage is unavailable.');$stored=date('YmdHis').'-'.bin2hex(random_bytes(8)).'.'.$ext;$relative='uploads/cost-workbook/'.date('Y/m').'/'.$stored;if(!move_uploaded_file((string)$f['tmp_name'],$dir.'/'.$stored))throw new RuntimeException('The invoice file could not be stored.');$u=cw_user();$pdo->prepare("INSERT INTO cw_supplier_invoices(uploaded_by,uploaded_by_name,original_filename,stored_file,file_type,file_hash,currency,extraction_status,extraction_message) VALUES(?,?,?,?,?,?,'NAD','not_started','Extracting invoice details')")->execute([$u['id'],$u['name'],basename((string)$f['name']),$relative,$mime,$hash]);$id=(int)$pdo->lastInsertId();$data=[];$message='Automatic extraction is unavailable for this file type. Enter the invoice manually.';$confidence='low';$status='manual_review';
  if($ext==='pdf'){$result=openai_extract_pdf($dir.'/'.$stored,basename((string)$f['name']),'supplier','');if($result['ok']){$data=$result['data'];$message=$result['message'];$confidence=(string)($data['confidence']??'medium');$status='complete';}else{$text=extract_pdf_text($dir.'/'.$stored);if(!empty($text['text'])){$data=parse_supplier_invoice_text((string)$text['text']);$message=$result['message'].' '.$text['message'];}$status=$data?'manual_review':'failed';}}
  $supplierName=trim((string)($data['supplier_name']??''));$supplierId=$supplierName!==''?si_supplier($pdo,$supplierName):0;$pdo->prepare('UPDATE cw_supplier_invoices SET supplier_id=?,supplier_name=?,invoice_number=?,invoice_date=?,currency=?,subtotal=?,vat_amount=?,invoice_total=?,extraction_status=?,extraction_confidence=?,extraction_message=? WHERE id=?')->execute([$supplierId?:null,$supplierName,(string)($data['invoice_number']??''),si_date($data['invoice_date']??''),strtoupper(substr((string)($data['currency']??'NAD'),0,3)),si_decimal($data['subtotal']??null),si_decimal($data['vat_amount']??null),si_decimal($data['total']??null),$status,$confidence,substr($message,0,500),$id]);
  $lines=array_merge((array)($data['raw_materials']??[]),(array)($data['packaging']??[]));$insert=$pdo->prepare("INSERT INTO cw_supplier_invoice_lines(supplier_invoice_id,raw_description,product_description,product_category,quantity,purchase_unit,unit_price,line_subtotal,line_total,item_type,match_status,review_status,extraction_confidence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");foreach($lines as $line){$name=trim((string)($line['name']??''));if($name==='')continue;$quantity=si_decimal($line['quantity']??null);$unit=trim((string)($line['unit']??''));$total=si_decimal($line['line_total']??null);$unitPrice=si_decimal($line['unit_price']??null);if($total===null&&$quantity!==null&&$unitPrice!==null)$total=number_format((float)$quantity*(float)$unitPrice,2,'.','');$insert->execute([$id,$name,$name,si_category($name),$quantity,$unit,$unitPrice,$total,$total,'unclassified','unmatched','needs_review',$confidence]);}
  si_reply(['ok'=>true,'id'=>$id,'message'=>$message,'stage'=>'ready_for_review']);
 }
 if($action==='invoice'){$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT * FROM cw_supplier_invoices WHERE id=?');$st->execute([$id]);$invoice=$st->fetch();if(!$invoice)si_reply(['error'=>'Invoice not found.'],404);$st=$pdo->prepare('SELECT * FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=? ORDER BY id');$st->execute([$id]);$suppliers=$pdo->query('SELECT id,name,supplier_type FROM cw_suppliers WHERE active=1 ORDER BY name')->fetchAll();si_reply(['invoice'=>$invoice,'lines'=>$st->fetchAll(),'suppliers'=>$suppliers,'original_url'=>'supplier-invoices-api.php?action=file&id='.$id]);}
 if($action==='save'){
  cw_require_admin();$b=si_body();$id=(int)($b['id']??0);$supplierName=trim((string)($b['supplier_name']??''));if($supplierName==='')throw new RuntimeException('Supplier name is required.');$supplierType=(string)($b['supplier_type']??'Uncategorised');if(!in_array($supplierType,si_types(true),true))throw new RuntimeException('Select a valid supplier type.');$invoiceType=(string)($b['invoice_type']??'Mixed');if(!in_array($invoiceType,si_types(false),true))throw new RuntimeException('Select a valid invoice type.');$date=si_date($b['invoice_date']??'');if(!$date)throw new RuntimeException('Enter a valid invoice date.');$number=trim((string)($b['invoice_number']??''));if($number==='')throw new RuntimeException('Invoice number is required.');$currency=strtoupper(trim((string)($b['currency']??'')));if(!preg_match('/^[A-Z]{3}$/',$currency))throw new RuntimeException('Enter a valid three-letter currency code.');$supplierId=si_supplier($pdo,$supplierName,$supplierType,true);$u=cw_user();$pdo->beginTransaction();$st=$pdo->prepare("SELECT * FROM cw_supplier_invoices WHERE id=? AND approval_status='draft' FOR UPDATE");$st->execute([$id]);if(!$st->fetch())throw new RuntimeException('Only draft invoices can be edited.');$dup=$pdo->prepare("SELECT id FROM cw_supplier_invoices WHERE id<>? AND supplier_id=? AND LOWER(TRIM(invoice_number))=LOWER(TRIM(?)) AND invoice_date=? AND approval_status<>'archived' LIMIT 1");$dup->execute([$id,$supplierId,$number,$date]);if($existing=(int)$dup->fetchColumn())throw new RuntimeException('Possible duplicate: invoice #'.$existing.' has the same supplier, invoice number and date.');
  $pdo->prepare("UPDATE cw_supplier_invoices SET supplier_id=?,supplier_name=?,supplier_type=?,invoice_type=?,invoice_number=?,invoice_date=?,currency=?,exchange_rate=?,subtotal=?,vat_amount=?,invoice_total=?,shipping_amount=?,review_status='reviewed',last_edited_by=?,last_edited_by_name=? WHERE id=?")->execute([$supplierId,$supplierName,$supplierType,$invoiceType,$number,$date,$currency,si_decimal($b['exchange_rate']??null)?:($currency==='NAD'?'1':null),si_decimal($b['subtotal']??null),si_decimal($b['vat_amount']??null),si_decimal($b['invoice_total']??null),si_decimal($b['shipping_amount']??null),$u['id'],$u['name'],$id]);
  $pdo->prepare('DELETE FROM cw_product_matches WHERE supplier_invoice_line_id IN (SELECT id FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=?)')->execute([$id]);$pdo->prepare('DELETE FROM cw_supplier_invoice_lines WHERE supplier_invoice_id=?')->execute([$id]);$insert=$pdo->prepare("INSERT INTO cw_supplier_invoice_lines(supplier_invoice_id,product_description,raw_description,supplier_sku,product_category,quantity,pack_size,purchase_unit,base_quantity,base_unit,line_subtotal,vat_amount,line_total,base_unit_cost,line_notes,item_type,match_status,review_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$valid=0;foreach((array)($b['lines']??[]) as $line){$name=trim((string)($line['product_description']??''));if($name==='')continue;$quantity=si_decimal($line['quantity']??null);$pack=si_decimal($line['pack_size']??null);$unit=trim((string)($line['purchase_unit']??''));list($base,$baseUnit,$error)=si_base($pdo,$quantity,$pack,$unit);$subtotal=si_decimal($line['line_subtotal']??null);$vat=si_decimal($line['vat_amount']??null);$cost=$base&&$subtotal!==null?number_format((float)$subtotal/(float)$base,6,'.',''):null;$review=$error===null&&$subtotal!==null?'valid':'needs_review';if($review==='valid')$valid++;$insert->execute([$id,$name,$name,trim((string)($line['supplier_sku']??'')),in_array($line['product_category']??'',si_categories(),true)?$line['product_category']:'Other',$quantity,$pack,$unit,$base,$baseUnit,$subtotal,$vat,number_format((float)$subtotal+(float)$vat,2,'.',''),$cost,trim((string)($line['line_notes']??'')),'unclassified','unmatched',$review]);}$pdo->commit();si_reply(['ok'=>true,'id'=>$id,'valid_lines'=>$valid,'message'=>'Invoice saved. Missing or uncertain fields remain highlighted.']);
 }
 if($action==='file'){$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT original_filename,stored_file,file_type FROM cw_supplier_invoices WHERE id=?');$st->execute([$id]);$file=$st->fetch();$path=$file?BASE_PATH.'/'.$file['stored_file']:'';if(!$file||!is_file($path))throw new RuntimeException('Original invoice file is unavailable.');header_remove('Content-Type');header('Content-Type: '.$file['file_type']);header('Content-Disposition: inline; filename="'.rawurlencode((string)$file['original_filename']).'"');header('X-Content-Type-Options: nosniff');readfile($path);exit;}
 si_reply(['error'=>'Unknown action.'],404);
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();si_reply(['error'=>$e->getMessage()],http_response_code()>=400?http_response_code():422);}
