<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/cost-workbook.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

function wp_reply(array $data,int $status=200):void{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function wp_body():array{$raw=file_get_contents('php://input');$data=json_decode((string)$raw,true);return is_array($data)?$data:$_POST;}
function wp_user():array{$u=current_user();return ['id'=>(int)($u['id']??0),'name'=>(string)($u['name']??$u['full_name']??'Owner')];}
function wp_json($value):string{return (string)json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
function wp_num($value,float $default=0):float{return is_numeric($value)?(float)$value:$default;}
function wp_settings(PDO $pdo):array{$out=[];$st=$pdo->query("SELECT setting_key,setting_value FROM cw_settings WHERE setting_key IN('wholesale_vat_rate','wholesale_minimum_margin','wholesale_default_margin','wholesale_rounding_rule')");foreach($st->fetchAll() as $row)$out[$row['setting_key']]=$row['setting_value'];return$out;}
function wp_round(float $price,string $rule):float{if($rule==='none')return round($price,2);if($rule==='up1')return ceil($price);if($rule==='up5')return ceil($price/5)*5;$step=max(.01,(float)$rule);return round($price/$step)*$step;}
function wp_products(PDO $pdo):array{
  $rows=$pdo->query("SELECT CONCAT('p:',p.id) product_key,'purchased' product_type,p.id product_id,p.product_name,p.short_code,p.product_category category,p.costing_basis,p.base_unit,c.id cost_source_id,CAST(c.id AS CHAR) cost_source_version,c.cost_date source_cost_date,c.landed_cost_per_base base_cost FROM cw_cost_products p JOIN cw_landed_product_costs c ON c.product_id=p.id WHERE p.active=1 AND c.id=(SELECT c2.id FROM cw_landed_product_costs c2 WHERE c2.product_id=p.id ORDER BY c2.cost_date DESC,c2.id DESC LIMIT 1) ORDER BY p.product_name")->fetchAll();
  $forms=$pdo->query("SELECT f.id,f.formulation_name product_name,f.formulation_code short_code,f.category,f.formulation_type costing_basis,v.id cost_source_id,v.version_no,v.effective_date source_cost_date,v.yield_unit,v.totals_json FROM cw_formulations f JOIN cw_formulation_versions v ON v.formulation_id=f.id AND v.version_no=f.current_version WHERE f.active=1 AND f.status_key='active' ORDER BY f.formulation_name")->fetchAll();
  foreach($forms as $f){$totals=json_decode((string)$f['totals_json'],true);$unit=(string)$f['yield_unit'];$rows[]=['product_key'=>'f:'.$f['id'],'product_type'=>'manufactured','product_id'=>$f['id'],'product_name'=>$f['product_name'],'short_code'=>$f['short_code'],'category'=>$f['category'],'costing_basis'=>$f['costing_basis'],'base_unit'=>$unit,'cost_source_id'=>$f['cost_source_id'],'cost_source_version'=>(string)$f['version_no'],'source_cost_date'=>$f['source_cost_date'],'base_cost'=>wp_num($totals['cost_per_yield_unit']??0)];}
  return $rows;
}
function wp_list(PDO $pdo,bool $history=false):array{$where=$history?'':' AND v.version_no=w.current_version';$sql="SELECT w.*,v.*,w.id wholesale_price_id,w.status_key current_status FROM cw_wholesale_prices w JOIN cw_wholesale_price_versions v ON v.wholesale_price_id=w.id WHERE w.active=1{$where} ORDER BY w.product_name,w.quantity,v.version_no DESC";$rows=$pdo->query($sql)->fetchAll();foreach($rows as &$row){$row['payload']=json_decode((string)$row['payload_json'],true)?:[];$row['tiers']=json_decode((string)$row['tiers_json'],true)?:[];}return$rows;}
function wp_calculate(array $b,array $settings):array{
  $base=max(0,wp_num($b['base_cost']??0));$qty=max(.000001,wp_num($b['quantity']??0));$content=$base*$qty;$vatRate=max(0,wp_num($settings['wholesale_vat_rate']??15));$packSource=(string)($b['packaging_source']??'required');$pack=0;$packVat=0;
  if($packSource==='setup')$pack=max(0,wp_num($b['packaging_setup_cost']??0));
  elseif($packSource==='manual'){$amount=max(0,wp_num($b['manual_packaging_amount']??0));$basis=(string)($b['packaging_cost_basis']??'exclusive');$treatment=(string)($b['packaging_vat_treatment']??'recoverable');if($basis==='inclusive'&&$treatment==='recoverable'){$pack=$amount/(1+$vatRate/100);$packVat=$amount-$pack;}else{$pack=$amount;$packVat=$basis==='exclusive'&&$treatment==='recoverable'?$amount*$vatRate/100:0;}}
  $otherKeys=['repacking_labour','wholesale_handling','outer_carton','protective_wrapping','pallet_contribution','other_cost'];$other=0;foreach($otherKeys as $key)$other+=max(0,wp_num($b[$key]??0));$total=$content+$pack+$other;$method=(string)($b['pricing_method']??'margin');$target=wp_num($b['target_margin']??($settings['wholesale_default_margin']??35));if($method==='margin'){$unrounded=$target>=100?0:$total/(1-$target/100);}elseif($method==='profit')$unrounded=$total+max(0,wp_num($b['desired_profit']??0));else$unrounded=max(0,wp_num($b['manual_price']??0));$price=wp_round($unrounded,(string)($b['rounding_rule']??($settings['wholesale_rounding_rule']??'.50')));$outputVat=$price*$vatRate/100;$inc=$price+$outputVat;$profit=$price-$total;$margin=$price>0?$profit/$price*100:0;$markup=$total>0?$profit/$total*100:0;$minimum=wp_num($settings['wholesale_minimum_margin']??20);$minimumPrice=$minimum>=100?0:$total/(1-$minimum/100);
  return ['product_content_cost'=>$content,'packaging_cost_used'=>$pack,'packaging_vat'=>$packVat,'other_costs'=>$other,'total_cost_ex_vat'=>$total,'unrounded_price_ex_vat'=>$unrounded,'price_ex_vat'=>$price,'output_vat'=>$outputVat,'price_inc_vat'=>$inc,'profit'=>$profit,'margin_percent'=>$margin,'markup_percent'=>$markup,'minimum_price_ex_vat'=>$minimumPrice,'below_minimum'=>$margin<$minimum];
}

try{
  $pdo=db();cw_install_schema($pdo);$action=(string)($_GET['action']??'bootstrap');if($_SERVER['REQUEST_METHOD']!=='GET')cw_require_csrf();
  if($action==='bootstrap'){$settings=wp_settings($pdo);$sizes=$pdo->query("SELECT id,label,measurement_type,base_value,base_unit FROM cw_size_conversions WHERE active=1 ORDER BY measurement_type,base_value")->fetchAll();$setups=$pdo->query("SELECT ps.id,ps.setup_name,ps.size_conversion_id,GROUP_CONCAT(CONCAT(pi.item_name,' × ',pc.quantity) ORDER BY pc.display_order SEPARATOR ', ') components,COALESCE(SUM(pc.component_cost_ex),0) cost_ex_vat FROM cw_packaging_setups ps LEFT JOIN cw_packaging_setup_components pc ON pc.packaging_setup_id=ps.id LEFT JOIN cw_packaging_items pi ON pi.id=pc.packaging_item_id WHERE ps.active=1 GROUP BY ps.id ORDER BY ps.setup_name")->fetchAll();wp_reply(['ok'=>true,'prices'=>wp_list($pdo,($_GET['history']??'')==='all'),'products'=>wp_products($pdo),'sizes'=>$sizes,'packaging_setups'=>$setups,'settings'=>$settings]);}
  if($action==='calculate'){$b=wp_body();wp_reply(['ok'=>true,'calculation'=>wp_calculate($b,wp_settings($pdo))]);}
  if($action==='save'){
    $b=wp_body();$products=wp_products($pdo);$product=null;foreach($products as $candidate)if($candidate['product_key']===($b['product_key']??'')){$product=$candidate;break;}if(!$product)throw new RuntimeException('Select a product with a current landed or approved formulation cost.');
    $label=trim((string)($b['wholesale_size_label']??''));$qty=wp_num($b['quantity']??0);$effective=(string)($b['effective_date']??'');if($label===''||$qty<=0||$effective==='')throw new RuntimeException('Product, wholesale size, quantity and effective date are required.');if(($b['packaging_source']??'required')==='required')throw new RuntimeException('Choose a packaging setup, enter manual packaging, or deliberately select no additional packaging.');
    $b['base_cost']=$product['base_cost'];if(($b['packaging_source']??'')==='setup'){$setupId=(int)($b['packaging_setup_id']??0);$st=$pdo->prepare("SELECT COALESCE(SUM(component_cost_ex),0) FROM cw_packaging_setup_components WHERE packaging_setup_id=?");$st->execute([$setupId]);$b['packaging_setup_cost']=(float)$st->fetchColumn();if($setupId<1)throw new RuntimeException('Select a packaging setup.');}
    $calc=wp_calculate($b,wp_settings($pdo));if($calc['below_minimum']&&trim((string)($b['below_minimum_reason']??''))==='')throw new RuntimeException('This price is below the configured minimum margin. Enter a reason to confirm the override.');
    $id=(int)($b['id']??0);$newVersion=!empty($b['new_version']);$u=wp_user();$pdo->beginTransaction();
    if($id){$st=$pdo->prepare('SELECT * FROM cw_wholesale_prices WHERE id=? FOR UPDATE');$st->execute([$id]);$current=$st->fetch();if(!$current)throw new RuntimeException('Wholesale price not found.');$version=$newVersion?((int)$current['current_version']+1):(int)$current['current_version'];if(!$newVersion&&in_array($current['status_key'],['active','future'],true))throw new RuntimeException('Approved wholesale prices are immutable. Recalculate as a new version.');$pdo->prepare('UPDATE cw_wholesale_prices SET product_type=?,product_id=?,product_name=?,short_code=?,category=?,wholesale_size_label=?,size_conversion_id=?,quantity=?,unit=?,moq=?,status_key=?,current_version=?,effective_date=?,expiry_date=?,updated_by=?,updated_by_name=? WHERE id=?')->execute([$product['product_type'],$product['product_id'],$product['product_name'],$product['short_code'],$product['category'],$label,($b['size_conversion_id']??'')?:null,$qty,(string)($b['unit']??$product['base_unit']),max(1,wp_num($b['moq']??1)),(string)($b['status_key']??'draft'),$version,$effective,($b['expiry_date']??'')?:null,$u['id'],$u['name'],$id]);if($newVersion)$pdo->prepare("UPDATE cw_wholesale_price_versions SET version_status='superseded' WHERE wholesale_price_id=? AND version_status IN('active','future','ready')")->execute([$id]);}
    else{$version=1;$pdo->prepare('INSERT INTO cw_wholesale_prices(product_type,product_id,product_name,short_code,category,wholesale_size_label,size_conversion_id,quantity,unit,moq,status_key,effective_date,expiry_date,created_by,created_by_name,updated_by,updated_by_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$product['product_type'],$product['product_id'],$product['product_name'],$product['short_code'],$product['category'],$label,($b['size_conversion_id']??'')?:null,$qty,(string)($b['unit']??$product['base_unit']),max(1,wp_num($b['moq']??1)),(string)($b['status_key']??'draft'),$effective,($b['expiry_date']??'')?:null,$u['id'],$u['name'],$u['id'],$u['name']]);$id=(int)$pdo->lastInsertId();}
    if(in_array((string)($b['status_key']??''),['active','future'],true)){$overlap=$pdo->prepare("SELECT COUNT(*) FROM cw_wholesale_prices WHERE id<>? AND active=1 AND product_type=? AND product_id=? AND wholesale_size_label=? AND moq=? AND status_key IN('active','future') AND effective_date<=COALESCE(?, '9999-12-31') AND COALESCE(expiry_date,'9999-12-31')>=?");$overlap->execute([$id,$product['product_type'],$product['product_id'],$label,max(1,wp_num($b['moq']??1)),($b['expiry_date']??'')?:null,$effective]);if((int)$overlap->fetchColumn()>0)throw new RuntimeException('An active wholesale price already overlaps this product, size, MOQ and effective period.');}
    $status=(string)($b['status_key']??'draft');$payload=[$id,$version,$status,$product['product_type']==='manufactured'?'formulation':'landed',$product['cost_source_id'],$product['cost_source_version'],$product['source_cost_date'],$product['base_cost'],$calc['product_content_cost'],(string)$b['packaging_source'],($b['packaging_setup_id']??'')?:null,$calc['packaging_cost_used'],(string)($b['pricing_method']??'margin'),wp_num($b['target_margin']??0),wp_num($b['desired_profit']??0),wp_num($b['manual_price']??0),$calc['total_cost_ex_vat'],$calc['unrounded_price_ex_vat'],$calc['price_ex_vat'],$calc['output_vat'],$calc['price_inc_vat'],$calc['profit'],$calc['margin_percent'],$calc['markup_percent'],$calc['minimum_price_ex_vat'],($b['below_minimum_reason']??'')?:null,$effective,($b['expiry_date']??'')?:null,wp_json($b),wp_json($b['tiers']??[]),$u['id'],$u['name']];
    $pdo->prepare("INSERT INTO cw_wholesale_price_versions(wholesale_price_id,version_no,version_status,cost_source_type,cost_source_id,cost_source_version,source_cost_date,base_cost,product_content_cost,packaging_source,packaging_setup_id,packaging_cost_used,pricing_method,target_margin,desired_profit,manual_price,total_cost_ex_vat,unrounded_price_ex_vat,price_ex_vat,output_vat,price_inc_vat,profit,margin_percent,markup_percent,minimum_price_ex_vat,below_minimum_reason,effective_date,expiry_date,payload_json,tiers_json,created_by,created_by_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE version_status=VALUES(version_status),payload_json=VALUES(payload_json),tiers_json=VALUES(tiers_json),base_cost=VALUES(base_cost),product_content_cost=VALUES(product_content_cost),packaging_cost_used=VALUES(packaging_cost_used),total_cost_ex_vat=VALUES(total_cost_ex_vat),unrounded_price_ex_vat=VALUES(unrounded_price_ex_vat),price_ex_vat=VALUES(price_ex_vat),output_vat=VALUES(output_vat),price_inc_vat=VALUES(price_inc_vat),profit=VALUES(profit),margin_percent=VALUES(margin_percent),markup_percent=VALUES(markup_percent),minimum_price_ex_vat=VALUES(minimum_price_ex_vat),below_minimum_reason=VALUES(below_minimum_reason),created_by=VALUES(created_by),created_by_name=VALUES(created_by_name),created_at=CURRENT_TIMESTAMP")->execute($payload);
    $pdo->prepare('INSERT INTO cw_wholesale_price_audit(wholesale_price_id,action_key,after_json,actor_id,actor_name) VALUES(?,?,?,?,?)')->execute([$id,$newVersion?'new_version':'saved',wp_json(['version'=>$version,'calculation'=>$calc]),$u['id'],$u['name']]);$pdo->commit();wp_reply(['ok'=>true,'id'=>$id,'version'=>$version,'calculation'=>$calc,'message'=>$newVersion?'New wholesale price version saved.':'Wholesale price saved.']);
  }
  if($action==='archive'){$id=(int)(wp_body()['id']??0);$u=wp_user();$pdo->prepare("UPDATE cw_wholesale_prices SET active=0,status_key='archived',updated_by=?,updated_by_name=? WHERE id=?")->execute([$u['id'],$u['name'],$id]);$pdo->prepare("INSERT INTO cw_wholesale_price_audit(wholesale_price_id,action_key,actor_id,actor_name) VALUES(?,'archived',?,?)")->execute([$id,$u['id'],$u['name']]);wp_reply(['ok'=>true]);}
  throw new RuntimeException('Unsupported action.');
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Wholesale pricing: '.get_class($e).' '.$e->getMessage());wp_reply(['ok'=>false,'message'=>$e->getMessage()],400);}
