<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/cost-workbook.php';
require_role('owner_admin', 'supervisor_manager');
$pageTitle='Cost Workbook | '.APP_NAME; $activeApp='cost-manager'; $bootError=null;
try { cw_install_schema(db()); } catch(Throwable $e) { $bootError=$e->getMessage(); }
include BASE_PATH.'/shared/header.php'; include BASE_PATH.'/shared/sidebar.php';
?>
<link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/cost-workbook.css?v=1">
<link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/cost-workbook-invoice.css?v=1">
<main class="workspace cw" id="costWorkbook" data-api="cw-api.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
 <header class="cw-hero"><div><p class="cw-eyebrow">Hambelela Organic</p><h1>Cost Workbook</h1><p>Review supplier costs, connect website products, and prepare reliable landed-cost decisions.</p></div><button class="cw-btn cw-primary" data-open-upload>Upload invoice</button></header>
 <?php if($bootError): ?><div class="cw-alert cw-error" role="alert"><strong>Cost Workbook setup needs attention.</strong> <?= htmlspecialchars($bootError,ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
 <div id="cwNotice" class="cw-alert" hidden></div>
 <nav class="cw-steps" aria-label="Workbook sections">
 <?php foreach(['Overview','Supplier Invoices','Transport','Packaging & Additional Costs','Landed Cost','Product Variations','Website Products & Profitability','Cost History','Exports','Settings'] as $i=>$label): ?><a href="#cw-section-<?= $i+1 ?>"><span><?= $i+1 ?></span><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></a><?php endforeach; ?>
 </nav>
 <section class="cw-section" id="cw-section-1" open><button class="cw-section-title" aria-expanded="true"><span><b>1</b> Overview</span><i>⌃</i></button><div class="cw-section-body"><div class="cw-metrics"><article><span>Active invoices</span><strong id="metricInvoices">—</strong></article><article><span>Needs review</span><strong id="metricReview">—</strong></article><article><span>Approved invoices</span><strong id="metricApproved">—</strong></article><article><span>Website items</span><strong id="metricWebsite">—</strong></article></div></div></section>
 <section class="cw-section" id="cw-section-2"><button class="cw-section-title" aria-expanded="true"><span><b>2</b> Supplier Invoices</span><i>⌃</i></button><div class="cw-section-body"><div class="cw-toolbar"><div><h2>Supplier invoice intake</h2><p>Uploads remain drafts until every required value is reviewed.</p></div><button class="cw-btn cw-primary" data-open-upload>Upload invoice</button></div><div class="cw-table-wrap"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Currency</th><th>Total</th><th>Lines</th><th>Extraction</th><th>Review</th><th>Approval</th><th>Transport</th><th>Uploaded by</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody id="invoiceRows"><tr><td colspan="13" class="cw-empty">Loading invoices…</td></tr></tbody></table></div></div></section>
 <?php $future=[3=>['Transport','Phase 2 will add transport-invoice upload, linking and allocation.'],4=>['Packaging & Additional Costs','Phase 2 will allocate confirmed packaging and additional costs.'],5=>['Landed Cost','Awaiting approved invoice costs and Phase 2 allocations.'],6=>['Product Variations','Recipes and variation costing will follow in Phase 2.']]; foreach($future as $n=>$x): ?><section class="cw-section" id="cw-section-<?= $n ?>"><button class="cw-section-title" aria-expanded="false"><span><b><?= $n ?></b> <?= $x[0] ?></span><i>⌄</i></button><div class="cw-section-body" hidden><div class="cw-empty-state"><strong>Future step</strong><p><?= $x[1] ?></p></div></div></section><?php endforeach; ?>
 <section class="cw-section" id="cw-section-7"><button class="cw-section-title" aria-expanded="true"><span><b>7</b> Website Products &amp; Profitability</span><i>⌃</i></button><div class="cw-section-body"><div class="cw-toolbar"><div><h2>Read-only WooCommerce snapshot</h2><p id="lastSync">No successful sync yet.</p><p id="snapshotStats">No snapshot counts yet.</p><p id="syncStatus" aria-live="polite">No sync attempt is active.</p></div><div class="cw-actions"><button class="cw-btn cw-primary" id="syncWebsite">Sync Website Data</button><button class="cw-btn" id="recoverSync" hidden>Recover interrupted sync</button></div></div><div class="cw-progress" id="syncProgress" hidden><span></span><p>Starting sync…</p></div><div class="cw-product-filters"><label>Search snapshot <input id="productSearch" placeholder="Product, variation or SKU"></label><label>Category <select id="productCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><thead><tr><th>Product</th><th>Variation</th><th>SKU</th><th>Type</th><th>Category</th><th>Price incl. VAT</th><th>Stock</th><th>Status</th><th>Cost status</th></tr></thead><tbody id="productRows"><tr><td colspan="9" class="cw-empty">Sync website data to create a snapshot.</td></tr></tbody></table></div></div></section>
 <section class="cw-section" id="cw-section-8"><button class="cw-section-title" aria-expanded="false"><span><b>8</b> Cost History</span><i>⌄</i></button><div class="cw-section-body" hidden><div class="cw-empty-state"><strong>Future step</strong><p>Dated approved cost history will appear here.</p></div></div></section>
 <section class="cw-section" id="cw-section-9"><button class="cw-section-title" aria-expanded="false"><span><b>9</b> Exports</span><i>⌄</i></button><div class="cw-section-body" hidden><div class="cw-empty-state"><strong>Future step</strong><p>Excel and CSV exports will be enabled after the costing workflow is complete.</p></div></div></section>
 <section class="cw-section" id="cw-section-10"><button class="cw-section-title" aria-expanded="true"><span><b>10</b> Settings</span><i>⌃</i></button><div class="cw-section-body"><form id="settingsForm" class="cw-settings"><label>Base currency<input name="base_currency" maxlength="3" value="NAD" required></label><label>VAT rate (%)<input name="vat_rate" type="number" step="0.01" min="0" value="15" required></label><label>Retail target margin (%)<input name="retail_target_margin" type="number" step="0.01" min="0" max="99.99" placeholder="Not selected"></label><label>Wholesale target margin (%)<input name="wholesale_target_margin" type="number" step="0.01" min="0" max="99.99" placeholder="Not selected"></label><label>Reseller target margin (%)<input name="reseller_target_margin" type="number" step="0.01" min="0" max="99.99" placeholder="Not selected"></label><label>Low-margin threshold (%)<input name="low_margin_threshold" type="number" step="0.01" min="0" max="100" placeholder="Not selected"></label><div class="cw-help"><p><strong>Gross margin</strong> measures profit as a percentage of the selling price excluding VAT.</p><p><strong>Markup</strong> measures profit as a percentage of cost.</p></div><button class="cw-btn cw-primary" type="submit">Save settings</button></form></div></section>
</main>
<dialog id="uploadDialog" class="cw-dialog"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Upload supplier invoices</h2><p>PDF, JPG, JPEG, PNG, XLSX or CSV; up to 15 MB each.</p><form id="uploadForm"><label class="cw-drop"><input type="file" name="invoice_files[]" multiple accept=".pdf,.jpg,.jpeg,.png,.xlsx,.csv"><strong>Drop invoices here or choose files</strong><span>Each file becomes its own draft invoice.</span></label><div id="uploadResults"></div><button class="cw-btn cw-primary" type="submit">Upload selected files</button></form></dialog>
<dialog id="reviewDialog" class="cw-dialog cw-review"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Review invoice</h2><form id="reviewForm"><input type="hidden" name="id"><div class="cw-form-grid"><label>Supplier<input name="supplier_name" required></label><label>Invoice number<input name="invoice_number" required></label><label>Invoice date<input name="invoice_date" type="date" required></label><label>Currency<input name="currency" maxlength="3" required></label><label>Exchange rate<input name="exchange_rate" type="number" step="0.000001" min="0.000001" inputmode="decimal" required></label><label>VAT treatment<select name="vat_treatment" required><option value="unconfirmed">Confirm treatment</option><option value="inclusive">Inclusive</option><option value="exclusive">Exclusive</option><option value="exempt">Exempt</option><option value="mixed">Mixed</option></select></label><label>Subtotal<input name="subtotal" type="number" step="0.01" readonly></label><label>VAT amount<input name="vat_amount" type="number" step="0.01" readonly></label><label>Invoice total<input name="invoice_total" type="number" step="0.01" readonly></label><label class="wide">Notes<textarea name="notes"></textarea></label></div><div class="cw-toolbar"><h3>Invoice lines</h3><button class="cw-btn" id="addLine" type="button">Add line</button></div><div class="cw-table-wrap cw-line-table"><table><thead><tr><th>Original description</th><th>Product name</th><th>Qty</th><th>Unit</th><th>Pack size</th><th>Unit cost</th><th>Discount</th><th>Subtotal</th><th>VAT</th><th>Total</th><th>Type</th><th></th></tr></thead><tbody id="reviewLines"></tbody></table></div><p class="cw-help">Discount is a fixed monetary amount. Totals are recalculated securely when the invoice is saved.</p><div class="cw-dialog-actions"><button class="cw-btn cw-primary" type="submit">Save review</button><button class="cw-btn" id="approveInvoice" type="button">Approve</button></div></form></dialog>
<dialog id="matchDialog" class="cw-dialog cw-match-dialog"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Match website item</h2><p>Search the successful read-only website snapshot. Choosing a result does not modify WooCommerce.</p><div class="cw-product-filters"><label>Product or variation <input id="matchSearch" placeholder="Name, variation or SKU"></label><label>Category <select id="matchCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><thead><tr><th>Product</th><th>Variation</th><th>SKU</th><th>Type</th><th>Category</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody id="matchRows"><tr><td colspan="8" class="cw-empty">Enter a search or select a category.</td></tr></tbody></table></div></dialog>
<template id="lineTemplate"><tr><td><input data-k="raw_description"></td><td><input data-k="product_description" required></td><td><input data-k="quantity" type="number" step="0.000001" min="0" inputmode="decimal" required></td><td><select data-k="purchase_unit"><option value="">Confirm</option><option>kg</option><option>g</option><option>L</option><option>ml</option><option>unit</option><option>pack</option></select></td><td><input data-k="pack_size" type="number" step="0.000001" min="0" inputmode="decimal"></td><td><input data-k="unit_price" type="number" step="0.000001" min="0" inputmode="decimal" required></td><td><input data-k="discount" type="number" step="0.01" min="0" inputmode="decimal" value="0.00" required></td><td><input data-k="line_subtotal" type="number" step="0.01" readonly></td><td><input data-k="vat_amount" type="number" step="0.01" min="0" inputmode="decimal" value="0.00" required></td><td><input data-k="line_total" type="number" step="0.01" readonly></td><td><select data-k="item_type"><option value="unclassified">Confirm type</option><option value="supplier_raw_material">Raw material</option><option value="website_product">Website product</option><option value="website_variation">Website variation</option><option value="packaging">Packaging</option><option value="additional_cost">Additional cost</option></select><button class="cw-btn" data-match-line type="button">Match website item</button></td><td><button class="cw-icon" data-remove-line type="button" aria-label="Remove line">×</button></td></tr></template>
<script src="<?= BASE_URL ?>/assets/js/cost-workbook.js?v=4" defer></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
