<?php
declare(strict_types=1);
namespace Hambelela\EPI;
use DateInterval;use DateTimeImmutable;use PDO;

/** Read-only Phase 6 cash-control analytics. All money is calculated as integer cents. */
final class BookkeepingPerformance
{
    private $pdo;private $settings=[];
    public function __construct(PDO$pdo){$this->pdo=$pdo;$this->settings=$this->loadSettings();Performance::configure($pdo);}
    public function getSummary(array$f=[]):array{$o=$this->reconcile($f);$d=$this->getDailyReconciliation($f);$v=$this->getVarianceSummary($f);$p=$this->getDepositPerformance($f);return['period'=>$this->periodPayload($f),'eligible_cash_orders'=>count($o),'matched_entries'=>count(array_filter($o,fn($x)=>in_array($x['match_status'],['exact_match','date_mismatch'],true))),'missing_entries'=>count(array_filter($o,fn($x)=>$x['match_status']==='missing_bookkeeping_entry')),'duplicate_entries'=>count(array_filter($o,fn($x)=>$x['match_status']==='duplicate_bookkeeping_entry')),'amount_mismatches'=>count(array_filter($o,fn($x)=>$x['match_status']==='amount_mismatch')),'requires_review'=>count(array_filter($o,fn($x)=>$x['requires_review'])),'expected_cash_cents'=>array_sum(array_column($o,'expected_cash_cents')),'recorded_cash_cents'=>array_sum(array_column($o,'actual_cash_cents')),'daily_controls'=>$d['summary'],'variance'=>$v,'deposits'=>$p['summary'],'current_risk'=>$this->getOutstandingRisk($f),'scoring_status'=>'not_calculated','financial_calculation'=>'integer_cents','methodology'=>'Direct IDs and exact references are automatic. Amount/date/customer candidates remain owner review only.'];}
    public function getEmployeeSummary(array$f=[]):array{$rows=$this->reconcile($f);$out=[];foreach($rows as$r){$id=(int)($r['created_by_id']??0);$k=(string)$id;if(!isset($out[$k]))$out[$k]=['employee_id'=>$id?:null,'employee_name'=>$r['created_by_name']?:'Insufficient historical data','eligible_cash_orders'=>0,'matched_entries'=>0,'missing_entries'=>0,'late_entries'=>0,'expected_cash_cents'=>0,'recorded_cash_cents'=>0];$out[$k]['eligible_cash_orders']++;$out[$k]['expected_cash_cents']+=$r['expected_cash_cents'];$out[$k]['recorded_cash_cents']+=$r['actual_cash_cents'];if(in_array($r['match_status'],['exact_match','date_mismatch'],true))$out[$k]['matched_entries']++;if($r['match_status']==='missing_bookkeeping_entry')$out[$k]['missing_entries']++;if($r['timing_status']==='late')$out[$k]['late_entries']++;}return array_values($out);}
    public function getOrderReconciliation(array$f=[]):array{return$this->reconcile($f);}
    public function getCashEntryCompliance(array$f=[]):array{$r=$this->reconcile($f);$timed=array_values(array_filter($r,fn($x)=>$x['delay_business_minutes']!==null));$delays=array_column($timed,'delay_business_minutes');sort($delays,SORT_NUMERIC);return['same_day'=>count(array_filter($timed,fn($x)=>$x['timing_status']==='on_time')),'next_business_day'=>count(array_filter($timed,fn($x)=>$x['timing_status']==='next_business_day')),'late'=>count(array_filter($timed,fn($x)=>$x['timing_status']==='late')),'missing'=>count(array_filter($r,fn($x)=>$x['match_status']==='missing_bookkeeping_entry')),'average_business_minutes'=>$delays?round(array_sum($delays)/count($delays),2):null,'median_business_minutes'=>$this->median($delays),'fastest_business_minutes'=>$delays?$delays[0]:null,'slowest_business_minutes'=>$delays?$delays[count($delays)-1]:null];}
    public function getDailyReconciliation(array$f=[]):array
    {[$a,$b]=$this->period($f);$s=$this->pdo->prepare("SELECT DATE(transaction_date) business_date,SUM(ROUND(cash_in*100)) cash_in_cents,SUM(ROUND(cash_out*100)) cash_out_cents,SUM(CASE WHEN source='opening_balance' OR transaction_type='opening_balance' THEN 1 ELSE 0 END) opening_count,SUM(CASE WHEN source='opening_balance' OR transaction_type='opening_balance' THEN ROUND(cash_in*100) ELSE 0 END) opening_cents FROM ops_cash_book_entries WHERE deleted_at IS NULL AND COALESCE(status,'active')='active' AND DATE(transaction_date) BETWEEN ? AND ? GROUP BY DATE(transaction_date) ORDER BY business_date DESC");$s->execute([$a->format('Y-m-d'),$b->format('Y-m-d')]);$days=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$re=$this->pdo->prepare('SELECT r.*,e.full_name reconciled_by FROM hambelela_cashbook_recon r LEFT JOIN ops_employees e ON e.id=r.logged_by WHERE r.recon_date BETWEEN ? AND ? ORDER BY r.recon_date,r.id');$re->execute([$a->format('Y-m-d'),$b->format('Y-m-d')]);$latest=[];foreach($re->fetchAll(PDO::FETCH_ASSOC)?:[]as$x)$latest[$x['recon_date']]=$x;$summary=['days_with_entries'=>count($days),'fully_reconciled'=>0,'unreconciled'=>0,'shortage_days'=>0,'overage_days'=>0,'missing_opening'=>0,'duplicate_opening'=>0];foreach($days as&$d){$r=$latest[$d['business_date']]??null;$d['cash_in_cents']=(int)$d['cash_in_cents'];$d['cash_out_cents']=(int)$d['cash_out_cents'];$d['opening_cents']=(int)$d['opening_cents'];$d['opening_status']=(int)$d['opening_count']===0?'missing':((int)$d['opening_count']>1?'duplicate':'recorded');$d['reconciliation']=$r?['id'=>(int)$r['id'],'expected_closing_cents'=>$this->cents($r['system_balance']),'actual_closing_cents'=>$this->cents($r['counted_total']),'variance_cents'=>$this->cents($r['variance']),'reconciled_by'=>$r['reconciled_by']?:'Insufficient historical data','created_at'=>$r['created_at']]:null;if(!$r)$summary['unreconciled']++;else{$summary['fully_reconciled']++;$v=$this->cents($r['variance']);if($v<0)$summary['shortage_days']++;elseif($v>0)$summary['overage_days']++;}if($d['opening_status']==='missing')$summary['missing_opening']++;elseif($d['opening_status']==='duplicate')$summary['duplicate_opening']++;}unset($d);return['summary'=>$summary,'days'=>$days,'opening_balance_rule'=>'One active opening balance per business date; enforced by the operational ledger before insert or date move.'];}
    public function getVarianceSummary(array$f=[]):array{[$a,$b]=$this->period($f);$s=$this->pdo->prepare('SELECT r.*,e.full_name reconciled_by FROM hambelela_cashbook_recon r LEFT JOIN ops_employees e ON e.id=r.logged_by WHERE r.recon_date BETWEEN ? AND ? ORDER BY r.recon_date DESC,r.id DESC');$s->execute([$a->format('Y-m-d'),$b->format('Y-m-d')]);$rows=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$short=0;$over=0;$sc=0;$oc=0;foreach($rows as&$r){$r['variance_cents']=$this->cents($r['variance']);if($r['variance_cents']<0){$short+=abs($r['variance_cents']);$sc++;}elseif($r['variance_cents']>0){$over+=$r['variance_cents'];$oc++;}}unset($r);return['shortage_cents'=>$short,'overage_cents'=>$over,'shortage_days'=>$sc,'overage_days'=>$oc,'exact_days'=>count(array_filter($rows,fn($x)=>$x['variance_cents']===0)),'unresolved_count'=>count(array_filter($rows,fn($x)=>$x['variance_cents']!==0&&trim((string)$x['variance_note'])==='')),'records'=>$rows];}
    public function getDepositPerformance(array$f=[]):array{[$a,$b]=$this->period($f);$s=$this->pdo->prepare("SELECT b.*,COALESCE(e.full_name,b.created_by_name) recorded_by_name FROM ops_cash_book_entries b LEFT JOIN ops_employees e ON e.id=COALESCE(b.created_by_user_id,b.recorded_by) WHERE DATE(b.transaction_date) BETWEEN ? AND ? AND b.deleted_at IS NULL AND COALESCE(b.status,'active')='active' AND CONCAT_WS(' ',b.transaction_type,b.source,b.description) REGEXP 'deposit|banking' ORDER BY b.transaction_date DESC");$s->execute([$a->format('Y-m-d'),$b->format('Y-m-d')]);$rows=$s->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($rows as&$r){$r['deposit_amount_cents']=max($this->cents($r['cash_in']),$this->cents($r['cash_out']));$r['timing_status']=$this->depositConfigured()?'recorded_requires_schedule_review':'insufficient_historical_data';}unset($r);return['summary'=>['recorded'=>count($rows),'amount_cents'=>array_sum(array_column($rows,'deposit_amount_cents')),'schedule_configured'=>$this->depositConfigured(),'on_time'=>null,'late'=>null,'missing'=>null],'records'=>$rows,'explanation'=>$this->depositConfigured()?'Deposit records are measurable; deadline compliance requires the configured schedule.':'Deposit schedule is not configured; timing and missing-deposit metrics are not inferred.'];}
    public function getOutstandingRisk(array$f=[]):array{$o=$this->reconcile($f);$d=$this->getDailyReconciliation($f);$v=$this->getVarianceSummary($f);$missing=array_values(array_filter($o,fn($x)=>$x['match_status']==='missing_bookkeeping_entry'));return['cash_orders_not_entered'=>count($missing),'unrecorded_cash_cents'=>array_sum(array_column($missing,'expected_cash_cents')),'unreconciled_business_days'=>$d['summary']['unreconciled'],'outstanding_variances'=>$v['unresolved_count'],'shortage_cents'=>$v['shortage_cents'],'overage_cents'=>$v['overage_cents'],'oldest_unrecorded_order'=>$missing?end($missing):null];}
    public function getEvidence(array$f=[],int$l=250):array{$r=$this->reconcile($f);return array_slice($r,0,max(1,min(1000,$l)));}
    public function getTimeline(array$f=[],int$l=250):array{[$a,$b]=$this->period($f);$w=["module='Bookkeeping'",'occurred_at>=?','occurred_at<?'];$p=[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];if(($f['employee_id']??'')!==''){$w[]='employee_id=?';$p[]=(int)$f['employee_id'];}$s=$this->pdo->prepare('SELECT * FROM epi_employee_activity WHERE '.implode(' AND ',$w).' ORDER BY occurred_at DESC,id DESC LIMIT '.max(1,min(1000,$l)));$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function employeeOptions():array{$q=$this->pdo->query("SELECT id,full_name FROM ops_employees WHERE status='active' ORDER BY full_name");return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function reconcile(array$f):array
    {[$a,$b]=$this->period($f);$w=["p.payment_method='cash'",'p.amount_cents>0',"o.payment_status IN ('paid','partial')",'DATE(COALESCE(o.payment_updated_at,p.updated_at,o.updated_at,o.created_at)) BETWEEN ? AND ?'];$p=[$a->format('Y-m-d'),$b->format('Y-m-d')];$s=$this->pdo->prepare('SELECT o.id,o.order_number,o.customer_name,o.status,o.payment_status,o.payment_method,o.total_amount,o.created_at order_created_at,COALESCE(o.payment_updated_at,p.updated_at,o.updated_at,o.created_at) cash_transaction_at,p.amount_cents expected_cash_cents FROM ops_orders o JOIN order_payment_allocations p ON p.order_id=o.id WHERE '.implode(' AND ',$w).' ORDER BY cash_transaction_at DESC,o.id DESC');$s->execute($p);$orders=$s->fetchAll(PDO::FETCH_ASSOC)?:[];
      $e=$this->pdo->prepare("SELECT b.*,COALESCE(x.full_name,b.created_by_name) creator_name FROM ops_cash_book_entries b LEFT JOIN ops_employees x ON x.id=COALESCE(b.created_by_user_id,b.recorded_by) WHERE DATE(b.transaction_date) BETWEEN DATE_SUB(?,INTERVAL 2 DAY) AND DATE_ADD(?,INTERVAL 2 DAY) ORDER BY b.created_at,b.id");$e->execute([$a->format('Y-m-d'),$b->format('Y-m-d')]);$entries=$e->fetchAll(PDO::FETCH_ASSOC)?:[];$byId=[];$byNum=[];$candidates=[];foreach($entries as$x){if((int)($x['related_order_id']??0)>0)$byId[(int)$x['related_order_id']][]=$x;$refs=[];if(trim((string)($x['related_order_number']??''))!=='')$refs[]=$this->normalRef((string)$x['related_order_number']);if(preg_match('/(?:WEB|INV)?[-\s]*#?(\d{3,})/i',(string)$x['description'],$m))$refs[]=(string)(int)$m[1];foreach(array_unique(array_filter($refs))as$ref)$byNum[$ref][]=$x;$key=substr((string)$x['transaction_date'],0,10).'|'.$this->cents($x['cash_in']).'|'.strtolower(trim((string)($x['customer_name']??'')));$candidates[$key][]=$x;}
      $out=[];foreach($orders as$o){$id=(int)$o['id'];$expected=(int)$o['expected_cash_cents'];$linked=$byId[$id]??[];$method=$linked?'direct_order_id':'';if(!$linked){$keys=array_unique(array_filter([$this->normalRef((string)$o['order_number']),(string)$id]));foreach($keys as$k)if(!empty($byNum[$k])){$linked=$byNum[$k];$method='exact_order_number';break;}}
        $active=array_values(array_filter($linked,fn($x)=>empty($x['deleted_at'])&&($x['status']??'active')==='active'));$actual=array_sum(array_map(fn($x)=>$this->cents($x['cash_in']),$active));$status='missing_bookkeeping_entry';$review=false;if(count($active)>1&&$actual>=$expected){$status='duplicate_bookkeeping_entry';$review=true;}elseif($active&&$actual!==$expected){$status='amount_mismatch';$review=true;}elseif(count($active)===1&&$actual===$expected)$status='exact_match';elseif(!$active){$key=substr((string)$o['cash_transaction_at'],0,10).'|'.$expected.'|'.strtolower(trim((string)$o['customer_name']));if(!empty($candidates[$key])){$status='partial_match';$method='amount_date_customer_candidate';$review=true;}else$review=true;}
        $first=$active[0]??null;$delay=null;$timing='insufficient_historical_data';if($first&&!empty($o['cash_transaction_at'])&&!empty($first['created_at'])){$delay=Performance::businessMinutes(Support::timestamp($o['cash_transaction_at']),Support::timestamp($first['created_at']));$same=substr((string)$o['cash_transaction_at'],0,10)===substr((string)$first['created_at'],0,10);$timing=$same?'on_time':($delay<=480?'next_business_day':'late');if($status==='exact_match'&&!$same)$status='date_mismatch';}
        $out[]=['order_id'=>$id,'order_number'=>$o['order_number'],'customer'=>$o['customer_name'],'cash_transaction_at'=>$o['cash_transaction_at'],'expected_cash_cents'=>$expected,'bookkeeping_entry_id'=>$first['id']??null,'bookkeeping_date'=>$first['transaction_date']??null,'bookkeeping_created_at'=>$first['created_at']??null,'actual_cash_cents'=>$actual,'variance_cents'=>$actual-$expected,'match_method'=>$method?:'none','match_confidence'=>$method==='direct_order_id'?'exact':($method==='exact_order_number'?'high':($method?'candidate':'none')),'match_status'=>$status,'timing_status'=>$timing,'delay_business_minutes'=>$delay,'created_by_id'=>$first['created_by_user_id']??$first['recorded_by']??null,'created_by_name'=>$first['creator_name']??null,'requires_review'=>$review,'review_status'=>$review?'pending_review':'not_required','evidence_source'=>'ops_orders + order_payment_allocations + ops_cash_book_entries','score_impact'=>null];}
      return$out;}
    private function loadSettings():array{$q=$this->pdo->query("SELECT setting_key,setting_value FROM epi_employee_performance_settings WHERE setting_key LIKE 'bookkeeping_%'");$o=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[]as$r)$o[$r['setting_key']]=$r['setting_value'];return$o;}
    private function depositConfigured():bool{$v=trim((string)($this->settings['bookkeeping_deposit_schedule']??''));return$v!==''&&$v!=='not_configured';}
    private function cents($v):int{return(int)round(((float)$v)*100);}
    private function normalRef(string$v):string{$v=trim($v);if(preg_match('/(?:WEB|INV)?[-_\s]*#?\s*(\d{3,})/i',$v,$m))return(string)(int)$m[1];return strtolower($v);}
    private function median(array$v){if(!$v)return null;$n=count($v);$m=intdiv($n,2);return$n%2?$v[$m]:round(($v[$m-1]+$v[$m])/2,2);}
    private function periodPayload(array$f):array{[$a,$b]=$this->period($f);return['from'=>$a->format('Y-m-d'),'to'=>$b->format('Y-m-d')];}
    private function period(array$f):array{$t=new DateTimeImmutable('today');$k=(string)($f['period']??'previous_month');if($k==='custom'&&!empty($f['date_from'])&&!empty($f['date_to']))return[new DateTimeImmutable($f['date_from']),new DateTimeImmutable($f['date_to'])];$m=['today'=>[$t,$t],'yesterday'=>[$t->modify('-1 day'),$t->modify('-1 day')],'this_week'=>[$t->modify('monday this week'),$t],'last_week'=>[$t->modify('monday last week'),$t->modify('sunday last week')],'this_month'=>[$t->modify('first day of this month'),$t],'previous_month'=>[$t->modify('first day of last month'),$t->modify('last day of last month')],'quarter'=>[$t->modify('-'.(((int)$t->format('n')-1)%3).' months')->modify('first day of this month'),$t],'year'=>[$t->setDate((int)$t->format('Y'),1,1),$t]];return$m[$k]??$m['previous_month'];}
}
