<?php
declare(strict_types=1);
namespace Hambelela\EPI;
use DateInterval;use DateTimeImmutable;use PDO;

/** Phase 6 read-only financial evidence service. Values are calculated in integer cents. */
final class BookkeepingPerformance
{
    private $pdo;private $businessTime;
    public function __construct(PDO $pdo){$this->pdo=$pdo;$this->businessTime=new BusinessTimeEngine($pdo);}
    public function getSummary(array $filters=[]):array
    {
        $orders=$this->getOrderReconciliation($filters);$daily=$this->getDailyReconciliation($filters);$deposits=$this->getDepositPerformance($filters);$risks=$this->getOutstandingRisk($filters);
        $timed=array_values(array_filter($orders,static fn($r)=>$r['business_minutes']!==null));$delays=array_column($timed,'business_minutes');sort($delays,SORT_NUMERIC);
        $exact=count(array_filter($orders,static fn($r)=>$r['match_status']==='exact_match'));$late=count(array_filter($orders,static fn($r)=>$r['timing_status']==='late'));$missing=count(array_filter($orders,static fn($r)=>$r['match_status']==='missing_bookkeeping_entry'));
        $short=0;$over=0;foreach($daily as$r){$v=(int)$r['variance_cents'];if($v<0)$short+=abs($v);elseif($v>0)$over+=$v;}
        $cashOut=$this->cashOutControl($filters);$timeline=$this->getTimeline($filters,1000);$corrections=count(array_filter($timeline,static fn($r)=>strpos((string)$r['activity_type'],'edited')!==false||strpos((string)$r['activity_type'],'moved')!==false||strpos((string)$r['activity_type'],'restored')!==false));
        return ['period'=>$this->periodPayload($filters),'order_reconciliation'=>['eligible_cash_orders'=>count($orders),'exact_matches'=>$exact,'missing_entries'=>$missing,'late_entries'=>$late,'amount_mismatches'=>count(array_filter($orders,static fn($r)=>$r['match_status']==='amount_mismatch')),'duplicate_entries'=>count(array_filter($orders,static fn($r)=>$r['match_status']==='duplicate_bookkeeping_entry')),'exact_match_percent'=>count($orders)?round($exact*100/count($orders),2):null],
            'cash_entry_timing'=>$this->stats($delays)+['same_day'=>count(array_filter($orders,static fn($r)=>$r['timing_status']==='same_day')),'next_business_day'=>count(array_filter($orders,static fn($r)=>$r['timing_status']==='next_business_day')),'late'=>$late,'missing'=>$missing],
            'daily_controls'=>['business_days'=>count($daily),'fully_reconciled'=>count(array_filter($daily,static fn($r)=>$r['status']==='fully_reconciled')),'unreconciled'=>count(array_filter($daily,static fn($r)=>$r['status']!=='fully_reconciled')),'missing_opening'=>count(array_filter($daily,static fn($r)=>$r['opening_status']==='missing')),'missing_closing'=>count(array_filter($daily,static fn($r)=>$r['closing_status']==='missing')),'shortage_cents'=>$short,'overage_cents'=>$over],
            'cash_out_control'=>$cashOut,'accuracy_reliability'=>['first_time_correct_percent'=>count($orders)?round($exact*100/count($orders),2):null,'correction_count'=>$corrections,'same_day_percent'=>count($timed)?round(count(array_filter($orders,static fn($r)=>$r['timing_status']==='same_day'))*100/count($timed),2):null,'owner_interventions'=>count(array_filter($timeline,static fn($r)=>strpos((string)$r['activity_type'],'review')!==false))],
            'deposits'=>$deposits['summary'],'current_risk'=>$risks,'potential_deduction_evidence'=>$this->candidateEvidence($orders,$daily,$deposits['rows']),'positive_performance_evidence'=>$this->positiveEvidence($orders,$daily,$deposits['rows']),'evidence_count'=>count($orders)+count($daily)+count($deposits['rows']),'scoring_status'=>'not_calculated'];
    }
    public function getEmployeeSummary(array $f=[]):array{return $this->getSummary($f);}
    public function getOrderReconciliation(array $f=[]):array
    {
        list($from,$to)=$this->period($f);$where=['p.payment_method=\'cash\'','p.amount_cents>0',"o.payment_status IN ('paid','partial')",'o.deleted_at IS NULL','COALESCE(o.status,\'\') NOT IN (\'cancelled\',\'refunded\')','COALESCE(o.payment_updated_at,p.updated_at,o.created_at)>=?','COALESCE(o.payment_updated_at,p.updated_at,o.created_at)<?'];$params=[$from->format('Y-m-d 00:00:00'),$to->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];
        $orders=$this->query('SELECT o.id,o.order_number,o.customer_name,o.total_amount,o.payment_status,o.payment_method,o.order_type,o.fulfilment_mode,o.created_at,o.payment_updated_at,p.amount_cents cash_cents,p.updated_at cash_updated_at FROM ops_orders o JOIN order_payment_allocations p ON p.order_id=o.id WHERE '.implode(' AND ',$where).' ORDER BY COALESCE(o.payment_updated_at,p.updated_at,o.created_at),o.id',$params);
        $entries=$this->entries($from->modify('-2 days'),$to->modify('+2 days'));$byOrder=[];$byNumber=[];$byAmountDate=[];foreach($entries as$e){if((int)$e['related_order_id']>0)$byOrder[(int)$e['related_order_id']][]=$e;if(trim((string)$e['related_order_number'])!=='')$byNumber[strtolower(trim((string)$e['related_order_number']))][]=$e;$byAmountDate[substr((string)$e['transaction_date'],0,10).'|'.(int)$e['cash_in_cents']][]=$e;}
        $out=[];foreach($orders as$o){$paymentAt=(string)($o['payment_updated_at']?:$o['cash_updated_at']?:$o['created_at']);$candidates=$byOrder[(int)$o['id']]??[];$method='direct_order_id';if(!$candidates){$key=strtolower(trim((string)$o['order_number']));$candidates=$byNumber[$key]??[];$method='exact_order_number';}if(!$candidates){$key=substr($paymentAt,0,10).'|'.(int)$o['cash_cents'];$possible=$byAmountDate[$key]??[];if(count($possible)===1){$candidates=$possible;$method='exact_amount_date_customer';}elseif(count($possible)>1){$method='ambiguous_owner_review';}}
            $active=array_values(array_filter($candidates,static fn($e)=>$e['active']));$recorded=array_sum(array_column($active,'cash_in_cents'));$status='missing_bookkeeping_entry';if($method==='ambiguous_owner_review')$status='partial_match';elseif(count($active)>1)$status='duplicate_bookkeeping_entry';elseif(count($active)===1&&$recorded===(int)$o['cash_cents'])$status='exact_match';elseif($recorded>0)$status='amount_mismatch';$entry=$active[0]??null;$minutes=null;$timing='insufficient_historical_data';if($entry&&$paymentAt&&$entry['created_at']){$minutes=$this->businessTime->workingMinutes($paymentAt,$entry['created_at']);$timing=substr($paymentAt,0,10)===substr($entry['created_at'],0,10)?'same_day':($minutes<=self::deadlineMinutes()?'next_business_day':'late');}
            $out[]=['order_id'=>(int)$o['id'],'order_number'=>$o['order_number'],'customer'=>$o['customer_name'],'business_date'=>substr($paymentAt,0,10),'walk_in'=>$this->walkIn($o),'cash_component_cents'=>(int)$o['cash_cents'],'bookkeeping_entry_id'=>$entry['id']??null,'bookkeeping_cents'=>$recorded,'variance_cents'=>$recorded-(int)$o['cash_cents'],'match_method'=>$method,'match_confidence'=>$method==='direct_order_id'?'exact':($method==='exact_order_number'?'high':($method==='ambiguous_owner_review'?'ambiguous':'review_required')),'match_status'=>$status,'order_time'=>$paymentAt?:null,'bookkeeping_time'=>$entry['created_at']??null,'business_minutes'=>$minutes,'timing_status'=>$timing,'created_by_employee_id'=>$entry['created_by_employee_id']??null,'created_by'=>$entry['created_by']??null,'review_status'=>$method==='ambiguous_owner_review'?'pending_review':'not_required','evidence_quality'=>$entry?'exact_logged_event':'incomplete_historical_evidence'];}
        return $this->filterRows($out,$f);
    }
    public function getCashEntryCompliance(array$f=[]):array{return $this->getSummary($f)['cash_entry_timing'];}
    public function getDailyReconciliation(array$f=[]):array
    {
        list($from,$to)=$this->period($f);$entries=$this->entries($from,$to);$days=[];foreach($entries as$e){$d=substr((string)$e['transaction_date'],0,10);if(!isset($days[$d]))$days[$d]=['business_date'=>$d,'opening_cents'=>0,'cash_in_cents'=>0,'cash_out_cents'=>0,'deposit_cents'=>0,'opening_count'=>0];if($e['opening']){$days[$d]['opening_cents']+=(int)$e['cash_in_cents']-(int)$e['cash_out_cents'];$days[$d]['opening_count']++;}elseif($e['deposit'])$days[$d]['deposit_cents']+=max((int)$e['cash_in_cents'],(int)$e['cash_out_cents']);else{$days[$d]['cash_in_cents']+=(int)$e['cash_in_cents'];$days[$d]['cash_out_cents']+=(int)$e['cash_out_cents'];}}
        $recons=[];foreach($this->query('SELECT r.*,e.full_name reconciled_by FROM hambelela_cashbook_recon r LEFT JOIN ops_employees e ON e.id=r.logged_by WHERE r.recon_date>=? AND r.recon_date<=? ORDER BY r.created_at,r.id',[$from->format('Y-m-d'),$to->format('Y-m-d')])as$r)$recons[(string)$r['recon_date']]=$r;
        foreach($days as$d=>&$row){$expected=$row['opening_cents']+$row['cash_in_cents']-$row['cash_out_cents'];$recon=$recons[$d]??null;$actual=$recon?self::cents($recon['counted_total']):null;$row['expected_closing_cents']=$expected;$row['actual_closing_cents']=$actual;$row['variance_cents']=$actual===null?0:$actual-$expected;$row['opening_status']=$row['opening_count']===0?'missing':($row['opening_count']>1?'duplicate':'recorded');$row['closing_status']=$actual===null?'missing':'recorded';$row['reconciled_by']=$recon['reconciled_by']??null;$row['reconciliation_at']=$recon['created_at']??null;$row['status']=$row['opening_status']==='recorded'&&$actual!==null&&$row['variance_cents']===0?'fully_reconciled':($actual===null?'missing_closing_balance':'unreconciled');}$rows=array_values($days);unset($row);return$rows;
    }
    public function getVarianceSummary(array$f=[]):array{$d=$this->getDailyReconciliation($f);return['days'=>$d,'shortages_cents'=>array_sum(array_map(static fn($r)=>min(0,(int)$r['variance_cents']),$d)),'overages_cents'=>array_sum(array_map(static fn($r)=>max(0,(int)$r['variance_cents']),$d))];}
    public function getDepositPerformance(array$f=[]):array{list($a,$b)=$this->period($f);$rows=array_values(array_filter($this->entries($a,$b),static fn($e)=>$e['deposit']));$configured=$this->setting('bookkeeping_deposit_deadline','not_configured')!=='not_configured';foreach($rows as&$r)$r['deposit_status']=$configured?'pending_timing_evaluation':'insufficient_historical_data';unset($r);return['summary'=>['deposits_logged'=>count($rows),'on_time'=>null,'late'=>null,'missing'=>null,'deadline_configured'=>$configured],'rows'=>$rows];}
    public function getOutstandingRisk(array$f=[]):array{$orders=$this->getOrderReconciliation($f);$daily=$this->getDailyReconciliation($f);$issues=array_values(array_filter($orders,static fn($r)=>$r['match_status']!=='exact_match'||$r['timing_status']==='late'));$value=array_sum(array_map(static fn($r)=>abs((int)$r['variance_cents']),$issues));return['cash_orders_not_entered'=>count(array_filter($issues,static fn($r)=>$r['match_status']==='missing_bookkeeping_entry')),'unreconciled_days'=>count(array_filter($daily,static fn($r)=>$r['status']!=='fully_reconciled')),'outstanding_variance_cents'=>$value,'oldest_issue'=>$issues[0]??null,'total_unresolved_financial_value_cents'=>$value,'separate_from_historical_metrics'=>true];}
    public function getEvidence(array$f=[],int$limit=500):array{return array_slice($this->getOrderReconciliation($f),0,max(1,min(1000,$limit)));}
    public function getTimeline(array$f=[],int$limit=250):array{list($a,$b)=$this->period($f);$max=max(1,min(1000,$limit));$w=["module='Bookkeeping'",'occurred_at>=?','occurred_at<?'];$p=[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];if(!empty($f['employee_id'])){$w[]='employee_id=?';$p[]=(int)$f['employee_id'];}$s=$this->pdo->prepare('SELECT * FROM epi_employee_activity WHERE '.implode(' AND ',$w).' ORDER BY occurred_at DESC,id DESC LIMIT '.$max);$s->execute($p);$rows=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$seen=[];foreach($rows as$r)$seen['epi:'.(string)$r['activity_uuid']]=true;$legacyWhere=['l.created_at>=?','l.created_at<?'];$legacyParams=[$p[0],$p[1]];if(!empty($f['employee_id'])){$legacyWhere[]='COALESCE(b.recorded_by,l.user_id)=?';$legacyParams[]=(int)$f['employee_id'];}$legacy=$this->query('SELECT l.*,COALESCE(b.recorded_by,l.user_id) employee_id,COALESCE(e.full_name,l.user_name) employee_name FROM hambelela_cashbook_log l LEFT JOIN ops_cash_book_entries b ON b.id=l.entry_id LEFT JOIN ops_employees e ON e.id=COALESCE(b.recorded_by,l.user_id) WHERE '.implode(' AND ',$legacyWhere).' ORDER BY l.created_at DESC,l.id DESC LIMIT '.$max,$legacyParams);foreach($legacy as$l){$key='legacy:'.(int)$l['id'];if(isset($seen[$key]))continue;$rows[]=['activity_uuid'=>$key,'module'=>'Bookkeeping','reference_number'=>$l['entry_id']?'BK-'.(int)$l['entry_id']:'BOOKKEEPING','employee_id'=>$l['employee_id'],'employee_name'=>$l['employee_name'],'activity_type'=>'bookkeeping_'.(string)$l['action'],'description'=>$l['description'],'previous_value'=>$l['old_value'],'new_value'=>$l['new_value'],'occurred_at'=>$l['created_at'],'activity_source'=>'hambelela_cashbook_log','metadata_json'=>json_encode(['field'=>$l['field'],'source_event_id'=>(int)$l['id']],JSON_UNESCAPED_SLASHES)];}$rows=array_slice($rows,0,$max);usort($rows,static fn($x,$y)=>strcmp((string)$y['occurred_at'],(string)$x['occurred_at']));return$rows;}
    public function employeeOptions():array{return$this->query("SELECT id,full_name FROM ops_employees WHERE status='active' ORDER BY full_name",[]);}
    private function cashOutControl(array$f):array{list($a,$b)=$this->period($f);$rows=array_values(array_filter($this->entries($a,$b),static fn($e)=>(int)$e['cash_out_cents']>0&&!$e['deposit']));$missingPurpose=count(array_filter($rows,static fn($e)=>trim((string)$e['description'])===''||strtolower(trim((string)$e['description']))==='cash out'));$missingEmployee=count(array_filter($rows,static fn($e)=>(int)$e['created_by_employee_id']<=0));return['entries'=>count($rows),'cash_out_cents'=>array_sum(array_column($rows,'cash_out_cents')),'missing_purpose'=>$missingPurpose,'missing_employee'=>$missingEmployee,'missing_approval'=>null,'evidence_status'=>'Historical approval and attachments are reported as insufficient when absent.','rows'=>$rows];}
    private function candidateEvidence(array$orders,array$daily,array$deposits):array{$out=[];foreach($orders as$r){$rule=null;if($r['match_status']==='missing_bookkeeping_entry')$rule='eligible_cash_order_not_entered';elseif($r['match_status']==='amount_mismatch')$rule='incorrect_cash_amount';elseif($r['match_status']==='duplicate_bookkeeping_entry')$rule='duplicate_entry';elseif($r['timing_status']==='late')$rule='cash_order_entered_late';if($rule)$out[]=['employee_id'=>$r['created_by_employee_id'],'business_date'=>$r['business_date'],'record_id'=>$r['bookkeeping_entry_id'],'order_id'=>$r['order_id'],'rule_triggered'=>$rule,'expected_cents'=>$r['cash_component_cents'],'actual_cents'=>$r['bookkeeping_cents'],'financial_variance_cents'=>$r['variance_cents'],'delay_minutes'=>$r['business_minutes'],'exception_status'=>'pending_review','review_status'=>'pending_review','owner_confirmation_status'=>'not_confirmed'];}foreach($daily as$r){if($r['opening_status']!=='recorded')$out[]=['business_date'=>$r['business_date'],'rule_triggered'=>$r['opening_status']==='missing'?'missing_opening_balance':'duplicate_opening_balance','review_status'=>'pending_review','owner_confirmation_status'=>'not_confirmed'];if($r['closing_status']==='missing')$out[]=['business_date'=>$r['business_date'],'rule_triggered'=>'missing_closing_balance','review_status'=>'pending_review','owner_confirmation_status'=>'not_confirmed'];if((int)$r['variance_cents']!==0)$out[]=['business_date'=>$r['business_date'],'rule_triggered'=>(int)$r['variance_cents']<0?'cash_shortage':'cash_overage','financial_variance_cents'=>$r['variance_cents'],'review_status'=>'pending_review','owner_confirmation_status'=>'not_confirmed'];}return$out;}
    private function positiveEvidence(array$orders,array$daily,array$deposits):array{$out=[];if($orders&&!array_filter($orders,static fn($r)=>$r['match_status']!=='exact_match'))$out[]=['rule'=>'all_eligible_cash_orders_entered','status'=>'candidate_only'];if($orders&&!array_filter($orders,static fn($r)=>$r['timing_status']==='late'))$out[]=['rule'=>'all_entries_on_time','status'=>'candidate_only'];if($daily&&!array_filter($daily,static fn($r)=>$r['status']!=='fully_reconciled'))$out[]=['rule'=>'full_reconciliation_compliance','status'=>'candidate_only'];return$out;}
    private function entries(DateTimeImmutable$a,DateTimeImmutable$b):array{$rows=$this->query("SELECT b.*,ROUND(b.cash_in*100) cash_in_cents,ROUND(b.cash_out*100) cash_out_cents,COALESCE(e.full_name,b.created_by_name,'Unknown employee') created_by,COALESCE(b.recorded_by,b.created_by_user_id) created_by_employee_id FROM ops_cash_book_entries b LEFT JOIN ops_employees e ON e.id=COALESCE(b.recorded_by,b.created_by_user_id) WHERE b.transaction_date>=? AND b.transaction_date<? ORDER BY b.created_at,b.id",[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')]);foreach($rows as&$r){$r['active']=empty($r['deleted_at'])&&in_array((string)($r['status']??'active'),['','active'],true);$r['opening']=in_array((string)$r['source'],['opening_balance'],true)||(string)$r['transaction_type']==='opening_balance';$r['deposit']=preg_match('/deposit|banking/i',(string)($r['transaction_type'].' '.$r['source'].' '.$r['description']))===1;}unset($r);return$rows;}
    private function filterRows(array$r,array$f):array{return array_values(array_filter($r,static function($x)use($f){foreach(['employee_id'=>'created_by_employee_id','match_status'=>'match_status','on_time'=>'timing_status']as$k=>$col)if(isset($f[$k])&&$f[$k]!==''&&(string)$x[$col]!== (string)$f[$k])return false;return true;}));}
    private function query(string$sql,array$p):array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function setting(string$k,string$d):string{try{$s=$this->pdo->prepare('SELECT setting_value FROM epi_employee_performance_settings WHERE setting_key=? LIMIT 1');$s->execute([$k]);return(string)($s->fetchColumn()?:$d);}catch(\Throwable$e){return$d;}}
    private function walkIn(array$o):bool{$v=strtolower((string)(($o['fulfilment_mode']??'').' '.($o['order_type']??'')));return strpos($v,'walk')!==false||strpos($v,'pos')!==false;}
    private static function cents($v):int{return(int)round((float)$v*100);}
    private static function deadlineMinutes():float{return 24*60;}
    private function stats(array$v):array{if(!$v)return['average'=>null,'median'=>null,'fastest'=>null,'slowest'=>null,'count'=>0,'status'=>'insufficient_historical_data'];sort($v,SORT_NUMERIC);$n=count($v);$m=intdiv($n,2);return['average'=>round(array_sum($v)/$n,2),'median'=>$n%2?$v[$m]:round(($v[$m-1]+$v[$m])/2,2),'fastest'=>$v[0],'slowest'=>$v[$n-1],'count'=>$n,'status'=>'verified'];}
    private function periodPayload(array$f):array{list($a,$b)=$this->period($f);return['from'=>$a->format('Y-m-d'),'to'=>$b->format('Y-m-d')];}
    private function period(array$f):array{$t=new DateTimeImmutable('today');$k=(string)($f['period']??'previous_month');if($k==='custom'&&!empty($f['date_from'])&&!empty($f['date_to']))return[new DateTimeImmutable($f['date_from']),new DateTimeImmutable($f['date_to'])];$m=['today'=>[$t,$t],'yesterday'=>[$t->modify('-1 day'),$t->modify('-1 day')],'this_week'=>[$t->modify('monday this week'),$t],'last_week'=>[$t->modify('monday last week'),$t->modify('sunday last week')],'this_month'=>[$t->modify('first day of this month'),$t],'previous_month'=>[$t->modify('first day of last month'),$t->modify('last day of last month')],'quarter'=>[$t->modify('-'.(((int)$t->format('n')-1)%3).' months')->modify('first day of this month'),$t],'year'=>[$t->setDate((int)$t->format('Y'),1,1),$t]];return$m[$k]??$m['previous_month'];}
}
