<?php
declare(strict_types=1);
namespace Hambelela\EPI;
use DateInterval;use DateTimeImmutable;use PDO;

/** Read-only Phase 5 Courier analytics. Produces evidence candidates, never scores. */
final class CourierPerformance
{
    private $pdo;private $settings=[];
    public function __construct(PDO$pdo){$this->pdo=$pdo;$this->settings=$this->loadSettings();}
    public function getSummary(array$f=[]):array{$r=$this->records($f);return['period'=>$this->periodPayload($f),'total'=>count($r),'uploaded'=>count(array_filter($r,fn($x)=>$x['uploaded_at'])),'sent'=>count(array_filter($r,fn($x)=>$x['sent_at'])),'pending'=>count(array_filter($r,fn($x)=>!$x['sent_at'])),'requires_review'=>count(array_filter($r,fn($x)=>$x['classification']==='requires_review')),'insufficient_historical_data'=>count(array_filter($r,fn($x)=>$x['classification']==='insufficient_historical_data')),'packer'=>$this->packerStats($r),'front_desk'=>$this->frontStats($r),'courier_types'=>$this->typeStats($r),'candidate_events'=>$this->candidateCount($f),'scoring_status'=>'not_calculated','methodology'=>'Packer upload and Front Desk send responsibility are measured separately. Late upstream availability is never charged to Front Desk.'];}
    public function getPackerSummary(array$f=[]):array{return$this->packerStats($this->records($f));}
    public function getFrontDeskSummary(array$f=[]):array{return$this->frontStats($this->records($f));}
    public function getUploadCompliance(array$f=[]):array{return array_values(array_filter($this->records($f),fn($r)=>$r['uploaded_at']));}
    public function getSendCompliance(array$f=[]):array{return array_values(array_filter($this->records($f),fn($r)=>$r['sent_at']||$r['status']!=='sent'));}
    public function getPending(array$f=[]):array{return array_values(array_filter($this->records($f),fn($r)=>!$r['sent_at']));}
    public function getCourierTypeBreakdown(array$f=[]):array{return$this->typeStats($this->records($f));}
    public function getExceptions(array$f=[]):array{return array_values(array_filter($this->records($f),fn($r)=>$r['classification']==='requires_review'||$r['classification']==='insufficient_historical_data'||$r['delay_owner']!=='none'));}
    public function getEvidence(array$f=[],int$limit=250):array{$rows=$this->records($f);return array_slice($rows,0,max(1,min(1000,$limit)));}
    public function getTimeline(array$f=[],int$limit=250):array{[$a,$b]=$this->period($f);$w=["module='Courier'",'occurred_at>=?','occurred_at<?'];$p=[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];if(($f['employee_id']??'')!==''){$w[]='employee_id=?';$p[]=(int)$f['employee_id'];}$s=$this->pdo->prepare('SELECT * FROM epi_employee_activity WHERE '.implode(' AND ',$w).' ORDER BY occurred_at DESC,id DESC LIMIT '.max(1,min(1000,$limit)));$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function employeeOptions():array{$q=$this->pdo->query("SELECT id,full_name FROM ops_employees WHERE status='active' ORDER BY full_name");return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function records(array$f):array
    {[$a,$b]=$this->period($f);$where=['w.deleted_at IS NULL','COALESCE(w.sent_date,DATE(w.uploaded_at)) BETWEEN ? AND ?'];$p=[$a->format('Y-m-d'),$b->format('Y-m-d')];if(($f['employee_id']??'')!==''){$where[]='(w.uploaded_by=? OR w.sent_by=?)';$p[]=(int)$f['employee_id'];$p[]=(int)$f['employee_id'];}if(($f['status']??'')!==''){$where[]='w.status=?';$p[]=$f['status'];}if(($f['courier_type']??'')!==''){$where[]='w.courier_names LIKE ?';$p[]='%'.$f['courier_type'].'%';}
      $s=$this->pdo->prepare("SELECT w.*,up.full_name uploaded_by_name,sp.full_name sent_by_name FROM hambelela_waybills w LEFT JOIN ops_employees up ON up.id=w.uploaded_by LEFT JOIN ops_employees sp ON sp.id=w.sent_by WHERE ".implode(' AND ',$where).' ORDER BY COALESCE(w.sent_date,DATE(w.uploaded_at)) DESC,w.id DESC');$s->execute($p);$raw=$s->fetchAll(PDO::FETCH_ASSOC)?:[];$out=[];foreach($raw as$r)$out[]=$this->classify($r);return$out;}
    private function classify(array$r):array
    {$business=trim((string)($r['sent_date']??''));$uploaded=$this->date($r['uploaded_at']??null);$sent=$this->date($r['sent_at']??null);$classification='verified';$reason=null;if($business===''){$classification='insufficient_historical_data';$reason='Courier business date is unavailable.';}if(!$uploaded){$classification='insufficient_historical_data';$reason='Upload timestamp is unavailable.';}
      $normalDeadline=null;$sendDeadline=null;$responseDeadline=null;$uploadResult='Insufficient historical data';$sendResult=$sent?'Insufficient historical data':'Pending';$delayOwner='none';$uploadDelay=null;$sendDelay=null;
      if($business!==''&&$uploaded){$day=new DateTimeImmutable($business);$weekday=(int)$day->format('N');$close=$weekday===6?($this->settings['courier_packer_close_saturday']??'13:00'):($this->settings['courier_packer_close_weekday']??'17:00');$normalDeadline=new DateTimeImmutable($business.' '.$close);$uploadDelay=$uploaded>$normalDeadline?Performance::businessMinutes($normalDeadline,$uploaded):0;$uploadResult=$uploaded<=$normalDeadline?'on_time':'late';
        $next=$this->nextBusinessDay($day);$sendDeadline=new DateTimeImmutable($next->format('Y-m-d').' '.($this->settings['courier_front_desk_send_deadline']??'09:00'));$responseDeadline=$this->addBusinessMinutes($uploaded,(int)($this->settings['courier_front_desk_response_minutes']??30));
        if($uploaded>$sendDeadline){$delayOwner='packer';$sendResult=$sent?'sent_after_late_availability':'blocked_by_late_upload';if($sent&&$sent>$responseDeadline){$sendResult='late_after_availability';$delayOwner='front_desk';$sendDelay=Performance::businessMinutes($responseDeadline,$sent);}}
        elseif($sent){$sendResult=$sent<=$sendDeadline?'on_time':'late';if($sent>$sendDeadline){$delayOwner='front_desk';$sendDelay=Performance::businessMinutes($sendDeadline,$sent);}}
        elseif(new DateTimeImmutable('now')>$sendDeadline){$sendResult='overdue';$delayOwner='front_desk';$sendDelay=Performance::businessMinutes($sendDeadline,new DateTimeImmutable('now'));}
      }
      $combined=(int)($r['number_of_waybills']??1)>1;if($combined&&$classification==='verified'){$classification='requires_review';$reason='Combined batch requires record-level review.';}
      return['record_id'=>(int)$r['id'],'batch_id'=>$r['batch_id'],'reference'=>$r['waybill_reference']?:('WAYBILL-'.$r['batch_id']),'order_id'=>$r['order_id'],'business_date'=>$business?:null,'business_date_source'=>$business!==''?'explicit_courier_batch_date':'unavailable','courier_type'=>$r['courier_names']?:'Unclassified','uploaded_by'=>$r['uploaded_by'],'uploaded_by_name'=>$r['uploaded_by_name']?:'Insufficient historical data','uploaded_at'=>$r['uploaded_at'],'normal_upload_deadline'=>$normalDeadline?$normalDeadline->format('Y-m-d H:i:s'):null,'approved_exception'=>false,'exception_note'=>null,'upload_result'=>$uploadResult,'upload_delay_business_minutes'=>$uploadDelay,'sent_by'=>$r['sent_by'],'sent_by_name'=>$r['sent_by_name']?:($sent?'Insufficient historical data':'—'),'sent_at'=>$r['sent_at'],'send_deadline'=>$sendDeadline?$sendDeadline->format('Y-m-d H:i:s'):null,'availability_response_deadline'=>$responseDeadline?$responseDeadline->format('Y-m-d H:i:s'):null,'send_result'=>$sendResult,'send_delay_business_minutes'=>$sendDelay,'delay_owner'=>$delayOwner,'status'=>$r['status'],'notes'=>$r['notes'],'classification'=>$classification,'review_reason'=>$reason,'evidence_source'=>'hambelela_waybills + ops_activity_logs + EPI','candidate_only'=>$delayOwner!=='none'];}
    private function packerStats(array$r):array{$e=array_values(array_filter($r,fn($x)=>$x['upload_result']!=='Insufficient historical data'));$on=count(array_filter($e,fn($x)=>$x['upload_result']==='on_time'));return['eligible'=>count($e),'on_time'=>$on,'late'=>count($e)-$on,'on_time_percent'=>count($e)?round($on*100/count($e),2):null,'insufficient'=>count($r)-count($e)];}
    private function frontStats(array$r):array{$e=array_values(array_filter($r,fn($x)=>!in_array($x['send_result'],['Insufficient historical data','blocked_by_late_upload','sent_after_late_availability'],true)));$on=count(array_filter($e,fn($x)=>$x['send_result']==='on_time'));return['eligible'=>count($e),'on_time'=>$on,'late_or_overdue'=>count($e)-$on,'on_time_percent'=>count($e)?round($on*100/count($e),2):null,'excluded_upstream_dependency'=>count(array_filter($r,fn($x)=>in_array($x['send_result'],['blocked_by_late_upload','sent_after_late_availability'],true)))];}
    private function typeStats(array$r):array{$o=[];foreach($r as$x){$k=$x['courier_type'];if(!isset($o[$k]))$o[$k]=['courier_type'=>$k,'total'=>0,'sent'=>0,'pending'=>0];$o[$k]['total']++;$x['sent_at']?$o[$k]['sent']++:$o[$k]['pending']++;}return array_values($o);}
    private function candidateCount(array$f):int{[$a,$b]=$this->period($f);$s=$this->pdo->prepare("SELECT COUNT(*) FROM epi_employee_evidence WHERE module='Courier' AND (action LIKE 'deduction_candidate_%' OR action LIKE 'bonus_candidate_%') AND occurred_at>=? AND occurred_at<?");$s->execute([$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')]);return(int)$s->fetchColumn();}
    private function loadSettings():array{$q=$this->pdo->query("SELECT setting_key,setting_value FROM epi_employee_performance_settings WHERE setting_key LIKE 'courier_%'");$o=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[]as$r)$o[$r['setting_key']]=$r['setting_value'];return$o;}
    private function date($v):?DateTimeImmutable{return trim((string)$v)!==''?Support::timestamp($v):null;}
    private function nextBusinessDay(DateTimeImmutable$d):DateTimeImmutable{$x=$d->modify('+1 day');for($i=0;$i<14;$i++){if((int)$x->format('N')<7){$s=$this->pdo->prepare('SELECT COUNT(*) FROM epi_employee_business_calendar WHERE business_date=? AND is_working_day=0');$s->execute([$x->format('Y-m-d')]);if(!(int)$s->fetchColumn())return$x;}$x=$x->modify('+1 day');}return$x;}
    private function addBusinessMinutes(DateTimeImmutable$d,int$m):DateTimeImmutable{return Performance::graceDueAt('courier_front_desk_response',$d);}
    private function periodPayload(array$f):array{[$a,$b]=$this->period($f);return['from'=>$a->format('Y-m-d'),'to'=>$b->format('Y-m-d')];}
    private function period(array$f):array{$t=new DateTimeImmutable('today');$k=(string)($f['period']??'previous_month');if($k==='custom'&&!empty($f['date_from'])&&!empty($f['date_to']))return[new DateTimeImmutable($f['date_from']),new DateTimeImmutable($f['date_to'])];$m=['today'=>[$t,$t],'yesterday'=>[$t->modify('-1 day'),$t->modify('-1 day')],'this_week'=>[$t->modify('monday this week'),$t],'last_week'=>[$t->modify('monday last week'),$t->modify('sunday last week')],'this_month'=>[$t->modify('first day of this month'),$t],'previous_month'=>[$t->modify('first day of last month'),$t->modify('last day of last month')],'quarter'=>[$t->modify('-'.(((int)$t->format('n')-1)%3).' months')->modify('first day of this month'),$t],'year'=>[$t->setDate((int)$t->format('Y'),1,1),$t]];return$m[$k]??$m['previous_month'];}
}
