<?php
declare(strict_types=1);
namespace Hambelela\EPI;
use DateInterval;use DateTimeImmutable;use PDO;use Throwable;

final class QualityPerformance
{
    private $pdo;
    public function __construct(PDO $pdo){$this->pdo=$pdo;Performance::configure($pdo);}
    public function getSummary(array $f=[]):array{$rows=$this->rows($f);$s=['errors_reported'=>count($rows),'confirmed_employee_errors'=>0,'pending_review'=>0,'business_errors'=>0,'system_errors'=>0,'external_errors'=>0,'open_errors'=>0,'resolved_errors'=>0,'reopened_errors'=>0,'customer_complaints'=>0,'net_financial_impact'=>0.0,'unresolved_financial_impact'=>0.0,'insufficient_historical_data'=>0];$cat=[];$sev=[];foreach($rows as$r){$type=(string)($r['responsibility_type']??'unconfirmed');$decision=(string)($r['review_decision']??'');if($decision==='confirmed_employee_error')$s['confirmed_employee_errors']++;elseif($decision===''||$decision==='pending_review')$s['pending_review']++;if($type==='business_error')$s['business_errors']++;if($type==='system_error')$s['system_errors']++;if(in_array($type,['supplier_error','courier_error','customer_error','external_dependency'],true))$s['external_errors']++;$status=strtolower((string)$r['status']);if(in_array($status,['resolved','closed'],true))$s['resolved_errors']++;else$s['open_errors']++;if((string)($r['repeat_status']??'')==='confirmed_repeat')$s['reopened_errors']++;if((string)$r['category']==='customer_complaint')$s['customer_complaints']++;$impact=(float)($r['net_financial_impact']??$r['financial_impact']??0);$s['net_financial_impact']+=$impact;if(!in_array($status,['resolved','closed'],true))$s['unresolved_financial_impact']+=$impact;if(empty($r['profile_id']))$s['insufficient_historical_data']++;$cat[(string)$r['category']]=($cat[(string)$r['category']]??0)+1;$sev[(string)$r['severity']]=($sev[(string)$r['severity']]??0)+1;}return$s+['categories'=>$cat,'severities'=>$sev,'current_risk'=>$this->getCurrentRisk($f),'resolution'=>$this->getResolutionPerformance($f)];}
    public function getEmployeeSummary(array$f=[]):array{$f['responsible_employee_id']=$f['employee_id']??'';$rows=$this->rows($f);$out=[];foreach($rows as$r){$id=(int)($r['current_responsible_employee_id']??0);if(!$id)continue;if(!isset($out[$id]))$out[$id]=['employee_id'=>$id,'employee_name'=>$r['responsible_name']??('Employee '.$id),'reported_against'=>0,'confirmed'=>0,'pending'=>0,'dismissed'=>0,'shared'=>0,'open'=>0,'resolved'=>0,'financial_impact'=>0.0];$x=&$out[$id];$x['reported_against']++;$d=(string)($r['review_decision']??'');if($d==='confirmed_employee_error')$x['confirmed']++;elseif($d==='dismissed'||$d==='excused')$x['dismissed']++;else$x['pending']++;if((string)$r['responsibility_type']==='shared_responsibility')$x['shared']++;if(in_array((string)$r['status'],['resolved','closed'],true))$x['resolved']++;else$x['open']++;$x['financial_impact']+=(float)($r['net_financial_impact']??0);}return array_values($out);}
    public function getReportingSummary(array$f=[]):array{$rows=$this->rows($f);$o=[];foreach($rows as$r){$id=(int)($r['logged_by']??0);if(!$id)continue;if(!isset($o[$id]))$o[$id]=['employee_id'=>$id,'employee_name'=>$r['logged_by_name']??('Employee '.$id),'errors_logged'=>0,'complete_records'=>0,'financial_impact_captured'=>0,'duplicates'=>0,'dismissed'=>0];$x=&$o[$id];$x['errors_logged']++;if($r['error_title']&&$r['description']&&$r['category']&&$r['severity'])$x['complete_records']++;if($r['has_financial_impact']!==null)$x['financial_impact_captured']++;if((string)($r['review_decision']??'')==='duplicate')$x['duplicates']++;if((string)($r['review_decision']??'')==='dismissed')$x['dismissed']++;}return array_values($o);}
    public function getCategorySummary(array$f=[]):array{return$this->group($f,'category');}
    public function getSeveritySummary(array$f=[]):array{return$this->group($f,'severity');}
    public function getResolutionPerformance(array$f=[]):array{$rows=$this->rows($f);$dur=[];$reopened=0;$accepted=0;foreach($rows as$r){if(!empty($r['resolved_at'])&&!empty($r['logged_at']))$dur[]=Performance::businessMinutes($r['logged_at'],$r['resolved_at']);if((string)($r['repeat_status']??'')==='confirmed_repeat')$reopened++;if(in_array((string)($r['review_decision']??''),['confirmed_employee_error','confirmed_business_error','confirmed_system_error','confirmed_supplier_error','confirmed_courier_error','confirmed_customer_error','shared_responsibility','excused'],true)&&in_array((string)$r['status'],['resolved','closed'],true))$accepted++;}sort($dur);$n=count($dur);return['measured'=>$n,'average_business_minutes'=>$n?round(array_sum($dur)/$n,1):null,'median_business_minutes'=>$n?($n%2?$dur[intdiv($n,2)]:round(($dur[$n/2-1]+$dur[$n/2])/2,1)):null,'fastest'=>$n?$dur[0]:null,'slowest'=>$n?$dur[$n-1]:null,'reopened'=>$reopened,'accepted'=>$accepted];}
    public function getRepeatErrors(array$f=[]):array{return array_values(array_filter($this->rows($f),static fn($r)=>!in_array((string)($r['repeat_status']??'first_occurrence'),['','first_occurrence'],true)));}
    public function getFinancialImpact(array$f=[]):array{$rows=$this->rows($f);$total=0;$recoverable=0;$recovered=0;foreach($rows as$r){$total+=(float)($r['net_financial_impact']??0);$recoverable+=(float)($r['recoverable_amount']??0);$recovered+=(float)($r['recovered_amount']??0);}return['net'=>$total,'recoverable'=>$recoverable,'recovered'=>$recovered,'pending_recovery'=>max(0,$recoverable-$recovered)];}
    public function getCurrentRisk(array$f=[]):array{$rows=$this->rows($f);$o=['new'=>0,'under_review'=>0,'unresolved'=>0,'critical_unresolved'=>0,'high_unresolved'=>0,'complaints_unresolved'=>0,'corrective_actions_overdue'=>0,'oldest_unresolved'=>null];foreach($rows as$r){$st=(string)$r['status'];$open=!in_array($st,['resolved','closed','dismissed','duplicate'],true);if($st==='new'||$st==='open')$o['new']++;if($st==='under_review')$o['under_review']++;if($open){$o['unresolved']++;if($r['severity']==='critical')$o['critical_unresolved']++;if($r['severity']==='high')$o['high_unresolved']++;if($r['category']==='customer_complaint')$o['complaints_unresolved']++;if($o['oldest_unresolved']===null||$r['logged_at']<$o['oldest_unresolved'])$o['oldest_unresolved']=$r['logged_at'];}}try{$q=$this->pdo->query("SELECT COUNT(*) FROM epi_quality_corrective_actions WHERE status NOT IN ('completed','cancelled') AND due_at<NOW()");$o['corrective_actions_overdue']=(int)$q->fetchColumn();}catch(Throwable$e){}return$o;}
    public function getCorrectiveActions(array$f=[]):array{try{$s=$this->pdo->query('SELECT ca.*,el.error_title,e.full_name responsible_name FROM epi_quality_corrective_actions ca JOIN ops_error_logs el ON el.id=ca.error_id LEFT JOIN ops_employees e ON e.id=ca.responsible_employee_id ORDER BY ca.created_at DESC LIMIT 500');return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable$e){return[];}}
    public function getEvidence(array$f=[],int$l=500):array{return array_slice($this->rows($f),0,max(1,min(1000,$l)));}
    public function getTimeline(array$f=[],int$l=500):array{[$a,$b]=$this->period($f);$w=["module='Error Log'",'occurred_at>=?','occurred_at<?'];$p=[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];$s=$this->pdo->prepare('SELECT * FROM epi_employee_activity WHERE '.implode(' AND ',$w).' ORDER BY occurred_at DESC,id DESC LIMIT '.max(1,min(1000,$l)));$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function employeeOptions():array{return$this->pdo->query("SELECT id,full_name FROM ops_employees WHERE status='active' ORDER BY full_name")->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function group(array$f,string$k):array{$o=[];foreach($this->rows($f)as$r)$o[(string)$r[$k]]=($o[(string)$r[$k]]??0)+1;arsort($o);return$o;}
    private function rows(array$f):array{[$a,$b]=$this->period($f);$w=['el.logged_at>=?','el.logged_at<?','el.deleted_at IS NULL'];$p=[$a->format('Y-m-d 00:00:00'),$b->add(new DateInterval('P1D'))->format('Y-m-d 00:00:00')];foreach(['category'=>'el.category','severity'=>'el.severity','status'=>'el.status','responsibility_type'=>'qp.responsibility_type','responsible_employee_id'=>'qp.current_responsible_employee_id']as$fk=>$col)if(($f[$fk]??'')!==''){$w[]=$col.'=?';$p[]=$f[$fk];}$sql="SELECT el.*,qp.id profile_id,qp.current_responsible_employee_id,qp.responsibility_type,qp.repeat_status,qp.root_cause_key,qp.resolved_at,lb.full_name logged_by_name,re.full_name responsible_name,(SELECT decision FROM epi_quality_owner_reviews rr WHERE rr.error_id=el.id ORDER BY rr.reviewed_at DESC,rr.id DESC LIMIT 1) review_decision,(SELECT net_financial_impact FROM epi_quality_financial_impacts fi WHERE fi.error_id=el.id ORDER BY fi.created_at DESC,fi.id DESC LIMIT 1) net_financial_impact,(SELECT recoverable_amount FROM epi_quality_financial_impacts fi WHERE fi.error_id=el.id ORDER BY fi.created_at DESC,fi.id DESC LIMIT 1) recoverable_amount,(SELECT recovered_amount FROM epi_quality_financial_impacts fi WHERE fi.error_id=el.id ORDER BY fi.created_at DESC,fi.id DESC LIMIT 1) recovered_amount FROM ops_error_logs el LEFT JOIN epi_quality_error_profiles qp ON qp.error_id=el.id LEFT JOIN ops_employees lb ON lb.id=el.logged_by LEFT JOIN ops_employees re ON re.id=qp.current_responsible_employee_id WHERE ".implode(' AND ',$w).' ORDER BY el.logged_at DESC,el.id DESC LIMIT 1000';try{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable$e){return[];}}
    private function period(array$f):array{$now=new DateTimeImmutable('now');$p=(string)($f['period']??'previous_month');if($p==='today')return[$now,$now];if($p==='this_month')return[$now->modify('first day of this month'),$now];if($p==='custom'&&!empty($f['date_from'])&&!empty($f['date_to']))return[new DateTimeImmutable($f['date_from']),new DateTimeImmutable($f['date_to'])];return[$now->modify('first day of last month'),$now->modify('last day of last month')];}
}

