const fs = require('fs');
const assert = require('assert');

const helper = fs.readFileSync('apps/operations/kpi-bookkeeping-reconciliation.php', 'utf8');
const api = fs.readFileSync('apps/operations/kpi-employee-data.php', 'utf8');
const ui = fs.readFileSync('assets/js/kpi-employee.js', 'utf8');
const migration = fs.readFileSync('operations-bookkeeping-kpi-migration.sql', 'utf8');
const allocationEndpoint = fs.readFileSync('apps/operations/kpi-bookkeeping-allocation.php', 'utf8');

assert.match(helper, /LOWER\(TRIM\(p\.payment_method\)\)='cash'/, 'cash component must come from authoritative allocations');
assert.match(helper, /related_order_id/, 'matching must use immutable order identity');
assert.match(helper, /numeric_order_number/, 'numeric order reference must be the primary key');
assert.match(helper, /amount_same_date/, 'unique amount and date candidates must remain labelled fuzzy evidence');
assert.match(helper, /amount_mismatch/);
assert.match(helper, /ambiguous/);
assert.match(helper, /bookkeeping_adoption_date/);
assert.match(helper, /isDeliveryMode/);
assert.match(helper, /walk in customer/);
assert.match(helper, /Delivery Driver Funds/);
assert.match(helper, /Expected Delivery Cash/);
assert.match(helper, /Cash delivery is reconciled against Delivery Driver Funds/i);
assert.match(helper, /AJ delivery/);
assert.match(helper, /shipping_total/);
assert.match(helper, /Deposits Recorded Amount/);
assert.match(helper, /money_out_entries/);
assert.match(helper, /created_at/);
assert.match(helper, /backdated/);
assert.match(helper, /retained float/i);
assert.doesNotMatch(helper, /UPDATE ops_cash_book_entries|UPDATE ops_orders|DELETE FROM ops_cash_book_entries/i, 'KPI must remain read-only');
assert.match(migration, /UNIQUE KEY uq_bookkeeping_order_allocation \(bookkeeping_entry_id, order_id\)/);
assert.match(migration, /review_status ENUM\('pending','confirmed','rejected'\)/);
assert.match(migration, /bookkeeping_order_allocation_audit/);
assert.match(api, /kpi_bookkeeping_reconciliation/);
assert.match(api, /\['bookkeeping'\]/, 'bookkeeping must remain connected to the central front-desk score');
assert.match(ui, /Daily cash reconciliation/);
assert.match(ui, /Order-level evidence/);
assert.match(ui, /Deposit records/);
assert.match(ui, /Delivery cash — excluded from score/);
assert.match(ui, /Money out breakdown/);
assert.match(ui, /Money Out — Payments and Uses/);
assert.match(ui, /What the money was used for/);
assert.match(ui, /key==='bookkeeping'.*moneyOutSection/);
assert.match(ui, /Gross cash/);
assert.match(ui, /Driver fee/);
assert.match(ui, /Bookkeeping risk/);
assert.match(ui, /data-confirm-bookkeeping-allocation/);
assert.match(allocationEndpoint, /current_role_key\(\) !== 'owner_admin'/);
assert.match(allocationEndpoint, /Only the Owner\/Admin/);
assert.match(allocationEndpoint, /beginTransaction/);
assert.match(allocationEndpoint, /bookkeeping_order_allocation_audit/);

console.log('Bookkeeping KPI reconciliation contract checks passed.');
