<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/shared/cost-workbook-history.php';
$dsn=getenv('CW_TEST_DSN');if(!$dsn){fwrite(STDERR,"CW_TEST_DSN missing\n");exit(2);} $pdo=new PDO($dsn,(string)getenv('CW_TEST_DB_USER'),(string)getenv('CW_TEST_DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$sets=['supplier_invoices'=>['label'=>'Supplier invoices','order'=>'id','search'=>['invoice_number']],'raw_materials'=>['label'=>'Raw materials','order'=>'id','search'=>['name']],'transport_invoices'=>['label'=>'Transport invoices','order'=>'id','search'=>['invoice_number']],'transport_allocations'=>['label'=>'Transport allocations','order'=>'id','search'=>['component_type']],'ingredient_costs_master'=>['label'=>'Ingredient costs','order'=>'component_id','search'=>['ingredient_name']],'packaging_costs_master'=>['label'=>'Packaging costs','order'=>'component_id','search'=>['packaging_name']],'finished_products'=>['label'=>'Finished products','order'=>'id','search'=>['name']],'product_recipes'=>['label'=>'Product recipes','order'=>'id','search'=>['version']],'woo_sales'=>['label'=>'Woo sales','order'=>'id','search'=>['product_name']]];
$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(array_keys($sets) as $t)$pdo->exec("DROP TABLE IF EXISTS `$t`");$pdo->exec('DROP TABLE IF EXISTS cw_history_guard');
foreach($sets as $t=>$c){$id=$c['order'];$search=$c['search'][0];$pdo->exec("CREATE TABLE `$t` (`$id` INT PRIMARY KEY, `$search` VARCHAR(190), amount DECIMAL(12,2), pdf_path VARCHAR(255))");for($i=1;$i<=($t==='supplier_invoices'?55:2);$i++){$st=$pdo->prepare("INSERT INTO `$t` VALUES(?,?,?,?)");$st->execute([$i,$i===1?'Synthetic <script>alert(&quot;x&quot;)</script>':"Synthetic $t $i",$i.'.25','private/test.pdf']);}}
$pdo->exec('CREATE TABLE cw_history_guard(id INT PRIMARY KEY, value VARCHAR(50))');$pdo->exec("INSERT INTO cw_history_guard VALUES(7,'unchanged')");
$hash=static function()use($pdo,$sets):string{$all=[];foreach(array_merge(array_keys($sets),['cw_history_guard']) as$t)$all[$t]=$pdo->query("SELECT * FROM `$t` ORDER BY 1")->fetchAll(PDO::FETCH_ASSOC);return hash('sha256',serialize($all));};$before=$hash();$assertions=0;$ok=static function(bool$v,string$m)use(&$assertions):void{$assertions++;if(!$v)throw new RuntimeException($m);};
foreach(array_keys($sets)as$t){$r=cw_history_fetch($pdo,$sets,$t,'','desc',1);$ok($r['dataset']===$t,"dataset $t");$ok(count($r['rows'])>0,"rows $t");$ok(!in_array('pdf_path',$r['columns'],true),"private path $t");}
$r=cw_history_fetch($pdo,$sets,'invalid','', 'invalid',0);$ok($r['dataset']==='supplier_invoices','invalid dataset fallback');$ok($r['direction']==='DESC','invalid direction fallback');$ok($r['page']===1,'zero page');$ok(count($r['rows'])===50,'pagination limit');
$r=cw_history_fetch($pdo,$sets,'supplier_invoices','Synthetic supplier_invoices 55','asc',2);$ok($r['total']===1,'search');$ok($r['page']===1,'large page clamped');
foreach(["' OR 1=1 --",'<b>unsafe</b>','"quoted"']as$q){$r=cw_history_fetch($pdo,$sets,'supplier_invoices',$q,'desc',-4);$ok($r['total']===0,'safe shaped search');$ok($r['page']===1,'negative page');}
$escaped=htmlspecialchars('Synthetic <script>alert(&quot;x&quot;)</script>',ENT_QUOTES,'UTF-8');$ok(str_contains($escaped,'&lt;script&gt;'),'escaping');$ok($before===$hash(),'all fixture hashes unchanged');
echo "Cost Workbook historical archive runtime assertions passed: $assertions\n";
