<?php
declare(strict_types=1);
if (!defined('BASE_PATH') || !isset($owner) || $owner) { http_response_code(403); exit; }
$view=(string)($_GET['view']??'dashboard');
$myWork=marketing_employee_work();
$productQuery=db()->prepare('SELECT id,product_name,status,change_notes FROM marketing_product_changes WHERE assigned_employee_id=? ORDER BY updated_at DESC');$productQuery->execute([marketing_employee_id()]);$myProducts=$productQuery->fetchAll();
$portalTasks=[];
if(marketing_table_exists('ops_checklist_tasks')){
    $portalTaskQuery=db()->prepare("SELECT id,task_name,status,priority,deadline,COALESCE(date_assigned,created_at) AS assigned_at FROM ops_checklist_tasks WHERE assigned_employee_id=? AND employee_visible=1 AND (scheduled_at IS NULL OR released_at IS NOT NULL) AND archived_at IS NULL AND deleted_at IS NULL AND status NOT IN('complete','completed','done','cancelled') ORDER BY CASE WHEN deadline IS NULL THEN 1 ELSE 0 END,deadline,id DESC LIMIT 100");
    $portalTaskQuery->execute([marketing_employee_id()]);
    $portalTasks=$portalTaskQuery->fetchAll();
}
$apps=['tasks'=>['Content Tasks','list-checks',[]],'calendar'=>['Calendar','calendar-days',[]],
    'social'=>['Social Media','share-2',['social_post','story','carousel']], 'reels'=>['Reels & Video','clapperboard',['reel']],
    'whatsapp'=>['WhatsApp','message-circle-more',['whatsapp_post']], 'blog'=>['Blog & SEO','search-check',['blog']],
    'newsletter'=>['Newsletter','mail',['newsletter']], 'website'=>['Website & Products','panels-top-left',['website_banner','product_image','product_listing','website_update']],
    'library'=>['Content Library','library',[]]];
$pending=static fn(array $i):bool=>!in_array($i['status'],['published','cancelled'],true);
$badges=[];foreach($apps as$key=>$app)$badges[$key]=count(array_filter($myWork,static fn(array $i):bool=>marketing_work_matches_app($i,$key)));
$badges['tasks']+=count($portalTasks);
$badges['website']+=count(array_filter($myProducts,fn($p)=>in_array($p['status'],['draft','changes_requested'],true)));
$weekStart=date('Y-m-d',strtotime('monday this week'));$weekEnd=date('Y-m-d',strtotime('monday next week'));
$stats=[['Assigned to Me',count(array_filter($myWork,$pending))+count($portalTasks),'list-checks'],
 ['Due Today',count(array_filter($myWork,fn($i)=>$pending($i)&&substr((string)$i['due_at'],0,10)===date('Y-m-d')))+count(array_filter($portalTasks,fn($i)=>substr((string)($i['deadline']??''),0,10)===date('Y-m-d'))),'calendar-days'],
 ['Due This Week',count(array_filter($myWork,fn($i)=>$pending($i)&&$i['due_at']>=$weekStart&&$i['due_at']<$weekEnd))+count(array_filter($portalTasks,fn($i)=>($i['deadline']??'')>=$weekStart&&($i['deadline']??'')<$weekEnd)),'calendar-clock'],
 ['Awaiting My Action',count(array_filter($myWork,fn($i)=>in_array($i['status'],['brief','to_create','in_progress','changes_requested'],true)))+count($portalTasks),'circle-play'],
 ['Ready to Publish',count(array_filter($myWork,fn($i)=>in_array($i['status'],['approved','scheduled'],true))),'send'],
 ['Completed This Week',count(array_filter($myWork,fn($i)=>$i['status']==='published'&&$i['published_at']>=$weekStart&&$i['published_at']<$weekEnd)),'circle-check']];
$isEssDashboard=true;$pageTitle='My Marketing Work | '.APP_NAME;$activeApp='marketing';
$extraStylesheets=[];foreach(['marketing','marketing-extras','marketing-execution'] as$css)$extraStylesheets[]=['path'=>'assets/css/'.$css.'.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/'.$css.'.css')];
require_once BASE_PATH.'/shared/ess-navigation.php';$essShellApps=ess_shell_apps();$essActiveModule='Marketing';$pageUsesPortalSidebar=false;$extraStylesheets[]=['path'=>'assets/css/ess-dashboard.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/ess-dashboard.css')];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/ess-sidebar.php';
?>
<main id="ess-main" class="workspace ess-dashboard-main marketing-workspace ess-marketing-page">
<nav class="marketing-local-nav" aria-label="Marketing"><a class="<?=$view==='dashboard'?'is-active':''?>" href="?view=dashboard">Home</a><a class="<?=$view==='apps'?'is-active':''?>" href="?view=apps">Apps</a></nav>
<?php if($message):?><p class="marketing-notice" role="status"><?=marketing_e($message)?></p><?php endif;?>
<?php if($view==='dashboard'):?>
<section class="marketing-hero">
 <div class="marketing-hero-copy"><p class="marketing-eyebrow">MARKETING &amp; SALES</p><h1 class="marketing-hero-title"><span class="is-olive">Create.</span> <span>Connect.</span> <span class="is-marketing">Convert.</span></h1><p class="marketing-hero-subtitle">All your marketing tools, content and assigned portal tasks in one workspace.</p><div class="marketing-hero-actions"><a class="marketing-btn-primary" href="?view=tasks"><i data-lucide="list-checks"></i>My Assigned Tasks</a><a class="marketing-btn-secondary" href="<?=BASE_URL?>/apps/operations/courier.php"><i data-lucide="truck"></i>Courier</a></div></div>
 <div class="marketing-hero-visual" aria-hidden="true"><img class="marketing-hero-botanical" src="<?=BASE_URL?>/assets/images/marketing-botanical.svg" alt=""><div class="marketing-visual-words"><span>Ideas</span><span>Content</span><span>Customers</span><span>Growth</span></div><p>Marketing that moves your business forward.</p></div>
</section>
<?php endif;?>
<?php if($view==='dashboard'):?><section class="marketing-kpi-grid" aria-label="My work overview"><?php foreach($stats as$stat):?><article class="marketing-kpi-card"><span class="marketing-kpi-icon"><i data-lucide="<?=$stat[2]?>"></i></span><div><span class="marketing-kpi-label"><?=$stat[0]?></span><strong><?=$stat[1]?></strong></div></article><?php endforeach;?></section><?php endif;?>
<?php if($view==='apps'):?><section class="marketing-apps-page"><header class="marketing-section-heading"><div><p>MARKETING WORKSPACE</p><h2>Marketing Apps</h2><span>Everything you need to execute your assigned content.</span></div></header>
<?php foreach(['PLAN'=>['tasks','calendar'],'CREATE'=>['social','reels','blog','newsletter'],'PUBLISH & MANAGE'=>['whatsapp','website','library']] as$category=>$keys):?><section class="marketing-app-category"><h3><?=marketing_e($category)?></h3><div><?php foreach($keys as$key):$app=$apps[$key];?><a class="marketing-app-page-tile" href="?view=<?=$key?>"><span class="marketing-app-icon"><i data-lucide="<?=$app[1]?>"></i></span><span><strong><?=$app[0]?></strong><small>Your assigned <?=marketing_e(strtolower($app[0]))?> work</small></span><i data-lucide="arrow-right"></i><?php if($badges[$key]>0&&$key!=='library'):?><span class="marketing-app-count" aria-label="<?=$badges[$key]?> outstanding"><?=$badges[$key]?></span><?php endif;?></a><?php endforeach;?></div></section><?php endforeach;?></section><?php endif;?>
<?php if($view==='dashboard'):?><div class="marketing-main-grid"><div class="marketing-home-stack"><section class="marketing-panel"><header class="marketing-panel-header"><div><h2><i data-lucide="layout-grid"></i>Marketing Apps</h2><p>Quick access to your marketing tools and workflows.</p></div><a class="marketing-panel-link" href="?view=apps">View all apps <i data-lucide="arrow-right"></i></a></header><div class="marketing-app-grid"><?php foreach($apps as$key=>$app):?><a class="marketing-app-tile" href="?view=<?=$key?>"><span class="marketing-app-icon"><i data-lucide="<?=$app[1]?>"></i></span><span><strong><?=$app[0]?></strong><small>Your assigned work</small></span><?php if($badges[$key]>0&&$key!=='library'):?><span class="marketing-app-count" aria-label="<?=$badges[$key]?> outstanding"><?=$badges[$key]?></span><?php endif;?></a><?php endforeach;?></div></section></div>
<aside class="marketing-home-aside"><section class="marketing-panel marketing-quick"><header class="marketing-panel-header"><div><h2><i data-lucide="zap"></i>Quick Actions</h2><p>Keep the work moving.</p></div></header><div><a href="?view=tasks"><i data-lucide="list-checks"></i>My Assigned Tasks</a><a href="?view=calendar"><i data-lucide="calendar-clock"></i>Calendar</a><a href="?view=library"><i data-lucide="library"></i>Content Library</a></div></section>
<section class="marketing-panel"><header class="marketing-panel-header"><div><h2><i data-lucide="calendar-days"></i>My Assigned Tasks</h2><p>Task Management and Marketing deadlines.</p></div><a class="marketing-panel-link" href="?view=tasks">View all</a></header><div class="marketing-upcoming"><?php foreach(array_slice($portalTasks,0,3)as$task):?><a href="<?=BASE_URL?>/apps/operations/checklists.php?task_view=active&amp;task_id=<?=(int)$task['id']?>"><span><?=marketing_e(!empty($task['deadline'])?date('d M',strtotime((string)$task['deadline'])):'Open')?></span><strong><?=marketing_e((string)$task['task_name'])?></strong><small>Task Management · <?=marketing_e(ucwords(str_replace('_',' ',(string)$task['status'])))?></small></a><?php endforeach;?><?php $upcoming=array_values(array_filter($myWork,fn($i)=>marketing_work_matches_app($i,'tasks')&&($i['due_at']||$i['publish_at'])));usort($upcoming,fn($a,$b)=>strcmp($a['due_at']?:$a['publish_at'],$b['due_at']?:$b['publish_at']));foreach(array_slice($upcoming,0,max(0,3-count($portalTasks)))as$i):?><a href="execution.php?id=<?=(int)$i['id']?>"><span><?=marketing_e(date('d M',strtotime($i['due_at']?:$i['publish_at'])))?></span><strong><?=marketing_e($i['title'])?></strong><small>Marketing content</small></a><?php endforeach;?><?php if(!$portalTasks&&!$upcoming):?><p class="marketing-empty">No assigned tasks.</p><?php endif;?></div></section></aside></div><section class="marketing-brand-strip"><span><i data-lucide="leaf"></i>Great marketing turns ideas into opportunities.</span><small>PLAN • CREATE • PUBLISH • MEASURE • GROW</small></section><?php endif;?>
<?php $items=array_values(array_filter($myWork,fn($i)=>marketing_work_matches_app($i,$view,false)));include __DIR__.'/app-shell.php'; ?>
<?php if($view==='calendar') include __DIR__.'/employee-calendar.php'; ?>
<?php if($view==='tasks'):?><section class="marketing-board"><header><div><p>TASK MANAGEMENT</p><h2>Portal tasks assigned to me</h2></div><a class="marketing-btn-secondary" href="<?=BASE_URL?>/apps/operations/checklists.php?task_view=active">Open Task Management</a></header><?php if(!$portalTasks):?><div class="marketing-empty"><strong>No active portal tasks.</strong><span>New assignments will appear here automatically.</span></div><?php else:?><div class="marketing-table-wrap"><table><thead><tr><th>Task</th><th>Assigned</th><th>Due</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($portalTasks as$task):?><tr><td><strong><?=marketing_e((string)$task['task_name'])?></strong><small>Task #<?=(int)$task['id']?></small></td><td><?=marketing_e((string)($task['assigned_at']??'—'))?></td><td><?=marketing_e((string)($task['deadline']??'Not scheduled'))?></td><td><?=marketing_e(ucwords((string)($task['priority']??'normal')))?></td><td><span class="marketing-status <?=marketing_e((string)$task['status'])?>"><?=marketing_e(ucwords(str_replace('_',' ',(string)$task['status'])))?></span></td><td><a class="marketing-btn-primary" href="<?=BASE_URL?>/apps/operations/checklists.php?task_view=active&amp;task_id=<?=(int)$task['id']?>">Open task</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?>
<?php if($view==='library'):
 $files=db()->prepare('SELECT v.id,v.file_name,v.version_label,w.title FROM marketing_item_versions v JOIN marketing_work_items w ON w.id=v.item_id WHERE w.assigned_employee_id=? AND w.cancelled_at IS NULL ORDER BY v.id DESC');$files->execute([marketing_employee_id()]);?>
<section class="marketing-panel"><h2>Assigned Content Library</h2><div class="marketing-library"><?php foreach($files->fetchAll() as$file):?><article><strong><?=marketing_e($file['title'])?></strong><span><?=marketing_e($file['file_name'])?></span><a class="marketing-btn-secondary" href="<?=BASE_URL?>/apps/marketing/file.php?id=<?=(int)$file['id']?>">Download <?=marketing_e($file['version_label'])?></a></article><?php endforeach;?></div></section>
<?php elseif(!in_array($view,['apps','dashboard','calendar'],true)):
 $types=$apps[$view][2]??[];$showCompleted=($_GET['completed']??'')==='1';
 $visible=array_filter($myWork,fn($i)=>marketing_work_matches_app($i,$view,!$showCompleted)&&(!$showCompleted||$i['status']==='published'));?>
<section class="marketing-board"><header><div><p>ASSIGNED CONTENT</p><h2><?=$view==='tasks'?'Marketing content tasks':marketing_e($apps[$view][0]??'Awaiting my action')?></h2></div><a class="marketing-btn-secondary" href="?view=<?=marketing_e($view)?>&amp;completed=<?=$showCompleted?'0':'1'?>"><?=$showCompleted?'Outstanding work':'Completed work'?></a></header>
<?php if(!$visible):?><div class="marketing-empty"><strong>You're all caught up.</strong><span>No Marketing work currently needs your attention in this view.</span></div><?php else:?><div class="marketing-table-wrap"><table><thead><tr><th>Content</th><th>Channel</th><th>Priority</th><th>Due</th><th>Publish</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($visible as$i):?><tr><td><?=marketing_e($i['title'])?></td><td><?=marketing_e(implode(', ',array_map(fn($c)=>marketing_execution_channels()[$c['channel_key']]??($i['platform']?:'Assigned work'),$i['execution_channels'])))?></td><td><?=marketing_e($i['priority'])?></td><td><?=marketing_e($i['due_at']?:'Not scheduled')?></td><td><?=marketing_e($i['publish_at']?:'Not scheduled')?></td><td><span class="marketing-status <?=marketing_e($i['status'])?>"><?=marketing_e(str_replace('_',' ',$i['status']))?></span></td><td><a class="marketing-btn-secondary" href="execution.php?id=<?=(int)$i['id']?>">Open work</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?>
<?php if($view==='website'&&$myProducts):?><section class="marketing-panel"><h2>Assigned product copy</h2><p>Prepare the copy here. The owner reviews and publishes changes to the shop.</p><?php foreach($myProducts as$p):?><article class="marketing-calendar-day"><h3><?=marketing_e($p['product_name'])?></h3><p><?=marketing_e(str_replace('_',' ',$p['status']))?></p><a href="product-work.php?id=<?=(int)$p['id']?>">Open assigned website work</a></article><?php endforeach;?></section><?php endif;?>
</main>
<?php include BASE_PATH.'/shared/ess-mobile-navigation.php'; ?><script defer src="<?=BASE_URL?>/assets/js/ess-dashboard.js?v=<?=filemtime(BASE_PATH.'/assets/js/ess-dashboard.js')?>"></script><?php include BASE_PATH.'/shared/footer.php'; ?>
