<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/marketing.php';
marketing_require_access();
$owner=marketing_is_owner();$user=current_user();$message='';$failed=false;
try {
 $item=marketing_execution_item((int)($_GET['id']??$_POST['id']??0));
 if($_SERVER['REQUEST_METHOD']==='POST') {
  marketing_verify();
  if(($_POST['action']??'')==='requirements'){
   marketing_require_owner();marketing_execution_requirements((int)$item['id'],(array)($_POST['required_channels']??[]),(array)($_POST['channel_instructions']??[]));
  } else marketing_execution_save($_POST);
  $message='Work saved.';$item=marketing_execution_item((int)$item['id']);
 }
}catch(Throwable $e){$message=$e->getMessage();$failed=true;if(!isset($item)){http_response_code(404);exit(marketing_e($message));}}
$rows=marketing_execution_rows($item);$progress=marketing_execution_progress($rows);
$q=db()->prepare('SELECT id,file_name,version_label FROM marketing_item_versions WHERE item_id=? ORDER BY id DESC');$q->execute([$item['id']]);$files=$q->fetchAll();
$isEssDashboard=true;$activeApp='marketing';$pageTitle='Assigned Marketing Work | '.APP_NAME;
$extraStylesheets=[];foreach(['marketing','marketing-extras','marketing-execution']as$css)$extraStylesheets[]=['path'=>'assets/css/'.$css.'.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/'.$css.'.css')];
require_once BASE_PATH.'/shared/ess-navigation.php';$essShellApps=ess_shell_apps();$essActiveModule='Marketing';$pageUsesPortalSidebar=false;$extraStylesheets[]=['path'=>'assets/css/ess-dashboard.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/ess-dashboard.css')];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/ess-sidebar.php';
?>
<main id="ess-main" class="workspace ess-dashboard-main marketing-workspace ess-marketing-page marketing-execution-workspace"><a class="marketing-btn-secondary" href="index.php?view=tasks">Back to content tasks</a>
<header class="marketing-section-heading"><div><p>ASSIGNED CONTENT</p><h1><?=marketing_e($item['title'])?></h1></div><span class="marketing-status <?=marketing_e($item['status'])?>"><?=marketing_e(str_replace('_',' ',$item['status']))?></span></header>
<?php if($message):?><p class="marketing-notice" role="status"><?=marketing_e($message)?></p><?php endif;?>
<section class="marketing-panel"><h2>Instructions</h2><p class="marketing-instruction-copy"><?=marketing_e($item['brief']?:'No instructions supplied.')?></p><dl class="marketing-execution-meta"><?php foreach(['priority'=>'Priority','due_at'=>'Due','publish_at'=>'Publish','campaign'=>'Campaign','product_reference'=>'Products','required_dimensions'=>'Dimensions','cta'=>'CTA']as$key=>$label):?><div><dt><?=$label?></dt><dd><?=marketing_e((string)($item[$key]?:'Not set'))?></dd></div><?php endforeach;?></dl></section>
<section class="marketing-panel"><h2>Attached assets</h2><div class="marketing-execution-assets"><?php foreach($files as$file):?><a class="marketing-btn-secondary" href="file.php?id=<?=(int)$file['id']?>"><?=marketing_e($file['version_label'].' · '.$file['file_name'])?></a><?php endforeach;?><?php if(!$files):?><p>No files attached yet.</p><?php endif;?></div><form method="post" action="index.php?view=tasks" enctype="multipart/form-data" class="marketing-execution-upload"><input type="hidden" name="csrf" value="<?=marketing_csrf()?>"><input type="hidden" name="action" value="upload"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><label>Attach prepared content or proof<input type="file" name="asset" required></label><button class="marketing-btn-primary">Upload file</button></form></section>
<form method="post" class="marketing-panel marketing-execution-form"><input type="hidden" name="csrf" value="<?=marketing_csrf()?>"><input type="hidden" name="id" value="<?=(int)$item['id']?>">
<header class="marketing-panel-header"><h2>Execution</h2><span><?=$progress['complete']?> / <?=$progress['total']?> channels complete · <?=$progress['percent']?>%</span></header><progress max="100" value="<?=$progress['percent']?>" aria-label="Channel completion"></progress>
<?php foreach($rows as$row):$key=$row['channel_key'];$posted=$failed?(array)($_POST['channels'][$key]??[]):[];$prepared=$failed?!empty($posted['prepared']):(bool)$row['prepared'];$completed=$failed?!empty($posted['completed']):(bool)$row['completed'];$label=marketing_execution_channels()[$key]??'Assigned channel';?>
<fieldset class="marketing-execution-channel"><legend><?=marketing_e($label)?></legend><input type="hidden" name="channels[<?=$key?>][present]" value="1"><p class="marketing-instruction-copy"><?=marketing_e((string)$row['instructions'])?></p><div class="marketing-execution-checks"><label><input type="checkbox" name="channels[<?=$key?>][prepared]" value="1" <?=$prepared?'checked':''?>>Prepared</label><label><input type="checkbox" name="channels[<?=$key?>][completed]" value="1" <?=$completed?'checked':''?>><?=$key==='website'?'Updated':($key==='newsletter'?'Sent':'Published / complete')?></label></div><div class="marketing-form-grid"><label>Proof link (optional)<input type="url" name="channels[<?=$key?>][proof_url]" maxlength="500" value="<?=marketing_e((string)($posted['proof_url']??$row['proof_url']??''))?>"></label><label>Completion notes<textarea name="channels[<?=$key?>][note]"><?=marketing_e((string)($posted['note']??$row['completion_note']??''))?></textarea></label></div></fieldset><?php endforeach;?>
<label>Prepared caption / copy<textarea name="caption"><?=marketing_e((string)($failed?($_POST['caption']??$item['caption']):$item['caption']))?></textarea></label><label>Update note<textarea name="note"><?=marketing_e((string)($failed?($_POST['note']??''):''))?></textarea></label>
<label>Work status<select name="execution_status" data-portal-custom-select><option value="<?=marketing_e($item['status'])?>">Keep current status — <?=marketing_e(str_replace('_',' ',$item['status']))?></option><?php foreach(['in_progress'=>'In Progress','ready_for_review'=>'Ready for Owner Review','published'=>'Complete / Published']as$status=>$label):?><option value="<?=$status?>" <?=$item['status']===$status?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><?php if((int)$item['approval_required']&&!marketing_execution_ready_to_publish($item)):?><p>Owner approval is required before publishing or completing channel work.</p><?php endif;?><button class="marketing-btn-primary">Save progress</button></form>
<?php if($owner):?><form method="post" class="marketing-panel"><h2>Channel requirements</h2><p>Unselected channels are no longer required. Their proof and progress are retained if you select them again.</p><input type="hidden" name="csrf" value="<?=marketing_csrf()?>"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><input type="hidden" name="action" value="requirements"><?php $byKey=array_column($rows,null,'channel_key');foreach(marketing_execution_channels()as$key=>$label):?><label class="marketing-channel-chip"><input type="checkbox" name="required_channels[]" value="<?=$key?>" <?=isset($byKey[$key])?'checked':''?>><?=marketing_e($label)?></label><label><?=marketing_e($label)?> instructions<textarea name="channel_instructions[<?=$key?>]"><?=marketing_e((string)($byKey[$key]['instructions']??''))?></textarea></label><?php endforeach;?><button class="marketing-btn-primary">Save requirements</button></form><?php endif;?>
</main><?php include BASE_PATH.'/shared/ess-mobile-navigation.php'; ?><script defer src="<?=BASE_URL?>/assets/js/ess-dashboard.js?v=<?=filemtime(BASE_PATH.'/assets/js/ess-dashboard.js')?>"></script><?php include BASE_PATH.'/shared/footer.php'; ?>
