<?php

declare(strict_types=1);

require_once __DIR__ . '/operations.php';
if(current_role_key()==='guest'){header('Location: '.BASE_URL.'/login.php');exit;}
if(!user_has_role('owner_admin','supervisor_manager')){http_response_code(403);exit('Owner or supervisor access required.');}
\Hambelela\EPI\Performance::configure(db());
$service=new \Hambelela\EPI\PackingPerformance(db());
$filters=['period'=>(string)($_GET['period']??'previous_month'),'date_from'=>(string)($_GET['date_from']??''),'date_to'=>(string)($_GET['date_to']??''),'employee_id'=>(string)($_GET['employee_id']??''),'priority'=>(string)($_GET['priority']??''),'packing_status'=>(string)($_GET['packing_status']??''),'product_state'=>(string)($_GET['product_state']??''),'workload_class'=>(string)($_GET['workload_class']??'')];
$summary=$service->getEmployeeSummary($filters);$orders=$service->getOrderSummary($filters);$evidence=$service->getEvidence($filters,200);$employees=$service->employeeOptions();
$pageTitle='EPI Packing Verification | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
function epi3_value($value): string{return $value===null?'Insufficient historical data':htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
?>
<main class="workspace module epi-page">
 <section class="module-header"><div><p class="eyebrow">Employee Performance Intelligence &middot; Phase 3 verification</p><h1>Packing &amp; Packing List Performance</h1><p>Owner verification only. Evidence calculations are shown without scores, charts or operational-table duplication.</p></div></section>
 <?php if(!\Hambelela\EPI\Performance::enabled()):?><section class="ops-alert">EPI background recording is disabled by its master feature flag. Existing evidence remains readable.</section><?php endif;?>
 <form method="get" class="section-card" style="padding:16px;display:flex;gap:10px;flex-wrap:wrap;align-items:end">
  <label><span>Employee</span><select name="employee_id"><option value="">All employees</option><?php foreach($employees as $e):?><option value="<?= (int)$e['id']?>" <?= (string)$e['id']===$filters['employee_id']?'selected':''?>><?=htmlspecialchars((string)$e['full_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label>
  <label><span>Period</span><select name="period"><?php foreach(['today'=>'Today','yesterday'=>'Yesterday','this_week'=>'This Week','last_week'=>'Last Week','this_month'=>'This Month','previous_month'=>'Previous Month','quarter'=>'Quarter','year'=>'Year','custom'=>'Custom'] as $v=>$l):?><option value="<?=$v?>" <?=$filters['period']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label>
  <label><span>From</span><input type="date" name="date_from" value="<?=htmlspecialchars($filters['date_from'],ENT_QUOTES,'UTF-8')?>"></label><label><span>To</span><input type="date" name="date_to" value="<?=htmlspecialchars($filters['date_to'],ENT_QUOTES,'UTF-8')?>"></label>
  <label><span>Priority</span><select name="priority"><option value="">All</option><?php foreach(['urgent','top_critical','high','important','medium','normal','low'] as $v):?><option value="<?=$v?>" <?=$filters['priority']===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label>
  <label><span>Product state</span><select name="product_state"><option value="">All</option><?php foreach(['liquid','solid','powder','butter','herb','other'] as $v):?><option value="<?=$v?>" <?=$filters['product_state']===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><button class="btn-primary">Apply</button>
 </form>
 <section class="section-card" style="padding:16px"><h2>Order fulfilment</h2><p>Distinct orders packed: <strong><?=epi3_value($orders['distinct_orders_packed'])?></strong> &middot; Collection: <?=epi3_value($orders['modes']['collection'])?> &middot; Delivery: <?=epi3_value($orders['modes']['delivery'])?> &middot; Courier: <?=epi3_value($orders['modes']['courier'])?> &middot; Walk-in assistance: <?=epi3_value($orders['modes']['walk_in_assistance'])?></p><p>New-to-Packed average: <?=epi3_value($orders['new_to_packed']['average'])?> business minutes. This is turnaround, not hands-on packing time.</p><a href="#evidence">View Evidence</a></section>
 <section class="section-card" style="padding:16px"><h2>Packing List</h2><p>Assigned: <?=epi3_value($summary['items_assigned'])?> &middot; Started: <?=epi3_value($summary['items_started'])?> &middot; Completed: <?=epi3_value($summary['items_completed'])?> &middot; Reopened: <?=epi3_value($summary['quality']['reopened'])?></p><p>Loaded-to-Started average: <?=epi3_value($summary['turnaround']['loaded_to_started']['average'])?> &middot; Started-to-Done average: <?=epi3_value($summary['turnaround']['started_to_done']['average'])?> &middot; Loaded-to-Completed average: <?=epi3_value($summary['turnaround']['loaded_to_completed']['average'])?></p><a href="#evidence">View Evidence</a></section>
 <section class="section-card" style="padding:16px"><h2>Accuracy, workload and compliance</h2><p>Exact: <?=epi3_value($summary['quantity']['exact'])?> &middot; Overpacked: <?=epi3_value($summary['quantity']['overpacked'])?> &middot; Underpacked: <?=epi3_value($summary['quantity']['underpacked'])?> &middot; Accuracy: <?=epi3_value($summary['quantity']['accuracy_percent'])?>%</p><p>Liquid: <?=epi3_value($summary['workload']['liquid'])?> &middot; Solid: <?=epi3_value($summary['workload']['solid'])?> &middot; Powder: <?=epi3_value($summary['workload']['powder'])?> &middot; Mass: <?=epi3_value($summary['workload']['mass_grams'])?> g &middot; Volume: <?=epi3_value($summary['workload']['volume_ml'])?> mL</p><p>Packer website confirmations: <?=epi3_value($summary['website']['confirmed'])?> &middot; Candidate deductions: <?=epi3_value($summary['deduction_candidates'])?> &middot; Candidate bonuses: <?=epi3_value($summary['bonus_candidates'])?> &middot; Final score: Not calculated</p><a href="#evidence">View Evidence</a></section>
 <section class="section-card" style="padding:16px"><h2>Current workload</h2><p>Not Started: <?=epi3_value($summary['current']['not_started'])?> &middot; In Progress: <?=epi3_value($summary['current']['in_progress'])?> &middot; Done: <?=epi3_value($summary['current']['done'])?> &middot; Website Update Pending: <?=epi3_value($summary['current']['website_update_pending'])?> &middot; Quantity Review Required: <?=epi3_value($summary['current']['quantity_review_required'])?></p></section>
 <section id="evidence" class="section-card" style="padding:16px;overflow:auto"><h2>Evidence used</h2><table class="ops-table"><thead><tr><th>Evidence ID</th><th>Reference</th><th>Employee</th><th>Action</th><th>Priority</th><th>Timestamp</th><th>Business duration</th><th>Source</th></tr></thead><tbody><?php if(!$evidence):?><tr><td colspan="8">No EPI Packing evidence exists for this filter.</td></tr><?php else:foreach($evidence as $r):?><tr><td><?=htmlspecialchars((string)$r['evidence_uuid'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['reference_number'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)($r['employee_name']?:'System'),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['action'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['priority'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['occurred_at'],ENT_QUOTES,'UTF-8')?></td><td><?=epi3_value($r['working_minutes'])?></td><td><?=htmlspecialchars((string)$r['activity_source'],ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;endif;?></tbody></table></section>
</main><?php include BASE_PATH.'/shared/footer.php';?>
