<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
if(current_role_key()==='guest'){header('Location: '.BASE_URL.'/login.php');exit;}
if(!user_has_role('owner_admin')){http_response_code(403);exit('Owner access required.');}
\Hambelela\EPI\Performance::configure(db());
$f=['period'=>(string)($_GET['period']??'previous_month'),'date_from'=>(string)($_GET['date_from']??''),'date_to'=>(string)($_GET['date_to']??''),'employee_id'=>(string)($_GET['employee_id']??'')];
$service=new \Hambelela\EPI\AttendancePerformance(db());$summary=$service->getSummary($f);$daily=$service->getDailyAttendance($f);$sessions=$service->getSessions($f);$online=$service->getOnlineEmployees($f);$notifications=$service->getNotificationResponse($f);$issues=$service->getCurrentIssues($f);$employees=$service->employeeOptions();
$pageTitle='EPI Attendance Verification | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
function epi8e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<main class="workspace module epi-page epi-attendance-page">
<section class="module-header"><div><p class="eyebrow">Employee Performance Intelligence &middot; Phase 8 verification</p><h1>Attendance, Portal Activity &amp; Work Reliability</h1><p>Owner-only verification. Portal presence is supporting evidence, not a clocking system or proof of physical attendance.</p></div></section>
<?php if(!\Hambelela\EPI\Performance::enabled()):?><section class="ops-alert">The EPI master feature flag is disabled. Historical session data remains visible, but new immutable EPI login/logout evidence will begin only when EPI is enabled.</section><?php endif;?>
<form method="get" class="section-card" style="padding:16px;display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label><span>Employee</span><select name="employee_id"><option value="">All employees</option><?php foreach($employees as$e):?><option value="<?=(int)$e['id']?>" <?=(string)$e['id']===$f['employee_id']?'selected':''?>><?=epi8e($e['full_name'])?></option><?php endforeach;?></select></label><label><span>Period</span><select name="period"><?php foreach(['today'=>'Today','yesterday'=>'Yesterday','this_week'=>'This Week','last_week'=>'Last Week','this_month'=>'This Month','previous_month'=>'Previous Month','quarter'=>'Quarter','year'=>'Year','custom'=>'Custom']as$v=>$l):?><option value="<?=$v?>" <?=$f['period']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label><span>From</span><input type="date" name="date_from" value="<?=epi8e($f['date_from'])?>"></label><label><span>To</span><input type="date" name="date_to" value="<?=epi8e($f['date_to'])?>"></label><button class="btn-primary">Apply</button></form>
<section class="section-card" style="padding:16px"><h2>Period summary</h2><p>Scheduled days: <?=(int)$summary['scheduled_days']?> &middot; Present: <?=(int)$summary['present_days']?> &middot; Approved leave: <?=(int)$summary['approved_leave_days']?> &middot; On time: <?=(int)$summary['on_time_days']?> &middot; Within grace: <?=(int)$summary['within_grace_days']?> &middot; Late: <?=(int)$summary['late_days']?> &middot; Review required: <?=(int)$summary['review_required']?></p><p><strong>Estimated portal active time:</strong> <?=epi8e($summary['portal_active_time_label'])?>. <?=epi8e($summary['explanation'])?></p></section>
<section class="section-card" style="padding:16px"><h2>Currently online / recently present</h2><div id="epi-attendance-online"><p>Passive refresh every 60 seconds. It never records meaningful activity.</p><?php if(!$online):?><p>No recent portal presence is available.</p><?php else:?><ul><?php foreach($online as$r):?><li><strong><?=epi8e($r['full_name'])?></strong> &middot; <?=epi8e($r['presence_status'])?> &middot; last passive presence <?=epi8e($r['last_seen_at'])?></li><?php endforeach;?></ul><?php endif;?></div></section>
<section class="section-card" style="padding:16px;overflow:auto"><h2>Daily attendance evidence</h2><table class="ops-table"><thead><tr><th>Date</th><th>Employee</th><th>Schedule</th><th>First login</th><th>Last meaningful activity</th><th>Portal active</th><th>Classification</th><th>Review</th></tr></thead><tbody><?php if(!$daily):?><tr><td colspan="8">No attendance evidence exists for this filter.</td></tr><?php else:foreach($daily as$r):?><tr><td><?=epi8e($r['business_date'])?></td><td><?=epi8e($r['employee_name'])?></td><td><?=$r['schedule']?epi8e($r['schedule']['start'].'–'.$r['schedule']['end']):'Not scheduled'?></td><td><?=epi8e($r['first_login']?:'Insufficient Evidence')?></td><td><?=epi8e($r['last_meaningful_activity']?:'Insufficient Evidence')?></td><td><?=epi8e($r['portal_active_time_label'])?></td><td><?=epi8e($r['classification'])?></td><td><?=$r['review_required']?'Owner review required':'—'?></td></tr><?php endforeach;endif;?></tbody></table></section>
<section class="section-card" style="padding:16px;overflow:auto"><h2>Authenticated sessions</h2><table class="ops-table"><thead><tr><th>Employee</th><th>Login</th><th>Last seen</th><th>Logout</th><th>Minutes</th><th>End reason</th></tr></thead><tbody><?php if(!$sessions):?><tr><td colspan="6">No session records exist for this filter.</td></tr><?php else:foreach($sessions as$r):?><tr><td><?=epi8e($r['employee_name'])?></td><td><?=epi8e($r['login_local'])?></td><td><?=epi8e($r['last_seen_local'])?></td><td><?=epi8e($r['logout_local']?:'Open session')?></td><td><?=(int)$r['session_minutes']?></td><td><?=epi8e($r['end_reason']?:$r['session_status'])?></td></tr><?php endforeach;endif;?></tbody></table></section>
<section class="section-card" style="padding:16px"><h2>Notification response evidence</h2><p>Delivered: <?=(int)$notifications['delivered']?> &middot; Read: <?=(int)$notifications['read']?> &middot; Unread: <?=(int)$notifications['unread']?> &middot; Average response: <?=$notifications['average_response_minutes']===null?'Insufficient Evidence':epi8e($notifications['average_response_minutes'].' minutes')?></p></section>
<section class="section-card" style="padding:16px"><h2>Owner review queue</h2><p>Derived review events: <?=count($issues['derived_review_events'])?> &middot; Recorded exceptions pending review: <?=count($issues['recorded_exceptions'])?></p><p><?=epi8e($issues['note'])?></p></section>
</main>
<script>(function(){const box=document.getElementById('epi-attendance-online');if(!box)return;setInterval(async()=>{try{const u=new URL('epi-attendance-performance-data.php',location.href);u.searchParams.set('kind','online');<?php if($f['employee_id']!==''):?>u.searchParams.set('employee_id',<?=json_encode($f['employee_id'])?>);<?php endif;?>const r=await fetch(u,{credentials:'same-origin',headers:{'X-Passive-Poll':'1'}});const j=await r.json();if(!j.ok)return;box.innerHTML='<p>Passive refresh every 60 seconds. It never records meaningful activity.</p>'+(j.data.length?'<ul>'+j.data.map(x=>'<li><strong>'+String(x.full_name).replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]))+'</strong> · '+x.presence_status+' · last passive presence '+x.last_seen_at+'</li>').join('')+'</ul>':'<p>No recent portal presence is available.</p>');}catch(e){}},60000);})();</script>
<?php include BASE_PATH.'/shared/footer.php';?>
