<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
if(current_role_key()==='guest'){header('Location: '.BASE_URL.'/login.php');exit;}
\Hambelela\EPI\Performance::configure(db());
$user=current_user();$owner=user_has_role('owner_admin');$viewer=(int)$user['id'];
$service=new \Hambelela\EPI\PerformanceScore(db());$employees=$owner?$service->employeeOptions():[['id'=>$viewer,'full_name'=>$user['name'],'role_key'=>$user['role_key']]];
$employee=(int)($_GET['employee_id']??$viewer);if(!$owner)$employee=$viewer;$year=(int)($_GET['year']??date('Y'));$month=(int)($_GET['month']??date('n'));$score=$service->getMonthlyScore($employee,$year,$month);$trend=$service->getTrend($employee,12);
if(empty($_SESSION['epi_scoring_csrf']))$_SESSION['epi_scoring_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['epi_scoring_csrf'];
$pageTitle='EPI Scoring Verification | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
function epi9e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function epi9score($v):string{return number_format(((int)$v)/100,2);}
?>
<main class="workspace module epi-page epi-scoring-page">
<section class="module-header"><div><p class="eyebrow">Employee Performance Intelligence &middot; Phase 9 verification</p><h1>Employee Performance Scoring</h1><p>Deterministic, evidence-based scoring. Pending or unverified evidence never changes a score.</p></div></section>
<?php if(!\Hambelela\EPI\Performance::enabled()):?><section class="ops-alert">The Employee Performance master feature flag is disabled. Phase 9 is available for owner verification only and does not affect existing performance pages.</section><?php endif;?>
<form method="get" class="section-card" style="padding:16px;display:flex;gap:10px;align-items:end;flex-wrap:wrap"><label><span>Employee</span><select name="employee_id"><?php foreach($employees as$e):?><option value="<?=(int)$e['id']?>" <?=(int)$e['id']===$employee?'selected':''?>><?=epi9e($e['full_name'])?></option><?php endforeach;?></select></label><label><span>Year</span><input name="year" type="number" min="2020" max="2100" value="<?=$year?>"></label><label><span>Month</span><select name="month"><?php for($m=1;$m<=12;$m++):?><option value="<?=$m?>" <?=$m===$month?'selected':''?>><?=epi9e(date('F',mktime(0,0,0,$m,1)))?></option><?php endfor;?></select></label><button class="btn-primary">Apply</button></form>
<?php if(!$score):?><section class="section-card" style="padding:18px"><h2>No calculated score</h2><p>An owner must first import verified evidence, review the resulting pending events, and calculate this month.</p><?php if($owner):?><div style="display:flex;gap:8px"><button class="btn-secondary" data-epi-action="sync">Import verified evidence</button><button class="btn-primary" data-epi-action="calculate">Calculate month</button></div><?php endif;?></section>
<?php else:?><section class="section-card" style="padding:18px"><h2><?=epi9e($score['employee_name'])?> &middot; <?=epi9e(date('F Y',mktime(0,0,0,$month,1,$year)))?></h2><p><strong>Opening:</strong> 100.00 &middot; <strong>Positive:</strong> +<?=epi9score($score['positive_hundredths'])?> &middot; <strong>Deductions:</strong> -<?=epi9score($score['deduction_hundredths'])?> &middot; <strong>Current score:</strong> <?=epi9score($score['final_hundredths'])?> &middot; <strong>Level:</strong> <?=epi9e($score['performance_level'])?></p><p>Status: <?=epi9e($score['score_status'])?> &middot; Confidence: <?=epi9e($score['confidence_label'])?> &middot; Completeness: <?=epi9score($score['data_completeness_hundredths'])?>% &middot; Pending owner review: <?=(int)$score['pending_review_count']?></p><?php if($owner):?><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn-secondary" data-epi-action="sync">Import verified evidence</button><button class="btn-primary" data-epi-action="calculate">Recalculate</button><?php if((int)$score['locked']===1):?><button class="btn-secondary" data-epi-action="unlock">Unlock month</button><?php else:?><button class="btn-secondary" data-epi-action="lock">Lock month</button><?php endif;?></div><?php endif;?></section>
<section class="section-card" style="padding:18px;overflow:auto"><h2>Category breakdown</h2><table class="ops-table"><thead><tr><th>Category</th><th>Weight</th><th>Positive</th><th>Deduction</th><th>Category score</th><th>Contribution</th></tr></thead><tbody><?php foreach($score['categories']as$r):?><tr><td><?=epi9e($r['category_name'])?></td><td><?=epi9score($r['weight_hundredths'])?>%</td><td>+<?=epi9score($r['positive_hundredths'])?></td><td>-<?=epi9score($r['deduction_hundredths'])?></td><td><?=epi9score($r['final_hundredths'])?></td><td><?=epi9score($r['weighted_contribution_hundredths'])?></td></tr><?php endforeach;?></tbody></table></section>
<section class="section-card" style="padding:18px;overflow:auto"><h2>Evidence decisions</h2><table class="ops-table"><thead><tr><th>Category</th><th>Kind</th><th>Impact</th><th>Status</th><th>Evidence</th><th>Owner review</th></tr></thead><tbody><?php if(!$score['events']):?><tr><td colspan="6">No rule-matched score events exist.</td></tr><?php else:foreach($score['events']as$r):?><tr><td><?=epi9e($r['category_key'])?></td><td><?=epi9e($r['event_kind'])?></td><td><?=epi9score($r['final_impact_hundredths'])?></td><td><?=epi9e($r['confirmation_status'])?></td><td><?=epi9e($r['evidence_uuid']?:'Manual/reversal')?></td><td><?php if($owner&&$r['confirmation_status']==='pending'):?><button class="btn-secondary" data-review-id="<?=(int)$r['id']?>" data-review-status="confirmed">Confirm</button> <button class="btn-secondary" data-review-id="<?=(int)$r['id']?>" data-review-status="dismissed">Dismiss</button><?php else:?><?=epi9e($r['reviewer_note']?:'&mdash;')?><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></section><?php endif;?>
<section class="section-card" style="padding:18px"><h2>12-month trend</h2><p><?php if(!$trend):?>No monthly scores yet.<?php else:foreach($trend as$t):?><?=epi9e(sprintf('%04d-%02d',$t['score_year'],$t['score_month']))?>: <?=epi9score($t['final_hundredths'])?><?=((int)$t['locked']===1?' (locked)':'')?> &nbsp; <?php endforeach;endif;?></p></section>
<?php if($owner):?><p><a href="epi-scoring-settings.php">Open scorecards and rules verification</a></p><?php endif;?></main>
<?php if($owner):?><script>(function(){const csrf=<?=json_encode($csrf)?>,employee=<?=$employee?>,year=<?=$year?>,month=<?=$month?>;async function post(body){const r=await fetch('epi-scoring-performance-data.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({csrf,employee_id:employee,year,month},body))});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');location.reload();}document.addEventListener('click',e=>{const a=e.target.closest('[data-epi-action]');if(a){let action=a.dataset.epiAction,note='';if(['calculate','lock','unlock'].includes(action)){note=prompt('Owner reason / note:')||'';if(!note)return;}post({action,reason:note,note});return;}const b=e.target.closest('[data-review-id]');if(b){const note=prompt('Required review note:')||'';if(!note)return;post({action:'review',event_id:Number(b.dataset.reviewId),status:b.dataset.reviewStatus,note});}});})();</script><?php endif;?>
<?php include BASE_PATH.'/shared/footer.php';?>
