<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
if(current_role_key()==='guest'){header('Location: '.BASE_URL.'/login.php');exit;}
\Hambelela\EPI\Performance::configure(db());
$user=current_user();$owner=user_has_role('owner_admin');$viewer=(int)$user['id'];
$service=new \Hambelela\EPI\PerformanceScore(db());$employees=$owner?$service->employeeOptions():[['id'=>$viewer,'full_name'=>$user['name'],'role_key'=>$user['role_key']]];
$employee=(int)($_GET['employee_id']??$viewer);if(!$owner)$employee=$viewer;$year=(int)($_GET['year']??date('Y'));$month=(int)($_GET['month']??date('n'));$score=$service->getMonthlyScore($employee,$year,$month);$trend=$service->getTrend($employee,12);$coverage=$owner?$service->getSourceCoverage($employee,$year,$month):[];$eligibility=$owner?$service->eligibilityTotals($employee,$year,$month):[];
if(empty($_SESSION['epi_scoring_csrf']))$_SESSION['epi_scoring_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['epi_scoring_csrf'];
$pageTitle='EPI Scoring Verification | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
function epi9e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function epi9score($v):string{return number_format(((int)$v)/100,2);}
?>
<main class="workspace module epi-page epi-scoring-page">
<section class="module-header"><div><p class="eyebrow">Employee Performance Intelligence &middot; Phase 9 verification</p><h1>Employee Performance Scoring</h1><p>Evidence first. Objective events apply automatically; only ambiguous or incomplete evidence needs review.</p></div></section>
<?php if(!\Hambelela\EPI\Performance::enabled()):?><section class="ops-alert">The Employee Performance master feature flag is disabled. Phase 9 is available for owner verification only and does not affect existing performance pages.</section><?php endif;?>
<form method="get" class="section-card" style="padding:16px;display:flex;gap:10px;align-items:end;flex-wrap:wrap"><label><span>Employee</span><select name="employee_id"><?php foreach($employees as$e):?><option value="<?=(int)$e['id']?>" <?=(int)$e['id']===$employee?'selected':''?>><?=epi9e($e['full_name'])?></option><?php endforeach;?></select></label><label><span>Year</span><input name="year" type="number" min="2020" max="2100" value="<?=$year?>"></label><label><span>Month</span><select name="month"><?php for($m=1;$m<=12;$m++):?><option value="<?=$m?>" <?=$m===$month?'selected':''?>><?=epi9e(date('F',mktime(0,0,0,$m,1)))?></option><?php endfor;?></select></label><button class="btn-primary">Apply</button></form>
<?php if(!$score):?><section class="section-card" style="padding:18px"><h2>Score: Not Calculated</h2><p>Status: <strong>Insufficient Historical Data</strong> &middot; Performance Level: <strong>Not Available</strong></p><p>Required source coverage is shown below. Missing evidence is never treated as perfect performance.</p><?php if($owner):?><div style="display:flex;gap:8px"><button class="btn-secondary" data-epi-action="classify">Classify evidence</button><button class="btn-primary" data-epi-action="calculate">Calculate month</button></div><?php endif;?></section>
<?php else:$official=$score['official_score_hundredths']??null;$resultType=(string)($score['result_type']??'legacy');?><section class="section-card" style="padding:18px"><h2><?=epi9e($score['employee_name'])?> &middot; <?=epi9e(date('F Y',mktime(0,0,0,$month,1,$year)))?></h2><p><strong>Score:</strong> <?=$official===null?'Not Calculated':epi9score($official).'%'?> &middot; <strong>Result:</strong> <?=epi9e(ucwords(str_replace('_',' ',$resultType)))?> &middot; <strong>Performance Level:</strong> <?=epi9e($score['official_performance_level']??'Not Available')?></p><p><strong>Confirmed Positive:</strong> +<?=epi9score($score['positive_hundredths'])?> &middot; <strong>Confirmed Deductions:</strong> -<?=epi9score($score['deduction_hundredths'])?> &middot; Confidence: <?=epi9e($score['confidence_label'])?> &middot; Source completeness: <?=epi9score($score['data_completeness_hundredths'])?>% &middot; Needs Review: <?=(int)$score['pending_review_count']?></p><?php if($owner):?><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn-secondary" data-epi-action="classify">Reclassify evidence</button><button class="btn-secondary" data-epi-action="sync">Import eligible evidence</button><button class="btn-primary" data-epi-action="calculate">Recalculate</button><?php if((int)$score['locked']===1):?><button class="btn-secondary" data-epi-action="unlock">Unlock month</button><?php elseif($resultType!=='insufficient_historical_data'):?><button class="btn-secondary" data-epi-action="lock">Lock month</button><?php endif;?></div><?php endif;?></section>
<section class="section-card" style="padding:18px;overflow:auto"><h2>Category status</h2><table class="ops-table"><thead><tr><th>Category</th><th>Weight</th><th>Status</th><th>Eligible score</th><th>Confidence</th><th>Missing sources</th></tr></thead><tbody><?php foreach($score['categories']as$r):?><tr><td><?=epi9e($r['category_name'])?></td><td><?=epi9score($r['weight_hundredths'])?>%</td><td><?=epi9e(ucwords(str_replace('_',' ',(string)($r['calculation_status']??'legacy'))))?></td><td><?=($r['official_score_hundredths']??null)===null?'Not Calculated':epi9score($r['official_score_hundredths']).'%'?></td><td><?=epi9e($r['confidence_label']??'Insufficient Historical Data')?></td><td><?=epi9e(implode(', ',json_decode((string)($r['missing_sources_json']??'[]'),true)?:[]))?></td></tr><?php endforeach;?></tbody></table></section>
<section class="section-card" style="padding:18px;overflow:auto"><h2>Score events</h2><p>Automatically Applied events already affect the score. Needs Review contains only ambiguous or incomplete cases. Excused, excluded and reversed events remain in the audit history.</p><table class="ops-table"><thead><tr><th>Category</th><th>Kind</th><th>Impact</th><th>Automatic status</th><th>Confidence</th><th>Evidence</th><th>Exception review</th></tr></thead><tbody><?php if(!$score['events']):?><tr><td colspan="7">No rule-matched score events exist.</td></tr><?php else:foreach($score['events']as$r):?><tr><td><?=epi9e($r['category_key'])?></td><td><?=epi9e($r['event_kind'])?></td><td><?=epi9score($r['final_impact_hundredths'])?></td><td><?=epi9e(ucwords(str_replace('_',' ',(string)($r['automatic_status']??'needs_review'))))?></td><td><?=epi9e(ucfirst((string)($r['confidence_level']??'insufficient')))?></td><td><?=epi9e($r['evidence_uuid']?:'Manual/reversal')?></td><td><?php if($owner&&($r['automatic_status']??'needs_review')==='needs_review'):?><button class="btn-secondary" data-review-id="<?=(int)$r['id']?>" data-review-status="confirmed">Apply</button> <button class="btn-secondary" data-review-id="<?=(int)$r['id']?>" data-review-status="dismissed">Exclude</button><?php else:?><?=epi9e($r['reviewer_note']?:($r['exception_status']?:'—'))?><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></section><?php endif;?>
<section class="section-card" style="padding:18px"><h2>12-month trend</h2><p><?php if(!$trend):?>No monthly results yet.<?php else:foreach($trend as$t):?><?=epi9e(sprintf('%04d-%02d',$t['score_year'],$t['score_month']))?>: <?=($t['official_score_hundredths']??null)===null?'Not Calculated':epi9score($t['official_score_hundredths']).'%'?> (<?=epi9e(ucwords(str_replace('_',' ',(string)($t['result_type']??'legacy'))))?>)<?=((int)$t['locked']===1?' (locked)':'')?> &nbsp; <?php endforeach;endif;?></p></section>
<?php if($owner):?><section class="section-card" style="padding:18px;overflow:auto"><h2>Required sources</h2><p>Completeness is calculated from role-specific historical sources, ownership, timestamps and required status history.</p><table class="ops-table"><thead><tr><th>Source</th><th>Importance</th><th>Expected</th><th>Eligible</th><th>Completeness</th><th>Ownership</th><th>Timestamps</th><th>Status</th><th>Missing reason</th></tr></thead><tbody><?php foreach(($coverage['sources']??[])as$r):?><tr><td><?=epi9e($r['source_name'])?></td><td><?=epi9e(ucfirst($r['importance']))?></td><td><?=(int)$r['records_expected']?></td><td><?=(int)$r['records_available']?></td><td><?=epi9score($r['completeness_hundredths'])?>%</td><td><?=epi9score($r['ownership_coverage_hundredths'])?>%</td><td><?=epi9score($r['timestamp_coverage_hundredths'])?>%</td><td><?=epi9e(ucfirst($r['source_status']))?></td><td><?=epi9e($r['reason_missing']??'—')?></td></tr><?php endforeach;?></tbody></table></section>
<section class="section-card" style="padding:18px;overflow:auto"><h2>Evidence eligibility totals</h2><table class="ops-table"><thead><tr><th>Module</th><th>Eligibility</th><th>Total</th></tr></thead><tbody><?php if(!$eligibility):?><tr><td colspan="3">No evidence records exist for this employee and period.</td></tr><?php else:foreach($eligibility as$r):?><tr><td><?=epi9e($r['module'])?></td><td><?=epi9e(ucwords(str_replace('_',' ',$r['eligibility_state'])))?></td><td><?=(int)$r['total']?></td></tr><?php endforeach;endif;?></tbody></table></section><?php endif;?>
<?php if($owner):?><p><a href="epi-scoring-settings.php">Open scorecards and rules verification</a></p><?php endif;?></main>
<?php if($owner):?><script>(function(){const csrf=<?=json_encode($csrf)?>,employee=<?=$employee?>,year=<?=$year?>,month=<?=$month?>;async function post(body){const r=await fetch('epi-scoring-performance-data.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({csrf,employee_id:employee,year,month},body))});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');location.reload();}document.addEventListener('click',e=>{const a=e.target.closest('[data-epi-action]');if(a){let action=a.dataset.epiAction,note='';if(['calculate','lock','unlock'].includes(action)){note=prompt('Owner reason / note:')||'';if(!note)return;}post({action,reason:note,note});return;}const b=e.target.closest('[data-review-id]');if(b){const note=prompt('Required review note:')||'';if(!note)return;post({action:'review',event_id:Number(b.dataset.reviewId),status:b.dataset.reviewStatus,note});}});})();</script><?php endif;?>
<?php include BASE_PATH.'/shared/footer.php';?>
