<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';if(current_role_key()==='guest'){header('Location: '.BASE_URL.'/login.php');exit;}if(!user_has_role('owner_admin','supervisor_manager')){http_response_code(403);exit('Owner or supervisor access required.');}
\Hambelela\EPI\Performance::configure(db());if(empty($_SESSION['epi_task_review_csrf']))$_SESSION['epi_task_review_csrf']=bin2hex(random_bytes(32));$reviewCsrf=(string)$_SESSION['epi_task_review_csrf'];$reviewNotice='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='review_task_evidence'){
    try{
        if(!hash_equals($reviewCsrf,(string)($_POST['csrf_token']??'')))throw new RuntimeException('Your session expired. Refresh and try again.');
        $target=trim((string)($_POST['evidence_uuid']??''));$decision=trim((string)($_POST['review_status']??''));$note=trim((string)($_POST['review_note']??''));$allowed=['confirmed','dismissed','excused','system_error','employee_error','external_dependency'];
        if($target===''||!in_array($decision,$allowed,true)||$note==='')throw new RuntimeException('Choose a review outcome and enter a supporting note.');
        $stmt=db()->prepare("SELECT * FROM epi_employee_evidence WHERE evidence_uuid=? AND module='Tasks' AND (action LIKE 'deduction_candidate_%' OR action LIKE 'bonus_candidate_%') LIMIT 1");$stmt->execute([$target]);$source=$stmt->fetch(PDO::FETCH_ASSOC);if(!$source)throw new RuntimeException('The candidate evidence could not be found.');
        $actorId=function_exists('ops_current_employee_id')?(int)ops_current_employee_id():0;$user=current_user();$actorName=(string)($user['name']??('Employee '.$actorId));$at=new DateTimeImmutable('now');
        $metadata=['target_evidence_uuid'=>$target,'review_status'=>$decision,'review_note'=>$note,'reviewed_by_id'=>$actorId?:null,'reviewed_by_name'=>$actorName,'reviewed_at'=>$at->format('Y-m-d H:i:s'),'immutable_review'=>true];
        \Hambelela\EPI\Performance::recordEvidence(['module'=>'Tasks','reference_number'=>$source['reference_number'],'employee_id'=>$source['employee_id'],'employee_name'=>$source['employee_name'],'department'=>$source['department'],'action'=>'task_evidence_reviewed','action_description'=>'Task candidate evidence reviewed: '.$decision,'previous_value'=>'pending_review','new_value'=>$decision,'timestamp'=>$at,'manual'=>true,'verified'=>true,'verified_by'=>$actorName,'activity_source'=>'epi_task_owner_review','deduplication_key'=>\Hambelela\EPI\Support::dedupe(['task-review',$target,$decision,$at->format('Y-m-d H:i:s')]),'metadata'=>$metadata]);
        \Hambelela\EPI\Performance::recordActivity(['module'=>'Tasks','reference_number'=>$source['reference_number'],'employee_id'=>$actorId?:null,'employee_name'=>$actorName,'department'=>'Task Management','activity_type'=>'task_evidence_reviewed','description'=>'Reviewed candidate '.$target.' as '.$decision,'timestamp'=>$at,'manual'=>true,'activity_source'=>'epi_task_owner_review','deduplication_key'=>\Hambelela\EPI\Support::dedupe(['task-review-activity',$target,$decision,$at->format('Y-m-d H:i:s')]),'metadata'=>$metadata]);
        $reviewNotice='Review recorded. The original candidate evidence was retained.';
    }catch(Throwable $error){$reviewNotice=$error->getMessage();}
}
$service=new \Hambelela\EPI\TaskPerformance(db());$filters=['period'=>(string)($_GET['period']??'previous_month'),'date_from'=>(string)($_GET['date_from']??''),'date_to'=>(string)($_GET['date_to']??''),'employee_id'=>(string)($_GET['employee_id']??''),'status'=>(string)($_GET['status']??''),'priority'=>(string)($_GET['priority']??''),'category'=>(string)($_GET['category']??''),'task_kind'=>(string)($_GET['task_kind']??''),'due_result'=>(string)($_GET['due_result']??''),'review_status'=>(string)($_GET['review_status']??'')];$summary=$service->getSummary($filters);$evidence=$service->getEvidence($filters,200);$timeline=$service->getTimeline($filters,100);$employees=$service->employeeOptions();$pageTitle='EPI Task Verification | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';function epi4v($v):string{return$v===null?'Insufficient historical data':htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<main class="workspace module epi-page"><section class="module-header"><div><p class="eyebrow">Employee Performance Intelligence &middot; Phase 4 verification</p><h1>Task Management Performance</h1><p>Owner verification only. Evidence, compliance and current risk are shown without final scores or operational-table duplication.</p></div></section>
<?php if(!\Hambelela\EPI\Performance::enabled()):?><section class="ops-alert">EPI background recording is disabled by its master feature flag. Existing evidence remains readable.</section><?php endif;?>
<?php if($reviewNotice!==''):?><section class="ops-alert"><?=htmlspecialchars($reviewNotice,ENT_QUOTES,'UTF-8')?></section><?php endif;?>
<form method="get" class="section-card" style="padding:16px;display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label><span>Employee</span><select name="employee_id"><option value="">All employees</option><?php foreach($employees as$e):?><option value="<?=(int)$e['id']?>" <?=(string)$e['id']===$filters['employee_id']?'selected':''?>><?=htmlspecialchars((string)$e['full_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label><span>Period</span><select name="period"><?php foreach(['today'=>'Today','yesterday'=>'Yesterday','this_week'=>'This Week','last_week'=>'Last Week','this_month'=>'This Month','previous_month'=>'Previous Month','quarter'=>'Quarter','year'=>'Year','custom'=>'Custom']as$v=>$l):?><option value="<?=$v?>" <?=$filters['period']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><label><span>From</span><input type="date" name="date_from" value="<?=htmlspecialchars($filters['date_from'],ENT_QUOTES,'UTF-8')?>"></label><label><span>To</span><input type="date" name="date_to" value="<?=htmlspecialchars($filters['date_to'],ENT_QUOTES,'UTF-8')?>"></label><label><span>Status</span><select name="status"><option value="">All</option><?php foreach(['new','in_progress','complete']as$v):?><option value="<?=$v?>" <?=$filters['status']===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label><label><span>Priority</span><select name="priority"><option value="">All</option><?php foreach(['urgent','important','normal']as$v):?><option value="<?=$v?>" <?=$filters['priority']===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><label><span>Kind</span><select name="task_kind"><option value="">All</option><option value="manual">Manual</option><option value="recurring">Recurring</option></select></label><button class="btn-primary">Apply</button></form>
<section class="section-card" style="padding:16px"><h2>Workload and completion</h2><p>Assigned: <?=epi4v($summary['workload']['tasks_assigned'])?> &middot; Manual: <?=epi4v($summary['workload']['manual_tasks'])?> &middot; Recurring occurrences: <?=epi4v($summary['workload']['recurring_occurrences'])?> &middot; Completed: <?=epi4v($summary['status']['completed'])?> &middot; Still open: <?=epi4v($summary['status']['still_open'])?></p><p>Completion: <?=epi4v($summary['completion']['completion_percent'])?>% of <?=epi4v($summary['completion']['eligible_assigned'])?> eligible assigned tasks. Cancelled tasks are excluded.</p><a href="#evidence">View Evidence</a></section>
<section class="section-card" style="padding:16px"><h2>Timeliness</h2><p>Created/Assigned-to-Started average: <?=epi4v($summary['timeliness']['created_to_started']['average'])?> &middot; Started-to-Completed average: <?=epi4v($summary['timeliness']['started_to_completed']['average'])?> &middot; Assigned-to-Completed average: <?=epi4v($summary['timeliness']['assigned_to_completed']['average'])?> business minutes</p><p>On time: <?=epi4v($summary['timeliness']['on_time_completed'])?> &middot; Late: <?=epi4v($summary['timeliness']['late_completed'])?> &middot; On-time rate: <?=epi4v($summary['timeliness']['on_time_percent'])?>%</p><a href="#evidence">View Evidence</a></section>
<section class="section-card" style="padding:16px"><h2>Compliance and quality</h2><p>Checklist: <?=epi4v($summary['compliance']['checklist']['percent'])?>% &middot; Mandatory notes: <?=epi4v($summary['compliance']['notes']['percent'])?>% &middot; Required evidence: <?=epi4v($summary['compliance']['evidence']['percent'])?>%</p><p>First-time-right: <?=epi4v($summary['quality']['first_time_right'])?> &middot; Reopened: <?=epi4v($summary['quality']['reopened'])?> &middot; Candidate deductions: <?=epi4v($summary['deduction_candidates'])?> &middot; Candidate bonuses: <?=epi4v($summary['bonus_candidates'])?> &middot; Final score: Not calculated</p><a href="#evidence">View Evidence</a></section>
<section class="section-card" style="padding:16px"><h2>Current risk</h2><p>Open: <?=epi4v($summary['current_risk']['total_open'])?> &middot; New: <?=epi4v($summary['current_risk']['new'])?> &middot; In Progress: <?=epi4v($summary['current_risk']['in_progress'])?> &middot; Due today: <?=epi4v($summary['current_risk']['due_today'])?> &middot; Overdue: <?=epi4v($summary['current_risk']['overdue'])?> &middot; Urgent overdue: <?=epi4v($summary['current_risk']['urgent_overdue'])?> &middot; Important overdue: <?=epi4v($summary['current_risk']['important_overdue'])?></p></section>
<section id="evidence" class="section-card" style="padding:16px;overflow:auto"><h2>Evidence used</h2><table class="ops-table"><thead><tr><th>Evidence ID</th><th>Task</th><th>Employee</th><th>Action</th><th>Status</th><th>Priority</th><th>Timestamp</th><th>Business duration</th><th>Review</th></tr></thead><tbody><?php if(!$evidence):?><tr><td colspan="9">No EPI Task evidence exists for this filter.</td></tr><?php else:foreach($evidence as$r):$m=json_decode((string)$r['metadata_json'],true)?:[];$candidate=strpos((string)$r['action'],'deduction_candidate_')===0||strpos((string)$r['action'],'bonus_candidate_')===0;?><tr><td><?=htmlspecialchars((string)$r['evidence_uuid'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)($m['task_title']??$r['reference_number']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)($r['employee_name']?:'System'),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['action'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['status_after'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['priority'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['occurred_at'],ENT_QUOTES,'UTF-8')?></td><td><?=epi4v($r['working_minutes'])?></td><td><?php if($candidate):?><form method="post" style="display:grid;gap:4px;min-width:210px"><input type="hidden" name="action" value="review_task_evidence"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($reviewCsrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="evidence_uuid" value="<?=htmlspecialchars((string)$r['evidence_uuid'],ENT_QUOTES,'UTF-8')?>"><select name="review_status" required><option value="">Pending review</option><?php foreach(['confirmed','dismissed','excused','system_error','employee_error','external_dependency']as$decision):?><option value="<?=$decision?>"><?=ucwords(str_replace('_',' ',$decision))?></option><?php endforeach;?></select><input name="review_note" required placeholder="Supporting note"><button class="btn-secondary" type="submit">Record review</button></form><?php else:?><?=htmlspecialchars((string)($m['review_status']??'not_required'),ENT_QUOTES,'UTF-8')?><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></section>
<section class="section-card" style="padding:16px;overflow:auto"><h2>Task activity timeline</h2><table class="ops-table"><thead><tr><th>Timestamp</th><th>Employee</th><th>Task</th><th>Event</th><th>Source</th><th>Activity ID</th></tr></thead><tbody><?php if(!$timeline):?><tr><td colspan="6">No EPI Task activity exists for this filter.</td></tr><?php else:foreach($timeline as$r):?><tr><td><?=htmlspecialchars((string)$r['occurred_at'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)($r['employee_name']?:'System'),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['reference_number'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['activity_type'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['activity_source'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars((string)$r['activity_uuid'],ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;endif;?></tbody></table></section></main><?php include BASE_PATH.'/shared/footer.php';?>
