<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
header('Content-Type: application/json; charset=utf-8');
function limited_error_json(array $body,int $status=200):void{http_response_code($status);echo json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
try{
    require_role('owner_admin','front_desk_admin','front_desk_admin_employee');
    if($_SERVER['REQUEST_METHOD']!=='POST')limited_error_json(['ok'=>false,'success'=>false,'error'=>'Method not allowed.'],405);
    $payload=json_decode((string)file_get_contents('php://input'),true);if(!is_array($payload))limited_error_json(['ok'=>false,'success'=>false,'error'=>'Invalid request.'],400);
    $allowed=['csrf','error_id','occurred_on','financial_impact'];$restricted=array_diff(array_keys($payload),$allowed);if($restricted)limited_error_json(['ok'=>false,'success'=>false,'error'=>'You do not have permission to update those error fields.'],403);
    $csrf=(string)($payload['csrf']??'');$expected=(string)($_SESSION['error_limited_edit_csrf']??'');if($csrf===''||$expected===''||!hash_equals($expected,$csrf))limited_error_json(['ok'=>false,'success'=>false,'error'=>'Your session expired. Refresh and try again.'],403);
    $errorId=max(0,(int)($payload['error_id']??0));$actorEmployee=(int)(ops_current_employee_id()??0);$visibilitySql='id=? AND deleted_at IS NULL';$visibilityParams=[$errorId];if(!user_has_role('owner_admin')){$visibilitySql.=' AND (employee_id=? OR people_involved LIKE ? OR people_involved LIKE ? OR people_involved LIKE ? OR people_involved LIKE ? OR logged_by=? OR EXISTS (SELECT 1 FROM ops_error_instruction_reads instruction_read JOIN ops_error_instructions instruction ON instruction.id=instruction_read.instruction_id WHERE instruction.error_id=ops_error_logs.id AND instruction_read.recipient_user_id=?))';array_push($visibilityParams,$actorEmployee,'['.$actorEmployee.']','['.$actorEmployee.',%','%,'.$actorEmployee.',%','%,'.$actorEmployee.']',$actorEmployee,$actorEmployee);}$rows=ops_rows("SELECT * FROM ops_error_logs WHERE {$visibilitySql} LIMIT 1",$visibilityParams);if(!$rows)limited_error_json(['ok'=>false,'success'=>false,'error'=>'Error record not found.'],404);$existing=$rows[0];
    $zone=new DateTimeZone('Africa/Windhoek');$rawDate=trim((string)($payload['occurred_on']??''));$date=DateTimeImmutable::createFromFormat('!Y-m-d',$rawDate,$zone);$dateErrors=DateTimeImmutable::getLastErrors();if(!$date||(is_array($dateErrors)&&(($dateErrors['warning_count']??0)||($dateErrors['error_count']??0)))||$date->format('Y-m-d')!==$rawDate)limited_error_json(['ok'=>false,'success'=>false,'error'=>'Please select a valid error date.'],422);if($date>new DateTimeImmutable('today',$zone))limited_error_json(['ok'=>false,'success'=>false,'error'=>'The error date cannot be in the future.'],422);
    $rawImpact=$payload['financial_impact']??null;$impact=null;if($rawImpact!==null&&trim((string)$rawImpact)!==''){$normalised=preg_replace('/^\s*N\$\s*/i','',trim((string)$rawImpact));$normalised=str_replace(',','',(string)$normalised);if(!preg_match('/^(?:0|[1-9]\d{0,9})(?:\.\d{1,2})?$/',$normalised))limited_error_json(['ok'=>false,'success'=>false,'error'=>'Financial impact must be zero or a valid positive amount.'],422);$impact=number_format((float)$normalised,2,'.','');}
    $actorUser=(int)(current_user()['id']??0);$actorNameRaw=(string)(current_user()['name']??'Employee');$actorName=function_exists('mb_substr')?mb_substr($actorNameRaw,0,190):substr($actorNameRaw,0,190);$role=current_role_key();$source=user_has_role('owner_admin')?'corrected_by_owner':'corrected_by_front';$oldDate=(string)($existing['occurred_on']??'');$oldImpact=$existing['financial_impact']===null?null:number_format((float)$existing['financial_impact'],2,'.','');$changedDate=$oldDate!==$rawDate;$changedImpact=$oldImpact!==$impact;
    db()->beginTransaction();try{
        if($changedDate||$changedImpact){db()->prepare('UPDATE ops_error_logs SET occurred_on=?,occurred_at=?,occurred_on_source=?,financial_impact=?,has_financial_impact=? WHERE id=? AND deleted_at IS NULL')->execute([$rawDate,$rawDate.' 00:00:00',$source,$impact,$impact===null?null:((float)$impact>0?1:0),$errorId]);$audit=db()->prepare('INSERT INTO ops_error_field_audit(error_id,field_name,previous_value,new_value,changed_by_employee_id,changed_by_user_id,changed_by_name,changed_by_role,change_source) VALUES(?,?,?,?,?,?,?,?,?)');if($changedDate)$audit->execute([$errorId,'occurred_on',$oldDate,$rawDate,$actorEmployee,$actorUser,$actorName,$role,$source]);if($changedImpact)$audit->execute([$errorId,'financial_impact',$oldImpact,$impact,$actorEmployee,$actorUser,$actorName,$role,$source]);$meta=['previous_error_date'=>$oldDate,'new_error_date'=>$rawDate,'previous_financial_impact'=>$oldImpact,'new_financial_impact'=>$impact,'changed_fields'=>array_values(array_filter([$changedDate?'occurred_on':null,$changedImpact?'financial_impact':null])),'actor_employee_id'=>$actorEmployee,'actor_user_id'=>$actorUser,'actor_name'=>$actorName,'actor_role'=>$role,'source'=>$source,'request_source'=>'error_log_ajax'];ops_activity_log('error_log_financial_details_updated','error_log',$errorId,$meta);}
        db()->commit();
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw$e;}
    $summary=ops_rows('SELECT COALESCE(SUM(financial_impact),0) total_financial_impact FROM ops_error_logs WHERE deleted_at IS NULL')[0]??[];$total=number_format((float)($summary['total_financial_impact']??0),2,'.','');$dateDisplay=$date->format('j M Y');$impactDisplay=$impact===null?'Not recorded':'N$'.number_format((float)$impact,2,'.',',');
    limited_error_json(['ok'=>true,'success'=>true,'error_id'=>$errorId,'error_date'=>$rawDate,'error_date_display'=>$dateDisplay,'financial_impact'=>$impact,'financial_impact_display'=>$impactDisplay,'updated_at_display'=>(new DateTimeImmutable('now',$zone))->format('j M Y · H:i'),'changed'=>$changedDate||$changedImpact,'summary_updates'=>['total_financial_impact'=>$total,'total_financial_impact_display'=>'N$'.number_format((float)$total,2,'.',',')],'data'=>['error_id'=>$errorId,'occurred_on'=>$rawDate,'financial_impact'=>$impact,'occurred_on_source'=>$source]]);
}catch(Throwable $e){error_log('Restricted Error Log update: '.$e->getMessage());limited_error_json(['ok'=>false,'success'=>false,'error'=>'The changes could not be saved. Please try again.'],500);}
