<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
header('Content-Type: application/json; charset=utf-8');
function limited_error_json(array $body,int $status=200):never{http_response_code($status);echo json_encode($body,JSON_UNESCAPED_SLASHES);exit;}
try{
    require_role('owner_admin','front_desk_admin','front_desk_admin_employee');
    if($_SERVER['REQUEST_METHOD']!=='POST')limited_error_json(['ok'=>false,'error'=>'Method not allowed.'],405);
    $payload=json_decode((string)file_get_contents('php://input'),true);if(!is_array($payload))limited_error_json(['ok'=>false,'error'=>'Invalid request.'],400);
    $allowed=['csrf','error_id','occurred_on','financial_impact'];$restricted=array_diff(array_keys($payload),$allowed);if($restricted)limited_error_json(['ok'=>false,'error'=>'You do not have permission to update those error fields.'],403);
    $csrf=(string)($payload['csrf']??'');$expected=(string)($_SESSION['error_limited_edit_csrf']??'');if($csrf===''||$expected===''||!hash_equals($expected,$csrf))limited_error_json(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],403);
    $errorId=max(0,(int)($payload['error_id']??0));$rows=ops_rows('SELECT * FROM ops_error_logs WHERE id=? AND deleted_at IS NULL LIMIT 1',[$errorId]);if(!$rows)limited_error_json(['ok'=>false,'error'=>'Error record not found.'],404);$existing=$rows[0];
    $zone=new DateTimeZone('Africa/Windhoek');$rawDate=trim((string)($payload['occurred_on']??''));$date=DateTimeImmutable::createFromFormat('!Y-m-d',$rawDate,$zone);$dateErrors=DateTimeImmutable::getLastErrors();if(!$date||(is_array($dateErrors)&&(($dateErrors['warning_count']??0)||($dateErrors['error_count']??0)))||$date->format('Y-m-d')!==$rawDate)limited_error_json(['ok'=>false,'error'=>'Please select the date the error occurred.'],422);if($date>new DateTimeImmutable('today',$zone))limited_error_json(['ok'=>false,'error'=>'The error occurrence date cannot be in the future.'],422);
    $rawImpact=$payload['financial_impact']??null;$impact=null;if($rawImpact!==null&&$rawImpact!==''){if(!preg_match('/^(?:0|[1-9]\d{0,9})(?:\.\d{1,2})?$/',(string)$rawImpact))limited_error_json(['ok'=>false,'error'=>'Enter a valid financial impact of zero or more.'],422);$impact=number_format((float)$rawImpact,2,'.','');}
    $actor=(int)(ops_current_employee_id()??0);$role=current_role_key();$source=user_has_role('owner_admin')?'corrected_by_owner':'corrected_by_front';$oldDate=(string)($existing['occurred_on']??'');$oldImpact=$existing['financial_impact']===null?null:(string)$existing['financial_impact'];
    db()->beginTransaction();try{db()->prepare('UPDATE ops_error_logs SET occurred_on=?,occurred_at=?,occurred_on_source=?,financial_impact=?,has_financial_impact=? WHERE id=? AND deleted_at IS NULL')->execute([$rawDate,$rawDate.' 00:00:00',$source,$impact,$impact===null?null:((float)$impact>0?1:0),$errorId]);$audit=db()->prepare('INSERT INTO ops_error_field_audit(error_id,field_name,previous_value,new_value,changed_by_employee_id,changed_by_role,change_source) VALUES(?,?,?,?,?,?,?)');if($oldDate!==$rawDate)$audit->execute([$errorId,'occurred_on',$oldDate,$rawDate,$actor,$role,$source]);if($oldImpact!==$impact)$audit->execute([$errorId,'financial_impact',$oldImpact,$impact,$actor,$role,$source]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw$e;}
    if($oldDate!==$rawDate)ops_activity_log($oldDate===''?'historical_occurrence_date_confirmed':'error_occurrence_date_changed','error_log',$errorId,['previous_value'=>$oldDate,'new_value'=>$rawDate,'actor_employee_id'=>$actor,'actor_role'=>$role,'source'=>$source]);if($oldImpact!==$impact)ops_activity_log('error_financial_impact_changed','error_log',$errorId,['previous_value'=>$oldImpact,'new_value'=>$impact,'actor_employee_id'=>$actor,'actor_role'=>$role,'source'=>$source]);
    limited_error_json(['ok'=>true,'data'=>['error_id'=>$errorId,'occurred_on'=>$rawDate,'financial_impact'=>$impact,'occurred_on_source'=>$source]]);
}catch(Throwable $e){error_log('Restricted Error Log update: '.$e->getMessage());limited_error_json(['ok'=>false,'error'=>'The changes could not be saved. Please try again.'],500);}
