<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
if(!user_has_role('owner_admin')){http_response_code(403);header('Cache-Control: no-store, private');exit('Access denied.');}
register_shutdown_function(static function():void{
    $fatal=error_get_last();
    if(!$fatal||!in_array((int)$fatal['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true))return;
    if(!headers_sent())http_response_code(200);
    echo '<main class="workspace module"><div class="ops-alert error">Historical attribution report could not load: '.htmlspecialchars((string)$fatal['message'],ENT_QUOTES,'UTF-8').'</div></main>';
});
require_once __DIR__.'/order-attribution-service.php';
$isOwner=true;
if(empty($_SESSION['order_attribution_csrf']))$_SESSION['order_attribution_csrf']=bin2hex(random_bytes(32));
$csrf=(string)$_SESSION['order_attribution_csrf'];$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!hash_equals($csrf,(string)($_POST['csrf_token']??'')))throw new RuntimeException('Your session expired. Refresh and try again.');
  $orderId=max(0,(int)($_POST['order_id']??0));$outcome=(string)($_POST['outcome']??'');$note=trim((string)($_POST['supporting_note']??''));$confirmedPacker=max(0,(int)($_POST['confirmed_packer_id']??0));$confirmedFrom=max(0,(int)($_POST['confirmation_obtained_from']??0));
  if(!$orderId||!in_array($outcome,['confirmed','unable_to_confirm'],true)||$note==='')throw new RuntimeException('Review the order and enter the required supporting note.');
  if($outcome==='confirmed'&&(!$confirmedPacker||!$confirmedFrom))throw new RuntimeException('Choose both the confirmed packer and the person who confirmed it.');
  $order=ops_rows('SELECT id,order_number,status,created_at,assigned_packer_id FROM ops_orders WHERE id=? LIMIT 1',[$orderId])[0]??null;if(!$order)throw new RuntimeException('Order not found.');
  $review=ops_rows('SELECT * FROM ops_order_attribution_reviews WHERE order_id=? LIMIT 1',[$orderId])[0]??null;if(!$review)throw new RuntimeException('Audit evidence is not available for this order.');
  $actor=ops_current_employee_id();$classification=$outcome==='confirmed'?'system_confirmed':'unable_to_confirm';$policy=((string)$order['created_at']>=ops_order_attribution_policy_date())?1:0;$compliance=$outcome==='confirmed'&&$policy?'missed_attribution':'excluded';
  db()->beginTransaction();
  db()->prepare('UPDATE ops_order_attribution_reviews SET classification=?,confirmed_packer_id=?,confirmation_obtained_from=?,supporting_note=?,assignment_method=?,policy_applies=?,compliance_result=?,reviewed_by=?,reviewed_at=NOW(),restored_at=IF(? IS NULL,NULL,NOW()) WHERE order_id=?')->execute([$classification,$confirmedPacker?:null,$confirmedFrom?:null,$note,$outcome==='confirmed'?'Historical staff confirmation':'Staff unable to confirm',$policy,$compliance,$actor,$confirmedPacker?:null,$orderId]);
  if($outcome==='confirmed')db()->prepare('UPDATE ops_orders SET assigned_packer_id=?,assigned_at=COALESCE(assigned_at,NOW()),updated_at=NOW() WHERE id=? AND assigned_packer_id IS NULL')->execute([$confirmedPacker,$orderId]);
  ops_activity_log($outcome==='confirmed'?'historical_packed_by_staff_confirmed':'historical_packed_by_unable_to_confirm','order',$orderId,['original_value'=>'Unassigned','new_packer_id'=>$confirmedPacker?:null,'correction_actor_id'=>$actor,'confirmation_obtained_from'=>$confirmedFrom?:null,'supporting_note'=>$note,'source_evidence'=>json_decode((string)($review['source_evidence_json']??'{}'),true),'historical_correction'=>true,'compliance_result'=>$compliance]);
  db()->commit();$message=$outcome==='confirmed'?'Historical Packed By assignment restored.':'Order marked Unable to confirm and excluded from individual performance scoring.';
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
$reportDataError='';$unassignedIds=[];
try{$unassignedIds=array_column(ops_rows("SELECT id FROM ops_orders WHERE assigned_packer_id IS NULL AND deleted_at IS NULL ORDER BY id"),'id');}catch(Throwable $e){$reportDataError='Unable to load unassigned orders: '.$e->getMessage();}
foreach($unassignedIds as$id){try{ops_seed_and_recover_order_attribution((int)$id);}catch(Throwable $e){error_log(date(DATE_ATOM).' attribution audit '.$id.': '.$e->getMessage().PHP_EOL,3,BASE_PATH.'/logs/kpi_errors.log');}}
$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['date_from']??''))?(string)$_GET['date_from']:'';$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['date_to']??''))?(string)$_GET['date_to']:'';$status=(string)($_GET['status']??'');$classification=(string)($_GET['classification']??'');
$where=['1=1'];$params=[];if($from!==''){$where[]='DATE(o.created_at)>=?';$params[]=$from;}if($to!==''){$where[]='DATE(o.created_at)<=?';$params[]=$to;}if($status!==''){$where[]='o.status=?';$params[]=$status;}if($classification!==''){$where[]='r.classification=?';$params[]=$classification;}
$rows=[];try{$rows=ops_rows("SELECT r.*,o.order_number,o.customer_name,o.status,o.created_at order_date,o.completed_at,possible.full_name possible_packer,confirmed.full_name confirmed_packer,source.full_name confirmation_source,reviewer.full_name correction_actor FROM ops_order_attribution_reviews r JOIN ops_orders o ON o.id=r.order_id LEFT JOIN ops_employees possible ON possible.id=r.possible_packer_id LEFT JOIN ops_employees confirmed ON confirmed.id=r.confirmed_packer_id LEFT JOIN ops_employees source ON source.id=r.confirmation_obtained_from LEFT JOIN ops_employees reviewer ON reviewer.id=r.reviewed_by WHERE ".implode(' AND ',$where).' ORDER BY o.created_at DESC,o.id DESC',$params);}catch(Throwable $e){$reportDataError=trim($reportDataError.' Unable to load audit results: '.$e->getMessage());}
$summary=['total'=>count($rows),'system_confirmed'=>0,'staff_confirmation_required'=>0,'unable_to_confirm'=>0,'restored'=>0,'excluded'=>0];foreach($rows as$row){$key=(string)$row['classification'];if(isset($summary[$key]))$summary[$key]++;if(!empty($row['restored_at']))$summary['restored']++;if(in_array($key,['unable_to_confirm','staff_confirmation_required'],true))$summary['excluded']++;}
$export=(string)($_GET['export']??'');
if(in_array($export,['csv','full_csv','staff_csv'],true)){
 header('Content-Type:text/csv; charset=utf-8');
 header('Cache-Control:no-store, private');
 $staffExport=$export==='staff_csv';
 header('Content-Disposition:attachment; filename="'.($staffExport?'unassigned-orders-staff-verification-copy.csv':'historical-unassigned-orders-full-owner-report.csv').'"');
 $out=fopen('php://output','wb');
 if($staffExport){
  fputcsv($out,['Unassigned Orders Staff Verification Copy']);
  fputcsv($out,['Order number','Order date','Customer name','Status','Completion date and time','Relevant available evidence','Possible packer (unconfirmed)','Confirmed packer','Confirmation source','Supporting reason','Unable to confirm']);
  foreach($rows as$row){if((string)$row['classification']!=='staff_confirmation_required')continue;$e=json_decode((string)$row['source_evidence_json'],true);fputcsv($out,[$row['order_number'],$row['order_date'],$row['customer_name'],$row['status'],$row['completed_at'],implode(', ',(array)($e['sources']??[])),($row['possible_packer']?((string)$row['possible_packer'].' (unconfirmed)'):''),'','','','']);}
 }else{
  fputcsv($out,['Historical Unassigned Orders Full Owner Report']);
  fputcsv($out,['Order','Order date','Completion date','Customer','Status','Classification','Possible packer','Confirmed packer','Confirmation obtained from','Evidence sources','Assignment method','Date restored','Supporting note','Compliance result','Correction actor']);
  foreach($rows as$row){$e=json_decode((string)$row['source_evidence_json'],true);fputcsv($out,[$row['order_number'],$row['order_date'],$row['completed_at'],$row['customer_name'],$row['status'],$row['classification'],$row['possible_packer'],$row['confirmed_packer'],$row['confirmation_source'],implode(', ',(array)($e['sources']??[])),$row['assignment_method'],$row['restored_at'],$row['supporting_note'],$row['compliance_result'],$row['correction_actor']]);}
 }
 fclose($out);exit;
}
$isStaffCopy=(string)($_GET['copy']??'')==='staff';
$employees=[];try{$hasPackingAssignable=ops_ensure_packing_assignable_column();$employeeEligibility=$hasPackingAssignable?"(e.packing_assignable=1 OR r.role_key IN ('front_desk_admin','supervisor_manager'))":"r.role_key IN ('front_desk_admin','packer','supervisor_manager')";$employees=ops_rows("SELECT e.id,e.full_name FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id WHERE e.status='active' AND {$employeeEligibility} ORDER BY e.full_name");}catch(Throwable $e){$reportDataError=trim($reportDataError.' Unable to load employees: '.$e->getMessage());}
$pageTitle='Historical Unassigned Orders Verification Report | '.APP_NAME;$activeApp='kpi';include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module historical-attribution-report"><header class="module-header"><div><p class="eyebrow">Orders · Attribution audit</p><h1><?=$isStaffCopy?'Staff Verification Copy':'Historical Unassigned Orders Verification Report'?></h1><p><?=$isStaffCopy?'Only unresolved orders requiring staff confirmation are included. Possible packers are unconfirmed.':'Original activity history is preserved. Only owner-approved corrections become final.'?></p></div><div><?php if($isStaffCopy):?><a class="btn-secondary" href="?export=staff_csv">Download Staff CSV</a><button class="btn-secondary" type="button" onclick="window.print()">Print Staff PDF</button><a class="btn-secondary" href="historical-order-attribution-report.php">Back to Owner Report</a><?php else:?><a class="btn-secondary" href="?<?=htmlspecialchars(http_build_query(array_merge($_GET,['export'=>'full_csv'])),ENT_QUOTES)?>">Full Owner Excel/CSV</a><a class="btn-secondary" href="?copy=staff">Staff Verification Copy</a><button class="btn-secondary" type="button" onclick="window.print()">Print Full Owner PDF</button><?php endif;?></div></header>
<?php if($message):?><div class="ops-alert success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="ops-alert error"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($reportDataError):?><div class="ops-alert error"><?=htmlspecialchars($reportDataError)?></div><?php endif;?>
<?php if($isStaffCopy):?>
<section class="employee-kpi-section"><header class="employee-kpi-section__header"><div><h2>Orders requiring confirmation</h2><p>Enter a confirmed packer or mark Unable to confirm. Returning this copy does not change attribution until the owner approves it.</p></div></header><div class="employee-kpi-evidence"><table class="data-table"><thead><tr><th>Order</th><th>Order date</th><th>Customer</th><th>Status</th><th>Completed</th><th>Available evidence</th><th>Possible packer</th><th>Confirmed packer</th><th>Confirmation source</th><th>Supporting reason</th><th>Unable to confirm</th></tr></thead><tbody><?php foreach($rows as$row):if($row['classification']==='staff_confirmation_required'):$e=json_decode((string)$row['source_evidence_json'],true);?><tr><td><?=htmlspecialchars((string)$row['order_number'])?></td><td><?=$row['order_date']?></td><td><?=htmlspecialchars((string)$row['customer_name'])?></td><td><?=htmlspecialchars((string)$row['status'])?></td><td><?=$row['completed_at']?:'—'?></td><td><?=htmlspecialchars(implode(', ',(array)($e['sources']??[])))?></td><td><?=htmlspecialchars((string)($row['possible_packer']?($row['possible_packer'].' (unconfirmed)'):'—'))?></td><td>________________</td><td>________________</td><td>________________</td><td>☐</td></tr><?php endif;endforeach;?></tbody></table></div></section>
<?php else:?>
<section class="kpi-health-grid attribution-summary"><?php foreach(['total'=>'Total unassigned orders reviewed','system_confirmed'=>'System confirmed','staff_confirmation_required'=>'Staff confirmation required','unable_to_confirm'=>'Unable to confirm','restored'=>'Assignments restored','excluded'=>'Orders excluded from performance scoring']as$key=>$label):?><article class="kpi-health-card"><span><?=$label?></span><strong><?=$summary[$key]?></strong></article><?php endforeach;?></section>
<form class="kpi-period-panel" method="get"><label><span>From</span><input type="date" name="date_from" value="<?=htmlspecialchars($from)?>"></label><label><span>To</span><input type="date" name="date_to" value="<?=htmlspecialchars($to)?>"></label><label><span>Status</span><select name="status"><option value="">All statuses</option><?php foreach(['in_progress','completed','packed','verified']as$v):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label><label><span>Classification</span><select name="classification"><option value="">All classifications</option><?php foreach(['system_confirmed','staff_confirmation_required','unable_to_confirm','not_applicable']as$v):?><option value="<?=$v?>" <?=$classification===$v?'selected':''?>><?=ucwords(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label><button class="btn-primary" type="submit">Apply filters</button></form>
<section class="employee-kpi-section"><header class="employee-kpi-section__header"><div><h2>Section A: System-confirmed assignments</h2><p>No employee action is required. Evidence sources checked: order stage events, global Activity Log, performance status events and order-item packing actors.</p></div></header><div class="employee-kpi-evidence"><table class="data-table"><thead><tr><th>Order</th><th>Order date</th><th>Completed</th><th>Packer</th><th>Evidence</th><th>Relevant timestamp</th><th>Method</th><th>Restored</th></tr></thead><tbody><?php foreach($rows as$row):if($row['classification']==='system_confirmed'&&!empty($row['restored_at'])&&$row['assignment_method']==='Historical system recovery'):$e=json_decode((string)$row['source_evidence_json'],true);?><tr><td><?=htmlspecialchars((string)$row['order_number'])?></td><td><?=$row['order_date']?></td><td><?=$row['completed_at']?></td><td><?=htmlspecialchars((string)$row['confirmed_packer'])?></td><td><?=htmlspecialchars(implode(', ',(array)($e['sources']??[])))?></td><td><?=htmlspecialchars((string)($e['first_packing_event']['occurred_at']??$e['completion_event']['occurred_at']??'—'))?></td><td><?=htmlspecialchars((string)$row['assignment_method'])?></td><td><?=$row['restored_at']?></td></tr><?php endif;endforeach;?></tbody></table></div></section>
<section class="employee-kpi-section"><header class="employee-kpi-section__header"><div><h2>Section B: Staff confirmation required</h2><p>Review and submit each order separately. Possible packers are never preselected.</p></div></header><div class="attribution-review-list"><?php foreach($rows as$row):if($row['classification']==='staff_confirmation_required'):$e=json_decode((string)$row['source_evidence_json'],true);?><article class="attribution-review-card"><h3><?=htmlspecialchars((string)$row['order_number'])?> · <?=htmlspecialchars((string)$row['customer_name'])?></h3><p><?=$row['order_date']?> · <?=htmlspecialchars((string)$row['status'])?> · Completed <?=$row['completed_at']?:'—'?></p><p>First packing actor: <?=htmlspecialchars((string)($e['first_packing_event']['actor_name']??$e['first_packing_event']['actor_id']??'—'))?> at <?=htmlspecialchars((string)($e['first_packing_event']['occurred_at']??'—'))?>. Completion actor: <?=htmlspecialchars((string)($e['completion_event']['actor_name']??$e['completion_event']['actor_id']??'—'))?> at <?=htmlspecialchars((string)($e['completion_event']['occurred_at']??'—'))?>.</p><p>Possible packer: <?=htmlspecialchars((string)($row['possible_packer']?:'—'))?>. Evidence: <?=htmlspecialchars(implode(', ',(array)($e['sources']??[])))?></p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="order_id" value="<?=(int)$row['order_id']?>"><label>Confirmed packer<select name="confirmed_packer_id"><option value="">Choose employee</option><?php foreach($employees as$person):?><option value="<?=(int)$person['id']?>"><?=htmlspecialchars((string)$person['full_name'])?></option><?php endforeach;?></select></label><label>Confirmation obtained from<select name="confirmation_obtained_from"><option value="">Choose employee</option><?php foreach($employees as$person):?><option value="<?=(int)$person['id']?>"><?=htmlspecialchars((string)$person['full_name'])?></option><?php endforeach;?></select></label><label>Evidence or reason<textarea name="supporting_note" required></textarea></label><label>Outcome<select name="outcome" required><option value="confirmed">Confirmed</option><option value="unable_to_confirm">Unable to confirm</option></select></label><button class="btn-primary" type="submit">Save this order review</button></form></article><?php endif;endforeach;?></div></section>
<?php endif;?></main>
<?php include BASE_PATH.'/shared/footer.php';?>
