<?php

declare(strict_types=1);

/** Read-only bookkeeping performance evidence. No operational row is changed here. */
function kpi_bookkeeping_reconciliation(int $employeeId, string $fromSql, string $toSql, array $settings): array
{
    $empty=['metrics'=>[],'orders'=>[],'daily'=>[],'deposits'=>[],'delivery_cash'=>[],'score'=>null,'score_evidence'=>'No eligible evidence.','deposit_schedule_configured'=>false,'excluded_from_scoring'=>0];
    if($employeeId<=0||!ops_table_exists('ops_orders')||!ops_table_exists('order_payment_allocations')||!ops_table_exists('ops_cash_book_entries'))return $empty;

    $adoption=(string)($settings['bookkeeping_adoption_date']??'2026-07-20');
    if($adoption<'2026-07-20')$adoption='2026-07-20';
    $fromDate=substr($fromSql,0,10);if($fromDate<$adoption)$fromDate=$adoption;
    $fromSql=$fromDate.' 00:00:00';
    $deadline=preg_match('/^\d{2}:\d{2}$/',(string)($settings['bookkeeping_cash_deadline']??''))?(string)$settings['bookkeeping_cash_deadline']:'17:00';
    $depositSchedule=trim((string)($settings['bookkeeping_deposit_schedule']??''));
    $depositConfigured=$depositSchedule!==''&&$depositSchedule!=='not_configured';
    $displayedAt=function_exists('ops_order_display_datetime_expr')?ops_order_display_datetime_expr('o'):'o.created_at';
    $orders=ops_rows("SELECT o.id,o.order_number,o.customer_name,o.customer_contact,o.payment_method,o.payment_status,o.status,o.total_amount,o.fulfilment_mode,o.order_type,o.completed_at,{$displayedAt} loaded_at,p.amount_cents,p.transaction_reference,p.source payment_source,p.updated_at allocation_updated_at FROM ops_orders o JOIN order_payment_allocations p ON p.order_id=o.id AND LOWER(TRIM(p.payment_method))='cash' AND p.amount_cents>0 WHERE LOWER(TRIM(o.status)) IN ('complete','completed') AND o.payment_status IN ('paid','partial') AND {$displayedAt} BETWEEN ? AND ? ORDER BY {$displayedAt},o.id",[$fromSql,$toSql]);

    $eligible=[];$delivery=[];
    foreach($orders as$order){$paymentText=strtolower(trim(implode(' ',[(string)$order['payment_method'],(string)$order['transaction_reference'],(string)$order['payment_source']])));$isDeliveryCash=preg_match('/\b(cod|cash[ _-]*(on[ _-]*)?delivery|driver[ _-]*(cash|collection))\b/',$paymentText)===1;$order['payment_type_detail']=$paymentText;$order['delivery_cash_excluded']=$isDeliveryCash;if($isDeliveryCash)$delivery[]=$order;else$eligible[]=$order;}

    $entries=ops_rows("SELECT b.*,COALESCE(e.full_name,b.created_by_name,'Unknown employee') created_by_name_resolved FROM ops_cash_book_entries b LEFT JOIN ops_employees e ON e.id=COALESCE(b.created_by_user_id,b.recorded_by) WHERE b.transaction_date BETWEEN DATE_SUB(?,INTERVAL 2 DAY) AND DATE_ADD(?,INTERVAL 2 DAY) AND b.deleted_at IS NULL AND COALESCE(b.status,'active')='active' ORDER BY b.created_at,b.id",[$fromSql,$toSql]);
    $entryNumbers=[];$entriesById=[];$entriesNoNumber=[];
    foreach($entries as$entry){$text=implode(' | ',array_filter([(string)($entry['related_order_number']??''),(string)($entry['description']??''),(string)($entry['notes']??''),(string)($entry['source']??'')]));preg_match_all('/\d{3,}/',$text,$m);$nums=[];foreach($m[0]??[]as$n){$n=(string)(int)$n;if($n!=='0')$nums[$n]=true;}$entry['_reference_text']=$text;$entry['_numbers']=array_keys($nums);if((int)($entry['related_order_id']??0)>0)$entriesById[(int)$entry['related_order_id']][]=$entry;if(count($entry['_numbers'])===1)$entryNumbers[$entry['_numbers'][0]][]=$entry;elseif(!$entry['_numbers']){$key=substr((string)$entry['transaction_date'],0,10).'|'.number_format((float)$entry['cash_in'],2,'.','');$entriesNoNumber[$key][]=$entry;}}
    $orderNumbers=[];$fuzzyOrderCounts=[];
    foreach($eligible as$order){preg_match_all('/\d{3,}/',(string)$order['order_number'],$m);$nums=array_values(array_unique(array_map(static function($v){return(string)(int)$v;},$m[0]??[])));$number=count($nums)===1?$nums[0]:null;if($number!==null)$orderNumbers[$number][]=(int)$order['id'];$key=substr((string)$order['loaded_at'],0,10).'|'.number_format(((int)$order['amount_cents'])/100,2,'.','');$fuzzyOrderCounts[$key]=($fuzzyOrderCounts[$key]??0)+1;}

    $rows=[];
    foreach($eligible as$order){$id=(int)$order['id'];$expected=(int)$order['amount_cents'];preg_match_all('/\d{3,}/',(string)$order['order_number'],$m);$nums=array_values(array_unique(array_map(static function($v){return(string)(int)$v;},$m[0]??[])));$number=count($nums)===1?$nums[0]:null;$candidates=$number!==null?($entryNumbers[$number]??[]):[];$method='none';$result='missing';$linked=[];
        if($number!==null&&(count($orderNumbers[$number]??[])>1||count($candidates)>1)){$linked=$candidates;$method='numeric_order_number';$result='ambiguous';}
        elseif($number!==null&&count($candidates)===1){$linked=$candidates;$method='numeric_order_number';$result='matched';}
        elseif(count($entriesById[$id]??[])===1){$linked=$entriesById[$id];$method='linked_order_id';$result='matched';}
        else{$key=substr((string)$order['loaded_at'],0,10).'|'.number_format($expected/100,2,'.','');$fuzzy=$entriesNoNumber[$key]??[];if(count($fuzzy)===1&&($fuzzyOrderCounts[$key]??0)===1){$linked=$fuzzy;$method='amount_same_date';$result='fuzzy';}elseif(count($fuzzy)>1||($fuzzyOrderCounts[$key]??0)>1){$linked=$fuzzy;$method='amount_same_date';$result='ambiguous';}}
        $first=$linked[0]??null;$recorded=count($linked)===1?(int)round(((float)$linked[0]['cash_in'])*100):0;if(in_array($result,['matched','fuzzy'],true)&&$recorded!==$expected)$result='amount_mismatch';
        $completed=(string)($order['completed_at']?:$order['loaded_at']);$delay=null;$sameDay=false;$beforeDeadline=false;$backdated=false;if($first&&strtotime($completed)!==false&&strtotime((string)$first['created_at'])!==false){$delay=max(0,(int)floor((strtotime((string)$first['created_at'])-strtotime($completed))/60));$sameDay=substr($completed,0,10)===substr((string)$first['created_at'],0,10);$beforeDeadline=$sameDay&&strtotime((string)$first['created_at'])<=strtotime(substr($completed,0,10).' '.$deadline.':00');$backdated=substr((string)$first['transaction_date'],0,10)<substr((string)$first['created_at'],0,10);}
        $rows[]=['order_id'=>$id,'order_number'=>$order['order_number'],'extracted_order_number'=>$number,'customer_name'=>$order['customer_name'],'loaded_at'=>$order['loaded_at'],'completed_at'=>$completed,'payment_date'=>$completed,'payment_type'=>'Cash','cash_expected'=>$expected/100,'paid'=>'Yes','bookkeeping_entry'=>$first?'BK-'.(int)$first['id']:null,'bookkeeping_entry_id'=>$first['id']??null,'raw_entry_reference'=>$first['_reference_text']??null,'cash_recorded'=>$recorded/100,'recorded_at'=>$first['created_at']??null,'effective_transaction_date'=>$first['transaction_date']??null,'recorded_by'=>$first['created_by_name_resolved']??null,'delay_minutes'=>$delay,'same_day'=>$sameDay,'before_deadline'=>$beforeDeadline,'backdated'=>$backdated,'result'=>$result,'match_method'=>$method,'evidence_source'=>$first?($method.' · ops_cash_book_entries #'.(int)$first['id']):'No matching ledger entry','requires_review'=>in_array($result,['missing','ambiguous','amount_mismatch'],true),'excluded_from_scoring'=>$result==='ambiguous'];}

    $deposits=array_values(array_filter($entries,static function($e){return preg_match('/deposit|banking/i',(string)($e['transaction_type'].' '.$e['source'].' '.$e['description']))===1;}));foreach($deposits as&$d){$d['deposit_amount']=max((float)$d['cash_out'],(float)$d['cash_in']);$d['recorded_at']=$d['created_at'];$d['recorded_by']=$d['created_by_name_resolved'];$d['timing_label']=$depositConfigured?'Recorded against configured deposit schedule':'Evidence only — deposit schedule/retained float not configured';}unset($d);
    $daily=[];foreach($rows as$row){$day=substr((string)$row['completed_at'],0,10);if(!isset($daily[$day]))$daily[$day]=['date'=>$day,'cash_orders'=>0,'expected_cash'=>0.0,'matched_orders'=>0,'recorded_cash'=>0.0,'missing'=>0,'variance'=>0.0,'same_day_entries'=>0,'deposit_expected'=>$depositConfigured?'Configured':'Not configured','deposit_recorded'=>0.0,'deposit_variance'=>null,'result'=>'Reconciled'];$daily[$day]['cash_orders']++;$daily[$day]['expected_cash']+=(float)$row['cash_expected'];$daily[$day]['recorded_cash']+=(float)$row['cash_recorded'];if(in_array($row['result'],['matched','fuzzy'],true))$daily[$day]['matched_orders']++;if($row['result']==='missing')$daily[$day]['missing']++;if($row['same_day'])$daily[$day]['same_day_entries']++;if($row['requires_review'])$daily[$day]['result']='Review';}
    foreach($deposits as$d){$day=substr((string)$d['transaction_date'],0,10);if(isset($daily[$day]))$daily[$day]['deposit_recorded']+=(float)$d['deposit_amount'];}foreach($daily as&$day){$day['variance']=round($day['expected_cash']-$day['recorded_cash'],2);if($depositConfigured)$day['deposit_variance']=round($day['expected_cash']-$day['deposit_recorded'],2);}unset($day);

    $scored=array_values(array_filter($rows,static function($r){return!$r['excluded_from_scoring'];}));$matchedRows=array_values(array_filter($scored,static function($r){return in_array($r['result'],['matched','fuzzy'],true);}));$missingRows=array_values(array_filter($scored,static function($r){return$r['result']==='missing';}));$timed=array_values(array_filter($matchedRows,static function($r){return$r['delay_minutes']!==null;}));$delays=array_column($timed,'delay_minutes');sort($delays,SORT_NUMERIC);$median=$delays?(count($delays)%2?$delays[intdiv(count($delays),2)]:round(($delays[count($delays)/2-1]+$delays[count($delays)/2])/2,1)):null;$sameDay=count(array_filter($timed,static function($r){return$r['before_deadline'];}));$matchRate=$scored?round(100*count($matchedRows)/count($scored),1):null;$sameDayRate=$timed?round(100*$sameDay/count($timed),1):null;$scoreParts=[];if($matchRate!==null)$scoreParts[]=['weight'=>70,'score'=>$matchRate,'label'=>'Cash-order match rate'];if($sameDayRate!==null)$scoreParts[]=['weight'=>30,'score'=>$sameDayRate,'label'=>'Same-day before deadline'];$weight=array_sum(array_column($scoreParts,'weight'));$score=$weight?round(array_sum(array_map(static function($p){return$p['weight']*$p['score'];},$scoreParts))/$weight,1):null;
    $expected=array_sum(array_column($rows,'cash_expected'));$recorded=array_sum(array_column($rows,'cash_recorded'));$moneyIn=array_sum(array_map(static function($e){return(float)$e['cash_in'];},$entries));$moneyOut=array_sum(array_map(static function($e){return(float)$e['cash_out'];},$entries));$oldest=$missingRows?$missingRows[0]:null;foreach($missingRows as$r)if((string)$r['completed_at']<(string)$oldest['completed_at'])$oldest=$r;
    $metrics=[['label'=>'Cash Orders Expected','value'=>count($rows)],['label'=>'Cash Orders Matched','value'=>count($matchedRows)],['label'=>'Match Rate','value'=>$matchRate,'format'=>'percent'],['label'=>'Cash Orders Missing','value'=>count($missingRows)],['label'=>'Missing Cash Value','value'=>array_sum(array_column($missingRows,'cash_expected')),'format'=>'currency'],['label'=>'Cash Amount Expected','value'=>$expected,'format'=>'currency'],['label'=>'Cash Amount Recorded','value'=>$recorded,'format'=>'currency'],['label'=>'Cash Variance','value'=>$expected-$recorded,'format'=>'currency'],['label'=>'Same-Day Logging Compliance','value'=>$sameDayRate,'format'=>'percent'],['label'=>'Average Logging Delay','value'=>$delays?round(array_sum($delays)/count($delays),1):null,'format'=>'minutes'],['label'=>'Median Logging Delay','value'=>$median,'format'=>'minutes'],['label'=>'Duplicate / Ambiguous / Mismatched','value'=>count(array_filter($rows,static function($r){return in_array($r['result'],['ambiguous','amount_mismatch'],true);}))],['label'=>'Deposits Expected','value'=>$depositConfigured?'Configured':'Not measured','status'=>$depositConfigured?'provisional':'unmeasured','explanation'=>$depositConfigured?'Uses the configured deposit rule.':'Deposit schedule and retained-float configuration are missing.'],['label'=>'Deposits Recorded','value'=>count($deposits)],['label'=>'Money In','value'=>$moneyIn,'format'=>'currency'],['label'=>'Money Out','value'=>$moneyOut,'format'=>'currency']];
    return['metrics'=>$metrics,'orders'=>$rows,'daily'=>array_values($daily),'deposits'=>$deposits,'delivery_cash'=>array_map(static function($o){return['order_id'=>(int)$o['id'],'order_number'=>$o['order_number'],'loaded_at'=>$o['loaded_at'],'amount'=>((int)$o['amount_cents'])/100,'payment_type_detail'=>$o['payment_type_detail'],'reason'=>'Cash Delivery / COD is collected later and excluded from bookkeeping cash-order scoring'];},$delivery),'score'=>$score,'score_components'=>$scoreParts,'score_evidence'=>count($matchedRows).' of '.count($scored).' eligible completed cash orders reconciled; '.$sameDay.' of '.count($timed).' timed matches logged by '.$deadline.'.','deposit_schedule_configured'=>$depositConfigured,'deposit_schedule'=>$depositSchedule?:null,'cash_deadline'=>$deadline,'adoption_date'=>$adoption,'period_from'=>$fromDate,'excluded_from_scoring'=>count(array_filter($rows,static function($r){return$r['excluded_from_scoring'];})),'matching_method'=>'Numeric order number first; linked order ID second; amount + same completion date only when unique','summary'=>['eligible_orders'=>count($rows),'matched'=>count($matchedRows),'fuzzy'=>count(array_filter($rows,static function($r){return$r['result']==='fuzzy';})),'missing'=>count($missingRows),'ambiguous'=>count(array_filter($rows,static function($r){return$r['result']==='ambiguous';})),'amount_mismatch'=>count(array_filter($rows,static function($r){return$r['result']==='amount_mismatch';})),'expected_cash'=>$expected,'recorded_cash'=>$recorded,'variance'=>$expected-$recorded,'oldest_missing'=>$oldest,'same_day_count'=>$sameDay,'timed_count'=>count($timed),'average_delay_minutes'=>$delays?round(array_sum($delays)/count($delays),1):null,'median_delay_minutes'=>$median,'fastest_delay_minutes'=>$delays?$delays[0]:null,'slowest_delay_minutes'=>$delays?$delays[count($delays)-1]:null,'delivery_cash_excluded'=>count($delivery),'money_in'=>$moneyIn,'money_out'=>$moneyOut]];
}
