<?php

declare(strict_types=1);

function kpi_packing_numeric_quantity(?string $value): ?float
{
    if($value===null||!preg_match('/-?\d+(?:\.\d+)?/',str_replace(',','',(string)$value),$match))return null;return(float)$match[0];
}

function kpi_packing_package_size(string $value):array
{
    $normalized=strtolower(trim($value));if(!preg_match('/(\d+(?:\.\d+)?)\s*(kg|kilograms?|g|grams?|l|litres?|liters?|ml|millilitres?|milliliters?)\b/i',$normalized,$match))return['type'=>'Unclassified','base_amount'=>null,'unit'=>null,'band'=>'Unclassified'];$amount=(float)$match[1];$unit=strtolower($match[2]);$liquid=in_array($unit,['l','litre','litres','liter','liters','ml','millilitre','millilitres','milliliter','milliliters'],true);if($liquid&&$unit!=='ml'&&strpos($unit,'milli')!==0)$amount*=1000;if(!$liquid&&($unit==='kg'||strpos($unit,'kilo')===0))$amount*=1000;$band=$amount<=100?'Small':($amount<1000?'Medium':'Large');return['type'=>$liquid?'Liquid':'Solid','base_amount'=>$amount,'unit'=>$liquid?'mL':'g','band'=>$band];
}

function kpi_packing_list_performance(array $employee,string $fromSql,string $toSql,array $holidays):array
{
    $zone=new DateTimeZone('Africa/Windhoek');$employeeId=(int)$employee['id'];$rows=ops_rows("SELECT p.id,'packing' timeline_module,p.item_name,p.received_weight variation,p.priority,p.quantity_planned,p.quantity_packed,p.date_loaded,p.created_at portal_created_at,p.date_started,p.date_completed,p.packing_status,p.assigned_employee_id,e.full_name assigned_to,p.notes,p.packing_website_confirmed,p.packing_website_completed_at,p.packing_website_completed_by,web.full_name website_completed_by_name,p.frontdesk_website_updated,p.frontdesk_website_updated_at,p.frontdesk_website_updated_by,p.workload_points,p.workload_points_override,p.workload_package_count,p.workload_weight_grams,p.workload_volume_ml,p.workload_unit_count,p.workload_parse_status FROM ops_packing_tasks p LEFT JOIN ops_employees e ON e.id=p.assigned_employee_id LEFT JOIN ops_employees web ON web.id=p.packing_website_completed_by WHERE p.assigned_employee_id=? AND p.date_loaded BETWEEN ? AND ? AND p.deleted_at IS NULL ORDER BY p.date_loaded DESC,p.id DESC LIMIT 500",[$employeeId,$fromSql,$toSql]);$eventsByItem=[];foreach(kpi_unified_events($fromSql,$toSql,null,'packing_list')as$event)$eventsByItem[(int)$event['record_id']][]=$event;
    $queue=[];$active=[];$total=[];$counts=['assigned'=>count($rows),'completed'=>0,'requested'=>0.0,'packed'=>0.0,'exact'=>0,'quantity_eligible'=>0,'solid_units'=>0.0,'liquid_units'=>0.0,'large'=>0,'needs_label'=>0,'needs_correction'=>0,'website_done'=>0,'website_required'=>0,'review'=>0];$evidence=[];
    foreach($rows as$row){$startEvent=null;$doneEvent=null;$labelEvent=null;$correctionEvent=null;$reopened=false;foreach($eventsByItem[(int)$row['id']]??[]as$event){$old=kpi_front_order_normalize((string)($event['previous_status']??''));$new=kpi_front_order_normalize((string)($event['new_status']??''));if(!$startEvent&&$new==='packing'&&in_array($old,['','notstarted'],true))$startEvent=$event;if(!$doneEvent&&$new==='done'&&in_array($old,['packing',''],true))$doneEvent=$event;if(!$labelEvent&&in_array($new,['packedlabelneeded','doneneedslabel'],true))$labelEvent=$event;if(!$correctionEvent&&in_array($new,['doneneedscorrection','needscorrection'],true))$correctionEvent=$event;if($doneEvent&&in_array($new,['packing','notstarted'],true))$reopened=true;}
        $loaded=!empty($row['date_loaded'])?new DateTimeImmutable((string)$row['date_loaded'],$zone):null;$started=$startEvent?new DateTimeImmutable((string)$startEvent['occurred_at'],$zone):(!empty($row['date_started'])?new DateTimeImmutable((string)$row['date_started'],$zone):null);$done=$doneEvent?new DateTimeImmutable((string)$doneEvent['occurred_at'],$zone):(!empty($row['date_completed'])?new DateTimeImmutable((string)$row['date_completed'],$zone):null);$invalid=!$loaded||($started&&$started<$loaded)||($done&&(!$started||$done<$started));$startActor=(int)($startEvent['actor_user_id']??0);$doneActor=(int)($doneEvent['actor_user_id']??0);$attribution=($startActor&&$startActor!==$employeeId)||($doneActor&&$doneActor!==$employeeId)?'Attribution conflict':'Confirmed packer attribution';
        $queueMinutes=!$invalid&&$loaded&&$started?kpi_business_minutes($loaded,$started,$holidays):null;$activeMinutes=!$invalid&&$started&&$done?kpi_business_minutes($started,$done,$holidays):null;$totalMinutes=!$invalid&&$loaded&&$done?kpi_business_minutes($loaded,$done,$holidays):null;if($queueMinutes!==null)$queue[]=$queueMinutes;if($activeMinutes!==null)$active[]=$activeMinutes;if($totalMinutes!==null)$total[]=$totalMinutes;
        $requested=kpi_packing_numeric_quantity((string)$row['quantity_planned']);$packed=kpi_packing_numeric_quantity((string)$row['quantity_packed']);$variance=$requested!==null&&$packed!==null?$packed-$requested:null;$quantityClass=$variance===null?'Missing quantity evidence':(abs($variance)<0.00001?'Exact match':($variance>0?'Overpacked — Requires owner approval':'Underpacked — Requires owner approval'));if($requested!==null)$counts['requested']+=$requested;if($packed!==null)$counts['packed']+=$packed;if($variance!==null){$counts['quantity_eligible']++;if(abs($variance)<0.00001)$counts['exact']++;}
        $size=kpi_packing_package_size((string)$row['variation']);if($packed!==null&&$size['type']==='Solid')$counts['solid_units']+=$packed;if($packed!==null&&$size['type']==='Liquid')$counts['liquid_units']+=$packed;if($size['band']==='Large')$counts['large']++;$status=kpi_front_order_normalize((string)$row['packing_status']);if($done)$counts['completed']++;if($labelEvent||in_array($status,['packedlabelneeded','doneneedslabel'],true))$counts['needs_label']++;if($correctionEvent||in_array($status,['doneneedscorrection','needscorrection'],true))$counts['needs_correction']++;$counts['website_required']++;if((int)$row['packing_website_confirmed']===1)$counts['website_done']++;
        $requiresReview=$invalid||$attribution!=='Confirmed packer attribution'||$variance===null||($variance!==null&&abs($variance)>=0.00001)||$size['type']==='Unclassified'||!$startEvent||!$doneEvent;if($requiresReview)$counts['review']++;
        $evidence[]=$row+['type'=>$size['type'],'size_band'=>$size['band'],'nominal_amount'=>$packed!==null&&$size['base_amount']!==null?$packed*$size['base_amount']:null,'nominal_unit'=>$size['unit'],'requested'=>$requested,'packed'=>$packed,'variance'=>$variance,'quantity_result'=>$quantityClass,'started_at'=>$startEvent['occurred_at']??$row['date_started'],'done_at'=>$doneEvent['occurred_at']??$row['date_completed'],'queue_minutes'=>$queueMinutes,'packing_minutes'=>$activeMinutes,'total_minutes'=>$totalMinutes,'started_by'=>$startEvent['actor_name']??'Start actor unavailable','done_by'=>$doneEvent['actor_name']??'Done actor unavailable','needs_label_at'=>$labelEvent['occurred_at']??null,'needs_correction_at'=>$correctionEvent['occurred_at']??null,'reopened'=>$reopened?'Yes':'No','final_state'=>$row['packing_status'],'website_update'=>(int)$row['packing_website_confirmed']===1?'Yes':'No','result'=>$invalid?'Invalid timestamp sequence — Excluded pending review':($requiresReview?'Requires owner review':'Confirmed'),'evidence_count'=>count($eventsByItem[(int)$row['id']]??[])];
    }
    $median=static function(array$values):?float{if(!$values)return null;sort($values,SORT_NUMERIC);$mid=intdiv(count($values),2);return count($values)%2?$values[$mid]:($values[$mid-1]+$values[$mid])/2;};$accuracy=$counts['quantity_eligible']?round(100*$counts['exact']/$counts['quantity_eligible'],1):null;
    return['rows'=>$evidence,'metrics'=>[['label'=>'Items Assigned','value'=>$counts['assigned']],['label'=>'Items Completed','value'=>$counts['completed']],['label'=>'Units Requested','value'=>round($counts['requested'],2)],['label'=>'Units Packed','value'=>round($counts['packed'],2)],['label'=>'Exact Quantity Accuracy','value'=>$accuracy,'format'=>'percent','numerator'=>$counts['exact'],'denominator'=>$counts['quantity_eligible']],['label'=>'Priority Adherence','value'=>null,'format'=>'percent','status'=>'unmeasured','explanation'=>'Queue-state and blocked-item evidence is incomplete; no automatic score effect.'],['label'=>'Average Queue Time','value'=>$queue?round(array_sum($queue)/count($queue),1):null,'format'=>'minutes'],['label'=>'Median Active Packing Time','value'=>$median($active),'format'=>'minutes'],['label'=>'Average Total Turnaround','value'=>$total?round(array_sum($total)/count($total),1):null,'format'=>'minutes'],['label'=>'Solid Units Packed','value'=>round($counts['solid_units'],2)],['label'=>'Liquid Units Packed','value'=>round($counts['liquid_units'],2)],['label'=>'Large-Volume Items','value'=>$counts['large']],['label'=>'Needs Label','value'=>$counts['needs_label']],['label'=>'Needs Correction','value'=>$counts['needs_correction']],['label'=>'Packer Website Updates Completed','value'=>$counts['website_done'],'numerator'=>$counts['website_done'],'denominator'=>$counts['website_required']],['label'=>'Items Requiring Review','value'=>$counts['review']]],'counts'=>$counts,'median_active'=>$median($active),'median_total'=>$median($total),'accuracy'=>$accuracy];
}
