<?php

declare(strict_types=1);

/**
 * Read-only, evidence-led Task Management KPI.
 * Employee clocks begin at the authoritative assignment/visibility timestamp.
 */
function kpi_task_json_list($value): array
{
    if (is_array($value)) return array_values(array_unique(array_map('strval', $value)));
    if (!is_string($value) || trim($value) === '') return [];
    $decoded=json_decode($value,true);
    return is_array($decoded)?array_values(array_unique(array_map('strval',$decoded))):[];
}

function kpi_task_median(array $values): ?float
{
    $values=array_values(array_filter($values,static fn($value):bool=>$value!==null));
    if(!$values)return null;sort($values,SORT_NUMERIC);$middle=intdiv(count($values),2);
    return round((float)(count($values)%2?$values[$middle]:($values[$middle-1]+$values[$middle])/2),1);
}

function kpi_task_management_performance(array $employee,string $fromSql,string $toSql,array $holidays=[]):array
{
    $zone=new DateTimeZone('Africa/Windhoek');$employeeId=(int)$employee['id'];
    $tasks=ops_rows("SELECT t.id,'task' timeline_module,t.task_name,t.instructions,t.checklist_type,t.priority,t.assigned_employee_id,t.date_assigned,t.employee_visible,t.created_at,t.deadline,t.status,t.started_at,t.completed_at,t.date_completed,t.completed_by,t.checklist_items,t.checked_items,t.completion_note,t.completion_note_required,t.completion_evidence_required,t.performance_scored,t.recurrence_key,t.recurring_template_id,t.source_template_id,t.archived_at,t.deleted_at,assignee.full_name assigned_to,creator.full_name created_by_name,completer.full_name completed_by_name FROM ops_checklist_tasks t LEFT JOIN ops_employees assignee ON assignee.id=t.assigned_employee_id LEFT JOIN ops_employees creator ON creator.id=t.created_by LEFT JOIN ops_employees completer ON completer.id=t.completed_by WHERE t.assigned_employee_id=? AND t.date_assigned BETWEEN ? AND ? AND t.employee_visible=1 AND t.performance_scored=1 AND t.deleted_at IS NULL AND t.archived_at IS NULL AND LOWER(t.status) NOT IN ('cancelled','deleted','trashed') ORDER BY t.date_assigned DESC,t.id DESC LIMIT 500",[$employeeId,$fromSql,$toSql]);
    $eventsByTask=[];foreach(kpi_unified_events($fromSql,$toSql,null,'tasks')as$event)$eventsByTask[(int)$event['record_id']][]=$event;
    $attachmentsByTask=[];if($tasks&&ops_table_exists('ops_checklist_attachments')){$ids=array_column($tasks,'id');$marks=implode(',',array_fill(0,count($ids),'?'));foreach(ops_rows("SELECT id,task_id,uploaded_by,uploaded_by_name,created_at,removed_at,removed_by FROM ops_checklist_attachments WHERE task_id IN ({$marks}) ORDER BY created_at,id",$ids)as$attachment)$attachmentsByTask[(int)$attachment['task_id']][]=$attachment;}
    $now=new DateTimeImmutable('now',$zone);$durations=['ack'=>[],'active'=>[],'turnaround'=>[]];
    $counts=['assigned'=>count($tasks),'completion_eligible'=>0,'completed'=>0,'completed_eligible'=>0,'early'=>0,'on_time'=>0,'late'=>0,'deadline_eligible'=>0,'pending'=>0,'overdue'=>0,'direct_complete'=>0,'reopened'=>0,'attribution_conflict'=>0,'review'=>0,'checklist_eligible'=>0,'checklist_compliant'=>0,'note_eligible'=>0,'note_compliant'=>0,'proof_eligible'=>0,'proof_compliant'=>0,'normal_assigned'=>0,'important_assigned'=>0,'urgent_assigned'=>0,'normal_completed'=>0,'important_completed'=>0,'urgent_completed'=>0];$rows=[];
    foreach($tasks as$task){
        $events=$eventsByTask[(int)$task['id']]??[];$assignmentEvent=null;$startEvent=null;$completeEvent=null;$directComplete=false;$reopened=false;$completionSnapshot=[];
        foreach($events as$event){$action=strtolower((string)$event['action']);$old=strtolower((string)($event['previous_status']??''));$new=strtolower((string)($event['new_status']??''));$metadata=(array)($event['metadata']??[]);
            if(!$assignmentEvent&&in_array($action,['task_created','task_assigned','task_reassigned','task_admin_updated'],true)&&(int)($metadata['assigned_employee_id']??0)===$employeeId)$assignmentEvent=$event;
            if(!$startEvent&&in_array($old,['new','not_started','pending',''],true)&&in_array($new,['in_progress','progress','started'],true))$startEvent=$event;
            if(!$completeEvent&&in_array($new,['complete','completed','approved'],true)){$completeEvent=$event;$directComplete=!in_array($old,['in_progress','progress','started'],true);$completionSnapshot=$metadata;}
            if($completeEvent&&in_array($old,['complete','completed','approved'],true)&&!in_array($new,['complete','completed','approved'],true))$reopened=true;
        }
        $assigned=!empty($task['date_assigned'])?new DateTimeImmutable((string)$task['date_assigned'],$zone):null;$created=!empty($task['created_at'])?new DateTimeImmutable((string)$task['created_at'],$zone):null;
        $started=$startEvent?new DateTimeImmutable((string)$startEvent['occurred_at'],$zone):null;$completed=$completeEvent?new DateTimeImmutable((string)$completeEvent['occurred_at'],$zone):null;$deadline=!empty($task['deadline'])?new DateTimeImmutable((string)$task['deadline'],$zone):null;
        $currentComplete=in_array(strtolower((string)$task['status']),['complete','completed','approved'],true);$invalid=!$assigned||($created&&$assigned<$created)||($started&&$started<$assigned)||($completed&&($completed<$assigned||($started&&$completed<$started)));
        $completionActorId=(int)($completeEvent['actor_user_id']??0);$personalCompletion=$completed&&$completionActorId===$employeeId;
        $attribution=($startEvent&&!empty($startEvent['actor_user_id'])&&(int)$startEvent['actor_user_id']!==$employeeId)||($completed&&!$personalCompletion);
        $ackMinutes=!$invalid&&$assigned&&$started?kpi_business_minutes($assigned,$started,$holidays):null;$activeMinutes=!$invalid&&$started&&$completed?kpi_business_minutes($started,$completed,$holidays):null;$turnaroundMinutes=!$invalid&&$assigned&&$completed?kpi_business_minutes($assigned,$completed,$holidays):null;
        if(!$attribution&&$ackMinutes!==null)$durations['ack'][]=$ackMinutes;if(!$attribution&&$activeMinutes!==null)$durations['active'][]=$activeMinutes;if(!$attribution&&$turnaroundMinutes!==null)$durations['turnaround'][]=$turnaroundMinutes;
        $priority=strtolower((string)$task['priority']);if(!in_array($priority,['normal','important','urgent'],true))$priority='normal';$counts[$priority.'_assigned']++;
        $deadlineResult='No deadline';if($deadline&&$personalCompletion){$counts['deadline_eligible']++;if($completed->format('Y-m-d')<$deadline->format('Y-m-d')){$deadlineResult='Completed early';$counts['early']++;}elseif($completed<=$deadline){$deadlineResult='Completed on time';$counts['on_time']++;}else{$deadlineResult='Completed late';$counts['late']++;}}
        elseif($deadline&&$completed){$deadlineResult='Completed by another actor — review';}
        elseif($deadline&&!$currentComplete){$counts['pending']++;if($now>$deadline){$deadlineResult='Overdue';$counts['overdue']++;}elseif($now->format('Y-m-d')===$deadline->format('Y-m-d'))$deadlineResult='Pending – Due Today';else$deadlineResult='Pending – Upcoming';}elseif(!$currentComplete)$counts['pending']++;
        if($personalCompletion){$counts['completed']++;$counts[$priority.'_completed']++;}if($directComplete){$counts['direct_complete']++;}if($reopened)$counts['reopened']++;if($attribution)$counts['attribution_conflict']++;
        $required=kpi_task_json_list($task['checklist_items']);$checkedAtCompletion=kpi_task_json_list($completionSnapshot['checked_items']??$task['checked_items']);$checklistResult='No checklist required';if($personalCompletion&&$required){$counts['checklist_eligible']++;$missing=array_values(array_diff($required,$checkedAtCompletion));if(!$missing){$counts['checklist_compliant']++;$checklistResult='Checklist complete before task completion';}else$checklistResult='Incomplete checklist';}
        $noteRequired=(int)$task['completion_note_required']===1;$noteValid=$personalCompletion&&trim((string)($completionSnapshot['completion_note']??$task['completion_note']))!=='';if($personalCompletion&&$noteRequired){$counts['note_eligible']++;if($noteValid)$counts['note_compliant']++;}
        $proofRequired=(int)$task['completion_evidence_required']===1;$validProof=false;$proofCount=0;foreach($attachmentsByTask[(int)$task['id']]??[]as$attachment){if(!empty($attachment['removed_at'])||(int)$attachment['uploaded_by']!==$employeeId)continue;$proofCount++;if($completed&&strtotime((string)$attachment['created_at'])<=strtotime((string)$completeEvent['occurred_at']))$validProof=true;}if($personalCompletion&&$proofRequired){$counts['proof_eligible']++;if($validProof)$counts['proof_compliant']++;}
        $missingExactAssignment=!$assignmentEvent;$requiresReview=$invalid||$attribution||$missingExactAssignment||($currentComplete&&!$completeEvent);if($requiresReview)$counts['review']++;else{$counts['completion_eligible']++;if($personalCompletion)$counts['completed_eligible']++;}
        $rows[]=$task+['category'=>trim((string)$task['checklist_type'])?:'Uncategorised','assigned_at'=>$task['date_assigned'],'assignment_evidence'=>$assignmentEvent?$assignmentEvent['source_log'].' #'.$assignmentEvent['source_event_id']:'Current-record timestamp only','started_at_evidence'=>$startEvent['occurred_at']??null,'completed_at_evidence'=>$completeEvent['occurred_at']??null,'started_by'=>$startEvent['actor_name']??'—','completed_by_evidence'=>$completeEvent['actor_name']??$task['completed_by_name']??'—','acknowledgement_minutes'=>$ackMinutes,'active_minutes'=>$activeMinutes,'turnaround_minutes'=>$turnaroundMinutes,'current_age_minutes'=>!$completed&&$assigned?kpi_business_minutes($started?:$assigned,$now,$holidays):null,'deadline_result'=>$deadlineResult,'status_process'=>$directComplete?'Completed without In Progress':($reopened?'Reopened after completion':'Expected sequence'),'checklist_result'=>$checklistResult,'completion_note_result'=>$noteRequired?($noteValid?'Valid required note':'Required note missing'):'Not required','proof_result'=>$proofRequired?($validProof?'Required proof supplied':'Required proof missing'):($proofCount?'Optional proof — evidence only':'Proof not required'),'attribution'=>$attribution?'Attribution conflict':($completed?'Personally completed':'Assigned employee'),'result'=>$requiresReview?'Requires owner review':'Reliable evidence','evidence_count'=>count($events)];
    }
    $percent=static fn(int$n,int$d):?float=>$d?round(100*$n/$d,1):null;$completionRate=$percent($counts['completed_eligible'],$counts['completion_eligible']);$onTime=$percent($counts['early']+$counts['on_time'],$counts['deadline_eligible']);
    $metrics=[['label'=>'Tasks Assigned','value'=>$counts['assigned']],['label'=>'Tasks Completed','value'=>$counts['completed']],['label'=>'Task Completion Rate','value'=>$completionRate,'format'=>'percent','numerator'=>$counts['completed_eligible'],'denominator'=>$counts['completion_eligible'],'status'=>$completionRate===null?'unmeasured':'ok'],['label'=>'Completed Early','value'=>$counts['early']],['label'=>'Completed On Time','value'=>$counts['on_time']],['label'=>'Completed Late','value'=>$counts['late']],['label'=>'On-time Completion Rate','value'=>$onTime,'format'=>'percent','numerator'=>$counts['early']+$counts['on_time'],'denominator'=>$counts['deadline_eligible'],'status'=>$onTime===null?'unmeasured':'ok'],['label'=>'Pending Tasks','value'=>$counts['pending']],['label'=>'Overdue Tasks','value'=>$counts['overdue']],['label'=>'Median Assignment-to-Start','value'=>kpi_task_median($durations['ack']),'format'=>'minutes'],['label'=>'Median Active Task Time','value'=>kpi_task_median($durations['active']),'format'=>'minutes'],['label'=>'Median Employee Turnaround','value'=>kpi_task_median($durations['turnaround']),'format'=>'minutes'],['label'=>'Checklist Compliance','value'=>$percent($counts['checklist_compliant'],$counts['checklist_eligible']),'format'=>'percent','numerator'=>$counts['checklist_compliant'],'denominator'=>$counts['checklist_eligible']],['label'=>'Completion-note Compliance','value'=>$percent($counts['note_compliant'],$counts['note_eligible']),'format'=>'percent','numerator'=>$counts['note_compliant'],'denominator'=>$counts['note_eligible']],['label'=>'Required-proof Compliance','value'=>$percent($counts['proof_compliant'],$counts['proof_eligible']),'format'=>'percent','numerator'=>$counts['proof_compliant'],'denominator'=>$counts['proof_eligible'],'status'=>$counts['proof_eligible']?'ok':'unmeasured'],['label'=>'Completed Without In Progress','value'=>$counts['direct_complete']],['label'=>'Reopened Tasks','value'=>$counts['reopened']],['label'=>'Attribution Conflicts','value'=>$counts['attribution_conflict']],['label'=>'Evidence Requiring Review','value'=>$counts['review']]];
    return['rows'=>$rows,'metrics'=>$metrics,'counts'=>$counts,'median_ack'=>kpi_task_median($durations['ack']),'median_active'=>kpi_task_median($durations['active']),'median_turnaround'=>kpi_task_median($durations['turnaround']),'completion_rate'=>$completionRate,'on_time_rate'=>$onTime];
}
