<?php
declare(strict_types=1);

function kpi_error_quality_performance(int $employeeId,string $fromSql,string $toSql,int $eligibleWork):array
{
    $rows=ops_rows("SELECT l.*,reporter.full_name reporter_name,responsible.full_name responsible_name,reviewer.full_name reviewer_name FROM ops_error_logs l LEFT JOIN ops_employees reporter ON reporter.id=l.logged_by LEFT JOIN ops_employees responsible ON responsible.id=l.responsible_employee_id LEFT JOIN ops_employees reviewer ON reviewer.id=l.accuracy_verified_by WHERE (l.logged_by=? OR l.responsible_employee_id=? OR l.employee_id=?) AND COALESCE(l.occurred_on,DATE(l.occurred_at),DATE(l.created_at),DATE(l.logged_at)) BETWEEN DATE(?) AND DATE(?) AND l.deleted_at IS NULL ORDER BY COALESCE(l.occurred_on,DATE(l.occurred_at),DATE(l.created_at),DATE(l.logged_at)),l.id",[$employeeId,$employeeId,$employeeId,$fromSql,$toSql]);
    $eventsByRecord=[];foreach(kpi_unified_events($fromSql,date('Y-m-d 23:59:59'),null,'error_log')as$event)$eventsByRecord[(int)$event['record_id']][]=$event;
    $confirmed=[];$reported=0;$complete=0;$resolved=0;$resolutionTimes=[];$unresolved=0;$financial=0.0;$evidence=[];
    foreach($rows as$row){$id=(int)$row['id'];$isReporter=(int)($row['logged_by']??0)===$employeeId;$attributionType=(string)($row['attribution_type']??'');$attributedId=(int)($row['attributed_employee_id']??$row['responsible_employee_id']??0);$isEmployeeAttribution=$attributionType==='employee'||($attributionType===''&&$attributedId>0);$isResponsible=$isEmployeeAttribution&&$attributedId===$employeeId;$isConfirmed=$isResponsible&&(int)$row['affects_kpi_accuracy']===1&&(int)($row['accuracy_verified_by']??0)>0;if($isReporter){$reported++;if(trim((string)$row['error_title'])!==''&&trim((string)$row['description'])!==''&&trim((string)$row['category'])!==''&&trim((string)$row['severity'])!=='')$complete++;}
        $resolvedAt=null;$resolver=null;$resolutionSource=null;foreach($eventsByRecord[$id]??[]as$event){if($resolvedAt===null&&strtolower((string)($event['new_status']??''))==='resolved'){$resolvedAt=(string)$event['occurred_at'];$resolver=$event['actor_name'];$resolutionSource=$event['source_log'].' #'.$event['source_event_id'];}}
        $minutes=$resolvedAt&&strtotime($resolvedAt)>=strtotime((string)$row['logged_at'])?(int)round((strtotime($resolvedAt)-strtotime((string)$row['logged_at']))/60):null;$age=$resolvedAt?null:max(0,(int)round((time()-strtotime((string)$row['logged_at']))/60));
        if($isConfirmed){$confirmed[]=['category'=>(string)$row['category'],'logged_at'=>(string)$row['logged_at'],'index'=>count($evidence)];if($resolvedAt){$resolved++;if($minutes!==null)$resolutionTimes[]=$minutes;}else$unresolved++;$financial+=(float)$row['financial_impact'];}
        $evidence[]=['id'=>$id,'error_reference'=>'ERR-'.$id,'logged_at'=>$row['logged_at'],'reporter_name'=>$row['reporter_name'],'responsible_name'=>$row['responsible_name']?:'Unattributed','category'=>ucwords(str_replace('_',' ',(string)$row['category'])),'severity'=>ucfirst((string)$row['severity']),'customer_impact'=>trim((string)$row['customer_impact'])!==''?'Yes':'Not recorded','status'=>ucfirst((string)$row['status']),'attribution_validation'=>$isConfirmed?'Owner confirmed':($isResponsible?'Awaiting owner confirmation':'Not attributed to employee'),'resolved_at'=>$resolvedAt,'resolver_name'=>$resolver?:'Unavailable','resolution_minutes'=>$minutes,'unresolved_age_minutes'=>$age,'recurrence_minutes'=>null,'recurrence_classification'=>'Not established','financial_impact_estimated'=>(float)$row['financial_impact'],'financial_impact_verified'=>null,'score_treatment'=>$isConfirmed?'Included as confirmed attribution':'Excluded from employee score','evidence_source'=>$resolutionSource?:'ops_error_logs authoritative record'];}
    $previous=[];foreach($confirmed as$item){$key=strtolower($item['category']);if(isset($previous[$key])){$delta=max(0,(int)round((strtotime($item['logged_at'])-$previous[$key])/60));$evidence[$item['index']]['recurrence_minutes']=$delta;$evidence[$item['index']]['recurrence_classification']='Possible recurrence — separate confirmed incident';}$previous[$key]=strtotime($item['logged_at']);}
    $average=$resolutionTimes?round(array_sum($resolutionTimes)/count($resolutionTimes),1):null;$confirmedCount=count($confirmed);$accuracy=$eligibleWork>0?max(0,100-(100*$confirmedCount/$eligibleWork)):null;usort($evidence,static fn(array$a,array$b):int=>strcmp((string)$b['logged_at'],(string)$a['logged_at']));
    return ['error_quality_performance'=>true,'provisional_label'=>'Confirmed attribution only — unavailable evidence is not inferred','metrics'=>[['label'=>'Errors reported','value'=>$reported],['label'=>'Confirmed attributable errors','value'=>$confirmedCount],['label'=>'Resolution rate','value'=>$confirmedCount?100*$resolved/$confirmedCount:null,'format'=>'percent','numerator'=>$resolved,'denominator'=>$confirmedCount],['label'=>'Average resolution time','value'=>$average,'format'=>'minutes'],['label'=>'Currently unresolved','value'=>$unresolved],['label'=>'Report completeness','value'=>$reported?100*$complete/$reported:null,'format'=>'percent','numerator'=>$complete,'denominator'=>$reported],['label'=>'Estimated financial impact','value'=>$financial,'format'=>'currency'],['label'=>'Accuracy','value'=>$accuracy,'format'=>'percent','status'=>$accuracy===null?'unmeasured':'partial_data']],'rows'=>$evidence,'definitions'=>['resolution_time'=>'First reliable resolved event minus logged_at.','unresolved_age'=>'Current time minus logged_at for unresolved incidents.','recurrence_interval'=>'Later confirmed incident logged_at minus the preceding confirmed incident logged_at for the same employee and category.','scoring'=>'Unattributed, unconfirmed and reporter-only records are excluded from individual scoring.']];
}
