<?php

declare(strict_types=1);
require_once __DIR__ . '/operations.php';
require_once __DIR__ . '/kpi-reporting.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

try {
    $employeeId=max(0,(int)($_GET['id']??0)); $section=(string)($_GET['section']??'overview');
    $employee=ops_rows('SELECT e.id,e.full_name,e.hire_date,e.working_days,e.shift_start,e.shift_end,e.late_grace_minutes,r.name role_name,r.role_key FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id WHERE e.id=? AND e.status=\'active\' AND r.role_key<>\'owner_admin\' LIMIT 1',[$employeeId])[0]??null;
    if(!$employee){http_response_code(404);echo json_encode(['ok'=>false,'message'=>'Employee not found.']);exit;}
    if((string)($_GET['action']??'')==='timeline'){$timelineModule=(string)($_GET['module']??'');$recordId=max(0,(int)($_GET['record_id']??0));if(!in_array($timelineModule,['order','packing','waybill','task','bookkeeping','website_update'],true)||!$recordId)throw new RuntimeException('Invalid timeline record.');$events=ops_rows("SELECT se.old_status,se.new_status,se.changed_at,e.full_name changed_by_name FROM kpi_status_events se LEFT JOIN ops_employees e ON e.id=se.changed_by WHERE se.module=? AND se.record_id=? ORDER BY se.changed_at",[$timelineModule,$recordId]);foreach($events as$eventIndex=>$event){$next=$events[$eventIndex+1]['changed_at']??null;$events[$eventIndex]['duration_minutes']=$next?max(0,(int)((strtotime((string)$next)-strtotime((string)$event['changed_at']))/60)):null;}echo json_encode(['ok'=>true,'module'=>$timelineModule,'record_id'=>$recordId,'events'=>$events,'empty_message'=>'No tracked events before 14 Jul 2026'],JSON_UNESCAPED_SLASHES);exit;}
    $zone=new DateTimeZone('Africa/Windhoek');$today=new DateTimeImmutable('today',$zone);$resolvedPeriod=kpi_resolve_reporting_period($_GET);$period=$resolvedPeriod['key'];$from=$resolvedPeriod['from'];$to=$resolvedPeriod['to'];
    if($to<$from)throw new RuntimeException('The end date must be on or after the start date.');$settings=[];foreach(ops_rows('SELECT setting_key,setting_value FROM kpi_settings')as$row)$settings[(string)$row['setting_key']]=(string)$row['setting_value'];$dataStart=new DateTimeImmutable($settings['data_start_date']??'2026-07-01',$zone);$adoption=new DateTimeImmutable($settings['adoption_date']??'2026-07-14',$zone);$effective=$from<$dataStart?$dataStart:$from;$rateFrom=$effective<$adoption?$adoption:$effective;$fromSql=$effective->format('Y-m-d 00:00:00');$rateSql=$rateFrom->format('Y-m-d 00:00:00');$toSql=$to->format('Y-m-d 23:59:59');
    $payload=['ok'=>true,'employee'=>$employee,'section'=>$section,'period'=>kpi_period_response($resolvedPeriod,$adoption,$effective),'last_refreshed_at'=>(new DateTimeImmutable('now',$zone))->format(DATE_ATOM)];
    $rawSessions=ops_rows('SELECT user_id,login_at,last_seen_at,logout_at FROM kpi_sessions WHERE user_id=? AND login_at BETWEEN ? AND ? ORDER BY login_at',[$employeeId,$rateSql,$toSql]);foreach($rawSessions as$rawSessionIndex=>$rawSession)$rawSessions[$rawSessionIndex]['employee']=(string)$employee['full_name'];$sessions=kpi_merge_presence_rows($rawSessions);$employeeScheduleRows=ops_rows('SELECT weekday,shift_start,shift_end FROM kpi_employee_schedules WHERE employee_id=? AND is_working=1 ORDER BY weekday',[$employeeId]);$employeeSchedule=[];foreach($employeeScheduleRows as$scheduleRow)$employeeSchedule[(int)$scheduleRow['weekday']]=$scheduleRow;$scheduleConfigured=count($employeeSchedule)>0;$grace=(int)($employee['late_grace_minutes']??($settings['late_grace_minutes']??10));foreach($sessions as$sessionIndex=>$session){$weekday=(int)(new DateTimeImmutable((string)$session['day'],new DateTimeZone('Africa/Windhoek')))->format('N');$daySchedule=$employeeSchedule[$weekday]??null;$firstTime=substr((string)$session['first_login'],11,5);$sessions[$sessionIndex]['scheduled']=$daySchedule!==null;$sessions[$sessionIndex]['shift_start']=$daySchedule?substr((string)$daySchedule['shift_start'],0,5):null;$sessions[$sessionIndex]['shift_end']=$daySchedule?substr((string)$daySchedule['shift_end'],0,5):null;$sessions[$sessionIndex]['late']=$daySchedule&&$firstTime!==''&&strtotime($firstTime)>strtotime((string)$sessions[$sessionIndex]['shift_start'].' +'.$grace.' minutes')?1:null;}
    $presence=ops_rows('SELECT COUNT(*) online FROM kpi_sessions WHERE user_id=? AND logout_at IS NULL AND last_seen_at>=DATE_SUB(NOW(),INTERVAL 10 MINUTE)',[$employeeId])[0]??[];$payload['online']=(int)($presence['online']??0)>0;$openPacking=ops_rows("SELECT id record_id,'packing' module,item_name item_label,packing_status current_status,date_loaded opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='packing' AND record_id=p.id),p.date_loaded),NOW()) age_hours FROM ops_packing_tasks p WHERE assigned_employee_id=? AND packing_status NOT IN ('done','website','packed_label_needed','done_needs_label','label_created') AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$openWaybills=ops_rows("SELECT id record_id,'waybill' module,COALESCE(customer_name,waybill_reference,CONCAT('Waybill #',id)) item_label,status current_status,uploaded_at opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='waybill' AND record_id=w.id),uploaded_at),NOW()) age_hours FROM hambelela_waybills w WHERE uploaded_by=? AND status IN ('pending','overdue') AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$openTasks=ops_rows("SELECT id record_id,'task' module,task_name item_label,status current_status,created_at opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='task' AND record_id=t.id),created_at),NOW()) age_hours FROM ops_checklist_tasks t WHERE assigned_employee_id=? AND status <> 'complete' AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$payload['open_work']=array_merge($openPacking,$openWaybills,$openTasks);
    if($section==='attendance'){$leave=[];$links=ops_table_exists('employee_user_links')?ops_rows('SELECT hr_employee_id FROM employee_user_links WHERE portal_user_id=? AND active=1 LIMIT 1',[$employeeId]):[];if($links&&function_exists('ops_hr_rows'))$leave=ops_hr_rows("SELECT leave_type,start_date,end_date,days,status FROM leave_requests WHERE employee_id=? AND status='approved' AND start_date<=? AND end_date>=? ORDER BY start_date",[(int)$links[0]['hr_employee_id'],$to->format('Y-m-d'),$rateFrom->format('Y-m-d')]);$payload['rows']=$sessions;$payload['leave']=$leave;$payload['summary']=['portal_presence_days'=>count($sessions),'portal_active_hours'=>array_sum(array_map(static fn($r)=>(float)$r['portal_active_hours'],$sessions)),'late_days'=>$scheduleConfigured?array_sum(array_map(static fn($r)=>(int)($r['late']??0),$sessions)):null,'schedule_configured'=>$scheduleConfigured,'leave_days'=>array_sum(array_map(static fn($r)=>(float)$r['days'],$leave))];}
    elseif($section==='packing'){$payload['rows']=ops_rows("SELECT id,'packing' timeline_module,item_name,weight_class,quantity_planned,date_loaded,date_started,date_completed,packing_status,priority,workload_points,workload_package_count,workload_weight_grams,workload_volume_ml,workload_unit_count,workload_parse_status,workload_breakdown_json,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_loaded,date_started) END queue_minutes,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END elapsed_minutes,frontdesk_website_updated,frontdesk_website_updated_at,frontdesk_website_updated_by FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY date_completed DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);}
    elseif($section==='orders'){$payload['rows']=ops_rows("SELECT o.id,'order' timeline_module,o.order_number,o.customer_name,o.status,o.total_amount,o.completed_at FROM ops_orders o WHERE o.assigned_packer_id=? AND o.status IN ('completed','packed','verified') AND o.completed_at BETWEEN ? AND ? ORDER BY o.completed_at DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);$orderPacks=ops_rows("SELECT COUNT(DISTINCT id) order_board_packs FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];$packingPacks=ops_rows("SELECT COUNT(DISTINCT id) packing_list_packs FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];$payload['summary']=['order_board_packs'=>(int)($orderPacks['order_board_packs']??0),'packing_list_packs'=>(int)($packingPacks['packing_list_packs']??0)];}
    elseif($section==='tasks'){$payload['rows']=ops_rows("SELECT id,'task' timeline_module,task_name,status,priority,created_at,deadline,completed_at FROM ops_checklist_tasks WHERE assigned_employee_id=? AND created_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);}
    elseif($section==='waybills'){$payload['rows']=ops_rows("SELECT id,'waybill' timeline_module,waybill_reference,customer_name,uploaded_at,due_by,sent_at,status,TIMESTAMPDIFF(MINUTE,uploaded_at,sent_at) duration_minutes FROM hambelela_waybills WHERE (uploaded_by=? OR sent_by=?) AND uploaded_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY uploaded_at DESC LIMIT 300",[$employeeId,$employeeId,$fromSql,$toSql]);}
    elseif($section==='quality'){$payload['rows']=ops_rows('SELECT id,error_title,category,severity,status,logged_at,resolution,responsible_employee_id,affects_kpi_accuracy,accuracy_verified_by,packing_task_id,order_reference FROM ops_error_logs WHERE (responsible_employee_id=? OR employee_id=?) AND logged_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY logged_at DESC LIMIT 300',[$employeeId,$employeeId,$fromSql,$toSql]);}
    elseif($section==='bookkeeping'){$payload['rows']=ops_rows('SELECT id,recon_date,system_balance,counted_total,variance,variance_note,created_at FROM hambelela_cashbook_recon WHERE logged_by=? AND recon_date BETWEEN ? AND ? ORDER BY recon_date DESC',[$employeeId,$effective->format('Y-m-d'),$to->format('Y-m-d')]);}
    elseif($section==='trends'){$payload['sessions']=$sessions;$payload['packing']=ops_rows("SELECT DATE(date_completed) day,COUNT(*) items,COALESCE(SUM(CASE WHEN workload_parse_status='parsed' OR workload_points_override IS NOT NULL THEN COALESCE(workload_points_override,workload_points) ELSE 0 END),0) points,AVG(CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END) avg_minutes FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL GROUP BY DATE(date_completed) ORDER BY day",[$employeeId,$rateSql,$toSql]);}
    elseif($section==='activity'){$module=(string)($_GET['module']??'');$params=[$employeeId,$fromSql,$toSql];$filter='';if(in_array($module,['order','packing','waybill','task','bookkeeping','website_update'],true)){$filter=' AND se.module=?';$params[]=$module;}$payload['rows']=ops_rows("SELECT se.id,se.module timeline_module,se.record_id,se.old_status,se.new_status,se.changed_at,e.full_name changed_by_name FROM kpi_status_events se LEFT JOIN ops_employees e ON e.id=se.changed_by WHERE se.changed_by=? AND se.changed_at BETWEEN ? AND ?{$filter} ORDER BY se.changed_at DESC LIMIT 500",$params);}
    else{
        $pack=ops_rows("SELECT COUNT(*) items,COALESCE(SUM(COALESCE(workload_points_override,workload_points)),0) points,AVG(CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END) avg_minutes,SUM(packing_status NOT IN ('done','website','packed_label_needed','done_needs_label','label_created')) open_items,SUM(workload_parse_status='pending_review') workload_review_rows FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
        $tasks=ops_rows("SELECT SUM(status = 'complete') done,SUM(status <> 'complete') pending FROM ops_checklist_tasks WHERE assigned_employee_id=? AND created_at BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
        $orderWork=ops_rows("SELECT COUNT(DISTINCT id) orders FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];
        $errors=ops_rows("SELECT SUM(responsible_employee_id=? AND affects_kpi_accuracy=1 AND accuracy_verified_by IS NOT NULL) explicitly_attributable_errors,SUM(employee_id=? AND responsible_employee_id IS NULL) unattributed_errors FROM ops_error_logs WHERE logged_at BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$employeeId,$fromSql,$toSql])[0]??[];
        $itemCount=(int)($pack['items']??0);$orderCount=(int)($orderWork['orders']??0);$eligibleWork=$itemCount+$orderCount;$attributableErrors=(int)($errors['explicitly_attributable_errors']??0);$unattributedErrors=(int)($errors['unattributed_errors']??0);$accuracyAvailable=$eligibleWork>0&&$unattributedErrors===0;
        $payload['summary']=['portal_active_hours'=>array_sum(array_map(static fn($r)=>(float)$r['portal_active_hours'],$sessions)),'portal_presence_days'=>count($sessions),'items'=>$itemCount,'points'=>(float)($pack['points']??0),'avg_minutes'=>$itemCount>=5&&$pack['avg_minutes']!==null?(float)$pack['avg_minutes']:null,'open_items'=>(int)($pack['open_items']??0),'orders'=>$orderCount,'tasks_done'=>(int)($tasks['done']??0),'tasks_pending'=>(int)($tasks['pending']??0),'errors'=>$attributableErrors,'unattributed_errors'=>$unattributedErrors,'accuracy_available'=>$accuracyAvailable,'accuracy_numerator'=>$attributableErrors,'accuracy_denominator'=>$eligibleWork,'accuracy'=>$accuracyAvailable?max(0,1-$attributableErrors/max(1,$eligibleWork)):null,'workload_review_rows'=>(int)($pack['workload_review_rows']??0)];
    }
    $orderPackSource=ops_rows("SELECT COUNT(DISTINCT id) order_board_packs FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];
    $packingPackSource=ops_rows("SELECT COUNT(DISTINCT id) packing_list_packs FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
    $payload['packing_sources']=[
        'order_board_packs'=>(int)($orderPackSource['order_board_packs']??0),
        'packing_list_packs'=>(int)($packingPackSource['packing_list_packs']??0),
        'order_source'=>'ops_orders.assigned_packer_id',
        'packing_source'=>'ops_packing_tasks.assigned_employee_id',
    ];
    if($section==='overview'&&isset($payload['summary'])){
        $payload['summary']['orders']=$payload['packing_sources']['order_board_packs'];
        $payload['summary']['items']=$payload['packing_sources']['packing_list_packs'];
    }
    $payload['composite']=['visible'=>false,'indicative'=>false,'score'=>null,'message'=>'Composite scores and rankings are disabled while KPI source integrity is under review.'];
    echo json_encode($payload,JSON_UNESCAPED_SLASHES);
}catch(Throwable$error){error_log(date(DATE_ATOM).' employee detail: '.$error->getMessage().PHP_EOL,3,BASE_PATH.'/logs/kpi_errors.log');http_response_code(500);echo json_encode(['ok'=>false,'message'=>'Employee performance is temporarily unavailable.']);}
