<?php
declare(strict_types=1);

function kpi_error_quality_performance(int $employeeId,string $fromSql,string $toSql,int $eligibleWork):array
{
    $rows=ops_rows("SELECT l.*,reporter.full_name reporter_name,responsible.full_name responsible_name,reviewer.full_name reviewer_name FROM ops_error_logs l LEFT JOIN ops_employees reporter ON reporter.id=l.logged_by LEFT JOIN ops_employees responsible ON responsible.id=l.responsible_employee_id LEFT JOIN ops_employees reviewer ON reviewer.id=l.accuracy_verified_by WHERE (l.logged_by=? OR l.responsible_employee_id=? OR l.employee_id=?) AND COALESCE(l.occurred_on,DATE(l.occurred_at),DATE(l.created_at),DATE(l.logged_at)) BETWEEN DATE(?) AND DATE(?) AND l.deleted_at IS NULL ORDER BY COALESCE(l.occurred_on,DATE(l.occurred_at),DATE(l.created_at),DATE(l.logged_at)),l.id",[$employeeId,$employeeId,$employeeId,$fromSql,$toSql]);
    $eventsByRecord=[];foreach(kpi_unified_events($fromSql,date('Y-m-d 23:59:59'),null,'error_log')as$event)$eventsByRecord[(int)$event['record_id']][]=$event;
    $confirmed=[];$reported=0;$complete=0;$resolved=0;$resolutionTimes=[];$unresolved=0;$financial=0.0;$reportedFinancial=0.0;$reportedGroups=[];$reportedDates=[];$evidence=[];
    foreach($rows as$row){$id=(int)$row['id'];$isReporter=(int)($row['logged_by']??0)===$employeeId;$attributionType=(string)($row['attribution_type']??'');$attributedId=(int)($row['attributed_employee_id']??$row['responsible_employee_id']??0);$isEmployeeAttribution=$attributionType==='employee'||($attributionType===''&&$attributedId>0);$isResponsible=$isEmployeeAttribution&&$attributedId===$employeeId;$isConfirmed=$isResponsible&&(int)$row['affects_kpi_accuracy']===1&&(int)($row['accuracy_verified_by']??0)>0;$statusKey=strtolower(trim((string)($row['status']??'')));$isResolvedState=in_array($statusKey,['resolved','closed','complete','completed'],true)||trim((string)($row['resolution']??''))!=='';if($isReporter){$reported++;$isComplete=trim((string)$row['error_title'])!==''&&trim((string)$row['description'])!==''&&trim((string)$row['category'])!==''&&trim((string)$row['severity'])!=='';if($isComplete)$complete++;$category=trim((string)($row['category']??''))?:'uncategorised';if(!isset($reportedGroups[$category]))$reportedGroups[$category]=['error_type'=>ucwords(str_replace('_',' ',$category)),'count'=>0,'complete'=>0,'open'=>0,'resolved'=>0,'financial_impact'=>0.0,'dates'=>[]];$group=&$reportedGroups[$category];$group['count']++;$group['complete']+=$isComplete?1:0;$group[$isResolvedState?'resolved':'open']++;$group['financial_impact']+=(float)($row['financial_impact']??0);$group['dates'][]=(string)$row['logged_at'];$reportedFinancial+=(float)($row['financial_impact']??0);$reportedDates[]=(string)$row['logged_at'];unset($group);}
        $resolvedAt=null;$resolver=null;$resolutionSource=null;foreach($eventsByRecord[$id]??[]as$event){if($resolvedAt===null&&strtolower((string)($event['new_status']??''))==='resolved'){$resolvedAt=(string)$event['occurred_at'];$resolver=$event['actor_name'];$resolutionSource=$event['source_log'].' #'.$event['source_event_id'];}}
        if($resolvedAt===null&&$isResolvedState)$resolvedAt=(string)($row['resolved_at']??$row['updated_at']??'')?:null;$minutes=$resolvedAt&&strtotime($resolvedAt)>=strtotime((string)$row['logged_at'])?(int)round((strtotime($resolvedAt)-strtotime((string)$row['logged_at']))/60):null;$age=$isResolvedState?null:max(0,(int)round((time()-strtotime((string)$row['logged_at']))/60));
        if($isConfirmed){$confirmed[]=['category'=>(string)$row['category'],'logged_at'=>(string)$row['logged_at'],'index'=>count($evidence)];if($isResolvedState){$resolved++;if($minutes!==null)$resolutionTimes[]=$minutes;}else$unresolved++;$financial+=(float)$row['financial_impact'];}
        $evidence[]=['id'=>$id,'error_reference'=>'ERR-'.$id,'logged_at'=>$row['logged_at'],'reporter_name'=>$row['reporter_name'],'responsible_name'=>$row['responsible_name']?:'Unattributed','category'=>ucwords(str_replace('_',' ',(string)$row['category'])),'severity'=>ucfirst((string)$row['severity']),'customer_impact'=>trim((string)$row['customer_impact'])!==''?'Yes':'Not recorded','status'=>ucfirst((string)$row['status']),'attribution_validation'=>$isConfirmed?'Owner confirmed':($isResponsible?'Awaiting owner confirmation':'Not attributed to employee'),'resolved_at'=>$resolvedAt,'resolver_name'=>$resolver?:'Unavailable','resolution_minutes'=>$minutes,'unresolved_age_minutes'=>$age,'recurrence_minutes'=>null,'recurrence_classification'=>'Not established','financial_impact_estimated'=>(float)$row['financial_impact'],'financial_impact_verified'=>null,'score_treatment'=>$isConfirmed?'Included as confirmed attribution':'Excluded from employee score','evidence_source'=>$resolutionSource?:'ops_error_logs authoritative record'];}
    $previous=[];foreach($confirmed as$item){$key=strtolower($item['category']);if(isset($previous[$key])){$delta=max(0,(int)round((strtotime($item['logged_at'])-$previous[$key])/60));$evidence[$item['index']]['recurrence_minutes']=$delta;$evidence[$item['index']]['recurrence_classification']='Possible recurrence — separate confirmed incident';}$previous[$key]=strtotime($item['logged_at']);}
    $gapDays=static function(array$dates):?float{$times=array_values(array_filter(array_map('strtotime',$dates)));sort($times);if(count($times)<2)return null;$gaps=[];for($i=1;$i<count($times);$i++)$gaps[]=($times[$i]-$times[$i-1])/86400;return round(array_sum($gaps)/count($gaps),1);};
    $reportingBreakdown=[];foreach($reportedGroups as$group){$dates=$group['dates'];sort($dates);$reportingBreakdown[]=['error_type'=>$group['error_type'],'count'=>$group['count'],'share_percent'=>$reported?round(100*$group['count']/$reported,1):0,'complete'=>$group['complete'],'open'=>$group['open'],'resolved'=>$group['resolved'],'financial_impact'=>round($group['financial_impact'],2),'latest_logged'=>$dates?end($dates):null,'average_days_between'=>$gapDays($dates)];}usort($reportingBreakdown,static fn(array$a,array$b):int=>$b['count']<=>$a['count']);
    $average=$resolutionTimes?round(array_sum($resolutionTimes)/count($resolutionTimes),1):null;$confirmedCount=count($confirmed);$accuracy=$eligibleWork>0?max(0,100-(100*$confirmedCount/$eligibleWork)):null;usort($evidence,static fn(array$a,array$b):int=>strcmp((string)$b['logged_at'],(string)$a['logged_at']));
    return ['error_quality_performance'=>true,'provisional_label'=>'Reporting activity and confirmed responsibility are measured separately','metrics'=>[['label'=>'Errors Logged by Cecilia','value'=>$reported,'explanation'=>'Errors this employee reported. Reporting an error does not make her responsible for it.'],['label'=>'Confirmed Errors Attributed to Cecilia','value'=>$confirmedCount,'explanation'=>'Only owner-confirmed errors assigned to this employee and approved to affect accuracy.'],['label'=>'Confirmed Error Resolution Rate','value'=>$confirmedCount?100*$resolved/$confirmedCount:null,'format'=>'percent','numerator'=>$resolved,'denominator'=>$confirmedCount,'explanation'=>'Resolved confirmed-attribution errors divided by all confirmed-attribution errors.'],['label'=>'Average Confirmed-Error Resolution Time','value'=>$average,'format'=>'minutes'],['label'=>'Confirmed Errors Still Open','value'=>$unresolved],['label'=>'Logged Report Completeness','value'=>$reported?100*$complete/$reported:null,'format'=>'percent','numerator'=>$complete,'denominator'=>$reported,'explanation'=>'Reports containing a title, description, category and severity. This is the positive reporting-quality component.'],['label'=>'Recorded Impact — Confirmed Errors','value'=>$financial,'format'=>'currency','explanation'=>'Sum of recorded financial impact on confirmed errors attributed to this employee; missing amounts are not estimated.'],['label'=>'Accuracy','value'=>$accuracy,'format'=>'percent','status'=>$accuracy===null?'unmeasured':'partial_data']],'reporting_summary'=>['errors_logged'=>$reported,'complete_reports'=>$complete,'reporting_score'=>$reported?round(100*$complete/$reported,1):null,'recorded_financial_impact'=>round($reportedFinancial,2),'average_days_between_reports'=>$gapDays($reportedDates)],'reporting_breakdown'=>$reportingBreakdown,'rows'=>$evidence,'definitions'=>['resolution_time'=>'First reliable resolved event minus logged_at. Resolved status counts in the rate even when its exact timestamp is unavailable.','unresolved_age'=>'Current time minus logged_at for unresolved incidents.','recurrence_interval'=>'Later confirmed incident logged_at minus the preceding confirmed incident logged_at for the same employee and category.','scoring'=>'Logging complete error reports is positive reporting-quality evidence. Only owner-confirmed responsibility can reduce accuracy; reporter-only records never do.','financial_impact'=>'Only recorded amounts are summed. No missing financial impact is inferred.']];
}
