<?php

declare(strict_types=1);

function kpi_packer_next_working_deadline(string $day, string $time, array $schedule, array $excludedDates, bool $includeSameDay): ?DateTimeImmutable
{
    $zone=new DateTimeZone('Africa/Windhoek');$cursor=new DateTimeImmutable($day,$zone);if(!$includeSameDay)$cursor=$cursor->modify('+1 day');
    for($guard=0;$guard<14;$guard++,$cursor=$cursor->modify('+1 day')){$date=$cursor->format('Y-m-d');$weekday=(int)$cursor->format('N');if(isset($excludedDates[$date])||empty($schedule[$weekday])||(int)($schedule[$weekday]['is_working']??1)!==1)continue;return new DateTimeImmutable($date.' '.$time,$zone);}return null;
}

function kpi_packer_orders_evidence(array $employee,string $fromSql,string $toSql,array $schedule,array $holidays,array $settings,array $leave=[]):array
{
    $zone=new DateTimeZone('Africa/Windhoek');$employeeId=(int)$employee['id'];$createdExpr=ops_order_display_datetime_expr('o');$deletedWhere=ops_column_exists('ops_orders','deleted_at')?' AND o.deleted_at IS NULL':'';
    $orders=ops_rows("SELECT o.id,'order' timeline_module,o.order_number,o.customer_name,o.customer_contact,o.status,o.payment_status,o.total_amount,COALESCE(NULLIF(o.fulfilment_mode,''),o.order_type) fulfilment_mode,{$createdExpr} loaded_at,o.created_at portal_imported_at,o.assigned_packer_id,p.full_name packed_by FROM ops_orders o LEFT JOIN ops_employees p ON p.id=o.assigned_packer_id WHERE o.assigned_packer_id=? AND (({$createdExpr} BETWEEN ? AND ?) OR o.status='new'){$deletedWhere} ORDER BY {$createdExpr} DESC,o.id DESC LIMIT 500",[$employeeId,$fromSql,$toSql]);
    $eventFrom=(new DateTimeImmutable($fromSql,$zone))->modify('-14 days')->format('Y-m-d H:i:s');$eventsByOrder=[];foreach(kpi_unified_events($eventFrom,$toSql,null,'orders')as$event){$eventsByOrder[(int)$event['record_id']][]=$event;}
    $excluded=array_fill_keys(array_map('strval',$holidays),true);foreach($leave as$leaveRow){if(empty($leaveRow['start_date'])||empty($leaveRow['end_date']))continue;$d=new DateTimeImmutable((string)$leaveRow['start_date'],$zone);$end=new DateTimeImmutable((string)$leaveRow['end_date'],$zone);while($d<=$end){$excluded[$d->format('Y-m-d')]=true;$d=$d->modify('+1 day');}}
    $leadMinutes=max(0,(int)($settings['minimum_courier_packing_lead_minutes']??30));$rows=[];$durations=[];$counts=['total'=>0,'courier'=>0,'delivery'=>0,'collection'=>0,'walkin'=>0,'courier_ready'=>0,'same_day'=>0,'review'=>0,'still_new'=>0];
    foreach($orders as$order){$loaded=!empty($order['loaded_at'])?new DateTimeImmutable((string)$order['loaded_at'],$zone):null;$firstInProgress=null;foreach($eventsByOrder[(int)$order['id']]??[]as$event){$action=kpi_front_order_normalize((string)($event['action']??''));$previous=kpi_front_order_normalize((string)($event['previous_status']??''));$next=kpi_front_order_normalize((string)($event['new_status']??''));if(($next==='inprogress'&&($previous===''||$previous==='new'))||in_array($action,['inprogress','orderinprogress'],true)){$firstInProgress=$event;break;}}
        $packedAt=$firstInProgress?new DateTimeImmutable((string)$firstInProgress['occurred_at'],$zone):null;$actorId=(int)($firstInProgress['actor_user_id']??0);$actorName=(string)($firstInProgress['actor_name']??'Packing actor unavailable');$mode=kpi_front_order_normalize((string)$order['fulfilment_mode']);$contactIndicator=strpos(kpi_front_order_normalize((string)$order['customer_contact']),'walkin')!==false;$nameIndicator=strpos(kpi_front_order_normalize((string)$order['customer_name']),'walkin')!==false;$isCollection=$mode==='collection';$walkState=$contactIndicator&&$isCollection?'Yes':(($contactIndicator&&!$isCollection)||($nameIndicator&&!$contactIndicator)?'Review':'No');
        $invalid=!$loaded||($packedAt&&$packedAt<$loaded);$attribution=$actorId>0&&$actorId!==$employeeId?'Requires owner review':'Confirmed';$review=$invalid||!$firstInProgress||$attribution!=='Confirmed'||$walkState==='Review';$businessMinutes=$loaded&&$packedAt&&!$invalid?kpi_business_minutes($loaded,$packedAt,$holidays):null;$elapsedMinutes=$loaded&&$packedAt&&!$invalid?(int)(($packedAt->getTimestamp()-$loaded->getTimestamp())/60):null;$deadline=null;$deadlineResult='Not applicable';$nearCutoff=false;
        if($mode==='courier'&&$loaded){$loadedDay=$loaded->format('Y-m-d');$beforeCutoff=$loaded->format('H:i:s')<'14:00:00';$deadline=kpi_packer_next_working_deadline($loadedDay,'14:00:00',$schedule,$excluded,$beforeCutoff);$available=$deadline?(int)(($deadline->getTimestamp()-$loaded->getTimestamp())/60):null;$nearCutoff=$beforeCutoff&&$available!==null&&$available<$leadMinutes;if(!$packedAt&&$deadline&&new DateTimeImmutable('now',$zone)>$deadline)$deadlineResult='Still not packed';elseif(!$packedAt)$deadlineResult='Waiting';elseif($deadline&&$packedAt<=$deadline)$deadlineResult=$deadline->format('Y-m-d')===$loadedDay?'Ready for same-day courier':'Ready by next working-day cutoff';else$deadlineResult=$nearCutoff?'Missed operational cutoff — Requires owner review':'Missed same-day courier cutoff';if($deadline&&$packedAt&&$packedAt<=$deadline)$counts['courier_ready']++;}
        if($invalid){$result='Invalid timestamp sequence — Excluded pending review';$counts['review']++;}elseif(!$firstInProgress){$result='Packing timestamp unavailable — Excluded from turnaround';$counts['still_new']++;$counts['review']++;}elseif($attribution!=='Confirmed'){$result='Attribution mismatch — Requires owner review';$counts['review']++;}elseif($walkState==='Review'){$result='Walk-in classification requires review';$counts['review']++;}elseif($nearCutoff&&$deadlineResult!=='Ready for same-day courier'){$result=$deadlineResult;$counts['review']++;}else{$result='Verified';if($walkState==='Yes')$counts['walkin']++;else{$counts['total']++;if($mode==='courier')$counts['courier']++;elseif($mode==='delivery')$counts['delivery']++;elseif($mode==='collection')$counts['collection']++;}if($loaded&&$packedAt&&$loaded->format('Y-m-d')===$packedAt->format('Y-m-d'))$counts['same_day']++;if($businessMinutes!==null)$durations[]=$businessMinutes;}
        $rows[]=$order+['walk_in'=>$walkState,'mode'=>ucfirst((string)$order['fulfilment_mode']),'in_progress_at'=>$firstInProgress['occurred_at']??null,'turnaround_minutes'=>$businessMinutes,'elapsed_minutes'=>$elapsedMinutes,'status_changed_by'=>$actorName,'status_changed_by_id'=>$actorId?:null,'courier_deadline'=>$deadline?$deadline->format('Y-m-d H:i:s'):null,'deadline_result'=>$deadlineResult,'items'=>null,'attribution'=>$attribution,'result'=>$result,'evidence_count'=>count($eventsByOrder[(int)$order['id']]??[])];
    }
    sort($durations,SORT_NUMERIC);$median=null;if($durations){$mid=intdiv(count($durations),2);$median=count($durations)%2?$durations[$mid]:($durations[$mid-1]+$durations[$mid])/2;}$average=$durations?round(array_sum($durations)/count($durations),1):null;
    return['rows'=>$rows,'metrics'=>[['label'=>'Distinct Orders Packed','value'=>$counts['total']],['label'=>'Average New-to-Packed Turnaround','value'=>$average,'format'=>'minutes'],['label'=>'Median New-to-Packed Turnaround','value'=>$median,'format'=>'minutes'],['label'=>'Courier Orders Packed','value'=>$counts['courier']],['label'=>'Courier Ready by 14:00','value'=>$counts['courier_ready']],['label'=>'Deliveries Packed','value'=>$counts['delivery']],['label'=>'Non-walk-in Collections Packed','value'=>$counts['collection']],['label'=>'Orders Completed Same Working Day','value'=>$counts['same_day']],['label'=>'Orders Requiring Review','value'=>$counts['review']]],'counts'=>$counts,'average_minutes'=>$average,'median_minutes'=>$median,'lead_minutes'=>$leadMinutes];
}
