<?php

declare(strict_types=1);

function kpi_packing_numeric_quantity(?string $value): ?float
{
    if($value===null||!preg_match('/-?\d+(?:\.\d+)?/',str_replace(',','',(string)$value),$match))return null;return(float)$match[0];
}

function kpi_packing_physical_quantities(?string $value):array
{
    $result=['mass_grams'=>0.0,'volume_ml'=>0.0,'pieces'=>0.0,'parsed'=>false,'packages'=>[]];$text=strtolower(str_replace(',',' ',trim((string)$value)));
    if($text==='')return$result;
    preg_match_all('/(\d+(?:\.\d+)?)\s*(kg|kilograms?|g|grams?|l|litres?|liters?|ml|millilitres?|milliliters?|pcs?|pieces?|units?)\b\s*(?:\(\s*(\d+(?:\.\d+)?)\s*\))?/i',$text,$matches,PREG_SET_ORDER);
    foreach($matches as$match){$amount=(float)$match[1];$unit=strtolower($match[2]);$count=isset($match[3])&&$match[3]!==''?(float)$match[3]:1.0;$total=$amount*$count;$result['parsed']=true;$baseUnit=in_array($unit,['kg','kilogram','kilograms','g','gram','grams'],true)?'g':(in_array($unit,['l','litre','litres','liter','liters','ml','millilitre','millilitres','milliliter','milliliters'],true)?'ml':'pieces');$baseSize=$amount*(in_array($unit,['kg','kilogram','kilograms','l','litre','litres','liter','liters'],true)?1000:1);$packageKey=$baseUnit.':'.(string)$baseSize;$result['packages'][$packageKey]=($result['packages'][$packageKey]??0)+$count;if(in_array($unit,['kg','kilogram','kilograms'],true))$result['mass_grams']+=$total*1000;elseif(in_array($unit,['g','gram','grams'],true))$result['mass_grams']+=$total;elseif(in_array($unit,['l','litre','litres','liter','liters'],true))$result['volume_ml']+=$total*1000;elseif(in_array($unit,['ml','millilitre','millilitres','milliliter','milliliters'],true))$result['volume_ml']+=$total;else$result['pieces']+=$total;}
    ksort($result['packages']);
    return$result;
}

function kpi_packing_package_size(string $value):array
{
    $normalized=strtolower(trim($value));if(!preg_match('/(\d+(?:\.\d+)?)\s*(kg|kilograms?|g|grams?|l|litres?|liters?|ml|millilitres?|milliliters?)\b/i',$normalized,$match))return['type'=>'Unclassified','base_amount'=>null,'unit'=>null,'band'=>'Unclassified'];$amount=(float)$match[1];$unit=strtolower($match[2]);$liquid=in_array($unit,['l','litre','litres','liter','liters','ml','millilitre','millilitres','milliliter','milliliters'],true);if($liquid&&$unit!=='ml'&&strpos($unit,'milli')!==0)$amount*=1000;if(!$liquid&&($unit==='kg'||strpos($unit,'kilo')===0))$amount*=1000;$band=$amount<=100?'Small':($amount<1000?'Medium':'Large');return['type'=>$liquid?'Liquid':'Solid','base_amount'=>$amount,'unit'=>$liquid?'mL':'g','band'=>$band];
}

function kpi_packing_list_performance(array $employee,string $fromSql,string $toSql,array $holidays):array
{
    $zone=new DateTimeZone('Africa/Windhoek');$employeeId=(int)$employee['id'];$rows=ops_rows("SELECT p.id,'packing' timeline_module,p.item_name,p.received_weight variation,p.priority,p.quantity_planned,p.quantity_packed,p.date_loaded,p.created_at portal_created_at,p.date_started,p.date_completed,p.packing_status,p.assigned_employee_id,e.full_name assigned_to,p.notes,p.packing_website_confirmed,p.packing_website_completed_at,p.packing_website_completed_by,web.full_name website_completed_by_name,p.frontdesk_website_updated,p.frontdesk_website_updated_at,p.frontdesk_website_updated_by,p.workload_points,p.workload_points_override,p.workload_package_count,p.workload_weight_grams,p.workload_volume_ml,p.workload_unit_count,p.workload_parse_status FROM ops_packing_tasks p LEFT JOIN ops_employees e ON e.id=p.assigned_employee_id LEFT JOIN ops_employees web ON web.id=p.packing_website_completed_by WHERE p.assigned_employee_id=? AND p.date_loaded BETWEEN ? AND ? AND p.deleted_at IS NULL ORDER BY p.date_loaded DESC,p.id DESC LIMIT 500",[$employeeId,$fromSql,$toSql]);$eventsByItem=[];foreach(kpi_unified_events($fromSql,$toSql,null,'packing_list')as$event)$eventsByItem[(int)$event['record_id']][]=$event;
    $queue=[];$active=[];$total=[];$counts=['assigned'=>count($rows),'completed'=>0,'requested'=>0.0,'packed'=>0.0,'exact'=>0,'quantity_eligible'=>0,'overpacked_review'=>0,'underpacked_review'=>0,'planned_mass_grams'=>0.0,'planned_volume_ml'=>0.0,'planned_piece_units'=>0.0,'packaged_mass_grams'=>0.0,'packaged_volume_ml'=>0.0,'packaged_piece_units'=>0.0,'mass_grams'=>0.0,'volume_ml'=>0.0,'piece_units'=>0.0,'solid_units'=>0.0,'liquid_units'=>0.0,'large'=>0,'needs_label'=>0,'needs_correction'=>0,'reopened'=>0,'website_done'=>0,'website_required'=>0,'review'=>0];$evidence=[];
    foreach($rows as$row){$startEvent=null;$doneEvent=null;$labelEvent=null;$correctionEvent=null;$reopened=false;foreach($eventsByItem[(int)$row['id']]??[]as$event){$old=kpi_front_order_normalize((string)($event['previous_status']??''));$new=kpi_front_order_normalize((string)($event['new_status']??''));if(!$startEvent&&$new==='packing'&&in_array($old,['','notstarted'],true))$startEvent=$event;if(!$doneEvent&&$new==='done'&&in_array($old,['packing',''],true))$doneEvent=$event;if(!$labelEvent&&in_array($new,['packedlabelneeded','doneneedslabel'],true))$labelEvent=$event;if(!$correctionEvent&&in_array($new,['doneneedscorrection','needscorrection'],true))$correctionEvent=$event;if($doneEvent&&in_array($new,['packing','notstarted'],true))$reopened=true;}
        $loaded=!empty($row['date_loaded'])?new DateTimeImmutable((string)$row['date_loaded'],$zone):null;$started=$startEvent?new DateTimeImmutable((string)$startEvent['occurred_at'],$zone):(!empty($row['date_started'])?new DateTimeImmutable((string)$row['date_started'],$zone):null);$done=$doneEvent?new DateTimeImmutable((string)$doneEvent['occurred_at'],$zone):(!empty($row['date_completed'])?new DateTimeImmutable((string)$row['date_completed'],$zone):null);$invalid=!$loaded||($started&&$started<$loaded)||($done&&(!$started||$done<$started));$startActor=(int)($startEvent['actor_user_id']??0);$doneActor=(int)($doneEvent['actor_user_id']??0);$attribution=($startActor&&$startActor!==$employeeId)||($doneActor&&$doneActor!==$employeeId)?'Attribution conflict':'Confirmed packer attribution';
        $timingEligible=!$invalid&&$attribution==='Confirmed packer attribution';$queueMinutes=$timingEligible&&$loaded&&$started?kpi_business_minutes($loaded,$started,$holidays):null;$activeMinutes=$timingEligible&&$started&&$done?kpi_business_minutes($started,$done,$holidays):null;$totalMinutes=$timingEligible&&$loaded&&$done?kpi_business_minutes($loaded,$done,$holidays):null;if($queueMinutes!==null)$queue[]=$queueMinutes;if($activeMinutes!==null)$active[]=$activeMinutes;if($totalMinutes!==null)$total[]=$totalMinutes;
        $requested=kpi_packing_physical_quantities((string)$row['quantity_planned']);$packed=kpi_packing_physical_quantities((string)$row['quantity_packed']);$variance=null;$quantityClass='Missing quantity evidence';if($requested['parsed']&&$packed['parsed']){$counts['quantity_eligible']++;$differences=['mass_grams'=>$packed['mass_grams']-$requested['mass_grams'],'volume_ml'=>$packed['volume_ml']-$requested['volume_ml'],'pieces'=>$packed['pieces']-$requested['pieces']];$exact=$requested['packages']==$packed['packages'];if($exact){$counts['exact']++;$quantityClass='Exact match';$variance='Exact';}else{$hasOver=(bool)array_filter($differences,static fn($difference):bool=>(float)$difference>0.00001);$hasUnder=(bool)array_filter($differences,static fn($difference):bool=>(float)$difference< -0.00001);if($hasOver&&!$hasUnder){$counts['overpacked_review']++;$quantityClass='Overpacked — Requires owner approval';}else{$counts['underpacked_review']++;$quantityClass=$hasUnder&&!$hasOver?'Underpacked — Requires owner approval':'Mixed quantity variance — Requires owner approval';}$variance='Review';}}$counts['planned_mass_grams']+=$requested['mass_grams'];$counts['planned_volume_ml']+=$requested['volume_ml'];$counts['planned_piece_units']+=$requested['pieces'];$counts['packaged_mass_grams']+=$packed['mass_grams'];$counts['packaged_volume_ml']+=$packed['volume_ml'];$counts['packaged_piece_units']+=$packed['pieces'];$status=kpi_front_order_normalize((string)$row['packing_status']);$isCompleted=$done&&!$invalid&&in_array($status,['done','website','packedlabelneeded','doneneedslabel','labelcreated'],true);$size=kpi_packing_package_size((string)$row['variation']);if($isCompleted&&$size['type']==='Solid')$counts['mass_grams']+=(float)$size['base_amount'];elseif($isCompleted&&$size['type']==='Liquid')$counts['volume_ml']+=(float)$size['base_amount'];elseif($isCompleted&&preg_match('/^\s*(\d+(?:\.\d+)?)\s*(?:pieces?|pcs?|units?)\s*$/i',(string)$row['variation'],$variationMatch))$counts['piece_units']+=(float)$variationMatch[1];if($size['band']==='Large')$counts['large']++;$status=kpi_front_order_normalize((string)$row['packing_status']);if($isCompleted)$counts['completed']++;if(in_array($status,['packedlabelneeded','doneneedslabel'],true))$counts['needs_label']++;if($correctionEvent||in_array($status,['doneneedscorrection','needscorrection'],true))$counts['needs_correction']++;$counts['website_required']++;if((int)$row['packing_website_confirmed']===1)$counts['website_done']++;
        if($reopened)$counts['reopened']++;$requiresReview=$invalid||$attribution!=='Confirmed packer attribution'||!$requested['parsed']||!$packed['parsed']||$quantityClass!=='Exact match'||($size['type']==='Unclassified'&&!preg_match('/^\s*\d+(?:\.\d+)?\s*(?:pieces?|pcs?|units?)\s*$/i',(string)$row['variation']))||!$startEvent||!$doneEvent;if($requiresReview)$counts['review']++;
        $evidence[]=$row+['type'=>$packed['mass_grams']>0?'Solid':($packed['volume_ml']>0?'Liquid':($packed['pieces']>0?'Pieces':'Unclassified')),'size_band'=>$size['band'],'nominal_amount'=>$packed['mass_grams']>0?$packed['mass_grams']:($packed['volume_ml']>0?$packed['volume_ml']:($packed['pieces']>0?$packed['pieces']:null)),'nominal_unit'=>$packed['mass_grams']>0?'g':($packed['volume_ml']>0?'mL':($packed['pieces']>0?'pieces':null)),'requested'=>$row['quantity_planned'],'packed'=>$row['quantity_packed'],'variance'=>$variance,'quantity_result'=>$quantityClass,'started_at'=>$startEvent['occurred_at']??$row['date_started'],'done_at'=>$doneEvent['occurred_at']??$row['date_completed'],'queue_minutes'=>$queueMinutes,'packing_minutes'=>$activeMinutes,'total_minutes'=>$totalMinutes,'started_by'=>$startEvent['actor_name']??'Start actor unavailable','done_by'=>$doneEvent['actor_name']??'Done actor unavailable','needs_label_at'=>$labelEvent['occurred_at']??null,'needs_correction_at'=>$correctionEvent['occurred_at']??null,'reopened'=>$reopened?'Yes':'No','final_state'=>$row['packing_status'],'website_update'=>(int)$row['packing_website_confirmed']===1?'Yes':'No','result'=>$invalid?'Invalid timestamp sequence — Excluded pending review':($requiresReview?'Requires owner review':'Confirmed'),'evidence_count'=>count($eventsByItem[(int)$row['id']]??[])];
    }
    $median=static function(array$values):?float{if(!$values)return null;sort($values,SORT_NUMERIC);$mid=intdiv(count($values),2);return count($values)%2?$values[$mid]:($values[$mid-1]+$values[$mid])/2;};$accuracy=$counts['quantity_eligible']?round(100*$counts['exact']/$counts['quantity_eligible'],1):null;
    return['rows'=>$evidence,'metrics'=>[['label'=>'Items Assigned','value'=>$counts['assigned']],['label'=>'Items Completed','value'=>$counts['completed']],['label'=>'Weight Packed','value'=>round($counts['mass_grams']/1000,2),'format'=>'kg','explanation'=>'Sum of the recorded Variation weight once per completed packing-list row; missing units require review.'],['label'=>'Liquid Volume Packed','value'=>round($counts['volume_ml']/1000,2),'format'=>'litres','explanation'=>'Sum of the recorded Variation liquid volume once per completed packing-list row; missing units require review.'],['label'=>'Pieces Packed','value'=>round($counts['piece_units'],2),'explanation'=>'Completed Variation entries explicitly labelled pieces, pcs or units. Bare numbers require review.'],['label'=>'Planned Package Weight','value'=>round($counts['planned_mass_grams']/1000,2),'format'=>'kg'],['label'=>'Recorded Package Weight','value'=>round($counts['packaged_mass_grams']/1000,2),'format'=>'kg'],['label'=>'Planned Package Volume','value'=>round($counts['planned_volume_ml']/1000,2),'format'=>'litres'],['label'=>'Recorded Package Volume','value'=>round($counts['packaged_volume_ml']/1000,2),'format'=>'litres'],['label'=>'Planned Package Pieces','value'=>round($counts['planned_piece_units'],2)],['label'=>'Recorded Package Pieces','value'=>round($counts['packaged_piece_units'],2)],['label'=>'Quantity Matches','value'=>$counts['exact'],'numerator'=>$counts['exact'],'denominator'=>$counts['quantity_eligible'],'explanation'=>'Packing-list rows where the full planned package breakdown exactly matches the recorded packed breakdown. Supplier shortages or overages remain review evidence and do not automatically reduce the employee score.'],['label'=>'Supplier Variances Awaiting Review','value'=>$counts['overpacked_review']+$counts['underpacked_review'],'explanation'=>$counts['overpacked_review'].' over and '.$counts['underpacked_review'].' under; these require owner confirmation before responsibility can be assigned.'],['label'=>'Average Queue Time','value'=>$queue?round(array_sum($queue)/count($queue),1):null,'format'=>'minutes'],['label'=>'Median Active Packing Time','value'=>$median($active),'format'=>'minutes'],['label'=>'Average Total Turnaround','value'=>$total?round(array_sum($total)/count($total),1):null,'format'=>'minutes'],['label'=>'Large-Volume Items','value'=>$counts['large']],['label'=>'Needs Label','value'=>$counts['needs_label']],['label'=>'Confirmed Corrections','value'=>$counts['needs_correction']],['label'=>'Packer Website Confirmations','value'=>$counts['website_done'],'numerator'=>$counts['website_done'],'denominator'=>$counts['website_required']],['label'=>'Items Requiring Review','value'=>$counts['review']]],'counts'=>$counts,'median_active'=>$median($active),'median_total'=>$median($total),'accuracy'=>$accuracy];
}
