<?php

declare(strict_types=1);
require_once __DIR__ . '/operations.php';
require_once __DIR__ . '/kpi-reporting.php';
require_role('owner_admin');
header('Content-Type: application/json; charset=utf-8');

try {
    $employeeId=max(0,(int)($_GET['id']??0)); $section=(string)($_GET['section']??'overview');
    $employee=ops_rows('SELECT e.id,e.full_name,e.hire_date,e.working_days,e.shift_start,e.shift_end,e.late_grace_minutes,r.name role_name,r.role_key FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id WHERE e.id=? AND e.status=\'active\' AND r.role_key<>\'owner_admin\' LIMIT 1',[$employeeId])[0]??null;
    if(!$employee){kpi_send_json(['ok'=>false,'success'=>false,'data'=>null,'message'=>'Employee not found.','error_code'=>'KPI_EMPLOYEE_NOT_FOUND'],404);}
    if((string)($_GET['action']??'')==='timeline'){$timelineModule=(string)($_GET['module']??'');$recordId=max(0,(int)($_GET['record_id']??0));if(!in_array($timelineModule,['order','packing','waybill','task','bookkeeping','website_update'],true)||!$recordId)throw new RuntimeException('Invalid timeline record.');$sectionMap=['order'=>'orders','packing'=>'packing_list','waybill'=>'courier_waybills','task'=>'tasks','bookkeeping'=>'bookkeeping','website_update'=>'website_updates'];$normalized=kpi_unified_events('2000-01-01 00:00:00','2099-12-31 23:59:59',null,$sectionMap[$timelineModule],null,$recordId);$events=[];foreach($normalized as$event)$events[]=['old_status'=>$event['previous_status'],'new_status'=>$event['new_status'],'changed_at'=>$event['occurred_at'],'changed_by_name'=>$event['actor_name'],'action_key'=>$event['action'],'related_reference'=>$event['related_reference'],'source_log'=>$event['source_log'],'source_event_id'=>$event['source_event_id'],'evidence_quality'=>$event['evidence_quality'],'metadata'=>$event['metadata']];foreach($events as$eventIndex=>$event){$next=$events[$eventIndex+1]['changed_at']??null;$events[$eventIndex]['duration_minutes']=$next?max(0,(int)((strtotime((string)$next)-strtotime((string)$event['changed_at']))/60)):null;$events[$eventIndex]['duration_evidence']=$next?'derived_from_logged_events':null;}kpi_send_json(['ok'=>true,'module'=>$timelineModule,'record_id'=>$recordId,'events'=>$events,'empty_message'=>'No matching Activity Log or authoritative record event was found for this transition.']);}
    $zone=new DateTimeZone('Africa/Windhoek');$today=new DateTimeImmutable('today',$zone);$resolvedPeriod=kpi_resolve_reporting_period($_GET);$period=$resolvedPeriod['key'];$from=$resolvedPeriod['from'];$to=$resolvedPeriod['to'];
    if($to<$from)throw new RuntimeException('The end date must be on or after the start date.');$settings=[];foreach(ops_rows('SELECT setting_key,setting_value FROM kpi_settings')as$row)$settings[(string)$row['setting_key']]=(string)$row['setting_value'];$dataStart=new DateTimeImmutable($settings['data_start_date']??'2026-07-01',$zone);$adoption=new DateTimeImmutable($settings['adoption_date']??'2026-07-14',$zone);$effective=$from<$dataStart?$dataStart:$from;$rateFrom=$effective<$adoption?$adoption:$effective;$fromSql=$effective->format('Y-m-d 00:00:00');$rateSql=$rateFrom->format('Y-m-d 00:00:00');$toSql=$to->format('Y-m-d 23:59:59');
    $logCoverage=kpi_activity_coverage_by_section();$sectionStart=static function(DateTimeImmutable $reportFrom,string $settingKey,string $fallback,?string $coverageSection=null)use($settings,$zone,$logCoverage):DateTimeImmutable{$configured=$settings[$settingKey]??$fallback;$earliest=$coverageSection&&isset($logCoverage[$coverageSection])&&$logCoverage[$coverageSection]<$configured?$logCoverage[$coverageSection]:$configured;$adopted=new DateTimeImmutable($earliest,$zone);return $reportFrom<$adopted?$adopted:$reportFrom;};
    $ordersFromSql=$sectionStart($effective,'orders_attribution_adoption_date','2026-07-10','orders')->format('Y-m-d 00:00:00');
    $packingFromSql=$sectionStart($effective,'packing_list_adoption_date','2026-07-01','packing_list')->format('Y-m-d 00:00:00');
    $packingTimingFromSql=$sectionStart($effective,'packing_timing_adoption_date','2026-07-14','packing_list')->format('Y-m-d 00:00:00');
    $websiteFromSql=$sectionStart($effective,'website_timing_adoption_date','2026-07-15','website_updates')->format('Y-m-d 00:00:00');
    $tasksFromSql=$sectionStart($effective,'tasks_adoption_date','2026-07-14','tasks')->format('Y-m-d 00:00:00');
    $waybillsFromSql=$sectionStart($effective,'waybills_adoption_date','2026-07-14','courier_waybills')->format('Y-m-d 00:00:00');
    $bookkeepingFromSql=$sectionStart($effective,'bookkeeping_adoption_date','2026-07-14','bookkeeping')->format('Y-m-d 00:00:00');
    $errorsFromSql=$sectionStart($effective,'error_log_adoption_date','2026-07-14','error_log')->format('Y-m-d 00:00:00');
    $portalFromSql=$sectionStart($effective,'portal_activity_adoption_date','2026-07-14','portal_activity')->format('Y-m-d 00:00:00');
    $payload=['ok'=>true,'employee'=>$employee,'section'=>$section,'period'=>kpi_period_response($resolvedPeriod,$adoption,$effective),'last_refreshed_at'=>(new DateTimeImmutable('now',$zone))->format(DATE_ATOM)];
    $payload['measurement_dates']=[
        'report_period'=>[$resolvedPeriod['from']->format('Y-m-d'),$resolvedPeriod['to']->format('Y-m-d')],
        'orders'=>$settings['orders_attribution_adoption_date']??'2026-07-10',
        'packing_list'=>$settings['packing_list_adoption_date']??'2026-07-01',
        'packing_timing'=>$settings['packing_timing_adoption_date']??'2026-07-14',
        'website_updates'=>$settings['website_timing_adoption_date']??'2026-07-15',
        'tasks'=>$settings['tasks_adoption_date']??'2026-07-14',
        'waybills'=>$settings['waybills_adoption_date']??'2026-07-14',
        'bookkeeping'=>$settings['bookkeeping_adoption_date']??'2026-07-14',
        'error_responsibility'=>$settings['error_log_adoption_date']??'2026-07-14',
        'portal_activity'=>$settings['portal_activity_adoption_date']??'2026-07-14',
        'activity_events'=>$settings['activity_event_adoption_date']??'2026-08-03',
    ];$payload['activity_log_coverage']=kpi_activity_coverage_by_section();foreach($payload['activity_log_coverage']as$coverageSection=>$coverageDate){$coverageKey=['orders'=>'orders','packing_list'=>'packing_list','website_updates'=>'website_updates','tasks'=>'tasks','courier_waybills'=>'waybills','bookkeeping'=>'bookkeeping','error_log'=>'error_responsibility','portal_activity'=>'portal_activity'][$coverageSection]??null;if($coverageKey&&isset($payload['measurement_dates'][$coverageKey])&&$coverageDate<$payload['measurement_dates'][$coverageKey])$payload['measurement_dates'][$coverageKey]=$coverageDate;}
    $rawSessions=ops_rows('SELECT user_id,login_at,last_seen_at,logout_at FROM kpi_sessions WHERE user_id=? AND login_at BETWEEN ? AND ? ORDER BY login_at',[$employeeId,$portalFromSql,$toSql]);foreach($rawSessions as$rawSessionIndex=>$rawSession)$rawSessions[$rawSessionIndex]['employee']=(string)$employee['full_name'];$sessions=kpi_merge_presence_rows($rawSessions);$employeeScheduleRows=ops_rows('SELECT weekday,shift_start,shift_end FROM kpi_employee_schedules WHERE employee_id=? AND is_working=1 ORDER BY weekday',[$employeeId]);$employeeSchedule=[];foreach($employeeScheduleRows as$scheduleRow)$employeeSchedule[(int)$scheduleRow['weekday']]=$scheduleRow;$scheduleSource=$employeeSchedule?'kpi_employee_schedules':null;if(!$employeeSchedule&&!empty($employee['working_days'])&&!empty($employee['shift_start'])&&!empty($employee['shift_end'])){foreach(preg_split('/[^0-9]+/',(string)$employee['working_days'],-1,PREG_SPLIT_NO_EMPTY)as$weekday){$weekday=(int)$weekday;if($weekday>=1&&$weekday<=7)$employeeSchedule[$weekday]=['weekday'=>$weekday,'shift_start'=>$employee['shift_start'],'shift_end'=>$employee['shift_end']];}$scheduleSource=$employeeSchedule?'ops_employees working schedule':null;}$scheduleConfigured=count($employeeSchedule)>0;$payload['schedule']=['configured'=>$scheduleConfigured,'source'=>$scheduleSource,'timezone'=>'Africa/Windhoek','late_grace_minutes'=>(int)($employee['late_grace_minutes']??($settings['late_grace_minutes']??10)),'rows'=>array_values($employeeSchedule)];$grace=(int)($employee['late_grace_minutes']??($settings['late_grace_minutes']??10));foreach($sessions as$sessionIndex=>$session){$weekday=(int)(new DateTimeImmutable((string)$session['day'],new DateTimeZone('Africa/Windhoek')))->format('N');$daySchedule=$employeeSchedule[$weekday]??null;$firstTime=substr((string)$session['first_login'],11,5);$sessions[$sessionIndex]['scheduled']=$daySchedule!==null;$sessions[$sessionIndex]['shift_start']=$daySchedule?substr((string)$daySchedule['shift_start'],0,5):null;$sessions[$sessionIndex]['shift_end']=$daySchedule?substr((string)$daySchedule['shift_end'],0,5):null;$sessions[$sessionIndex]['schedule_source']=$scheduleSource;$sessions[$sessionIndex]['late']=$daySchedule&&$firstTime!==''&&strtotime($firstTime)>strtotime((string)$sessions[$sessionIndex]['shift_start'].' +'.$grace.' minutes')?1:null;}
    $presence=ops_rows('SELECT COUNT(*) online FROM kpi_sessions WHERE user_id=? AND logout_at IS NULL AND last_seen_at>=DATE_SUB(NOW(),INTERVAL 10 MINUTE)',[$employeeId])[0]??[];$payload['online']=(int)($presence['online']??0)>0;$openPacking=ops_rows("SELECT id record_id,'packing' module,item_name item_label,packing_status current_status,date_loaded opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='packing' AND record_id=p.id),p.date_loaded),NOW()) age_hours FROM ops_packing_tasks p WHERE assigned_employee_id=? AND packing_status NOT IN ('done','website','packed_label_needed','done_needs_label','label_created') AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$openWaybills=ops_rows("SELECT id record_id,'waybill' module,COALESCE(customer_name,waybill_reference,CONCAT('Waybill #',id)) item_label,status current_status,uploaded_at opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='waybill' AND record_id=w.id),uploaded_at),NOW()) age_hours FROM hambelela_waybills w WHERE uploaded_by=? AND status IN ('pending','overdue') AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$openTasks=ops_rows("SELECT id record_id,'task' module,task_name item_label,status current_status,created_at opened_at,TIMESTAMPDIFF(HOUR,COALESCE((SELECT MAX(changed_at) FROM kpi_status_events WHERE module='task' AND record_id=t.id),created_at),NOW()) age_hours FROM ops_checklist_tasks t WHERE assigned_employee_id=? AND status <> 'complete' AND deleted_at IS NULL ORDER BY age_hours DESC LIMIT 30",[$employeeId]);$payload['open_work']=array_merge($openPacking,$openWaybills,$openTasks);
    if($section==='all'){
        $roleKey=(string)$employee['role_key'];$packerRole=strpos($roleKey,'packer')!==false;$frontDeskRole=strpos($roleKey,'front_desk')!==false;
        $leave=[];$links=ops_table_exists('employee_user_links')?ops_rows('SELECT hr_employee_id FROM employee_user_links WHERE portal_user_id=? AND active=1 LIMIT 1',[$employeeId]):[];if($links&&function_exists('ops_hr_rows'))$leave=ops_hr_rows("SELECT leave_type,start_date,end_date,days,status FROM leave_requests WHERE employee_id=? AND status='approved' AND start_date<=? AND end_date>=? ORDER BY start_date",[(int)$links[0]['hr_employee_id'],$to->format('Y-m-d'),$effective->format('Y-m-d')]);
        $orders=ops_rows("SELECT o.id,'order' timeline_module,o.order_number,o.customer_name,o.status,o.payment_status,o.total_amount,o.created_at,o.packed_at,o.completed_at FROM ops_orders o WHERE o.assigned_packer_id=? AND o.status IN ('completed','packed','verified') AND o.completed_at BETWEEN ? AND ? ORDER BY o.completed_at DESC LIMIT 300",[$employeeId,$ordersFromSql,$toSql]);
        $packing=ops_rows("SELECT id,'packing' timeline_module,item_name,quantity_planned,date_loaded,date_started,date_completed,packing_status,priority,COALESCE(workload_points_override,workload_points) workload_points,workload_points_override,workload_package_count,workload_weight_grams,workload_volume_ml,workload_unit_count,workload_parse_status,workload_breakdown_json,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_loaded,date_started) END queue_minutes,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END elapsed_minutes,frontdesk_website_updated,frontdesk_website_updated_at,frontdesk_website_updated_by FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY date_completed DESC LIMIT 300",[$employeeId,$packingFromSql,$toSql]);
        $website=$frontDeskRole?ops_rows("SELECT id,'website_update' timeline_module,item_name,date_loaded,date_completed,frontdesk_website_updated_at updated_at,frontdesk_website_updated_by,CASE WHEN frontdesk_website_updated_at>=date_loaded THEN TIMESTAMPDIFF(MINUTE,date_loaded,frontdesk_website_updated_at) END lag_minutes,CASE WHEN frontdesk_website_updated_at>=date_completed THEN TIMESTAMPDIFF(MINUTE,date_completed,frontdesk_website_updated_at) END completion_lag_minutes FROM ops_packing_tasks WHERE (frontdesk_website_updated_by=? OR COALESCE(frontdesk_website_updated,0)=0) AND date_loaded BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY date_loaded DESC LIMIT 300",[$employeeId,$websiteFromSql,$toSql]):ops_rows("SELECT id,'website_update' timeline_module,item_name,date_loaded,date_completed,frontdesk_website_updated_at updated_at,frontdesk_website_updated_by,CASE WHEN frontdesk_website_updated_at>=date_loaded THEN TIMESTAMPDIFF(MINUTE,date_loaded,frontdesk_website_updated_at) END lag_minutes,CASE WHEN frontdesk_website_updated_at>=date_completed THEN TIMESTAMPDIFF(MINUTE,date_completed,frontdesk_website_updated_at) END completion_lag_minutes FROM ops_packing_tasks WHERE date_loaded BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY date_loaded DESC LIMIT 300",[$websiteFromSql,$toSql]);
        $tasks=ops_rows("SELECT id,'task' timeline_module,task_name,status,priority,created_at,deadline,completed_at,CASE WHEN status IN ('complete','completed','approved') AND completed_at<=deadline THEN 1 ELSE 0 END completed_on_time,CASE WHEN status IN ('complete','completed','approved') AND completed_at>deadline THEN 1 ELSE 0 END completed_late,CASE WHEN status NOT IN ('complete','completed','approved') AND deadline<NOW() THEN 1 ELSE 0 END open_overdue,CASE WHEN completed_at>deadline THEN TIMESTAMPDIFF(MINUTE,deadline,completed_at) END late_minutes FROM ops_checklist_tasks WHERE assigned_employee_id=? AND (created_at BETWEEN ? AND ? OR completed_at BETWEEN ? AND ?) AND deleted_at IS NULL ORDER BY COALESCE(completed_at,created_at) DESC LIMIT 300",[$employeeId,$tasksFromSql,$toSql,$tasksFromSql,$toSql]);
        $waybills=ops_rows("SELECT w.id,'waybill' timeline_module,w.waybill_reference,w.order_id,w.customer_name,w.created_at,w.uploaded_at,w.uploaded_by,uploader.full_name uploaded_by_name,w.due_by,w.sent_at,w.sent_by,sender.full_name sent_by_name,w.status,CASE WHEN w.sent_at>=w.uploaded_at THEN TIMESTAMPDIFF(MINUTE,w.uploaded_at,w.sent_at) END duration_minutes,CASE WHEN w.sent_at>w.due_by THEN TIMESTAMPDIFF(MINUTE,w.due_by,w.sent_at) END late_minutes,CASE WHEN w.status='sent' AND w.sent_at<=w.due_by THEN 1 ELSE 0 END sent_on_time,CASE WHEN w.status='sent' AND w.sent_at>w.due_by THEN 1 ELSE 0 END sent_late,CASE WHEN w.status IN ('pending','overdue') AND w.due_by<NOW() THEN 1 ELSE 0 END currently_overdue FROM hambelela_waybills w LEFT JOIN ops_employees uploader ON uploader.id=w.uploaded_by LEFT JOIN ops_employees sender ON sender.id=w.sent_by WHERE (w.uploaded_by=? OR w.sent_by=?) AND (w.uploaded_at BETWEEN ? AND ? OR w.sent_at BETWEEN ? AND ?) AND w.deleted_at IS NULL ORDER BY COALESCE(w.sent_at,w.uploaded_at) DESC LIMIT 300",[$employeeId,$employeeId,$waybillsFromSql,$toSql,$waybillsFromSql,$toSql]);
        $holidayRows=ops_table_exists('kpi_holidays')?ops_rows('SELECT holiday_date FROM kpi_holidays WHERE active=1 AND holiday_date BETWEEN ? AND ?',[$effective->format('Y-m-d'),$to->format('Y-m-d')]):[];$holidays=array_column($holidayRows,'holiday_date');foreach($waybills as$waybillIndex=>$waybill){$waybills[$waybillIndex]['business_minutes']=null;if(!empty($waybill['uploaded_at'])&&!empty($waybill['sent_at'])&&strtotime((string)$waybill['sent_at'])>=strtotime((string)$waybill['uploaded_at'])){$waybills[$waybillIndex]['business_minutes']=kpi_business_minutes(new DateTimeImmutable((string)$waybill['uploaded_at'],$zone),new DateTimeImmutable((string)$waybill['sent_at'],$zone),$holidays);}}
        $bookkeeping=ops_rows("SELECT b.id,b.transaction_date,b.description,b.cash_in,b.cash_out,b.notes,b.status,b.deleted_at FROM ops_cash_book_entries b WHERE COALESCE(b.recorded_by,b.created_by_user_id)=? AND b.transaction_date BETWEEN ? AND ? ORDER BY b.transaction_date DESC LIMIT 300",[$employeeId,$bookkeepingFromSql,$toSql]);
        $reconciliations=ops_rows('SELECT id,recon_date,system_balance,counted_total,variance,variance_note,created_at FROM hambelela_cashbook_recon WHERE logged_by=? AND recon_date BETWEEN ? AND ? ORDER BY recon_date DESC',[$employeeId,substr($bookkeepingFromSql,0,10),$to->format('Y-m-d')]);
        $quality=ops_rows("SELECT l.id,l.error_title,l.category,l.severity,l.status,l.logged_at,l.resolution,l.logged_by,l.employee_id,l.responsible_employee_id,l.affects_kpi_accuracy,l.accuracy_verified_by,l.packing_task_id,l.order_reference,logger.full_name logged_by_name,responsible.full_name responsible_employee_name FROM ops_error_logs l LEFT JOIN ops_employees logger ON logger.id=l.logged_by LEFT JOIN ops_employees responsible ON responsible.id=l.responsible_employee_id WHERE (l.responsible_employee_id=? OR l.logged_by=? OR l.employee_id=?) AND l.logged_at BETWEEN ? AND ? AND l.deleted_at IS NULL ORDER BY l.logged_at DESC LIMIT 300",[$employeeId,$employeeId,$employeeId,$errorsFromSql,$toSql]);
        $activityTimeline=[];foreach(array_reverse(array_slice(kpi_unified_events($fromSql,$toSql,$employeeId),-500))as$event)$activityTimeline[]=['id'=>$event['event_id'],'portal_section'=>$event['section'],'record_type'=>$event['record_type'],'record_id'=>$event['record_id'],'action_key'=>$event['action'],'previous_status'=>$event['previous_status'],'new_status'=>$event['new_status'],'occurred_at'=>$event['occurred_at'],'employee_name'=>$event['actor_name'],'related_reference'=>$event['related_reference'],'source_page'=>$event['source_log'].' #'.$event['source_event_id'],'source_log'=>$event['source_log'],'source_event_id'=>$event['source_event_id'],'evidence_quality'=>$event['evidence_quality'],'metadata'=>$event['metadata']];
        $validPacking=array_values(array_filter($packing,static fn(array $row):bool=>$row['elapsed_minutes']!==null&&(string)$row['date_completed']>=$packingTimingFromSql));$elapsed=array_map(static fn(array $row):float=>(float)$row['elapsed_minutes'],$validPacking);sort($elapsed,SORT_NUMERIC);$median=function(array $values):?float{if(!$values)return null;$middle=intdiv(count($values),2);return count($values)%2?$values[$middle]:($values[$middle-1]+$values[$middle])/2;};
        $validWebsite=array_values(array_filter($website,static fn(array $row):bool=>$row['lag_minutes']!==null));$websiteLag=array_map(static fn(array $row):float=>(float)$row['lag_minutes'],$validWebsite);sort($websiteLag,SORT_NUMERIC);$pendingWebsite=count(array_filter($website,static fn(array $row):bool=>empty($row['updated_at'])));$websiteTarget=max(1,(int)($settings['website_update_lag_target_minutes']??60));
        $eligible=$packerRole?count($orders)+count($packing):count($website)+count($waybills)+count($tasks)+count($bookkeeping);$attributable=count(array_filter($quality,static fn(array $row):bool=>(int)$row['responsible_employee_id']>0&&(int)$row['responsible_employee_id']===$employeeId&&(int)$row['affects_kpi_accuracy']===1&&!empty($row['accuracy_verified_by'])));$accuracy=$eligible>0?max(0,100-(100*$attributable/$eligible)):null;
        $payload['sections']=[
          'overview'=>['metrics'=>[['label'=>'Current score','value'=>null,'status'=>'unmeasured'],['label'=>'Performance band','value'=>null,'status'=>'unmeasured'],['label'=>'Productivity','value'=>null,'status'=>'partial_data'],['label'=>'Accuracy','value'=>$accuracy,'format'=>'percent','status'=>$accuracy===null?'unmeasured':'partial_data'],['label'=>'Packing speed','value'=>$median($elapsed),'format'=>'minutes','status'=>$elapsed?'partial_data':'unmeasured'],['label'=>'Attendance','value'=>null,'status'=>$scheduleConfigured?'partial_data':'unmeasured'],['label'=>'Tasks completed','value'=>count(array_filter($tasks,static fn($r)=>in_array($r['status'],['complete','completed','approved'],true)))],['label'=>'Data coverage','value'=>null,'status'=>'partial_data']],'reference_only'=>false],
          'attendance'=>['metrics'=>[['label'=>'Scheduled working days','value'=>$scheduleConfigured?count($employeeSchedule):null],['label'=>'Days present','value'=>count($sessions)],['label'=>'Approved leave','value'=>array_sum(array_column($leave,'days'))],['label'=>'Late arrivals','value'=>$scheduleConfigured?array_sum(array_column($sessions,'late')):null],['label'=>'Portal Active Time','value'=>round(array_sum(array_column($sessions,'portal_active_hours')),1),'format'=>'hours'],['label'=>'Reliable attendance hours','value'=>null,'status'=>'unmeasured']],'rows'=>$sessions,'coverage'=>$scheduleConfigured?'partial_data':'unmeasured'],
          'orders'=>['metrics'=>[['label'=>'Distinct orders packed','value'=>count($orders)],['label'=>'Orders finalised','value'=>null,'status'=>'unmeasured'],['label'=>'Average orders per day','value'=>count($sessions)?round(count($orders)/count($sessions),1):null],['label'=>'Order errors','value'=>count(array_filter($quality,static fn($r)=>!empty($r['order_reference']))) ]],'rows'=>$orders,'reference_only'=>!$packerRole],
          'packing'=>['metrics'=>[['label'=>'Packing List rows completed','value'=>count($packing)],['label'=>'Total packages produced','value'=>array_sum(array_column($packing,'workload_package_count'))],['label'=>'Workload points','value'=>round(array_sum(array_column($packing,'workload_points')),1)],['label'=>'Valid timing records','value'=>count($validPacking),'denominator'=>count($packing)],['label'=>'Median packing duration','value'=>$median($elapsed),'format'=>'minutes','status'=>$elapsed?'partial_data':'unmeasured'],['label'=>'Average packing duration','value'=>$elapsed?round(array_sum($elapsed)/count($elapsed),1):null,'format'=>'minutes','status'=>$elapsed?'partial_data':'unmeasured'],['label'=>'Accuracy','value'=>$accuracy,'format'=>'percent','status'=>$accuracy===null?'unmeasured':'partial_data']],'rows'=>$packing,'reference_only'=>!$packerRole],
          'website_updates'=>['metrics'=>[['label'=>'Products loaded','value'=>count($website)],['label'=>'Products updated','value'=>count($validWebsite)],['label'=>'Awaiting update','value'=>$pendingWebsite],['label'=>'Completion rate','value'=>count($website)?round(100*count($validWebsite)/count($website),1):null,'format'=>'percent'],['label'=>'Median update time','value'=>$median($websiteLag),'format'=>'minutes'],['label'=>'Within target','value'=>$validWebsite?round(100*count(array_filter($websiteLag,static fn($v)=>$v<=$websiteTarget))/count($validWebsite),1):null,'format'=>'percent']],'rows'=>$website,'reference_only'=>!$frontDeskRole],
          'tasks'=>['metrics'=>[['label'=>'Tasks assigned','value'=>count($tasks)],['label'=>'Tasks completed','value'=>count(array_filter($tasks,static fn($r)=>in_array($r['status'],['complete','completed','approved'],true)))],['label'=>'Open tasks','value'=>count(array_filter($tasks,static fn($r)=>!in_array($r['status'],['complete','completed','approved'],true)))],['label'=>'Open overdue','value'=>array_sum(array_column($tasks,'open_overdue'))],['label'=>'Completed late','value'=>array_sum(array_column($tasks,'completed_late'))],['label'=>'Completed on time','value'=>array_sum(array_column($tasks,'completed_on_time'))]],'rows'=>$tasks],
          'waybills'=>['metrics'=>[['label'=>'Waybills handled','value'=>count($waybills)],['label'=>'Sent on time','value'=>array_sum(array_column($waybills,'sent_on_time'))],['label'=>'Sent late','value'=>array_sum(array_column($waybills,'sent_late'))],['label'=>'Currently overdue','value'=>array_sum(array_column($waybills,'currently_overdue'))]],'rows'=>$waybills,'reference_only'=>!$frontDeskRole],
          'bookkeeping'=>['metrics'=>[['label'=>'Ledger records','value'=>count($bookkeeping)],['label'=>'Cash-ups completed','value'=>count($reconciliations)],['label'=>'Total variance','value'=>array_sum(array_column($reconciliations,'variance')),'format'=>'currency'],['label'=>'Deleted or corrected','value'=>count(array_filter($bookkeeping,static fn($r)=>!empty($r['deleted_at'])||(string)$r['status']!=='active'))]],'rows'=>$bookkeeping,'reconciliations'=>$reconciliations,'reference_only'=>!$frontDeskRole],
          'quality'=>['metrics'=>[['label'=>'Employee-attributable errors','value'=>$attributable],['label'=>'Accuracy','value'=>$accuracy,'format'=>'percent','numerator'=>$accuracy===null?null:max(0,$eligible-$attributable),'denominator'=>$accuracy===null?null:$eligible,'status'=>$accuracy===null?'unmeasured':'partial_data'],['label'=>'Eligible completed work','value'=>$eligible],['label'=>'Errors reported by employee','value'=>count(array_filter($quality,static fn($row):bool=>(int)($row['logged_by']??0)===$employeeId))]],'rows'=>$quality],
          'score_breakdown'=>['enabled'=>false,'message'=>'Composite scores, performance bands, rankings and bonuses remain disabled until source coverage is complete.','rows'=>[]]
        ];
        $taskCompleted=count(array_filter($tasks,static fn($row):bool=>in_array((string)$row['status'],['complete','completed','approved'],true)));
        $taskRate=count($tasks)>0?100*$taskCompleted/count($tasks):null;
        $timingCoverage=count($packing)>0?100*count($validPacking)/count($packing):null;
        $speedTargetMinutes=max(1,(float)($settings['target_fulfilment_hours']??6)*60);
        $speedResult=$median($elapsed)!==null?min(100,100*$speedTargetMinutes/max($speedTargetMinutes,(float)$median($elapsed))):null;
        $websiteRate=count($website)>0?100*count($validWebsite)/count($website):null;
        $waybillSent=array_values(array_filter($waybills,static fn($row):bool=>(string)$row['status']==='sent'));
        $waybillRate=count($waybillSent)>0?100*array_sum(array_column($waybillSent,'sent_on_time'))/count($waybillSent):null;
        if($packerRole){
            $scoreComponents=[
                ['key'=>'productivity','label'=>'Productivity and workload-adjusted output','weight'=>30,'result'=>null,'evidence'=>'No approved workload target is configured.'],
                ['key'=>'accuracy','label'=>'Packing accuracy','weight'=>25,'result'=>$accuracy,'evidence'=>$attributable.' verified attributable errors across '.$eligible.' eligible records.'],
                ['key'=>'speed','label'=>'Packing speed','weight'=>15,'result'=>$speedResult,'evidence'=>count($validPacking).' valid timing records of '.count($packing).'.'],
                ['key'=>'attendance','label'=>'Attendance and reliability','weight'=>10,'result'=>null,'evidence'=>$scheduleConfigured?'Attendance coverage is incomplete.':'Employee schedule is not configured.'],
                ['key'=>'compliance','label'=>'Process compliance','weight'=>10,'result'=>$timingCoverage,'evidence'=>count($validPacking).' of '.count($packing).' packing rows have valid timing.'],
                ['key'=>'tasks','label'=>'Tasks and team contribution','weight'=>10,'result'=>$taskRate,'evidence'=>$taskCompleted.' of '.count($tasks).' assigned tasks completed.'],
            ];
        }else{
            $scoreComponents=[
                ['key'=>'orders','label'=>'Orders and customer-processing completion','weight'=>20,'result'=>null,'evidence'=>'Authoritative front-desk finalisation denominator is not yet available.'],
                ['key'=>'website','label'=>'Website updates','weight'=>15,'result'=>$websiteRate,'evidence'=>count($validWebsite).' of '.count($website).' required updates completed.'],
                ['key'=>'waybills','label'=>'Courier waybills','weight'=>15,'result'=>$waybillRate,'evidence'=>array_sum(array_column($waybillSent,'sent_on_time')).' of '.count($waybillSent).' sent on time.'],
                ['key'=>'bookkeeping','label'=>'Bookkeeping completion and accuracy','weight'=>15,'result'=>null,'evidence'=>'Qualifying cash-order reconciliation is not yet complete.'],
                ['key'=>'tasks','label'=>'Tasks','weight'=>15,'result'=>$taskRate,'evidence'=>$taskCompleted.' of '.count($tasks).' assigned tasks completed.'],
                ['key'=>'accuracy','label'=>'Accuracy and attributable errors','weight'=>10,'result'=>$accuracy,'evidence'=>$attributable.' owner-verified attributable errors. Errors merely logged by this employee are excluded.'],
                ['key'=>'attendance','label'=>'Attendance and process compliance','weight'=>10,'result'=>null,'evidence'=>$scheduleConfigured?'Attendance coverage is incomplete.':'Employee schedule is not configured.'],
            ];
        }
        $payload['sections']['score_breakdown']=kpi_calculate_role_score($scoreComponents);
        $roleScore=$payload['sections']['score_breakdown'];
        $payload['sections']['overview']['metrics'][0]=['label'=>$roleScore['provisional']?'Provisional score':'Current score','value'=>$roleScore['score'],'format'=>'percent','status'=>$roleScore['score']===null?'unmeasured':($roleScore['provisional']?'partial_data':'complete_data'),'explanation'=>'Role-specific measured components only; missing components are excluded and measured weights are renormalised.'];
        $payload['sections']['overview']['metrics'][1]=['label'=>$roleScore['provisional']?'Provisional band':'Performance band','value'=>$roleScore['band'],'status'=>$roleScore['score']===null?'unmeasured':($roleScore['provisional']?'partial_data':'complete_data'),'explanation'=>'Not final while evidence coverage is incomplete.'];
        $payload['sections']['overview']['metrics'][2]=['label'=>$packerRole?'Role focus: packing output':'Role focus: front-desk operations','value'=>$packerRole?count($packing):count($website)+count($waybills)+count($bookkeeping),'status'=>'partial_data','explanation'=>$packerRole?'Completed Packing List rows attributed to this employee.':'Website updates, courier waybills and bookkeeping records attributed to this employee.'];
        $payload['sections']['overview']['metrics'][7]=['label'=>'Data coverage','value'=>$roleScore['measured_weight'],'format'=>'percent','status'=>$roleScore['measured_weight']>=100?'complete_data':'partial_data','explanation'=>'Share of the configured role score supported by measurable evidence in this period.'];
        $payload['activity_timeline']=['rows'=>$activityTimeline,'historical_limit'=>'Existing section logs, global Activity Logs, status logs and authoritative records are used first. Only a specific transition absent from all sources is unavailable.'];
        $payload['data_quality']=['status'=>($scheduleConfigured&&count($validPacking)===count($packing))?'complete_data':'partial_data','warnings'=>array_values(array_filter([$scheduleConfigured?null:'Employee schedule is not configured.',count($validPacking)<count($packing)?'Some packing rows have missing or invalid timing.':null,count(array_filter($packing,static fn($r)=>(string)$r['workload_parse_status']==='pending_review'))?'Some quantities need workload review.':null]))];
        $payload['composite']=array_merge(['visible'=>true,'indicative'=>true],$payload['sections']['score_breakdown']);
        kpi_send_json($payload);
    }
    if($section==='attendance'){$leave=[];$links=ops_table_exists('employee_user_links')?ops_rows('SELECT hr_employee_id FROM employee_user_links WHERE portal_user_id=? AND active=1 LIMIT 1',[$employeeId]):[];if($links&&function_exists('ops_hr_rows'))$leave=ops_hr_rows("SELECT leave_type,start_date,end_date,days,status FROM leave_requests WHERE employee_id=? AND status='approved' AND start_date<=? AND end_date>=? ORDER BY start_date",[(int)$links[0]['hr_employee_id'],$to->format('Y-m-d'),$rateFrom->format('Y-m-d')]);$payload['rows']=$sessions;$payload['leave']=$leave;$payload['summary']=['portal_presence_days'=>count($sessions),'portal_active_hours'=>array_sum(array_map(static fn($r)=>(float)$r['portal_active_hours'],$sessions)),'late_days'=>$scheduleConfigured?array_sum(array_map(static fn($r)=>(int)($r['late']??0),$sessions)):null,'schedule_configured'=>$scheduleConfigured,'leave_days'=>array_sum(array_map(static fn($r)=>(float)$r['days'],$leave))];}
    elseif($section==='packing'){$payload['rows']=ops_rows("SELECT id,'packing' timeline_module,item_name,weight_class,quantity_planned,date_loaded,date_started,date_completed,packing_status,priority,workload_points,workload_package_count,workload_weight_grams,workload_volume_ml,workload_unit_count,workload_parse_status,workload_breakdown_json,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_loaded,date_started) END queue_minutes,CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END elapsed_minutes,frontdesk_website_updated,frontdesk_website_updated_at,frontdesk_website_updated_by FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY date_completed DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);}
    elseif($section==='orders'){$payload['rows']=ops_rows("SELECT o.id,'order' timeline_module,o.order_number,o.customer_name,o.status,o.total_amount,o.completed_at FROM ops_orders o WHERE o.assigned_packer_id=? AND o.status IN ('completed','packed','verified') AND o.completed_at BETWEEN ? AND ? ORDER BY o.completed_at DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);$orderPacks=ops_rows("SELECT COUNT(DISTINCT id) order_board_packs FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];$packingPacks=ops_rows("SELECT COUNT(DISTINCT id) packing_list_packs FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];$payload['summary']=['order_board_packs'=>(int)($orderPacks['order_board_packs']??0),'packing_list_packs'=>(int)($packingPacks['packing_list_packs']??0)];}
    elseif($section==='tasks'){$payload['rows']=ops_rows("SELECT id,'task' timeline_module,task_name,status,priority,created_at,deadline,completed_at FROM ops_checklist_tasks WHERE assigned_employee_id=? AND created_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 300",[$employeeId,$fromSql,$toSql]);}
    elseif($section==='waybills'){$payload['rows']=ops_rows("SELECT id,'waybill' timeline_module,waybill_reference,customer_name,uploaded_at,due_by,sent_at,status,TIMESTAMPDIFF(MINUTE,uploaded_at,sent_at) duration_minutes FROM hambelela_waybills WHERE (uploaded_by=? OR sent_by=?) AND uploaded_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY uploaded_at DESC LIMIT 300",[$employeeId,$employeeId,$fromSql,$toSql]);}
    elseif($section==='quality'){$payload['rows']=ops_rows('SELECT id,error_title,category,severity,status,logged_at,resolution,responsible_employee_id,affects_kpi_accuracy,accuracy_verified_by,packing_task_id,order_reference FROM ops_error_logs WHERE (responsible_employee_id=? OR employee_id=?) AND logged_at BETWEEN ? AND ? AND deleted_at IS NULL ORDER BY logged_at DESC LIMIT 300',[$employeeId,$employeeId,$fromSql,$toSql]);}
    elseif($section==='bookkeeping'){$payload['rows']=ops_rows('SELECT id,recon_date,system_balance,counted_total,variance,variance_note,created_at FROM hambelela_cashbook_recon WHERE logged_by=? AND recon_date BETWEEN ? AND ? ORDER BY recon_date DESC',[$employeeId,$effective->format('Y-m-d'),$to->format('Y-m-d')]);}
    elseif($section==='trends'){$payload['sessions']=$sessions;$payload['packing']=ops_rows("SELECT DATE(date_completed) day,COUNT(*) items,COALESCE(SUM(CASE WHEN workload_parse_status='parsed' OR workload_points_override IS NOT NULL THEN COALESCE(workload_points_override,workload_points) ELSE 0 END),0) points,AVG(CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END) avg_minutes FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL GROUP BY DATE(date_completed) ORDER BY day",[$employeeId,$rateSql,$toSql]);}
    elseif($section==='activity'){$module=(string)($_GET['module']??'');$events=kpi_unified_events($fromSql,$toSql,$employeeId,$module!==''?$module:null);$payload['rows']=[];foreach(array_reverse(array_slice($events,-500))as$event)$payload['rows'][]=['id'=>$event['event_id'],'portal_section'=>$event['section'],'timeline_module'=>$event['section'],'record_type'=>$event['record_type'],'record_id'=>$event['record_id'],'action_key'=>$event['action'],'old_status'=>$event['previous_status'],'new_status'=>$event['new_status'],'changed_at'=>$event['occurred_at'],'changed_by_name'=>$event['actor_name'],'related_reference'=>$event['related_reference'],'source_log'=>$event['source_log'],'source_event_id'=>$event['source_event_id'],'evidence_quality'=>$event['evidence_quality'],'metadata'=>$event['metadata']];$payload['historical_limit']='Only the specific transitions absent from Activity Logs and authoritative records are unavailable.';}
    else{
        $pack=ops_rows("SELECT COUNT(*) items,COALESCE(SUM(COALESCE(workload_points_override,workload_points)),0) points,AVG(CASE WHEN date_loaded<=date_started AND date_started<=date_completed THEN TIMESTAMPDIFF(MINUTE,date_started,date_completed) END) avg_minutes,SUM(packing_status NOT IN ('done','website','packed_label_needed','done_needs_label','label_created')) open_items,SUM(workload_parse_status='pending_review') workload_review_rows FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
        $tasks=ops_rows("SELECT SUM(status = 'complete') done,SUM(status <> 'complete') pending FROM ops_checklist_tasks WHERE assigned_employee_id=? AND created_at BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
        $orderWork=ops_rows("SELECT COUNT(DISTINCT id) orders FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];
        $errors=ops_rows("SELECT SUM(responsible_employee_id=? AND affects_kpi_accuracy=1 AND accuracy_verified_by IS NOT NULL) explicitly_attributable_errors,SUM(employee_id=? AND responsible_employee_id IS NULL) unattributed_errors FROM ops_error_logs WHERE logged_at BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$employeeId,$fromSql,$toSql])[0]??[];
        $itemCount=(int)($pack['items']??0);$orderCount=(int)($orderWork['orders']??0);$eligibleWork=$itemCount+$orderCount;$attributableErrors=(int)($errors['explicitly_attributable_errors']??0);$unattributedErrors=(int)($errors['unattributed_errors']??0);$accuracyAvailable=$eligibleWork>0&&$unattributedErrors===0;
        $payload['summary']=['portal_active_hours'=>array_sum(array_map(static fn($r)=>(float)$r['portal_active_hours'],$sessions)),'portal_presence_days'=>count($sessions),'items'=>$itemCount,'points'=>(float)($pack['points']??0),'avg_minutes'=>$itemCount>=5&&$pack['avg_minutes']!==null?(float)$pack['avg_minutes']:null,'open_items'=>(int)($pack['open_items']??0),'orders'=>$orderCount,'tasks_done'=>(int)($tasks['done']??0),'tasks_pending'=>(int)($tasks['pending']??0),'errors'=>$attributableErrors,'unattributed_errors'=>$unattributedErrors,'accuracy_available'=>$accuracyAvailable,'accuracy_numerator'=>$attributableErrors,'accuracy_denominator'=>$eligibleWork,'accuracy'=>$accuracyAvailable?max(0,1-$attributableErrors/max(1,$eligibleWork)):null,'workload_review_rows'=>(int)($pack['workload_review_rows']??0)];
    }
    $orderPackSource=ops_rows("SELECT COUNT(DISTINCT id) order_board_packs FROM ops_orders WHERE assigned_packer_id=? AND status IN ('completed','packed','verified') AND completed_at BETWEEN ? AND ?",[$employeeId,$fromSql,$toSql])[0]??[];
    $packingPackSource=ops_rows("SELECT COUNT(DISTINCT id) packing_list_packs FROM ops_packing_tasks WHERE assigned_employee_id=? AND date_completed BETWEEN ? AND ? AND deleted_at IS NULL",[$employeeId,$fromSql,$toSql])[0]??[];
    $payload['packing_sources']=[
        'order_board_packs'=>(int)($orderPackSource['order_board_packs']??0),
        'packing_list_packs'=>(int)($packingPackSource['packing_list_packs']??0),
        'order_source'=>'ops_orders.assigned_packer_id',
        'packing_source'=>'ops_packing_tasks.assigned_employee_id',
    ];
    if($section==='overview'&&isset($payload['summary'])){
        $payload['summary']['orders']=$payload['packing_sources']['order_board_packs'];
        $payload['summary']['items']=$payload['packing_sources']['packing_list_packs'];
    }
    $payload['composite']=['visible'=>false,'indicative'=>false,'score'=>null,'message'=>'Composite scores and rankings are disabled while KPI source integrity is under review.'];
    kpi_send_json($payload);
}catch(Throwable$error){error_log(date(DATE_ATOM).' employee detail: '.$error->getMessage().' in '.$error->getFile().':'.$error->getLine().PHP_EOL,3,BASE_PATH.'/logs/kpi_errors.log');kpi_send_json(['ok'=>false,'success'=>false,'data'=>null,'message'=>'Employee performance is temporarily unavailable.','error_code'=>'KPI_EMPLOYEE_REPORT_FAILED'],500);}
