<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
require_once BASE_PATH.'/shared/woocommerce.php';
require_once __DIR__.'/lib/orders-documents.php';

function orders_document_fail(string $message,int $status):void{http_response_code($status);header('Content-Type: text/plain; charset=utf-8');header('Cache-Control: private, no-store');echo $message;exit;}
function orders_document_json(array $payload,int $status=200):void{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: private, no-store');echo json_encode($payload,JSON_UNESCAPED_SLASHES);exit;}
function orders_document_log_request(int $portalId,string $sourceType,?int $sourceId,string $type,string $result,int $status,string $code):void{ops_order_documents_log('Document renderer request',['portal_order_id'=>$portalId,'source_type'=>$sourceType,'source_order_id'=>$sourceId,'document_type'=>$type,'renderer_result'=>$result,'http_status'=>$status,'error_code'=>$code,'timestamp'=>gmdate(DATE_ATOM)]);}
function orders_document_pos_request(int $sourceId,string $type,string $mode):array{
    $url=rtrim(WC_STORE_URL,'/').'/wp-json/hpos/v1/documents/'.$sourceId.'/'.rawurlencode($type).'?'.http_build_query(['mode'=>$mode,'consumer_key'=>WC_CONSUMER_KEY,'consumer_secret'=>WC_CONSUMER_SECRET]);
    $ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>30,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_HTTPHEADER=>['Accept: '.($mode==='download'?'application/pdf':'text/html, application/json')]]);
    $body=curl_exec($ch);$error=curl_error($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$contentType=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);
    if(!is_string($body))throw new RuntimeException($error?:'empty_response');return ['body'=>$body,'status'=>$status,'content_type'=>$contentType];
}
if(current_role_key()==='guest')orders_document_fail('Your session expired. Please log in again.',401);
$orderId=filter_input(INPUT_GET,'order_id',FILTER_VALIDATE_INT);$type=strtolower(trim((string)($_GET['document_type']??'')));$action=strtolower(trim((string)($_GET['action']??'')));
if(!$orderId||!in_array($action,['availability','view','download','print'],true))orders_document_fail('Choose a valid order document and action.',422);
if($action!=='availability'&&!in_array($type,['receipt','invoice'],true))orders_document_fail('Choose a valid order document and action.',422);
if(!ops_database_ready()||!ops_column_exists('ops_orders','woo_order_id')||!wc_configured())orders_document_fail('Unable to load document. Try again.',503);
$order=ops_rows('SELECT id, order_number, woo_order_id FROM ops_orders WHERE id = ? AND deleted_at IS NULL LIMIT 1',[(int)$orderId])[0]??null;if(!$order)orders_document_fail('Order not found.',404);
$sourceId=(int)($order['woo_order_id']??0);
if($sourceId<=0){orders_document_log_request((int)$orderId,'woocommerce',null,$type,'missing_mapping',404,'source_mapping_missing');if($action==='availability')orders_document_json(['portal_order_id'=>(int)$orderId,'source_order_id'=>null,'documents'=>['receipt'=>['available'=>false,'state'=>'source_order_not_found'],'invoice'=>['available'=>false,'state'=>'source_order_not_found']]]);orders_document_fail('Source order not found.',404);}
try{
    if($action==='availability'){$probe=orders_document_pos_request($sourceId,'receipt','availability');if($probe['status']===404){orders_document_log_request((int)$orderId,'woocommerce',$sourceId,'all','source_order_not_found',404,'source_order_not_found');orders_document_json(['portal_order_id'=>(int)$orderId,'source_order_id'=>$sourceId,'documents'=>['receipt'=>['available'=>false,'state'=>'source_order_not_found'],'invoice'=>['available'=>false,'state'=>'source_order_not_found']]]);}if($probe['status']<200||$probe['status']>=300)throw new RuntimeException('pos_http_'.$probe['status']);orders_document_log_request((int)$orderId,'woocommerce',$sourceId,'all','ready',200,'');orders_document_json(['portal_order_id'=>(int)$orderId,'source_order_id'=>$sourceId,'documents'=>['receipt'=>['available'=>true,'state'=>'ready'],'invoice'=>['available'=>true,'state'=>'ready']]]);}
    $result=orders_document_pos_request($sourceId,$type,$action);if($result['status']===404){orders_document_log_request((int)$orderId,'woocommerce',$sourceId,$type,'source_order_not_found',404,'source_order_not_found');orders_document_fail('Source order not found.',404);}if($result['status']<200||$result['status']>=300)throw new RuntimeException('pos_http_'.$result['status']);$expected=$action==='download'?'application/pdf':'text/html';if(stripos($result['content_type'],$expected)!==0)throw new RuntimeException('invalid_renderer_content_type');
    $visible=preg_replace('/^(?:WEB|INV)[-_\s#]*/i','',(string)($order['order_number']??$sourceId));$filename=ucfirst($type).'-INV-'.preg_replace('/[^A-Za-z0-9_-]/','',$visible).($action==='download'?'.pdf':'.html');orders_document_log_request((int)$orderId,'woocommerce',$sourceId,$type,'success',200,'');ops_activity_log('pos_'.$type.'_'.$action,'order',(int)$orderId,['source_order_id'=>$sourceId,'document_type'=>$type,'message'=>ucfirst($action).'ed POS '.$type.'.']);header('Content-Type: '.$expected.($action==='download'?'':'; charset=utf-8'));header('Content-Disposition: '.($action==='download'?'attachment':'inline').'; filename="'.$filename.'"');header('X-Portal-Original-Document: 1');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');echo $result['body'];
}catch(Throwable $e){orders_document_log_request((int)$orderId,'woocommerce',$sourceId,$type,'failed',502,preg_replace('/[^a-z0-9_\-]/i','_',substr($e->getMessage(),0,80)));orders_document_fail('Unable to load document. Try again.',502);}
