<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';
require_once BASE_PATH.'/shared/system-issues.php';
header('Content-Type: application/json; charset=utf-8');

function worker_callback_reply(int $status,array $body): never {http_response_code($status);echo json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function worker_callback_stage(array $issue,string $required): void {if((string)$issue['workflow_stage']!==$required)throw new DomainException('Callback is stale for the current workflow stage.');}

if($_SERVER['REQUEST_METHOD']!=='POST')worker_callback_reply(405,['error'=>'POST required']);
if(!defined('SYSTEM_ISSUES_WORKER_SECRET')||SYSTEM_ISSUES_WORKER_SECRET==='')worker_callback_reply(503,['error'=>'Repair worker is not configured']);
if(!system_issues_schema_ready())worker_callback_reply(503,['error'=>'System Issues storage unavailable']);
$raw=(string)file_get_contents('php://input');$timestamp=(string)($_SERVER['HTTP_X_HAMBELELA_TIMESTAMP']??'');$nonce=(string)($_SERVER['HTTP_X_HAMBELELA_NONCE']??'');$provided=(string)($_SERVER['HTTP_X_HAMBELELA_SIGNATURE']??'');
if(!ctype_digit($timestamp)||abs(time()-(int)$timestamp)>300||!preg_match('/^[A-Za-z0-9._:-]{16,190}$/',$nonce))worker_callback_reply(401,['error'=>'Expired or invalid callback']);
$canonical=$timestamp."\n".$nonce."\n".hash('sha256',$raw);$expected='sha256='.hash_hmac('sha256',$canonical,SYSTEM_ISSUES_WORKER_SECRET);if($provided===''||!hash_equals($expected,$provided))worker_callback_reply(401,['error'=>'Invalid signature']);
$payload=json_decode($raw,true);if(!is_array($payload))worker_callback_reply(400,['error'=>'Invalid JSON']);
$event=(string)($payload['event']??'');$providerEventId=mb_substr(trim((string)($payload['provider_event_id']??'')),0,190);$runId=mb_substr(trim((string)($payload['workflow_run_id']??'')),0,120);$issueId=(int)($payload['issue_id']??0);$jobId=(int)($payload['job_id']??0);$attempt=(int)($payload['attempt_number']??0);$eventTimestamp=strtotime((string)($payload['event_timestamp']??''));
$allowed=['repair_started','patch_generated','repair_failed','tests_started','tests_failed','tests_passed','pull_request_created'];if(!in_array($event,$allowed,true)||$providerEventId===''||$runId===''||$jobId<1||$attempt<1)worker_callback_reply(422,['error'=>'Complete callback identity is required']);
if($issueId<1||$eventTimestamp===false||abs(time()-$eventTimestamp)>600)worker_callback_reply(422,['error'=>'Valid issue and event timestamps are required']);

db()->beginTransaction();try{
 db()->prepare('DELETE FROM system_issue_worker_nonces WHERE created_at < DATE_SUB(NOW(),INTERVAL 1 DAY)')->execute();
 db()->prepare('INSERT INTO system_issue_worker_nonces(nonce_hash,worker_identifier,request_timestamp) VALUES(?,?,?)')->execute([hash('sha256',$nonce),'github-actions-callback',(int)$timestamp]);
 $job=ops_rows('SELECT * FROM system_issue_workflow_outbox WHERE id=? FOR UPDATE',[$jobId])[0]??null;if(!$job)throw new OutOfBoundsException('Repair job was not found.');
 if((int)$job['issue_id']!==$issueId||(int)$job['attempts']!==$attempt||!hash_equals((string)$job['worker_run_id'],$runId))throw new DomainException('Callback does not own the current repair attempt.');
 $issue=ops_rows('SELECT * FROM system_issues WHERE id=? FOR UPDATE',[(int)$job['issue_id']])[0]??null;if(!$issue)throw new OutOfBoundsException('Issue was not found.');
 $integration=ops_rows('SELECT * FROM system_issue_integrations WHERE job_id=? AND attempt_number=? FOR UPDATE',[$jobId,$attempt])[0]??null;if(!$integration)throw new DomainException('Controlled integration record is missing.');
 db()->prepare('INSERT INTO system_issue_provider_events(provider_event_id,issue_id,job_id,attempt_number,event_type) VALUES(?,?,?,?,?)')->execute([$providerEventId,(int)$issue['id'],$jobId,$attempt,$event]);
 $from=(string)$issue['workflow_stage'];$message='';$meta=['job_id'=>$jobId,'attempt_number'=>$attempt,'workflow_run_id'=>$runId];
 if($event==='repair_started'){worker_callback_stage($issue,'codex_queued');db()->prepare("UPDATE system_issues SET workflow_stage='codex_running',workflow_version=workflow_version+1,internal_status='codex_running',employee_status='fix_in_progress',codex_status='running' WHERE id=?")->execute([(int)$issue['id']]);db()->prepare("UPDATE system_issue_integrations SET status='codex_running',base_commit_sha=? WHERE id=?")->execute([preg_match('/^[a-f0-9]{40}$/',(string)($payload['base_commit_sha']??''))?(string)$payload['base_commit_sha']:null,(int)$integration['id']]);$message='Codex started the approved repair in the read-only GitHub job.';}
 elseif($event==='patch_generated'){worker_callback_stage($issue,'codex_running');db()->prepare("UPDATE system_issue_workflow_outbox SET status='patch_generated' WHERE id=?")->execute([$jobId]);db()->prepare("UPDATE system_issue_integrations SET status='patch_generated' WHERE id=?")->execute([(int)$integration['id']]);$message='Codex generated a patch artifact for isolated validation.';}
 elseif($event==='tests_started'){worker_callback_stage($issue,'codex_running');db()->prepare("UPDATE system_issues SET workflow_stage='testing',workflow_version=workflow_version+1,internal_status='testing',employee_status='testing' WHERE id=?")->execute([(int)$issue['id']]);db()->prepare("UPDATE system_issue_integrations SET status='testing',patch_commit_sha=? WHERE id=?")->execute([preg_match('/^[a-f0-9]{40}$/',(string)($payload['patch_commit_sha']??''))?(string)$payload['patch_commit_sha']:null,(int)$integration['id']]);$message='The isolated repair patch entered validation.';}
 elseif($event==='tests_passed'){worker_callback_stage($issue,'testing');$tested=(string)($payload['tested_commit_sha']??'');if(!preg_match('/^[a-f0-9]{40}$/',$tested))throw new DomainException('A tested commit SHA is required.');db()->prepare("UPDATE system_issue_integrations SET status='tests_passed',tests_passed_at=NOW(),tested_commit_sha=?,test_summary=? WHERE id=?")->execute([$tested,mb_substr((string)($payload['test_summary']??'Checks passed.'),0,2000),(int)$integration['id']]);$message='The repair checks passed for commit '.$tested.'.';$meta['tested_commit_sha']=$tested;}
 elseif($event==='pull_request_created'){worker_callback_stage($issue,'testing');$fresh=ops_rows('SELECT * FROM system_issue_integrations WHERE id=? FOR UPDATE',[(int)$integration['id']])[0];$commit=(string)($payload['patch_commit_sha']??'');if(empty($fresh['tests_passed_at'])||$commit===''||!hash_equals((string)$fresh['tested_commit_sha'],$commit))throw new DomainException('Only the tested commit may be proposed.');$pr=(int)($payload['pull_request_number']??0);$url=mb_substr((string)($payload['pull_request_url']??''),0,500);if($pr<1||$url==='')throw new DomainException('Pull request details are required.');db()->prepare("UPDATE system_issue_integrations SET status='pr_open',pull_request_number=?,external_url=?,patch_commit_sha=? WHERE id=?")->execute([$pr,$url,$commit,(int)$integration['id']]);db()->prepare("UPDATE system_issue_workflow_outbox SET status='processed',processed_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$jobId]);db()->prepare("UPDATE system_issues SET workflow_stage='ready_to_deploy',workflow_version=workflow_version+1,internal_status='ready_to_deploy',employee_status='testing',codex_status='complete' WHERE id=?")->execute([(int)$issue['id']]);$message='A tested repair pull request is ready for owner deployment approval.';$meta['pull_request_number']=$pr;$meta['pull_request_url']=$url;}
 else {$reason=mb_substr((string)($payload['error']??'The repair worker reported a failure.'),0,1000);db()->prepare("UPDATE system_issue_workflow_outbox SET status='failed',last_error=?,processed_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$reason,$jobId]);db()->prepare("UPDATE system_issue_integrations SET status='failed',last_error=? WHERE id=?")->execute([$reason,(int)$integration['id']]);db()->prepare("UPDATE system_issues SET workflow_stage='repair_failed',workflow_version=workflow_version+1,internal_status='repair_failed',employee_status='reopened',codex_status='failed' WHERE id=?")->execute([(int)$issue['id']]);$message=$event==='tests_failed'?'The repair checks failed; no pull request was opened.':'The repair worker failed safely; no pull request was opened.';}
 system_issue_event((int)$issue['id'],'worker_'.$event,$from,$event,$message,$meta);db()->commit();worker_callback_reply(200,['ok'=>true,'event'=>$event,'job_id'=>$jobId]);
}catch(PDOException $e){if(db()->inTransaction())db()->rollBack();if((string)$e->getCode()==='23000')worker_callback_reply(200,['ok'=>true,'duplicate'=>true]);error_log('System issue worker callback: '.$e->getMessage());worker_callback_reply(500,['error'=>'Callback could not be recorded']);}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();worker_callback_reply(409,['error'=>$e->getMessage()]);}
