<?php
declare(strict_types=1);
require_once __DIR__.'/operations.php';require_once BASE_PATH.'/shared/system-issues.php';require_login();
$pageTitle='System Issues Log | '.APP_NAME;$activeApp='system-issues';$ready=ops_database_ready()&&system_issues_schema_ready();$employeeId=(int)(ops_current_employee_id()??0);$owner=user_has_role('owner_admin','supervisor_manager');$flash=$_SESSION['system_issue_flash']??null;unset($_SESSION['system_issue_flash']);
function si_redirect(string $message,string $type='success',string $suffix=''): void {$_SESSION['system_issue_flash']=['message'=>$message,'type'=>$type];header('Location: '.BASE_URL.'/apps/operations/system-issues.php'.$suffix,true,303);exit;}
if($ready&&$_SERVER['REQUEST_METHOD']==='POST')try{
    system_issue_verify_csrf((string)($_POST['csrf']??''));$action=ops_post_string('action',40);
    if($action==='report'){
        $fields=[];foreach(['problem'=>1200,'location'=>255,'attempted_action'=>1200,'observed_behaviour'=>1800,'expected_behaviour'=>1200]as$key=>$max){$fields[$key]=ops_post_string($key,$max);if($fields[$key]==='')throw new RuntimeException('Please complete every problem-description field.');}
        $route=mb_substr((string)($_POST['route']??''),0,500);$title=mb_substr($fields['problem'],0,90);$s=db()->prepare("INSERT INTO system_issues(reporter_employee_id,title,problem,location,attempted_action,observed_behaviour,expected_behaviour,route,internal_status) VALUES(?,?,?,?,?,?,?,?,'ai_processing')");$s->execute([$employeeId,$title,$fields['problem'],$fields['location'],$fields['attempted_action'],$fields['observed_behaviour'],$fields['expected_behaviour'],$route]);$id=(int)db()->lastInsertId();$key=system_issue_generate_key($id);system_issue_uploads($id,$employeeId);system_issue_event($id,'reported',null,'ai_processing','Employee submitted a system issue.');system_issue_notify(['title'=>'System issue received','message'=>$key.' was saved and is being reviewed.','action_link'=>BASE_URL.'/apps/operations/system-issues.php?issue='.$id],[$employeeId]);$result=system_issue_triage($id);si_redirect((string)($result['message']??'Problem reported successfully.'),'success','?issue='.$id);
    }
    $id=max(1,(int)($_POST['issue_id']??0));$issue=ops_rows('SELECT * FROM system_issues WHERE id=?',[$id])[0]??null;if(!$issue||(!$owner&&(int)$issue['reporter_employee_id']!==$employeeId))throw new RuntimeException('Issue not found.');
    if($action==='add_information'){$message=ops_post_string('message',2000);if($message==='')throw new RuntimeException('Enter the requested information.');system_issue_uploads($id,$employeeId);system_issue_event($id,'employee_information_added',$issue['internal_status'],'ai_processing',$message);db()->prepare("UPDATE system_issues SET internal_status='ai_processing',employee_status='under_review' WHERE id=?")->execute([$id]);system_issue_triage($id);si_redirect('Information sent for review.','success','?issue='.$id);}
    if($action==='join_duplicate'){$duplicate=max(1,(int)($_POST['duplicate_id']??0));$target=ops_rows('SELECT * FROM system_issues WHERE id=? AND duplicate_of_id IS NULL',[$duplicate])[0]??null;if(!$target)throw new RuntimeException('The original issue is unavailable.');db()->prepare("UPDATE system_issues SET duplicate_of_id=?,internal_status='duplicate',employee_status='under_review' WHERE id=?")->execute([$duplicate,$id]);db()->prepare('UPDATE system_issues SET affected_count=affected_count+1 WHERE id=?')->execute([$duplicate]);system_issue_event($id,'joined_duplicate',$issue['internal_status'],'duplicate','Joined '.$target['issue_key'].'.',['duplicate_of'=>$duplicate]);si_redirect('You joined '.$target['issue_key'].' as an affected employee.','success','?issue='.$duplicate);}
    if($owner&&$action==='queue_repair'){system_issue_queue_repair($id);si_redirect('Controlled repair queued.','success','?issue='.$id);}
    if($owner&&$action==='set_status'&&($_POST['status']??'')==='testing')$_POST['status']='tests_passed';
    if($owner&&$action==='set_status'){$to=ops_post_string('status',30);$integration=ops_rows('SELECT * FROM system_issue_integrations WHERE issue_id=? ORDER BY id DESC LIMIT 1',[$id])[0]??null;if(in_array($to,['tests_passed','merged','deployed','verified','done'],true)&&!$integration)throw new RuntimeException('A controlled repair record is required first.');$now=date('Y-m-d H:i:s');if($to==='tests_passed'){db()->prepare("UPDATE system_issue_integrations SET status='tests_passed',tests_passed_at=? WHERE id=?")->execute([$now,$integration['id']]);$internal='testing';$employee='testing';}elseif($to==='merged'){if(empty($integration['tests_passed_at']))throw new RuntimeException('Tests must pass before merge.');db()->prepare("UPDATE system_issue_integrations SET status='merged',merged_at=? WHERE id=?")->execute([$now,$integration['id']]);$internal='pr_open';$employee='testing';}elseif($to==='deployed'){if(empty($integration['merged_at']))throw new RuntimeException('The pull request must be merged before deployment.');db()->prepare("UPDATE system_issue_integrations SET status='deployed',deployed_at=? WHERE id=?")->execute([$now,$integration['id']]);$internal='deployed';$employee='testing';}elseif($to==='verified'){if(empty($integration['deployed_at']))throw new RuntimeException('Deployment must succeed before live verification.');db()->prepare("UPDATE system_issue_integrations SET status='verified',live_verified_at=? WHERE id=?")->execute([$now,$integration['id']]);$internal='verified';$employee='testing';}elseif($to==='done'){if(empty($integration['tests_passed_at'])||empty($integration['merged_at'])||empty($integration['deployed_at'])||empty($integration['live_verified_at']))throw new RuntimeException('Done requires passed tests, merge, deployment and live verification.');$internal='done';$employee='done';}elseif($to==='deferred'){$internal='deferred';$employee='deferred';}elseif($to==='reopened'){$internal='new';$employee='reopened';}else throw new RuntimeException('Invalid status.');$verified=$to==='done'?$integration['live_verified_at']:$issue['verified_at'];db()->prepare('UPDATE system_issues SET internal_status=?,employee_status=?,verified_at=?,verified_by=? WHERE id=?')->execute([$internal,$employee,$verified,$to==='done'?$employeeId:$issue['verified_by'],$id]);system_issue_event($id,'status_changed',$issue['internal_status'],$internal,'Owner updated the controlled workflow.');system_issue_notify(['title'=>'System issue '.$employee,'message'=>$issue['issue_key'].' is now '.system_issue_status_label($employee).'.','action_link'=>BASE_URL.'/apps/operations/system-issues.php?issue='.$id],[(int)$issue['reporter_employee_id']]);si_redirect('Issue status updated.','success','?issue='.$id);}
}catch(Throwable $e){si_redirect($e->getMessage(),'error',isset($id)?'?issue='.$id:'');}
$where=$owner?'1=1':'(i.reporter_employee_id=? OR i.id IN (SELECT duplicate_of_id FROM system_issues WHERE reporter_employee_id=?))';$params=$owner?[]:[$employeeId,$employeeId];$issues=ops_rows("SELECT i.*,e.full_name reporter_name,(SELECT COUNT(*) FROM system_issue_attachments a WHERE a.issue_id=i.id) attachment_count FROM system_issues i LEFT JOIN ops_employees e ON e.id=i.reporter_employee_id WHERE $where ORDER BY FIELD(i.internal_status,'new','ai_processing','needs_information','brief_ready','codex_queued','codex_running','pr_open','testing','deployed','verified','done','deferred','duplicate'),i.updated_at DESC",$params);$selectedId=max(0,(int)($_GET['issue']??0));$selected=null;foreach($issues as$row)if((int)$row['id']===$selectedId)$selected=$row;
$brief=null;$events=[];$attachments=[];$duplicates=[];$integration=null;if($selected){$briefRow=ops_rows('SELECT * FROM system_issue_ai_briefs WHERE issue_id=? ORDER BY id DESC LIMIT 1',[(int)$selected['id']])[0]??null;$brief=$briefRow&&!empty($briefRow['ai_brief_json'])?json_decode($briefRow['ai_brief_json'],true):null;$events=ops_rows('SELECT v.*,e.full_name actor_name FROM system_issue_events v LEFT JOIN ops_employees e ON e.id=v.actor_employee_id WHERE issue_id=? ORDER BY created_at DESC,id DESC',[(int)$selected['id']]);$attachments=ops_rows('SELECT id,original_name,mime_type,size_bytes,created_at FROM system_issue_attachments WHERE issue_id=? ORDER BY id',[(int)$selected['id']]);$duplicates=system_issue_duplicate_candidates($selected);$integration=ops_rows('SELECT * FROM system_issue_integrations WHERE issue_id=? ORDER BY id DESC LIMIT 1',[(int)$selected['id']])[0]??null;}
include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace system-issues-page" id="system-issues-page">
 <header class="system-issues-hero"><div><span>Technical support</span><h1>System Issues Log</h1><p>Report portal problems in your own words. Reports never affect employee performance.</p></div><button class="button primary" type="button" data-open-report><i data-lucide="bug"></i> Report a Problem</button></header>
 <?php if(is_array($flash)):?><div class="system-issues-alert is-<?=htmlspecialchars($flash['type'])?>"><?=htmlspecialchars($flash['message'])?></div><?php endif;?>
 <section class="system-issues-assurance"><i data-lucide="shield-check"></i><div><strong>Safe to report</strong><span>System issues are separate from the Error Log and never count as mistakes, discipline, bonuses or KPI evidence.</span></div></section>
 <div class="system-issues-layout">
  <section class="system-issues-list"><header><div><h2><?= $owner?'All reported issues':'Your reported issues'?></h2><p><?=count($issues)?> visible</p></div></header>
   <?php if(!$issues):?><div class="system-issues-empty"><i data-lucide="circle-check-big"></i><strong>No system issues reported</strong><span>Use “Report a Problem” when something in the portal does not work as expected.</span></div><?php endif;?>
   <?php foreach($issues as$row):?><a class="system-issue-row<?=((int)$row['id']===$selectedId)?' is-selected':''?>" href="?issue=<?=(int)$row['id']?>"><div><span class="system-issue-key"><?=htmlspecialchars($row['issue_key'])?></span><strong><?=htmlspecialchars($row['title'])?></strong><small><?=htmlspecialchars($row['location'])?> · <?=htmlspecialchars($row['reporter_name']??'Employee')?> · <?=date('d M Y · H:i',strtotime($row['created_at']))?></small></div><div><span class="system-issue-status is-<?=htmlspecialchars($row['employee_status'])?>"><?=htmlspecialchars(system_issue_status_label($row['employee_status']))?></span><?php if((int)$row['affected_count']>1):?><small><?=(int)$row['affected_count']?> affected</small><?php endif;?></div></a><?php endforeach;?>
  </section>
  <aside class="system-issue-detail">
   <?php if(!$selected):?><div class="system-issues-empty"><i data-lucide="mouse-pointer-click"></i><strong>Select an issue</strong><span>Its progress and requests for information will appear here.</span></div><?php else:?><header><span><?=htmlspecialchars($selected['issue_key'])?></span><h2><?=htmlspecialchars($selected['title'])?></h2><div><span class="system-issue-status is-<?=htmlspecialchars($selected['employee_status'])?>"><?=htmlspecialchars(system_issue_status_label($selected['employee_status']))?></span><?php if($selected['verified_at']):?><small><?=date('d M Y · H:i',strtotime($selected['verified_at']))?></small><?php endif;?></div></header>
   <dl class="system-issue-plain"><div><dt>What happened</dt><dd><?=nl2br(htmlspecialchars($selected['problem']))?></dd></div><div><dt>Where</dt><dd><?=htmlspecialchars($selected['location'])?></dd></div><div><dt>Trying to do</dt><dd><?=nl2br(htmlspecialchars($selected['attempted_action']))?></dd></div><div><dt>Went wrong</dt><dd><?=nl2br(htmlspecialchars($selected['observed_behaviour']))?></dd></div><div><dt>Expected</dt><dd><?=nl2br(htmlspecialchars($selected['expected_behaviour']))?></dd></div></dl>
   <?php if($attachments):?><div class="system-issue-evidence"><h3>Evidence</h3><?php foreach($attachments as$a):?><a href="system-issue-attachment.php?id=<?=(int)$a['id']?>"><i data-lucide="paperclip"></i><?=htmlspecialchars($a['original_name'])?><small><?=number_format($a['size_bytes']/1024,1)?> KB</small></a><?php endforeach;?></div><?php endif;?>
   <?php if($selected['internal_status']==='needs_information'):?><form method="post" enctype="multipart/form-data" class="system-issue-info-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars(system_issue_csrf())?>"><input type="hidden" name="action" value="add_information"><input type="hidden" name="issue_id" value="<?=(int)$selected['id']?>"><h3>More information needed</h3><p><?=htmlspecialchars((string)($events[0]['message']??'Please add more details.'))?></p><textarea name="message" required placeholder="Add the requested information in your own words"></textarea><input type="file" name="evidence[]" multiple accept=".png,.jpg,.jpeg,.webp,.mp4,.pdf"><button class="button primary">Send information</button></form><?php endif;?>
   <?php if(!$owner&&$duplicates&&$selected['internal_status']!=='duplicate'):?><section class="system-issue-duplicates"><h3>This issue may already exist</h3><?php foreach($duplicates as$d):?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(system_issue_csrf())?>"><input type="hidden" name="action" value="join_duplicate"><input type="hidden" name="issue_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="duplicate_id" value="<?=(int)$d['id']?>"><span><?=htmlspecialchars($d['issue_key'].' · '.$d['title'])?></span><button class="button">Join existing issue</button></form><?php endforeach;?></section><?php endif;?>
   <?php if($owner&&$brief):?><details class="system-issue-brief" open><summary>AI technical brief <span><?=htmlspecialchars(strtoupper((string)$selected['ai_risk_level']))?> risk</span></summary><?php foreach(['summary'=>'Summary','observed_behaviour'=>'Observed behaviour','expected_behaviour'=>'Expected behaviour','steps_to_reproduce'=>'Steps to reproduce','affected_module'=>'Affected module','likely_root_cause'=>'Likely root cause','scope_of_fix'=>'Scope of fix','acceptance_criteria'=>'Acceptance criteria','required_tests'=>'Required tests','deployment_notes'=>'Deployment notes']as$key=>$label):?><div><strong><?=htmlspecialchars($label)?></strong><p><?=nl2br(htmlspecialchars(is_array($brief[$key]??null)?implode("\n",$brief[$key]):(string)($brief[$key]??'—')))?></p></div><?php endforeach;?></details>
    <section class="system-issue-controls"><h3>Controlled repair workflow</h3><p>Protected or backend changes require owner-controlled handling. Nothing writes directly to main.</p><?php if($integration):?><code><?=htmlspecialchars($integration['branch_name']??'')?></code><?php elseif($selected['ai_risk_level']==='low'&&$selected['internal_status']==='brief_ready'):?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(system_issue_csrf())?>"><input type="hidden" name="action" value="queue_repair"><input type="hidden" name="issue_id" value="<?=(int)$selected['id']?>"><button class="button primary">Queue controlled repair</button></form><?php else:?><span class="system-issue-review-required">Owner approval and manual control required</span><?php endif;?><form method="post" class="system-issue-status-form"><input type="hidden" name="csrf" value="<?=htmlspecialchars(system_issue_csrf())?>"><input type="hidden" name="action" value="set_status"><input type="hidden" name="issue_id" value="<?=(int)$selected['id']?>"><select name="status"><option value="testing">Testing</option><option value="deployed">Deployed</option><option value="verified">Live verified</option><option value="done">Done (after verification)</option><option value="reopened">Reopened</option><option value="deferred">Deferred</option></select><button class="button">Update workflow</button></form></section><?php endif;?>
   <?php if($events):?><section class="system-issue-timeline"><h3>Activity</h3><?php foreach($events as$event):?><div><span></span><p><strong><?=htmlspecialchars(ucwords(str_replace('_',' ',$event['event_type'])))?></strong><?=htmlspecialchars($event['message']??'')?><small><?=date('d M Y · H:i',strtotime($event['created_at']))?><?=!empty($event['actor_name'])?' · '.htmlspecialchars($event['actor_name']):''?></small></p></div><?php endforeach;?></section><?php endif;?>
   <?php endif;?>
  </aside>
 </div>
</main>
<dialog class="system-issue-dialog" data-report-dialog><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=htmlspecialchars(system_issue_csrf())?>"><input type="hidden" name="action" value="report"><input type="hidden" name="route" value="<?=htmlspecialchars((string)($_SERVER['HTTP_REFERER']??''))?>"><header><div><span>Simple problem report</span><h2>Report a Problem</h2><p>No technical language is needed.</p></div><button type="button" data-close-report aria-label="Close">×</button></header><?php foreach(['problem'=>'What is the problem?','location'=>'Where did it happen?','attempted_action'=>'What were you trying to do?','observed_behaviour'=>'What went wrong?','expected_behaviour'=>'What should have happened?']as$key=>$label):?><label><span><?=htmlspecialchars($label)?></span><textarea name="<?=$key?>" required></textarea></label><?php endforeach;?><label><span>Add screenshot or video <small>Optional</small></span><input type="file" name="evidence[]" multiple accept=".png,.jpg,.jpeg,.webp,.mp4,.pdf"><em>PNG, JPG, WEBP, MP4 or PDF · 25 MB each</em></label><footer><button type="button" class="button" data-close-report>Cancel</button><button class="button primary">Submit problem</button></footer></form></dialog>
<script>document.addEventListener('DOMContentLoaded',()=>{const d=document.querySelector('[data-report-dialog]');document.querySelector('[data-open-report]')?.addEventListener('click',()=>d.showModal());document.querySelectorAll('[data-close-report]').forEach(b=>b.addEventListener('click',()=>d.close()));d?.addEventListener('click',e=>{if(e.target===d)d.close()});if(window.lucide)lucide.createIcons()});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const option=document.querySelector('.system-issue-status-form option[value="testing"]');if(option)option.textContent='Tests passed';});</script>
<?php include BASE_PATH.'/shared/footer.php';?>
