<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';header('Referrer-Policy: no-referrer');
$actor=null;if(!empty($_SESSION['partner']))try{$actor=$partnerAuth->actor($_SESSION['partner']);}catch(DomainException $e){}
if($_SERVER['REQUEST_METHOD']==='POST'){
 header('Content-Type: application/json');try{
  \Hambelela\Delivery\PartnerAuth::csrf((string)($_POST['csrf']??''));if(($_POST['password']??'')!==($_POST['confirmation']??''))throw new DomainException('Passwords must match.');
  $token=(string)($_POST['token']??'');(new \Hambelela\Delivery\PartnerAccess(db()))->password((string)($_POST['password']??''),$token,$token===''?$actor:null,(string)($_POST['current']??''));
  unset($_SESSION['partner']);session_regenerate_id(true);echo '{"success":true}';
 }catch(DomainException $e){http_response_code(400);echo json_encode(['error'=>$e->getMessage()]);}catch(Throwable $e){http_response_code(503);echo '{"error":"Password could not be changed."}';}exit;
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tedlaser account password</title><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-core.css"><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-controls.css"></head><body data-delivery-ui><main class="delivery-login"><div class="eyebrow">TEDLASER · ACCOUNT</div><h1>Set your password</h1><p>Use a unique password of at least 16 characters. Changing it signs out existing sessions.</p><form id="partner-password" method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'],ENT_QUOTES)?>"><input type="hidden" name="token" value=""><label id="current-password-label">Current password<input name="current" type="password" autocomplete="current-password"></label><label>New password<input name="password" type="password" minlength="16" maxlength="72" required autocomplete="new-password"></label><label>Confirm password<input name="confirmation" type="password" minlength="16" maxlength="72" required autocomplete="new-password"></label><button class="primary">Save password</button><p role="status" id="password-result"></p></form><a class="secondary" href="login.php">Partner sign-in</a></main><script src="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/js/delivery-partner-reset.js"></script></body></html>
