<?php declare(strict_types=1); ?>
<section class="recurring-task-view" data-recurring-task-view>
  <header class="recurring-task-heading">
    <div><span>Recurring definitions</span><h2>Recurring Tasks</h2><p>Manage the rules that create future tasks. Completed history is never rewritten.</p></div>
    <button class="dtb-btn dtb-btn-primary" type="button" data-task-create-open data-task-create-kind="recurring"><i data-lucide="plus"></i><span>Add Recurring Task</span></button>
  </header>
  <div class="recurring-summary" aria-label="Recurring task summary">
    <?php foreach ([['Active recurring tasks','active','repeat-2'],['Paused','paused','pause'],['Next 24 hours','next_24_hours','clock-3'],['Needs attention','attention','triangle-alert']] as [$label,$key,$icon]): ?>
      <article><span class="recurring-summary__icon"><i data-lucide="<?= $icon ?>" aria-hidden="true"></i></span><span><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></span><strong><?= number_format((int)$recurringSummary[$key]) ?></strong></article>
    <?php endforeach; ?>
  </div>
  <form method="get" class="recurring-filters">
    <input type="hidden" name="task_view" value="recurring">
    <label class="recurring-search"><i data-lucide="search" aria-hidden="true"></i><input type="search" name="recurring_search" value="<?= htmlspecialchars((string)($_GET['recurring_search']??''),ENT_QUOTES,'UTF-8') ?>" placeholder="Search recurring tasks" aria-label="Search recurring tasks"></label>
    <label><span class="sr-only">Status</span><select name="recurring_status" aria-label="Filter by status"><option value="">All statuses</option><?php foreach(['active'=>'Active','paused'=>'Paused','ended'=>'Ended','cancelled'=>'Cancelled'] as $value=>$label): ?><option value="<?= $value ?>"<?= (string)($_GET['recurring_status']??'')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
    <button type="submit"><i data-lucide="list-filter" aria-hidden="true"></i><span>Apply filters</span></button>
  </form>
  <div class="recurring-table-wrap"><table class="recurring-task-table"><thead><tr><th>Task</th><th>Assignment</th><th>Frequency</th><th>Next Run</th><th>Notes</th><th>Status</th><th>Generated</th><th>Actions</th></tr></thead><tbody>
  <?php if(!$recurringDefinitions): ?><tr><td colspan="8" class="recurring-empty">No recurring task definitions match this view.</td></tr><?php endif; ?>
  <?php foreach($recurringDefinitions as $definition):
    $id=(int)$definition['id']; $status=(string)($definition['status']??'active');
    $assignment=($definition['assignment_type']??'specific')==='floating'?'Floating · '.ucwords(str_replace('_',' ',(string)($definition['floating_eligible_role']??''))):((string)($definition['assigned_name']??'')?:'All eligible packers');
    $releaseMinutes=(int)($definition['release_offset_minutes']??0); $releaseRule=$releaseMinutes<=0?'At occurrence':($releaseMinutes%1440===0?($releaseMinutes/1440).' day(s) before':($releaseMinutes%60===0?($releaseMinutes/60).' hour(s) before':$releaseMinutes.' minutes before'));
    $dueDays=(int)($definition['occurrence_due_days']??0); $dueRule=($dueDays===0?'Same day':$dueDays.' day(s) after').' · '.substr((string)($definition['occurrence_due_time']?:$definition['due_time']),0,5);
    $notesPreview=task_instructions_plain_text((string)($definition['instructions']??'')); $frequency=checklist_recurrence_label((string)$definition['recurring_rule']).' · '.substr((string)$definition['due_time'],0,5);
  ?>
    <tr<?= !empty($definition['needs_attention'])?' class="needs-attention"':'' ?>>
      <td data-label="Task"><button type="button" class="recurring-task-name" data-recurring-open="<?= $id ?>"><strong><?= htmlspecialchars((string)$definition['task_name'],ENT_QUOTES,'UTF-8') ?></strong></button><?php if(!empty($definition['needs_attention'])):?><small><i data-lucide="triangle-alert"></i>Needs attention</small><?php endif;?></td>
      <td data-label="Assignment"><?= htmlspecialchars($assignment,ENT_QUOTES,'UTF-8') ?></td><td data-label="Frequency"><?= htmlspecialchars($frequency,ENT_QUOTES,'UTF-8') ?></td>
      <td data-label="Next Run"><?= !empty($definition['next_run_at'])?htmlspecialchars(date('d M Y · H:i',strtotime((string)$definition['next_run_at'])),ENT_QUOTES,'UTF-8'):'—' ?></td>
      <td data-label="Notes"><span class="recurring-notes-preview" title="<?= htmlspecialchars($notesPreview,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($notesPreview!==''?$notesPreview:'No notes added',ENT_QUOTES,'UTF-8') ?></span></td>
      <td data-label="Status"><span class="recurring-status recurring-status--<?= htmlspecialchars($status,ENT_QUOTES,'UTF-8') ?>"><?= ucfirst($status) ?></span></td>
      <td data-label="Generated"><button type="button" class="recurring-generated-link" data-recurring-occurrences="<?= $id ?>"><?= number_format((int)$definition['generated_count']) ?> tasks</button></td>
      <td data-label="Actions"><div class="recurring-actions"><button type="button" data-recurring-open="<?= $id ?>"><i data-lucide="panel-right-open"></i><span>View</span></button><button type="button" data-recurring-edit="<?= $id ?>"><i data-lucide="pencil"></i><span>Edit</span></button></div></td>
    </tr>
    <tr class="recurring-occurrences-row" data-recurring-occurrences-row="<?= $id ?>" hidden><td colspan="8"><div data-recurring-occurrences-content>Loading generated tasks…</div></td></tr>
    <tr class="recurring-detail-host"><td colspan="8"><div class="recurring-detail-backdrop" data-recurring-detail-backdrop="<?= $id ?>" hidden></div>
    <aside class="recurring-detail-drawer" data-recurring-detail="<?= $id ?>" aria-hidden="true" aria-labelledby="recurring-title-<?= $id ?>">
      <header><div><span>Recurring task</span><h3 id="recurring-title-<?= $id ?>"><?= htmlspecialchars((string)$definition['task_name'],ENT_QUOTES,'UTF-8') ?></h3><p>Future schedule definition</p></div><button type="button" data-recurring-detail-close aria-label="Close recurring task details"><i data-lucide="x"></i></button></header>
      <div class="recurring-detail-body">
        <section><h4><i data-lucide="layout-dashboard"></i>Overview</h4><dl><div><dt>Status</dt><dd><span class="recurring-status recurring-status--<?= htmlspecialchars($status,ENT_QUOTES,'UTF-8') ?>"><?= ucfirst($status) ?></span></dd></div><div><dt>Priority</dt><dd><?= htmlspecialchars(ucfirst((string)($definition['priority']??'normal')),ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Assigned to</dt><dd><?= htmlspecialchars($assignment,ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Role</dt><dd><?= htmlspecialchars(($definition['assignment_type']??'specific')==='floating'?ucwords(str_replace('_',' ',(string)($definition['floating_eligible_role']??'Eligible employees'))):'Assigned employee',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Created</dt><dd><?= !empty($definition['created_at'])?htmlspecialchars(date('d M Y · H:i',strtotime((string)$definition['created_at'])),ENT_QUOTES,'UTF-8'):'—' ?></dd></div><div><dt>Created by</dt><dd><?= htmlspecialchars((string)($definition['created_by_name']??'System'),ENT_QUOTES,'UTF-8') ?></dd></div></dl></section>
        <section><h4><i data-lucide="calendar-clock"></i>Schedule</h4><dl><div><dt>Frequency</dt><dd><?= htmlspecialchars($frequency,ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Next run</dt><dd><?= !empty($definition['next_run_at'])?htmlspecialchars(date('d M Y · H:i',strtotime((string)$definition['next_run_at'])),ENT_QUOTES,'UTF-8'):'—' ?></dd></div><div><dt>Release</dt><dd><?= htmlspecialchars($releaseRule,ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Due</dt><dd><?= htmlspecialchars($dueRule,ENT_QUOTES,'UTF-8') ?></dd></div></dl></section>
        <section><h4><i data-lucide="file-text"></i>Task instructions</h4><div class="recurring-instructions"><?= checklist_render_instructions((string)($definition['instructions']??'')) ?></div></section>
        <section><h4><i data-lucide="sticky-note"></i>Notes</h4><p class="recurring-full-notes"><?= htmlspecialchars($notesPreview!==''?$notesPreview:'No additional notes were added.',ENT_QUOTES,'UTF-8') ?></p></section>
        <section><h4><i data-lucide="activity"></i>Activity</h4><dl><div><dt>Generated</dt><dd><button type="button" class="recurring-generated-link" data-recurring-occurrences="<?= $id ?>" data-recurring-close-before-occurrences><?= number_format((int)$definition['generated_count']) ?> tasks</button></dd></div><div><dt>Last generated</dt><dd><?= !empty($definition['generated_last_at'])?htmlspecialchars(date('d M Y · H:i',strtotime((string)$definition['generated_last_at'])),ENT_QUOTES,'UTF-8'):'No generated task yet' ?></dd></div><?php if(!empty($definition['last_error'])):?><div class="is-warning"><dt>Latest issue</dt><dd><?= htmlspecialchars((string)$definition['last_error'],ENT_QUOTES,'UTF-8') ?></dd></div><?php endif;?></dl></section>
        <section class="recurring-control"><h4><i data-lucide="settings-2"></i>Recurrence control</h4><p>Stopping future recurrences will prevent new tasks from being generated. Existing tasks will remain unchanged.</p><div><?php if($status==='active'):?><form method="post"><input type="hidden" name="action" value="recurring_pause"><input type="hidden" name="recurring_template_id" value="<?= $id ?>"><button type="submit"><i data-lucide="pause"></i>Pause recurrence</button></form><?php elseif($status==='paused'):?><form method="post"><input type="hidden" name="action" value="recurring_resume"><input type="hidden" name="recurring_template_id" value="<?= $id ?>"><button type="submit"><i data-lucide="play"></i>Resume recurrence</button></form><?php endif;?><?php if(!in_array($status,['ended','cancelled'],true)):?><form method="post" data-recurring-stop-form data-recurring-name="<?= htmlspecialchars((string)$definition['task_name'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="recurring_end"><input type="hidden" name="recurring_template_id" value="<?= $id ?>"><button type="submit" class="is-danger"><i data-lucide="octagon-x"></i>Stop Future Recurrences</button></form><?php endif;?></div></section>
      </div>
    </aside></td></tr>
  <?php endforeach; ?></tbody></table></div>
  <?php foreach($recurringDefinitions as $definition): $id=(int)$definition['id']; $savedRule=(string)$definition['recurring_rule']; $savedDays=[]; if(preg_match('/^weekly_days:([1-7](?:,[1-7])*)$/',$savedRule,$savedMatch))$savedDays=array_map('intval',explode(',',$savedMatch[1])); ?>
    <dialog class="recurring-edit-dialog" data-recurring-edit-dialog="<?= $id ?>"><form method="post"><header><div><span>Future occurrences only</span><h3>Edit Recurring Task</h3></div><button type="button" data-recurring-edit-close aria-label="Close"><i data-lucide="x"></i></button></header><input type="hidden" name="action" value="recurring_update"><input type="hidden" name="recurring_template_id" value="<?= $id ?>"><input type="hidden" name="version_no" value="<?= (int)($definition['version_no']??1) ?>"><label><span>Task name</span><input name="task_name" value="<?= htmlspecialchars((string)$definition['task_name'],ENT_QUOTES,'UTF-8') ?>" required></label><label><span>Instructions</span><textarea name="instructions" required><?= htmlspecialchars((string)$definition['instructions'],ENT_QUOTES,'UTF-8') ?></textarea></label><div class="recurring-edit-grid"><label><span>Priority</span><select name="priority"><?php foreach($priorities as $value=>$label):?><option value="<?= $value ?>"<?= (string)$definition['priority']===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><label><span>Frequency</span><select name="recurring_rule"><option value="daily_business_day"<?= $savedRule==='daily_business_day'?' selected':'' ?>>Every business day</option><option value="weekly_days"<?= $savedDays?' selected':'' ?>>Weekly on selected days</option><?php foreach(['twice_weekly','weekly_1','weekly_2','weekly_3','weekly_4','weekly_5','weekly_saturday'] as $value):?><option value="<?= $value ?>"<?= $savedRule===$value?' selected':'' ?>><?= htmlspecialchars(checklist_recurrence_label($value),ENT_QUOTES,'UTF-8') ?></option><?php endforeach;?></select></label><fieldset class="task-repeat-weekdays"><legend>Repeat on</legend><?php foreach([1=>'Mon',2=>'Tue',3=>'Wed',4=>'Thu',5=>'Fri',6=>'Sat',7=>'Sun'] as $day=>$label):?><label><input type="checkbox" name="repeat_weekdays[]" value="<?=$day?>"<?=in_array($day,$savedDays,true)?' checked':''?>><span><?=$label?></span></label><?php endforeach;?></fieldset><label><span>Repeat time</span><input type="time" name="due_time" value="<?= htmlspecialchars(substr((string)$definition['due_time'],0,5),ENT_QUOTES,'UTF-8') ?>" required></label><label><span>Start date</span><input type="date" name="start_date" value="<?= htmlspecialchars((string)($definition['start_date']??''),ENT_QUOTES,'UTF-8') ?>"></label><label><span>End date</span><input type="date" name="end_date" value="<?= htmlspecialchars((string)($definition['end_date']??''),ENT_QUOTES,'UTF-8') ?>"></label></div><p>Changes apply to future generated occurrences only. Completed and already-generated task history is not rewritten.</p><footer><button type="button" data-recurring-edit-close>Cancel</button><button type="submit">Save Future Rule</button></footer></form></dialog>
  <?php endforeach; ?>
  <dialog class="recurring-stop-dialog" data-recurring-stop-dialog><form method="dialog"><div class="recurring-stop-dialog__icon"><i data-lucide="triangle-alert"></i></div><span>Recurring task control</span><h3>Stop future recurrences?</h3><p><strong data-recurring-stop-name></strong> will stop generating new tasks. Existing tasks will not be deleted.</p><div><button type="button" data-recurring-stop-cancel>Keep Recurring</button><button type="button" class="is-danger" data-recurring-stop-confirm><i data-lucide="octagon-x"></i>Stop Recurrences</button></div></form></dialog>
</section>
