<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/accounts-input-vat.php';

function import_vat_require_owner(): void { require_login(); if(!accounts_is_owner()){http_response_code(403);exit('You do not have access to Import VAT.');} }
function import_vat_schema_ready(): void {
 static $ready=false;if($ready)return;
 $queries=[
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_liabilities(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_date DATE NOT NULL,import_month CHAR(7) NOT NULL,supplier VARCHAR(190) NOT NULL,description TEXT NOT NULL,reference VARCHAR(190) NOT NULL,source_system VARCHAR(80) NULL,country_origin VARCHAR(100) NULL,currency VARCHAR(20) NULL,supplier_invoice_value DECIMAL(13,2) NULL,customs_value DECIMAL(13,2) NULL,payment_arrangement VARCHAR(40) NOT NULL,import_vat_amount DECIMAL(13,2) NOT NULL,duty_amount DECIMAL(13,2) NOT NULL DEFAULT 0,other_charge_amount DECIMAL(13,2) NOT NULL DEFAULT 0,total_due DECIMAL(13,2) NOT NULL,due_date DATE NOT NULL,notes TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_by INT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME NULL,deleted_by INT NULL,UNIQUE KEY uq_import_reference(reference),KEY idx_import_month(import_month,deleted_at),KEY idx_import_due(due_date,deleted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,payment_date DATE NOT NULL,amount DECIMAL(13,2) NOT NULL,reference VARCHAR(190) NULL,payment_method VARCHAR(80) NULL,notes TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at DATETIME NULL,reversed_by INT NULL,reversal_reason VARCHAR(500) NULL,KEY idx_import_payment(import_id,reversed_at),KEY idx_import_payment_date(payment_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_documents(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,payment_id BIGINT UNSIGNED NULL,document_type VARCHAR(40) NOT NULL,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,uploaded_by INT NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at DATETIME NULL,deleted_by INT NULL,UNIQUE KEY uq_import_document(stored_filename),KEY idx_import_document(import_id,payment_id,deleted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,action_key VARCHAR(50) NOT NULL,before_json LONGTEXT NULL,after_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_import_audit(import_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_month_status(month_key CHAR(7) PRIMARY KEY,reconciled TINYINT(1) NOT NULL DEFAULT 0,updated_by INT NOT NULL,updated_by_name VARCHAR(190) NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
 ];foreach($queries as$q)db()->exec($q);$ready=true;
}
function import_vat_csrf(): string {if(empty($_SESSION['import_vat_csrf']))$_SESSION['import_vat_csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['import_vat_csrf'];}
function import_vat_verify(string $token): void {if($token===''||!hash_equals(import_vat_csrf(),$token))throw new RuntimeException('Your session expired. Refresh and try again.');}
function import_vat_month(string $v): string{return preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$v)?$v:date('Y-m');}
function import_vat_audit(int$id,string$action,?array$before,?array$after):void{$u=current_user();db()->prepare('INSERT INTO accounts_import_vat_audit(import_id,action_key,before_json,after_json,actor_id,actor_name)VALUES(?,?,?,?,?,?)')->execute([$id,$action,$before?json_encode($before,JSON_UNESCAPED_SLASHES):null,$after?json_encode($after,JSON_UNESCAPED_SLASHES):null,(int)($u['id']??0),(string)($u['name']??'Owner')]);}
function import_vat_record(int$id):?array{$s=db()->prepare('SELECT * FROM accounts_import_vat_liabilities WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$r=$s->fetch();return$r?:null;}
function import_vat_status(float$due,float$paid,string$dueDate):string{$out=$due-$paid;if($paid>$due+0.005)return'overpayment';if($out<=0.005)return'paid';if($dueDate<date('Y-m-d'))return'overdue';if($paid>0)return'partially_paid';if($dueDate<=date('Y-m-d',strtotime('+7 days')))return'due_soon';return'unpaid';}
function import_vat_payload(string$month,string$view='imports'):array{
 import_vat_schema_ready();$where=$view==='payments'?'DATE_FORMAT(l.due_date,\'%Y-%m\')=?':'l.import_month=?';$s=db()->prepare("SELECT l.*,COALESCE(SUM(CASE WHEN p.reversed_at IS NULL THEN p.amount ELSE 0 END),0) paid FROM accounts_import_vat_liabilities l LEFT JOIN accounts_import_vat_payments p ON p.import_id=l.id WHERE l.deleted_at IS NULL AND $where GROUP BY l.id ORDER BY l.due_date,l.id");$s->execute([$month]);$rows=$s->fetchAll();
 $summary=['imports'=>count($rows),'import_vat'=>0.0,'other_charges'=>0.0,'total_due'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'overdue'=>0.0];
 foreach($rows as&$r){$r['paid']=(float)$r['paid'];$r['outstanding']=max(0,round((float)$r['total_due']-$r['paid'],2));$r['status']=import_vat_status((float)$r['total_due'],$r['paid'],(string)$r['due_date']);foreach(['import_vat_amount'=>'import_vat','total_due'=>'total_due']as$a=>$b)$summary[$b]+=(float)$r[$a];$summary['other_charges']+=(float)$r['duty_amount']+(float)$r['other_charge_amount'];$summary['paid']+=$r['paid'];$summary['outstanding']+=$r['outstanding'];if($r['status']==='overdue')$summary['overdue']+=$r['outstanding'];$ps=db()->prepare('SELECT * FROM accounts_import_vat_payments WHERE import_id=? ORDER BY payment_date,id');$ps->execute([(int)$r['id']]);$r['payments']=$ps->fetchAll();$ds=db()->prepare('SELECT id,payment_id,document_type,original_filename,mime_type,file_size FROM accounts_import_vat_documents WHERE import_id=? AND deleted_at IS NULL ORDER BY id');$ds->execute([(int)$r['id']]);$r['documents']=$ds->fetchAll();}
 foreach($summary as$k=>$v)if(is_float($v))$summary[$k]=round($v,2);unset($r);
 $progress=[];for($i=1;$i<=12;$i++){$key=substr($month,0,4).'-'.str_pad((string)$i,2,'0',STR_PAD_LEFT);$q=db()->prepare('SELECT COUNT(*),COALESCE(SUM(total_due),0) FROM accounts_import_vat_liabilities WHERE deleted_at IS NULL AND import_month=?');$q->execute([$key]);[$count,$due]=$q->fetch(PDO::FETCH_NUM);$progress[]=['month'=>$key,'count'=>(int)$count,'status'=>(int)$count?'in_progress':'no_imports'];}
 return['month'=>$month,'view'=>$view,'summary'=>$summary,'records'=>$rows,'progress'=>$progress];
}
