<?php
declare(strict_types=1);

require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/accounts-input-vat.php';
require_once BASE_PATH.'/shared/accounts-output-vat.php';
require_once BASE_PATH.'/shared/accounts-import-vat.php';

function vat_reconciliation_require_owner(): void { require_login(); if (!accounts_is_owner()) { http_response_code(403); exit('You do not have access to VAT Reconciliation.'); } }
function vat_reconciliation_csrf(): string { if (empty($_SESSION['vat_reconciliation_csrf'])) $_SESSION['vat_reconciliation_csrf']=bin2hex(random_bytes(32)); return (string)$_SESSION['vat_reconciliation_csrf']; }
function vat_reconciliation_verify(string $token): void { if ($token==='' || !hash_equals(vat_reconciliation_csrf(),$token)) throw new RuntimeException('Your session expired. Refresh and try again.'); }
function vat_reconciliation_money(float $value): float { return round($value,2); }

function vat_reconciliation_schema_ready(): void {
    static $ready=false; if ($ready) return;
    $queries=[
        "CREATE TABLE IF NOT EXISTS accounts_vat_return_periods(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_code VARCHAR(30) NOT NULL,label VARCHAR(100) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,due_date DATE NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'provisional',created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_vat_return_period(period_code),KEY idx_vat_return_dates(start_date,end_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_import_vat_credit_eligibility(import_id BIGINT UNSIGNED PRIMARY KEY,eligibility_status VARCHAR(40) NOT NULL DEFAULT 'pending_review',eligible_amount DECIMAL(13,2) NOT NULL DEFAULT 0,evidence_status VARCHAR(40) NOT NULL DEFAULT 'needs_evidence',assigned_period_id BIGINT UNSIGNED NULL,suggested_period_id BIGINT UNSIGNED NULL,decision_reason VARCHAR(500) NULL,decided_by INT NULL,decided_by_name VARCHAR(190) NULL,decided_at DATETIME NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_import_credit_period(assigned_period_id,eligibility_status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_vat_reconciliation_adjustments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id BIGINT UNSIGNED NOT NULL,direction VARCHAR(20) NOT NULL,amount DECIMAL(13,2) NOT NULL,reason VARCHAR(500) NOT NULL,note TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at DATETIME NULL,reversed_by INT NULL,reversal_reason VARCHAR(500) NULL,KEY idx_vat_adjustment(period_id,reversed_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_vat_reconciliation_snapshots(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id BIGINT UNSIGNED NOT NULL,source_hash CHAR(64) NOT NULL,output_vat DECIMAL(13,2) NOT NULL,input_vat DECIMAL(13,2) NOT NULL,import_vat DECIMAL(13,2) NOT NULL,adjustments DECIMAL(13,2) NOT NULL,final_position DECIMAL(13,2) NOT NULL,source_json LONGTEXT NOT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_vat_snapshot_period(period_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_vat_reconciliation_filings(period_id BIGINT UNSIGNED PRIMARY KEY,filed_date DATE NOT NULL,filing_reference VARCHAR(190) NOT NULL,note TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_vat_reconciliation_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id BIGINT UNSIGNED NOT NULL,payment_date DATE NOT NULL,amount DECIMAL(13,2) NOT NULL,reference VARCHAR(190) NULL,payment_method VARCHAR(80) NULL,note TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at DATETIME NULL,reversed_by INT NULL,reversal_reason VARCHAR(500) NULL,KEY idx_vat_return_payment(period_id,reversed_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS accounts_vat_reconciliation_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,period_id BIGINT UNSIGNED NULL,action_key VARCHAR(60) NOT NULL,before_json LONGTEXT NULL,after_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_vat_reconciliation_audit(period_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
    ]; foreach($queries as $query) db()->exec($query); $ready=true;
}

function vat_reconciliation_audit(?int $periodId,string $action,?array $before,?array $after): void { $u=current_user(); db()->prepare('INSERT INTO accounts_vat_reconciliation_audit(period_id,action_key,before_json,after_json,actor_id,actor_name)VALUES(?,?,?,?,?,?)')->execute([$periodId,$action,$before?json_encode($before,JSON_UNESCAPED_SLASHES):null,$after?json_encode($after,JSON_UNESCAPED_SLASHES):null,(int)($u['id']??0),(string)($u['name']??'Owner')]); }
function vat_reconciliation_period_code(string $value): string { if (preg_match('/^(20\d{2})-(0[1-9]|1[0-2])$/',$value,$m)) { $month=(int)$m[2]; $start=$month%2===0?$month-1:$month; return $m[1].'-'.str_pad((string)$start,2,'0',STR_PAD_LEFT); } return date('Y').'-'.str_pad((string)(((int)date('n')%2===0)?(int)date('n')-1:(int)date('n')),2,'0',STR_PAD_LEFT); }
function vat_reconciliation_ensure_period(string $code): array { vat_reconciliation_schema_ready(); $code=vat_reconciliation_period_code($code); $start=$code.'-01'; $end=date('Y-m-t',strtotime($start.' +1 month')); $label=date('M',strtotime($start)).'–'.date('M Y',strtotime($end)); $due=date('Y-m-d',strtotime($end.' +25 days')); $u=current_user(); db()->prepare('INSERT IGNORE INTO accounts_vat_return_periods(period_code,label,start_date,end_date,due_date,created_by,created_by_name)VALUES(?,?,?,?,?,?,?)')->execute([$code,$label,$start,$end,$due,(int)($u['id']??0),(string)($u['name']??'Owner')]); $q=db()->prepare('SELECT * FROM accounts_vat_return_periods WHERE period_code=?');$q->execute([$code]);return(array)$q->fetch(); }
function vat_reconciliation_months(array $period): array { $months=[];$cursor=substr((string)$period['start_date'],0,7);$end=substr((string)$period['end_date'],0,7);while($cursor<=$end){$months[]=$cursor;$cursor=date('Y-m',strtotime($cursor.'-01 +1 month'));}return$months; }

function vat_reconciliation_sources(array $period): array {
    accounts_input_vat_schema_ready(); output_vat_schema_ready(); import_vat_schema_ready();
    $months=vat_reconciliation_months($period);$output=0.0;$input=0.0;$monthRows=[];$outputReady=true;$inputReady=true;
    foreach($months as $month){
        $op=output_vat_period($month);$os=(array)($op['source_summary']??[]);$of=vat_reconciliation_money((float)($os['woo_vat']??0)+(float)($op['adjustment_amount']??0));$oc=!empty($op['completed_at']);if(!$oc)$outputReady=false;$output+=$of;
        $outputInclusive=vat_reconciliation_money((float)($os['gross_sales']??$os['total_sales']??0));$outputExclusive=vat_reconciliation_money((float)($os['net_sales_excl_vat']??($outputInclusive-$of)));
        $iq=db()->prepare("SELECT COALESCE(SUM(amount_incl_vat),0),COALESCE(SUM(vat_amount),0),COALESCE(SUM(amount_excl_vat),0),COUNT(*) FROM accounts_input_vat_purchases WHERE deleted_at IS NULL AND purchase_date>=? AND purchase_date<? AND review_status<>'excluded'");$iq->execute([$month.'-01',date('Y-m-d',strtotime($month.'-01 +1 month'))]);$ir=$iq->fetch(PDO::FETCH_NUM);$iv=(float)$ir[1];$input+=$iv;
        $is=db()->prepare('SELECT capture_complete FROM accounts_input_vat_month_status WHERE month_key=?');$is->execute([$month]);$ic=(bool)$is->fetchColumn();if(!$ic)$inputReady=false;
        $monthRows[]=['month'=>$month,'output_inclusive'=>$outputInclusive,'output_vat'=>$of,'output_exclusive'=>$outputExclusive,'output_complete'=>$oc,'input_inclusive'=>vat_reconciliation_money((float)$ir[0]),'input_vat'=>vat_reconciliation_money($iv),'input_exclusive'=>vat_reconciliation_money((float)$ir[2]),'input_records'=>(int)$ir[3],'input_complete'=>$ic];
    }
    $candidate=db()->prepare("SELECT l.*,COALESCE((SELECT SUM(p.amount) FROM accounts_import_vat_payments p WHERE p.import_id=l.id AND p.reversed_at IS NULL),0) paid,e.eligibility_status,e.eligible_amount,e.evidence_status,e.assigned_period_id,e.decision_reason,e.decided_by_name,e.decided_at,(SELECT COUNT(*) FROM accounts_import_vat_documents d WHERE d.import_id=l.id AND d.deleted_at IS NULL) evidence_count FROM accounts_import_vat_liabilities l LEFT JOIN accounts_import_vat_credit_eligibility e ON e.import_id=l.id WHERE l.deleted_at IS NULL AND (e.assigned_period_id=? OR (e.assigned_period_id IS NULL AND l.import_date>=? AND l.import_date<=?)) ORDER BY l.import_date,l.id");$candidate->execute([(int)$period['id'],$period['start_date'],$period['end_date']]);$imports=$candidate->fetchAll();$eligible=0.0;$pending=0;foreach($imports as &$row){$row['eligibility_status']=$row['eligibility_status']?:'pending_review';$row['evidence_status']=$row['evidence_status']?:(((int)$row['evidence_count']>0||!empty($row['source_statement_id']))?'evidence_present':'needs_evidence');if($row['eligibility_status']==='eligible'&&(int)$row['assigned_period_id']===(int)$period['id'])$eligible+=(float)$row['eligible_amount'];elseif(in_array($row['eligibility_status'],['pending_review','needs_evidence'],true))$pending++;}unset($row);
    $aq=db()->prepare("SELECT COALESCE(SUM(CASE WHEN direction='increase' THEN amount ELSE -amount END),0) FROM accounts_vat_reconciliation_adjustments WHERE period_id=? AND reversed_at IS NULL");$aq->execute([(int)$period['id']]);$adjustments=(float)$aq->fetchColumn();
    return ['months'=>$monthRows,'output_vat'=>vat_reconciliation_money($output),'input_vat'=>vat_reconciliation_money($input),'import_vat'=>vat_reconciliation_money($eligible),'adjustments'=>vat_reconciliation_money($adjustments),'final_position'=>vat_reconciliation_money($output-$input-$eligible+$adjustments),'output_ready'=>$outputReady,'input_ready'=>$inputReady,'import_ready'=>$pending===0,'imports'=>$imports,'pending_imports'=>$pending];
}

function vat_reconciliation_payload(string $code): array {
    $period=vat_reconciliation_ensure_period($code);$sources=vat_reconciliation_sources($period);$canonical=['period'=>$period['period_code'],'months'=>$sources['months'],'import_decisions'=>array_map(function($r){return[$r['id'],$r['eligibility_status'],$r['eligible_amount'],$r['assigned_period_id'],$r['evidence_status']];},$sources['imports']),'adjustments'=>$sources['adjustments']];$hash=hash('sha256',json_encode($canonical,JSON_UNESCAPED_SLASHES));
    $sq=db()->prepare('SELECT * FROM accounts_vat_reconciliation_snapshots WHERE period_id=?');$sq->execute([(int)$period['id']]);$snapshot=$sq->fetch()?:null;$sourceChanged=$snapshot&&!hash_equals((string)$snapshot['source_hash'],$hash);
    $fq=db()->prepare('SELECT * FROM accounts_vat_reconciliation_filings WHERE period_id=?');$fq->execute([(int)$period['id']]);$filing=$fq->fetch()?:null;$pq=db()->prepare('SELECT * FROM accounts_vat_reconciliation_payments WHERE period_id=? AND reversed_at IS NULL ORDER BY payment_date,id');$pq->execute([(int)$period['id']]);$payments=$pq->fetchAll();$paid=0.0;foreach($payments as$p)$paid+=(float)$p['amount'];
    $ready=$sources['output_ready']&&$sources['input_ready']&&$sources['import_ready'];$status=$filing?'filed':($snapshot?'ready_to_file':($ready?'review_complete':'provisional'));
    return ['period'=>$period,'sources'=>$sources,'source_hash'=>$hash,'source_changed'=>(bool)$sourceChanged,'snapshot'=>$snapshot,'filing'=>$filing,'payments'=>$payments,'paid'=>vat_reconciliation_money($paid),'balance'=>vat_reconciliation_money(max(0,(float)($snapshot['final_position']??$sources['final_position'])-$paid)),'ready'=>$ready,'status'=>$status,'csrf'=>vat_reconciliation_csrf()];
}
