<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/accounts-import-vat.php';

function paye_require_access():void{require_login();if(!accounts_can('paye.view')){http_response_code(403);exit('You do not have access to PAYE.');}}
function paye_csrf():string{if(empty($_SESSION['paye_csrf']))$_SESSION['paye_csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['paye_csrf'];}
function paye_verify(string$token):void{if($token===''||!hash_equals(paye_csrf(),$token))throw new RuntimeException('Your session expired. Refresh and try again.');}
function paye_schema_ready():void{static$ready=false;if($ready)return;foreach([
"CREATE TABLE IF NOT EXISTS accounts_paye_statements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,sha256 CHAR(64) NOT NULL,statement_period CHAR(7) NULL,status VARCHAR(40) NOT NULL DEFAULT 'processed',parse_message TEXT NULL,rows_detected INT NOT NULL DEFAULT 0,uploaded_by INT NOT NULL,uploaded_by_name VARCHAR(190) NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_statement_hash(sha256),KEY idx_paye_statement_period(statement_period,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_paye_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NOT NULL,source_row_number INT NOT NULL,tax_year VARCHAR(20) NOT NULL,tax_period VARCHAR(40) NOT NULL,accounting_period CHAR(7) NOT NULL,due_date DATE NOT NULL,action_date DATE NULL,reference VARCHAR(190) NULL,transaction_type VARCHAR(190) NOT NULL,classification VARCHAR(40) NOT NULL,amount DECIMAL(13,2) NOT NULL,source_hash CHAR(64) NOT NULL,source_json LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_source_hash(source_hash),KEY idx_paye_period(accounting_period,classification)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_paye_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NULL,action_key VARCHAR(60) NOT NULL,details_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_paye_audit(statement_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
]as$q){db()->exec($q);}$ready=true;}
function paye_due_date(string$month,?string$source=null):string{if($source&&preg_match('/^20\d{2}-\d{2}-\d{2}$/',$source))return$source;return date('Y-m-d',strtotime($month.'-01 +1 month +19 days'));}
function paye_statement_history():array{$q=db()->query('SELECT id,original_filename,mime_type,file_size,statement_period,status,parse_message,rows_detected,uploaded_by_name,uploaded_at FROM accounts_paye_statements ORDER BY id DESC LIMIT 100');return$q->fetchAll();}
function paye_payload(string$month):array{paye_schema_ready();$month=import_vat_month($month);$q=db()->prepare("SELECT accounting_period,MIN(due_date) due_date,GROUP_CONCAT(DISTINCT NULLIF(reference,'') ORDER BY reference SEPARATOR ', ') reference,SUM(CASE WHEN classification IN('assessment','revision') THEN amount ELSE 0 END) assessed,SUM(CASE WHEN classification='payment' THEN amount ELSE 0 END) paid,SUM(CASE WHEN classification='ignored_penalty' THEN amount ELSE 0 END) penalties,SUM(CASE WHEN classification='ignored_interest' THEN amount ELSE 0 END) interest FROM accounts_paye_rows WHERE accounting_period=? GROUP BY accounting_period");$q->execute([$month]);$rows=$q->fetchAll();$summary=['periods'=>0,'assessed'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'overdue'=>0.0];foreach($rows as&$r){$r['assessed']=round((float)$r['assessed'],2);$r['paid']=round((float)$r['paid'],2);$r['outstanding']=max(0,round($r['assessed']-$r['paid'],2));$r['status']=$r['outstanding']<=.005?'paid':($r['due_date']<date('Y-m-d')?'overdue':($r['paid']>0?'partially_paid':'unpaid'));$summary['periods']++;$summary['assessed']+=$r['assessed'];$summary['paid']+=$r['paid'];$summary['outstanding']+=$r['outstanding'];if($r['status']==='overdue')$summary['overdue']+=$r['outstanding'];}unset($r);foreach(['assessed','paid','outstanding','overdue']as$k)$summary[$k]=round($summary[$k],2);$progress=[];for($i=1;$i<=12;$i++){$key=substr($month,0,4).'-'.str_pad((string)$i,2,'0',STR_PAD_LEFT);$c=db()->prepare('SELECT COUNT(*) FROM accounts_paye_rows WHERE accounting_period=?');$c->execute([$key]);$progress[]=['month'=>$key,'count'=>(int)$c->fetchColumn()];}return['month'=>$month,'summary'=>$summary,'records'=>$rows,'progress'=>$progress,'history'=>paye_statement_history(),'csrf'=>paye_csrf()];}
function paye_audit(?int$id,string$action,array$details):void{$u=current_user();db()->prepare('INSERT INTO accounts_paye_audit(statement_id,action_key,details_json,actor_id,actor_name)VALUES(?,?,?,?,?)')->execute([$id,$action,json_encode($details,JSON_UNESCAPED_SLASHES),(int)$u['id'],(string)$u['name']]);}
