<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/accounts-import-vat.php';

function paye_require_access():void{require_login();if(!accounts_can('paye.view')){http_response_code(403);exit('You do not have access to PAYE.');}}
function paye_csrf():string{if(empty($_SESSION['paye_csrf']))$_SESSION['paye_csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['paye_csrf'];}
function paye_verify(string$token):void{if($token===''||!hash_equals(paye_csrf(),$token))throw new RuntimeException('Your session expired. Refresh and try again.');}
function paye_schema_ready():void{static$ready=false;if($ready)return;foreach([
"CREATE TABLE IF NOT EXISTS accounts_paye_statements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,sha256 CHAR(64) NOT NULL,statement_period CHAR(7) NULL,status VARCHAR(40) NOT NULL DEFAULT 'processed',parse_message TEXT NULL,rows_detected INT NOT NULL DEFAULT 0,uploaded_by INT NOT NULL,uploaded_by_name VARCHAR(190) NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_statement_hash(sha256),KEY idx_paye_statement_period(statement_period,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_paye_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NOT NULL,source_row_number INT NOT NULL,tax_year VARCHAR(20) NOT NULL,tax_period VARCHAR(40) NOT NULL,accounting_period CHAR(7) NOT NULL,due_date DATE NOT NULL,action_date DATE NULL,reference VARCHAR(190) NULL,transaction_type VARCHAR(190) NOT NULL,classification VARCHAR(40) NOT NULL,amount DECIMAL(13,2) NOT NULL,source_hash CHAR(64) NOT NULL,source_json LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_source_hash(source_hash),KEY idx_paye_period(accounting_period,classification)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_paye_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NULL,action_key VARCHAR(60) NOT NULL,details_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_paye_audit(statement_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
]as$q){db()->exec($q);}paye_reclassify_existing_rows();$ready=true;}
function paye_classification(string$transactionType,string$current='needs_review'):string{if($current!=='needs_review')return$current;$value=trim($transactionType);if($value===''||preg_match('/\b(reversal|reversed|dishonou?red|rejected)\b/i',$value))return$current;if(preg_match('/\b(payment|receipt|credit allocation|payment allocation|electronic payment|EFT)\b/i',$value))return'payment';if(preg_match('/\b(assessment revision|revised assessment|revision)\b/i',$value))return'revision';if(preg_match('/\b(assessment|return assessed|original return)\b/i',$value))return'assessment';return$current;}
function paye_reclassify_existing_rows():void{try{$q=db()->query("SELECT id,transaction_type,classification FROM accounts_paye_rows WHERE classification='needs_review'");$update=db()->prepare('UPDATE accounts_paye_rows SET classification=? WHERE id=? AND classification=\'needs_review\'');foreach($q->fetchAll()as$row){$classification=paye_classification((string)$row['transaction_type'],(string)$row['classification']);if($classification!=='needs_review')$update->execute([$classification,(int)$row['id']]);}}catch(Throwable$e){error_log('PAYE row reclassification failed: '.$e->getMessage());}}
function paye_due_date(string$month,?string$source=null):string{if($source&&preg_match('/^20\d{2}-\d{2}-\d{2}$/',$source))return$source;return date('Y-m-d',strtotime($month.'-01 +1 month +19 days'));}
function paye_statement_history():array{$q=db()->query('SELECT id,original_filename,mime_type,file_size,statement_period,status,parse_message,rows_detected,uploaded_by_name,uploaded_at FROM accounts_paye_statements ORDER BY id DESC LIMIT 100');return$q->fetchAll();}
function paye_payload(string$month):array{paye_schema_ready();$month=import_vat_month($month);$q=db()->prepare("SELECT accounting_period,MIN(due_date) due_date,GROUP_CONCAT(DISTINCT NULLIF(reference,'') ORDER BY reference SEPARATOR ', ') reference,MIN(CASE WHEN classification IN('assessment','revision') THEN action_date END) submitted_date,MAX(CASE WHEN classification='payment' THEN action_date END) payment_date,SUM(CASE WHEN classification IN('assessment','revision') THEN amount ELSE 0 END) assessed,SUM(CASE WHEN classification='payment' THEN amount ELSE 0 END) paid,SUM(CASE WHEN classification='ignored_penalty' THEN amount ELSE 0 END) penalties,SUM(CASE WHEN classification='ignored_interest' THEN amount ELSE 0 END) interest,SUM(CASE WHEN classification='needs_review' THEN 1 ELSE 0 END) review_count FROM accounts_paye_rows WHERE accounting_period=? GROUP BY accounting_period");$q->execute([$month]);$rows=$q->fetchAll();$summary=['periods'=>0,'submitted'=>0,'assessed'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'overdue'=>0.0];foreach($rows as&$r){$r['assessed']=round((float)$r['assessed'],2);$r['paid']=round((float)$r['paid'],2);$r['review_count']=(int)$r['review_count'];$r['return_status']=$r['assessed']>0?'submitted':'not_detected';if($r['return_status']==='submitted')$summary['submitted']++;$r['outstanding']=max(0,round($r['assessed']-$r['paid'],2));$r['payment_status']=$r['outstanding']<=.005&&$r['assessed']>0?'paid':($r['paid']>0?'partially_paid':'unpaid');$r['status']=$r['review_count']>0&&$r['assessed']<=0?'review_required':($r['payment_status']==='paid'?'paid':($r['due_date']<date('Y-m-d')?'overdue':$r['payment_status']));$summary['periods']++;$summary['assessed']+=$r['assessed'];$summary['paid']+=$r['paid'];$summary['outstanding']+=$r['outstanding'];if($r['status']==='overdue')$summary['overdue']+=$r['outstanding'];}unset($r);foreach(['assessed','paid','outstanding','overdue']as$k)$summary[$k]=round($summary[$k],2);$progress=[];for($i=1;$i<=12;$i++){$key=substr($month,0,4).'-'.str_pad((string)$i,2,'0',STR_PAD_LEFT);$c=db()->prepare("SELECT COUNT(*) row_count,SUM(CASE WHEN classification IN('assessment','revision') THEN 1 ELSE 0 END) submitted FROM accounts_paye_rows WHERE accounting_period=?");$c->execute([$key]);$p=$c->fetch();$progress[]=['month'=>$key,'count'=>(int)$p['row_count'],'submitted'=>(int)$p['submitted']>0];}return['month'=>$month,'summary'=>$summary,'records'=>$rows,'progress'=>$progress,'history'=>paye_statement_history(),'csrf'=>paye_csrf()];}
function paye_audit(?int$id,string$action,array$details):void{$u=current_user();db()->prepare('INSERT INTO accounts_paye_audit(statement_id,action_key,details_json,actor_id,actor_name)VALUES(?,?,?,?,?)')->execute([$id,$action,json_encode($details,JSON_UNESCAPED_SLASHES),(int)$u['id'],(string)$u['name']]);}
