<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/accounts-import-vat.php';

function paye_require_access():void{require_login();if(!accounts_can('paye.view')){http_response_code(403);exit('You do not have access to PAYE.');}}
function paye_csrf():string{if(empty($_SESSION['paye_csrf']))$_SESSION['paye_csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['paye_csrf'];}
function paye_verify(string$token):void{if($token===''||!hash_equals(paye_csrf(),$token))throw new RuntimeException('Your session expired. Refresh and try again.');}

function paye_schema_ready():void{
 static$ready=false;if($ready)return;
 foreach([
  "CREATE TABLE IF NOT EXISTS accounts_paye_statements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,sha256 CHAR(64) NOT NULL,statement_period CHAR(7) NULL,status VARCHAR(40) NOT NULL DEFAULT 'processed',parse_message TEXT NULL,rows_detected INT NOT NULL DEFAULT 0,uploaded_by INT NOT NULL,uploaded_by_name VARCHAR(190) NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_statement_hash(sha256),KEY idx_paye_statement_period(statement_period,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
  "CREATE TABLE IF NOT EXISTS accounts_paye_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NOT NULL,source_row_number INT NOT NULL,tax_year VARCHAR(20) NOT NULL,tax_period VARCHAR(40) NOT NULL,accounting_period CHAR(7) NOT NULL,due_date DATE NOT NULL,action_date DATE NULL,reference VARCHAR(190) NULL,transaction_type VARCHAR(190) NOT NULL,classification VARCHAR(40) NOT NULL,amount DECIMAL(13,2) NOT NULL,source_hash CHAR(64) NOT NULL,source_json LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_source_hash(source_hash),KEY idx_paye_period(accounting_period,classification)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
  "CREATE TABLE IF NOT EXISTS accounts_paye_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NULL,action_key VARCHAR(60) NOT NULL,details_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_paye_audit(statement_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
  "CREATE TABLE IF NOT EXISTS accounts_paye_periods(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,accounting_period CHAR(7) NOT NULL,tax_year SMALLINT UNSIGNED NOT NULL,tax_period TINYINT UNSIGNED NOT NULL,due_date DATE NOT NULL,return_status VARCHAR(32) NOT NULL DEFAULT 'pending_submission',return_id VARCHAR(80) NULL,return_version VARCHAR(20) NULL,eft_reference VARCHAR(80) NULL,submitted_at DATETIME NULL,submitted_by INT NULL,submitted_by_name VARCHAR(190) NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_paye_accounting_period(accounting_period),KEY idx_paye_return_status(return_status,due_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
 ]as$sql)db()->exec($sql);
 paye_seed_return_register();paye_reclassify_existing_rows();$ready=true;
}

function paye_tax_cycle(string$month):array{$year=(int)substr($month,0,4);$calendarMonth=(int)substr($month,5,2);return$calendarMonth>=3?['tax_year'=>$year+1,'tax_period'=>$calendarMonth-2]:['tax_year'=>$year,'tax_period'=>$calendarMonth+10];}
function paye_monthly_estimate():float{return 3577.45;}
function paye_due_date(string$month,?string$source=null):string{if($source&&preg_match('/^20\d{2}-\d{2}-\d{2}$/',$source))return$source;$due=new DateTimeImmutable($month.'-20 +1 month');$weekday=(int)$due->format('N');if($weekday===6)$due=$due->modify('+2 days');elseif($weekday===7)$due=$due->modify('+1 day');return$due->format('Y-m-d');}
function paye_ensure_period(string$month):void{$cycle=paye_tax_cycle($month);db()->prepare('INSERT IGNORE INTO accounts_paye_periods(accounting_period,tax_year,tax_period,due_date)VALUES(?,?,?,?)')->execute([$month,$cycle['tax_year'],$cycle['tax_period'],paye_due_date($month)]);}

function paye_seed_return_register():void{
 $rows=[
  ['2025-11',2026,9,'2025-12-22','assessed','29377641','2','1021378034014202511'],['2025-12',2026,10,'2026-01-20','assessed','29382540','2','1021378034014202512'],
  ['2026-01',2026,11,'2026-02-20','assessed','29382549','2','1021378034014202601'],['2026-02',2026,12,'2026-03-20','assessed','29382856','2','1021378034014202602'],
  ['2026-03',2027,1,'2026-04-20','assessed','29382620','1','1021378034014202603'],['2026-04',2027,2,'2026-05-20','assessed','29495070','1','1021378034014202604'],
  ['2026-05',2027,3,'2026-06-22','pending_submission',null,null,'1021378034014202605'],['2026-06',2027,4,'2026-07-20','pending_submission',null,null,'1021378034014202606'],
  ['2026-07',2027,5,'2026-08-20','pending_submission',null,null,'1021378034014202607'],['2026-08',2027,6,'2026-09-21','pending_submission',null,null,'1021378034014202608']
 ];
 $insert=db()->prepare('INSERT IGNORE INTO accounts_paye_periods(accounting_period,tax_year,tax_period,due_date,return_status,return_id,return_version,eft_reference)VALUES(?,?,?,?,?,?,?,?)');foreach($rows as$row)$insert->execute($row);
}

function paye_classification(string$type,string$current='needs_review'):string{if($current!=='needs_review')return$current;$value=trim($type);if($value===''||preg_match('/\b(reversal|reversed|dishonou?red|rejected)\b/i',$value))return$current;if(preg_match('/\b(payment|receipt|credit allocation|payment allocation|electronic payment|EFT)\b/i',$value))return'payment';if(preg_match('/\b(assessment revision|revised assessment|revision)\b/i',$value))return'revision';if(preg_match('/\b(assessment|return assessed|original return)\b/i',$value))return'assessment';return$current;}
function paye_reclassify_existing_rows():void{try{$query=db()->query("SELECT id,transaction_type,classification FROM accounts_paye_rows WHERE classification='needs_review'");$update=db()->prepare("UPDATE accounts_paye_rows SET classification=? WHERE id=? AND classification='needs_review'");foreach($query->fetchAll()as$row){$classification=paye_classification((string)$row['transaction_type'],(string)$row['classification']);if($classification!=='needs_review')$update->execute([$classification,(int)$row['id']]);}}catch(Throwable$error){error_log('PAYE row reclassification failed: '.$error->getMessage());}}
function paye_statement_history():array{return db()->query('SELECT id,original_filename,mime_type,file_size,statement_period,status,parse_message,rows_detected,uploaded_by_name,uploaded_at FROM accounts_paye_statements ORDER BY id DESC LIMIT 100')->fetchAll();}

function paye_payload(string$month):array{
 paye_schema_ready();$month=import_vat_month($month);paye_ensure_period($month);
 $query=db()->prepare("SELECT p.accounting_period,p.tax_year,p.tax_period,p.due_date,p.return_status register_status,p.return_id,p.return_version,p.eft_reference,p.submitted_at,p.submitted_by_name,MIN(CASE WHEN r.classification IN('assessment','revision') THEN r.action_date END) assessed_date,MAX(CASE WHEN r.classification='payment' THEN r.action_date END) payment_date,SUM(CASE WHEN r.classification IN('assessment','revision') THEN r.amount ELSE 0 END) assessed,SUM(CASE WHEN r.classification='payment' THEN r.amount ELSE 0 END) paid,SUM(CASE WHEN r.classification='ignored_penalty' THEN r.amount ELSE 0 END) penalties,SUM(CASE WHEN r.classification='ignored_interest' THEN r.amount ELSE 0 END) interest,SUM(CASE WHEN r.classification='needs_review' THEN 1 ELSE 0 END) review_count FROM accounts_paye_periods p LEFT JOIN accounts_paye_rows r ON r.accounting_period=p.accounting_period WHERE p.accounting_period=? GROUP BY p.id");
 $query->execute([$month]);$row=$query->fetch();$rows=[];$summary=['periods'=>1,'submitted'=>0,'assessed'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'estimated_outstanding'=>0.0,'monthly_estimate'=>paye_monthly_estimate(),'overdue'=>0.0];
 if($row){$row['assessed']=round((float)$row['assessed'],2);$row['paid']=round((float)$row['paid'],2);$row['review_count']=(int)$row['review_count'];$hasAmount=$row['assessed']>0;$hasAssessment=$hasAmount||$row['register_status']==='assessed';$row['return_status']=$hasAssessment?'assessed':($row['register_status']==='submitted'?'submitted':'pending_submission');$row['submitted_date']=$row['submitted_at']?:$row['assessed_date'];$summary['submitted']=$row['return_status']==='pending_submission'?0:1;$row['outstanding']=$hasAmount?max(0,round($row['assessed']-$row['paid'],2)):0.0;$row['estimated_outstanding']=$hasAmount?0.0:paye_monthly_estimate();$row['payment_status']=!$hasAssessment?'not_payable_yet':(!$hasAmount?'assessment_amount_pending':($row['paid']+0.005>=$row['assessed']?'paid':($row['paid']>0?'partially_paid':'awaiting_payment')));$row['status']=$row['return_status']==='pending_submission'?'pending_submission':($row['return_status']==='submitted'?'awaiting_assessment':(!$hasAmount?'assessment_amount_pending':($row['payment_status']==='paid'?'paid':($row['due_date']<date('Y-m-d')?'overdue':'awaiting_payment'))));$summary['assessed']=$row['assessed'];$summary['paid']=$row['paid'];$summary['outstanding']=$row['outstanding'];$summary['estimated_outstanding']=$row['estimated_outstanding'];$summary['overdue']=$row['status']==='overdue'?$row['outstanding']:0.0;$rows[]=$row;}
 $progress=[];for($i=1;$i<=12;$i++){$key=substr($month,0,4).'-'.str_pad((string)$i,2,'0',STR_PAD_LEFT);paye_ensure_period($key);$status=db()->prepare("SELECT p.return_status,EXISTS(SELECT 1 FROM accounts_paye_rows r WHERE r.accounting_period=p.accounting_period AND r.classification IN('assessment','revision')) assessed,EXISTS(SELECT 1 FROM accounts_paye_rows r WHERE r.accounting_period=p.accounting_period AND r.classification='payment') paid FROM accounts_paye_periods p WHERE p.accounting_period=?");$status->execute([$key]);$period=$status->fetch();$progress[]=['month'=>$key,'status'=>(int)$period['paid']?'paid':((int)$period['assessed']?'assessed':$period['return_status'])];}
 return['month'=>$month,'summary'=>$summary,'records'=>$rows,'progress'=>$progress,'history'=>paye_statement_history(),'csrf'=>paye_csrf()];
}

function paye_save_return(array$input):array{
 $month=import_vat_month((string)($input['accounting_period']??''));$status=(string)($input['return_status']??'pending_submission');if(!in_array($status,['pending_submission','submitted','assessed'],true))throw new RuntimeException('Choose a valid PAYE return status.');paye_ensure_period($month);$user=current_user();$submitted=$status==='pending_submission'?null:date('Y-m-d H:i:s');$returnId=trim((string)($input['return_id']??''));$eft=trim((string)($input['eft_reference']??''));$due=import_vat_normal_date((string)($input['due_date']??''))?:paye_due_date($month);db()->prepare('UPDATE accounts_paye_periods SET return_status=?,return_id=?,eft_reference=?,due_date=?,submitted_at=?,submitted_by=?,submitted_by_name=? WHERE accounting_period=?')->execute([$status,$returnId?:null,$eft?:null,$due,$submitted,$submitted?(int)$user['id']:null,$submitted?(string)$user['name']:null,$month]);paye_audit(null,'return_status_updated',['period'=>$month,'status'=>$status,'return_id'=>$returnId,'eft_reference'=>$eft,'due_date'=>$due]);return paye_payload($month);
}
function paye_audit(?int$id,string$action,array$details):void{$user=current_user();db()->prepare('INSERT INTO accounts_paye_audit(statement_id,action_key,details_json,actor_id,actor_name)VALUES(?,?,?,?,?)')->execute([$id,$action,json_encode($details,JSON_UNESCAPED_SLASHES),(int)$user['id'],(string)$user['name']]);}
