<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/accounts-input-vat.php';
require_once BASE_PATH.'/shared/accounts-output-vat.php';
require_once BASE_PATH.'/shared/accounts-vat-reconciliation.php';

function sage_require_owner(): void { require_login(); if(!accounts_is_owner()){http_response_code(403);exit('You do not have access to Sage Posting & Reconciliation.');} }
function sage_month(string $v): string { return preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$v)?$v:date('Y-m'); }
function sage_money($v): float { return round((float)$v,2); }
function sage_schema_ready(): bool { static $ready=false;if($ready)return true;$sql=[
"CREATE TABLE IF NOT EXISTS accounts_sage_settings(id TINYINT PRIMARY KEY,customer_name VARCHAR(190) NOT NULL DEFAULT 'Hambelela Sales',posting_mode VARCHAR(30) NOT NULL DEFAULT 'summary_monthly',bank_statement_method VARCHAR(40) NOT NULL DEFAULT 'manual_sage_upload',account_mapping_json LONGTEXT NULL,updated_by INT NULL,updated_by_name VARCHAR(190) NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_sage_periods(month_key CHAR(7) PRIMARY KEY,status VARCHAR(30) NOT NULL DEFAULT 'not_started',prepared_at DATETIME NULL,prepared_by INT NULL,prepared_by_name VARCHAR(190) NULL,sage_customer VARCHAR(190) NULL,sage_document_number VARCHAR(190) NULL,sage_posting_date DATE NULL,sage_total DECIMAL(13,2) NULL,sage_vat DECIMAL(13,2) NULL,sage_note TEXT NULL,explained_bank_difference DECIMAL(13,2) NOT NULL DEFAULT 0,bank_difference_note TEXT NULL,input_vat_checked TINYINT(1) NOT NULL DEFAULT 0,bank_reviewed TINYINT(1) NOT NULL DEFAULT 0,sage_vat_control DECIMAL(13,2) NULL,posted_at DATETIME NULL,reconciled_at DATETIME NULL,reconciled_by INT NULL,reconciled_by_name VARCHAR(190) NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_sage_receipts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,month_key CHAR(7) NOT NULL,receipt_date DATE NOT NULL,amount DECIMAL(13,2) NOT NULL,payment_method VARCHAR(80) NOT NULL,bank_account VARCHAR(190) NULL,sage_reference VARCHAR(190) NULL,allocated_to_sales TINYINT(1) NOT NULL DEFAULT 1,timing_difference TINYINT(1) NOT NULL DEFAULT 0,notes TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at DATETIME NULL,KEY idx_sage_receipt_month(month_key,reversed_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_sage_purchase_status(purchase_id BIGINT UNSIGNED PRIMARY KEY,sage_account VARCHAR(190) NULL,vat_code VARCHAR(80) NULL,sage_status VARCHAR(30) NOT NULL DEFAULT 'not_posted',sage_reference VARCHAR(190) NULL,possible_asset TINYINT(1) NOT NULL DEFAULT 0,note TEXT NULL,updated_by INT NOT NULL,updated_by_name VARCHAR(190) NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS accounts_sage_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,month_key CHAR(7) NOT NULL,action_key VARCHAR(60) NOT NULL,before_json LONGTEXT NULL,after_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_sage_audit(month_key,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" ];foreach($sql as$q)db()->exec($q);db()->exec("INSERT IGNORE INTO accounts_sage_settings(id,customer_name,posting_mode,bank_statement_method,account_mapping_json)VALUES(1,'Hambelela Sales','summary_monthly','manual_sage_upload','{}')");$ready=true;return true; }
function sage_csrf(): string { if(empty($_SESSION['sage_csrf']))$_SESSION['sage_csrf']=bin2hex(random_bytes(32));return (string)$_SESSION['sage_csrf']; }
function sage_verify(string $v): void { if($v===''||!hash_equals(sage_csrf(),$v))throw new RuntimeException('Your session expired. Refresh and try again.'); }
function sage_audit(string $month,string $action,$before,$after): void {$u=current_user();db()->prepare('INSERT INTO accounts_sage_audit(month_key,action_key,before_json,after_json,actor_id,actor_name)VALUES(?,?,?,?,?,?)')->execute([$month,$action,$before===null?null:json_encode($before,JSON_UNESCAPED_SLASHES),$after===null?null:json_encode($after,JSON_UNESCAPED_SLASHES),(int)$u['id'],(string)$u['name']]);}
function sage_settings(): array {$r=db()->query('SELECT * FROM accounts_sage_settings WHERE id=1')->fetch()?:[];$r['account_mapping']=$r['account_mapping_json']?json_decode((string)$r['account_mapping_json'],true):[];return $r;}
function sage_period(string $month): array {$q=db()->prepare('SELECT * FROM accounts_sage_periods WHERE month_key=?');$q->execute([$month]);return $q->fetch()?:['month_key'=>$month,'status'=>'not_started','sage_total'=>null,'sage_vat'=>null,'sage_vat_control'=>null,'explained_bank_difference'=>0,'input_vat_checked'=>0,'bank_reviewed'=>0];}
function sage_expected_receipts(string $month): array {$result=[];try{$start=$month.'-01';$end=date('Y-m-d',strtotime($start.' +1 month'));$q=db()->prepare("SELECT COALESCE(NULLIF(TRIM(p.payment_method),''),'Unspecified') method,SUM(p.amount_cents)/100 amount FROM order_payment_allocations p JOIN ops_orders o ON o.id=p.order_id WHERE p.amount_cents>0 AND DATE(COALESCE(o.payment_updated_at,p.updated_at,o.updated_at,o.created_at))>=? AND DATE(COALESCE(o.payment_updated_at,p.updated_at,o.updated_at,o.created_at))<? GROUP BY COALESCE(NULLIF(TRIM(p.payment_method),''),'Unspecified') ORDER BY amount DESC");$q->execute([$start,$end]);foreach($q->fetchAll() as$r)$result[]=['method'=>(string)$r['method'],'amount'=>sage_money($r['amount'])];}catch(Throwable $e){error_log('Sage expected receipt summary unavailable: '.$e->getMessage());}return $result;}
function sage_possible_asset(string $text): bool {return (bool)preg_match('/\b(machine|machinery|equipment|computer|laptop|printer|furniture|vehicle|freezer|fridge|oven)\b/i',$text);}
function sage_payload(string $month): array {sage_schema_ready();$month=sage_month($month);$output=output_vat_period($month);$s=(array)($output['source_summary']??[]);$period=sage_period($month);$settings=sage_settings();$portalTotal=sage_money($s['gross_sales']??0);$reportedVat=sage_money($s['woo_vat']??0);$outputAdjustment=sage_money($output['adjustment_amount']??0);$finalVat=sage_money($reportedVat+$outputAdjustment);$standardSource=sage_money($s['standard_sales']??($s['total_sales']??0));$shipping=sage_money($s['shipping']??0);$shippingVat=sage_money($s['shipping_tax']??0);$shippingGross=sage_money($shipping+$shippingVat);$standardIncl=sage_money(max(0,$standardSource-$shippingGross));$standardVat=sage_money(max(0,$reportedVat-$shippingVat));$pack=['customer'=>(string)($period['sage_customer']??$settings['customer_name']??'Hambelela Sales'),'posting_date'=>date('Y-m-t',strtotime($month.'-01')),'reference'=>'HO-SALES-'.$month,'description'=>'Hambelela Website & Store Sales — '.date('F Y',strtotime($month.'-01')),'standard_incl'=>$standardIncl,'standard_excl'=>sage_money($standardIncl-$standardVat),'standard_vat'=>$standardVat,'reported_vat'=>$reportedVat,'output_adjustment'=>$outputAdjustment,'final_output_vat'=>$finalVat,'zero_rated'=>sage_money($s['zero_rated_sales']??0),'exempt'=>sage_money($s['exempt_sales']??0),'shipping_gross'=>$shippingGross,'shipping_vat'=>$shippingVat,'shipping_net'=>$shipping,'discounts'=>sage_money($s['discounts']??0),'refunds'=>sage_money($s['refunds']??0),'total_incl'=>$portalTotal];
$expected=sage_expected_receipts($month);$expectedTotal=sage_money(array_sum(array_column($expected,'amount')));$q=db()->prepare('SELECT * FROM accounts_sage_receipts WHERE month_key=? AND reversed_at IS NULL ORDER BY receipt_date,id');$q->execute([$month]);$receipts=$q->fetchAll();$bankTotal=sage_money(array_sum(array_map(function($r){return(float)$r['amount'];},$receipts)));$explained=sage_money($period['explained_bank_difference']??0);$bankDifference=sage_money($expectedTotal-$bankTotal-$explained);
$start=$month.'-01';$end=date('Y-m-d',strtotime($start.' +1 month'));$q=db()->prepare("SELECT p.id,p.purchase_date,p.supplier,p.description,p.invoice_reference,p.amount_incl_vat,p.vat_amount,p.amount_excl_vat,p.vat_treatment,COALESCE(s.sage_account,'') sage_account,COALESCE(s.vat_code,'') vat_code,COALESCE(s.sage_status,'not_posted') sage_status,COALESCE(s.sage_reference,'') sage_reference,COALESCE(s.possible_asset,0) possible_asset,COALESCE(s.note,'') sage_note FROM accounts_input_vat_purchases p LEFT JOIN accounts_sage_purchase_status s ON s.purchase_id=p.id WHERE p.deleted_at IS NULL AND p.review_status<>'excluded' AND p.purchase_date>=? AND p.purchase_date<? ORDER BY p.purchase_date,p.id");$q->execute([$start,$end]);$purchases=$q->fetchAll();foreach($purchases as&$p)if(!(int)$p['possible_asset']&&sage_possible_asset((string)$p['description']))$p['possible_asset']=1;unset($p);$inputVat=sage_money(array_sum(array_map(function($r){return(float)$r['vat_amount'];},$purchases)));
$sageTotal=$period['sage_total']===null?null:sage_money($period['sage_total']);$sageVat=$period['sage_vat']===null?null:sage_money($period['sage_vat']);$salesDiff=$sageTotal===null?null:sage_money($portalTotal-$sageTotal);$vatDiff=$sageVat===null?null:sage_money($finalVat-$sageVat);$maps=(array)($settings['account_mapping']??[]);$mappingReady=trim((string)($maps['standard_account']??''))!==''&&trim((string)($maps['standard_vat_code']??''))!=='';$vatPeriod=vat_reconciliation_period_code($month);$vatPayload=vat_reconciliation_payload($vatPeriod);$portalVatControl=sage_money($vatPayload['sources']['final_position']??0);$sageVatControl=$period['sage_vat_control']===null?null:sage_money($period['sage_vat_control']);$vatControlDiff=$sageVatControl===null?null:sage_money($portalVatControl-$sageVatControl);$vatControlMatch=$vatControlDiff!==null&&abs($vatControlDiff)<=0.02;$salesMatch=$salesDiff!==null&&abs($salesDiff)<=0.02&&$vatDiff!==null&&abs($vatDiff)<=0.02;$canReconcile=$salesMatch&&$vatControlMatch&&(bool)$period['input_vat_checked']&&(bool)$period['bank_reviewed']&&abs($bankDifference)<=0.02;$status=(string)$period['status'];if($sageTotal!==null&&!$salesMatch)$status='needs_review';
return ['month'=>$month,'settings'=>$settings,'period'=>$period,'posting_pack'=>$pack,'portal_sales'=>$portalTotal,'sage_posted'=>$sageTotal,'sales_difference'=>$salesDiff,'vat_difference'=>$vatDiff,'sales_match'=>$salesMatch,'mapping_ready'=>$mappingReady,'expected_receipts'=>$expected,'expected_receipts_total'=>$expectedTotal,'receipts'=>$receipts,'bank_receipts_total'=>$bankTotal,'explained_difference'=>$explained,'bank_difference'=>$bankDifference,'purchases'=>$purchases,'input_vat'=>$inputVat,'portal_vat_period'=>$vatPeriod,'portal_vat_control'=>$portalVatControl,'vat_control_difference'=>$vatControlDiff,'vat_control_match'=>$vatControlMatch,'can_reconcile'=>$canReconcile,'display_status'=>$status,'double_count_warning'=>'Bank receipts settle the Hambelela Sales posting or an approved clearing account. Never post them again as sales revenue.'];}
