<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/accounts-input-vat.php';
require_once BASE_PATH.'/shared/accounts-import-vat-parser.php';

function import_vat_require_owner(): void { require_login(); if(!accounts_can('import_vat.view')){http_response_code(403);exit('You do not have access to Import VAT.');} }
function import_vat_schema_ready(): void {
 static $ready=false;if($ready)return;
 $queries=[
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_liabilities(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_date DATE NOT NULL,import_month CHAR(7) NOT NULL,supplier VARCHAR(190) NOT NULL,description TEXT NOT NULL,reference VARCHAR(190) NOT NULL,source_system VARCHAR(80) NULL,country_origin VARCHAR(100) NULL,currency VARCHAR(20) NULL,supplier_invoice_value DECIMAL(13,2) NULL,customs_value DECIMAL(13,2) NULL,payment_arrangement VARCHAR(40) NOT NULL,import_vat_amount DECIMAL(13,2) NOT NULL,duty_amount DECIMAL(13,2) NOT NULL DEFAULT 0,other_charge_amount DECIMAL(13,2) NOT NULL DEFAULT 0,total_due DECIMAL(13,2) NOT NULL,due_date DATE NOT NULL,notes TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_by INT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME NULL,deleted_by INT NULL,UNIQUE KEY uq_import_reference(reference),KEY idx_import_month(import_month,deleted_at),KEY idx_import_due(due_date,deleted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,payment_date DATE NOT NULL,amount DECIMAL(13,2) NOT NULL,reference VARCHAR(190) NULL,payment_method VARCHAR(80) NULL,notes TEXT NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at DATETIME NULL,reversed_by INT NULL,reversal_reason VARCHAR(500) NULL,KEY idx_import_payment(import_id,reversed_at),KEY idx_import_payment_date(payment_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_documents(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,payment_id BIGINT UNSIGNED NULL,document_type VARCHAR(40) NOT NULL,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,uploaded_by INT NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at DATETIME NULL,deleted_by INT NULL,UNIQUE KEY uq_import_document(stored_filename),KEY idx_import_document(import_id,payment_id,deleted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,import_id BIGINT UNSIGNED NOT NULL,action_key VARCHAR(50) NOT NULL,before_json LONGTEXT NULL,after_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_import_audit(import_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_month_status(month_key CHAR(7) PRIMARY KEY,reconciled TINYINT(1) NOT NULL DEFAULT 0,updated_by INT NOT NULL,updated_by_name VARCHAR(190) NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_statements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(190) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,sha256 CHAR(64) NOT NULL,statement_period CHAR(7) NULL,status VARCHAR(40) NOT NULL DEFAULT 'uploaded',parse_message TEXT NULL,rows_detected INT NOT NULL DEFAULT 0,liabilities_detected INT NOT NULL DEFAULT 0,payments_detected INT NOT NULL DEFAULT 0,new_records INT NOT NULL DEFAULT 0,matched_payments INT NOT NULL DEFAULT 0,duplicates_skipped INT NOT NULL DEFAULT 0,needs_review INT NOT NULL DEFAULT 0,uploaded_by INT NOT NULL,uploaded_by_name VARCHAR(190) NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,confirmed_by INT NULL,confirmed_by_name VARCHAR(190) NULL,confirmed_at DATETIME NULL,UNIQUE KEY uq_import_statement_hash(sha256),KEY idx_import_statement_period(statement_period,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_statement_rows(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NOT NULL,source_row_number INT NOT NULL,transaction_date DATE NULL,due_date DATE NULL,reference VARCHAR(190) NULL,description TEXT NULL,debit DECIMAL(13,2) NOT NULL DEFAULT 0,credit DECIMAL(13,2) NOT NULL DEFAULT 0,import_vat_amount DECIMAL(13,2) NOT NULL DEFAULT 0,other_charge_amount DECIMAL(13,2) NOT NULL DEFAULT 0,payment_amount DECIMAL(13,2) NOT NULL DEFAULT 0,row_kind VARCHAR(30) NOT NULL DEFAULT 'unknown',confidence VARCHAR(20) NOT NULL DEFAULT 'low',match_status VARCHAR(40) NOT NULL DEFAULT 'needs_review',matched_import_id BIGINT UNSIGNED NULL,excluded TINYINT(1) NOT NULL DEFAULT 0,source_json LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_import_statement_row(statement_id,source_row_number),KEY idx_import_statement_rows(statement_id,row_kind,match_status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_statement_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,statement_id BIGINT UNSIGNED NOT NULL,action_key VARCHAR(50) NOT NULL,details_json LONGTEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_import_statement_audit(statement_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
 "CREATE TABLE IF NOT EXISTS accounts_import_vat_settings(setting_key VARCHAR(100) PRIMARY KEY,setting_value VARCHAR(500) NOT NULL,updated_by INT NOT NULL DEFAULT 0,updated_by_name VARCHAR(190) NOT NULL DEFAULT '',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
 ];foreach($queries as$q){try{db()->exec($q);}catch(Throwable$e){error_log('Import VAT schema migration failed: '.$e->getMessage());}}
 try{$hasOld=db()->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$hasOld->execute(['accounts_import_vat_statement_rows','row_number']);$hasNew=db()->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$hasNew->execute(['accounts_import_vat_statement_rows','source_row_number']);if((int)$hasOld->fetchColumn()&&!(int)$hasNew->fetchColumn())db()->exec('ALTER TABLE accounts_import_vat_statement_rows CHANGE COLUMN `row_number` source_row_number INT NOT NULL');}catch(Throwable$e){error_log('Import VAT row_number column rename failed: '.$e->getMessage());}
 foreach(['accounts_import_vat_liabilities','accounts_import_vat_payments'] as $table){try{foreach(['source_statement_id'=>'BIGINT UNSIGNED NULL','source_statement_row_id'=>'BIGINT UNSIGNED NULL'] as $column=>$definition){$check=db()->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$check->execute([$table,$column]);if(!(int)$check->fetchColumn())db()->exec("ALTER TABLE {$table} ADD COLUMN {$column} {$definition}");}$index='uq_'.$table.'_statement_row';$check=db()->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$check->execute([$table,$index]);if(!(int)$check->fetchColumn())db()->exec("ALTER TABLE {$table} ADD UNIQUE KEY {$index}(source_statement_id,source_statement_row_id)");}catch(Throwable$e){error_log('Import VAT source-link migration failed for '.$table.': '.$e->getMessage());}}
 $statementColumns=['revision_count'=>'INT NOT NULL DEFAULT 0','penalty_count'=>'INT NOT NULL DEFAULT 0','interest_count'=>'INT NOT NULL DEFAULT 0','reprocessed_at'=>'DATETIME NULL','reprocessed_by'=>'INT NULL','reprocessed_by_name'=>'VARCHAR(190) NULL','reprocess_reason'=>'VARCHAR(500) NULL'];$rowColumns=['tax_type'=>'VARCHAR(120) NULL','transaction_type'=>'VARCHAR(190) NULL','liability_type'=>'VARCHAR(190) NULL','doc_number'=>'VARCHAR(190) NULL','tax_year'=>'VARCHAR(20) NULL','tax_period'=>'VARCHAR(40) NULL','effective_date'=>'DATE NULL','action_date'=>'DATE NULL','transaction_amount'=>'DECIMAL(13,2) NOT NULL DEFAULT 0','classification'=>'VARCHAR(40) NOT NULL DEFAULT \'needs_review\'','included_in_payable'=>'TINYINT(1) NOT NULL DEFAULT 0','source_hash'=>'CHAR(64) NULL','waiver_status'=>'VARCHAR(40) NULL','match_method'=>'VARCHAR(100) NULL'];$liabilityColumns=['namra_tax_year'=>'SMALLINT UNSIGNED NULL','namra_tax_period'=>'TINYINT UNSIGNED NULL','accounting_period'=>'CHAR(7) NULL','effective_date'=>'DATE NULL','action_date'=>'DATE NULL'];foreach([['accounts_import_vat_statements',$statementColumns],['accounts_import_vat_statement_rows',$rowColumns],['accounts_import_vat_liabilities',$liabilityColumns]]as$migration){try{foreach($migration[1]as$column=>$definition){$check=db()->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$check->execute([$migration[0],$column]);if(!(int)$check->fetchColumn())db()->exec('ALTER TABLE '.$migration[0].' ADD COLUMN '.$column.' '.$definition);}}catch(Throwable$e){error_log('Import VAT NamRA field migration failed: '.$e->getMessage());}}
 try{$check=db()->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$check->execute(['accounts_import_vat_liabilities','idx_import_accounting_period']);if(!(int)$check->fetchColumn())db()->exec('ALTER TABLE accounts_import_vat_liabilities ADD KEY idx_import_accounting_period(accounting_period,deleted_at)');}catch(Throwable$e){error_log('Import VAT accounting period index migration failed: '.$e->getMessage());}
 try{db()->exec("INSERT IGNORE INTO accounts_import_vat_settings(setting_key,setting_value)VALUES('penalty_interest_exclusion_active','1'),('penalty_interest_review_date','2026-10-31')");}catch(Throwable$e){error_log('Import VAT settings seed failed: '.$e->getMessage());}
 $ready=true;
}
function import_vat_csrf(): string {if(empty($_SESSION['import_vat_csrf']))$_SESSION['import_vat_csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['import_vat_csrf'];}
function import_vat_verify(string $token): void {if($token===''||!hash_equals(import_vat_csrf(),$token))throw new RuntimeException('Your session expired. Refresh and try again.');}
function import_vat_month(string $v): string{return preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$v)?$v:date('Y-m');}
function import_vat_audit(int$id,string$action,?array$before,?array$after):void{$u=current_user();db()->prepare('INSERT INTO accounts_import_vat_audit(import_id,action_key,before_json,after_json,actor_id,actor_name)VALUES(?,?,?,?,?,?)')->execute([$id,$action,$before?json_encode($before,JSON_UNESCAPED_SLASHES):null,$after?json_encode($after,JSON_UNESCAPED_SLASHES):null,(int)($u['id']??0),(string)($u['name']??'Owner')]);}
function import_vat_record(int$id):?array{$s=db()->prepare('SELECT * FROM accounts_import_vat_liabilities WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$r=$s->fetch();return$r?:null;}
function import_vat_statement_audit(int$id,string$action,array$details=[]):void{$u=current_user();db()->prepare('INSERT INTO accounts_import_vat_statement_audit(statement_id,action_key,details_json,actor_id,actor_name)VALUES(?,?,?,?,?)')->execute([$id,$action,json_encode($details,JSON_UNESCAPED_SLASHES),(int)($u['id']??0),(string)($u['name']??'Owner')]);}
function import_vat_statement(int$id):?array{$s=db()->prepare('SELECT * FROM accounts_import_vat_statements WHERE id=?');$s->execute([$id]);$r=$s->fetch();if(!$r)return null;$q=db()->prepare('SELECT * FROM accounts_import_vat_statement_rows WHERE statement_id=? ORDER BY source_row_number,id');$q->execute([$id]);$r['rows']=$q->fetchAll();foreach($r['rows']as&$row){$row['accounting_period']=import_vat_tax_period_month((string)$row['tax_year'],(string)$row['tax_period']);}unset($row);return$r;}
function import_vat_statement_history():array{$s=db()->query('SELECT id,original_filename,mime_type,file_size,sha256,statement_period,status,parse_message,rows_detected,liabilities_detected,payments_detected,revision_count,penalty_count,interest_count,new_records,matched_payments,duplicates_skipped,needs_review,uploaded_by_name,uploaded_at,confirmed_by_name,confirmed_at,reprocessed_at,reprocessed_by_name,reprocess_reason FROM accounts_import_vat_statements ORDER BY id DESC LIMIT 100');return$s->fetchAll();}
function import_vat_settings():array{$s=db()->query("SELECT setting_key,setting_value FROM accounts_import_vat_settings WHERE setting_key IN ('penalty_interest_exclusion_active','penalty_interest_review_date')");$out=[];foreach($s->fetchAll()as$r)$out[$r['setting_key']]=$r['setting_value'];return$out;}
function import_vat_money($value):float{$clean=preg_replace('/[^0-9.\-]/','',str_replace(',','',(string)$value));return$clean===''?0.0:round((float)$clean,2);}
function import_vat_normal_date(string$value):?string{$value=trim($value);if($value==='')return null;foreach(['Y-m-d','d/m/Y','d-m-Y','d.m.Y','m/d/Y']as$f){$d=DateTime::createFromFormat('!'.$f,$value);if($d&&$d->format($f)===$value)return$d->format('Y-m-d');}return null;}
function import_vat_csv_rows(string$path):array{
 $h=fopen($path,'rb');if(!$h)throw new RuntimeException('The statement file could not be read.');$first=fgets($h);rewind($h);$counts=[','=>substr_count((string)$first,','),';'=>substr_count((string)$first,';'),"\t"=>substr_count((string)$first,"\t")];arsort($counts);$delimiter=(string)array_key_first($counts);$headers=fgetcsv($h,0,$delimiter);if(!$headers){fclose($h);throw new RuntimeException('The CSV statement has no header row.');}$normalized=[];foreach($headers as$i=>$name){$key=strtolower(trim(preg_replace('/[^a-z0-9]+/i',' ',(string)$name)));$normalized[$i]=$key;}
 $find=function(array$needles)use($normalized){foreach($normalized as$i=>$h){foreach($needles as$n)if($h===$n||strpos($h,$n)!==false)return$i;}return null;};$map=['tax_type'=>$find(['tax type']),'transaction_type'=>$find(['transaction type']),'liability_type'=>$find(['liability type']),'doc_number'=>$find(['doc no','document number']),'tax_year'=>$find(['tax year']),'tax_period'=>$find(['tax period']),'due_date'=>$find(['due date']),'effective_date'=>$find(['effective date']),'action_date'=>$find(['action date']),'amount'=>$find(['transaction amount'])];
 foreach(['tax_type','transaction_type','liability_type','doc_number','tax_year','tax_period','due_date','effective_date','action_date','amount']as$required)if($map[$required]===null){fclose($h);throw new RuntimeException('The CSV is not the confirmed NamRA Transaction Records format. Missing heading: '.str_replace('_',' ',$required).'. No records were posted.');}
 $rows=[];$line=1;while(($values=fgetcsv($h,0,$delimiter))!==false){$line++;if(!array_filter($values,function($v){return trim((string)$v)!=='';}))continue;$get=function($key)use($map,$values){return trim((string)($values[$map[$key]]??''));};$transactionType=$get('transaction_type');preg_match('/^\s*(\d{3})\b/',$transactionType,$codeMatch);$code=$codeMatch[1]??'';$classification=['201'=>'assessment','204'=>'revision','129'=>'payment','481'=>'ignored_penalty','304'=>'ignored_interest'][$code]??'needs_review';$included=in_array($classification,['assessment','revision','payment'],true);$amount=abs(import_vat_money($get('amount')));$kind=in_array($classification,['assessment','revision'],true)?'liability':($classification==='payment'?'payment':'unknown');$doc=$get('doc_number');$taxYear=$get('tax_year');$taxPeriod=$get('tax_period');$fingerprint=hash('sha256',implode('|',[$get('tax_type'),$transactionType,$get('liability_type'),$doc,$taxYear,$taxPeriod,$get('due_date'),$get('effective_date'),$get('action_date'),number_format($amount,2,'.','')]));$rows[]=['source_row_number'=>$line,'transaction_date'=>import_vat_normal_date($get('action_date'))?:import_vat_normal_date($get('effective_date')),'due_date'=>import_vat_normal_date($get('due_date')),'reference'=>$doc,'description'=>$transactionType,'debit'=>$kind==='liability'?$amount:0,'credit'=>$classification==='payment'?$amount:0,'import_vat_amount'=>$kind==='liability'?$amount:0,'other_charge_amount'=>0,'payment_amount'=>$classification==='payment'?$amount:0,'row_kind'=>$kind,'confidence'=>$classification==='needs_review'?'low':'high','match_status'=>$classification==='needs_review'?'needs_review':($included?'new':'excluded'),'tax_type'=>$get('tax_type'),'transaction_type'=>$transactionType,'liability_type'=>$get('liability_type'),'doc_number'=>$doc,'tax_year'=>$taxYear,'tax_period'=>$taxPeriod,'effective_date'=>import_vat_normal_date($get('effective_date')),'action_date'=>import_vat_normal_date($get('action_date')),'transaction_amount'=>$amount,'classification'=>$classification,'included_in_payable'=>$included?1:0,'source_hash'=>$fingerprint,'waiver_status'=>in_array($classification,['ignored_penalty','ignored_interest'],true)?'pending_waiver':null,'source_json'=>json_encode(array_combine($headers,array_pad($values,count($headers),'')),JSON_UNESCAPED_SLASHES)];}fclose($h);return$rows;
}
function import_vat_status(float$due,float$paid,string$dueDate):string{$out=$due-$paid;if($paid>$due+0.005)return'overpayment';if($out<=0.005)return'paid';if($dueDate<date('Y-m-d'))return'overdue';if($paid>0)return'partially_paid';if($dueDate<=date('Y-m-d',strtotime('+7 days')))return'due_soon';return'unpaid';}
function import_vat_payload(string$month,string$view='imports'):array{
 import_vat_schema_ready();$where=$view==='payments'?'DATE_FORMAT(l.due_date,\'%Y-%m\')=?':'COALESCE(l.accounting_period,l.import_month)=?';$s=db()->prepare("SELECT l.*,COALESCE(SUM(CASE WHEN p.reversed_at IS NULL THEN p.amount ELSE 0 END),0) paid FROM accounts_import_vat_liabilities l LEFT JOIN accounts_import_vat_payments p ON p.import_id=l.id WHERE l.deleted_at IS NULL AND $where GROUP BY l.id ORDER BY l.due_date,l.id");$s->execute([$month]);$rows=$s->fetchAll();
 $summary=['imports'=>count($rows),'import_vat'=>0.0,'other_charges'=>0.0,'total_due'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'overdue'=>0.0,'paid_count'=>0,'partial_count'=>0,'unpaid_count'=>0,'overdue_count'=>0];
 foreach($rows as&$r){$r['paid']=(float)$r['paid'];$r['outstanding']=max(0,round((float)$r['total_due']-$r['paid'],2));$r['status']=import_vat_status((float)$r['total_due'],$r['paid'],(string)$r['due_date']);$r['payment_state']=$r['outstanding']<=0.005?'paid':($r['paid']>0?'partially_paid':'unpaid');$summary[$r['payment_state']==='paid'?'paid_count':($r['payment_state']==='partially_paid'?'partial_count':'unpaid_count')]++;foreach(['import_vat_amount'=>'import_vat','total_due'=>'total_due']as$a=>$b)$summary[$b]+=(float)$r[$a];$summary['other_charges']+=(float)$r['duty_amount']+(float)$r['other_charge_amount'];$summary['paid']+=$r['paid'];$summary['outstanding']+=$r['outstanding'];if($r['status']==='overdue'){$summary['overdue']+=$r['outstanding'];$summary['overdue_count']++;}$ps=db()->prepare('SELECT * FROM accounts_import_vat_payments WHERE import_id=? ORDER BY payment_date,id');$ps->execute([(int)$r['id']]);$r['payments']=$ps->fetchAll();$ds=db()->prepare('SELECT id,payment_id,document_type,original_filename,mime_type,file_size FROM accounts_import_vat_documents WHERE import_id=? AND deleted_at IS NULL ORDER BY id');$ds->execute([(int)$r['id']]);$r['documents']=$ds->fetchAll();}
 foreach($summary as$k=>$v)if(is_float($v))$summary[$k]=round($v,2);unset($r);
 $progress=[];for($i=1;$i<=12;$i++){$key=substr($month,0,4).'-'.str_pad((string)$i,2,'0',STR_PAD_LEFT);$q=db()->prepare('SELECT COUNT(*),COALESCE(SUM(total_due),0) FROM accounts_import_vat_liabilities WHERE deleted_at IS NULL AND COALESCE(accounting_period,import_month)=?');$q->execute([$key]);[$count,$due]=$q->fetch(PDO::FETCH_NUM);$progress[]=['month'=>$key,'count'=>(int)$count,'status'=>(int)$count?'in_progress':'no_imports'];}
 return['month'=>$month,'view'=>$view,'summary'=>$summary,'records'=>$rows,'progress'=>$progress];
}
