<?php
declare(strict_types=1);

function cw_render_overview(array $period): void { ?>
<section class="accounts-app-section" aria-labelledby="costing-tools-title"><header><div><p class="eyebrow">Applications</p><h2 id="costing-tools-title">Costing Tools</h2></div></header><div class="accounts-app-grid">
<a class="accounts-app-card accounting-app-card accounting-app-card--size-conversions" href="<?= cw_page_url('size-conversions.php',$period) ?>"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="ruler"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Size Conversions</h3><p>Manage the standard liquid and weight sizes used in product costing calculations.</p><strong>Open Size Conversions <span aria-hidden="true">&rarr;</span></strong></div></a>
<?php $cards=[
['supplier-invoices.php','receipt-text','Supplier Invoices','Upload supplier invoices, extract purchased items and review product costs by supplier and date.'],
['transport-costs.php','truck','Transport Costs','Upload or record transport charges, link them to supplier invoices and allocate delivery costs by weight.'],
['packaging-costs.php','package-open','Packaging Costs','Record packaging materials, calculate unit costs and assign containers and labels to product sizes.'],
['landed-product-costs.php','calculator','Landed Product Costs','Combine supplier and transport costs to calculate each product’s landed cost by kilogram, litre or individual unit.'],
['formulations.php','flask-conical','Formulation Costing','Build formulations, calculate batch and unit costs, and generate recommended selling prices.'],
['wholesale-pricing.php','boxes','Wholesale Pricing','Calculate wholesale prices, VAT, packaging, profit and margins for bulk product sizes.'],
['shipments.php','ship','Shipments','Link approved invoices and record shipment expenses.'],
['landed-costs.php','calculator','Landed Costs','Allocate and reconcile landed costs for approved shipments.'],
['product-matching.php','scan-search','Product Matching','Match calculated sale sizes to the website product snapshot.'],
['profitability.php','chart-no-axes-combined','Pricing & Margins','Review private cost, price, profit, margin and markup previews.'],
['historical-cost-records.php','history','Historical Records','View preserved, read-only records from the previous costing system.']
]; foreach($cards as $card): ?><a class="accounts-app-card accounting-app-card" href="<?= cw_page_url($card[0],$period) ?>"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="<?= htmlspecialchars($card[1],ENT_QUOTES,'UTF-8') ?>"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3><?= htmlspecialchars($card[2],ENT_QUOTES,'UTF-8') ?></h3><p><?= htmlspecialchars($card[3],ENT_QUOTES,'UTF-8') ?></p><strong>Open <?= htmlspecialchars($card[2],ENT_QUOTES,'UTF-8') ?> <span aria-hidden="true">&rarr;</span></strong></div></a><?php endforeach; ?>
</div></section>
<?php }

function cw_render_size_conversions(array $period): void
{
    $groups = [
        'volume' => ['title'=>'Liquid volume','description'=>'Millilitres and litres converted to litres.','column'=>'Value in litres'],
        'weight' => ['title'=>'Product weight','description'=>'Grams and kilograms converted to kilograms.','column'=>'Value in kilograms'],
    ]; ?>
<aside class="size-conversions__notice" role="note"><i data-lucide="info" aria-hidden="true"></i><span>Liquid sizes are converted to litres. Weight sizes are converted to kilograms. These conversion values are used by the Cost Workbook when calculating product costs.</span></aside>
<div class="size-conversions__grid" data-size-conversion-api="size-conversions-api.php" data-size-conversion-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><?php foreach($groups as $type=>$group): ?><section class="size-conversions__panel" aria-labelledby="size-conversions-<?= $type ?>"><header class="size-conversions__panel-header"><h2 class="size-conversions__panel-title" id="size-conversions-<?= $type ?>"><?= htmlspecialchars($group['title'],ENT_QUOTES,'UTF-8') ?></h2><p class="size-conversions__panel-description"><?= htmlspecialchars($group['description'],ENT_QUOTES,'UTF-8') ?></p></header><div class="size-conversions__table-wrap"><table class="size-conversions__table" data-conversion-table="<?= $type ?>"><thead><tr><th scope="col">Size</th><th scope="col"><?= htmlspecialchars($group['column'],ENT_QUOTES,'UTF-8') ?></th><th scope="col">Actions</th></tr></thead><tbody><?php foreach(cw_size_conversions_by_type($type) as $row): ?><tr data-conversion-id="<?= (int)$row['id'] ?>" data-conversion='<?= htmlspecialchars(json_encode($row,JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?>'><td><?= htmlspecialchars($row['label'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($row['base_value_display'],ENT_QUOTES,'UTF-8') ?></td><td><button type="button" class="size-conversions__edit-button" aria-label="Edit <?= htmlspecialchars($row['label'],ENT_QUOTES,'UTF-8') ?> conversion" title="Edit conversion" data-conversion-edit="<?= (int)$row['id'] ?>"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 20h4l11-11a2.8 2.8 0 0 0-4-4L4 16v4Z" stroke="currentColor" stroke-linejoin="round"/><path d="m13.5 6.5 4 4" stroke="currentColor"/></svg></button></td></tr><?php endforeach; ?></tbody></table></div></section><?php endforeach; ?></div>
<div class="size-conversions__drawer-backdrop" data-conversion-backdrop></div><aside class="size-conversions__drawer" role="dialog" aria-modal="true" aria-labelledby="sizeConversionDrawerTitle" aria-hidden="true" data-conversion-drawer><header class="size-conversions__drawer-header"><div><h2 class="size-conversions__drawer-title" id="sizeConversionDrawerTitle">Add Size Conversion</h2><p class="size-conversions__drawer-description">Add a product size and its equivalent value in litres or kilograms.</p></div><button class="size-conversions__drawer-close" type="button" aria-label="Close size conversion panel" data-conversion-close><svg viewBox="0 0 24 24" width="16" height="16" fill="none" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" stroke="currentColor" stroke-linecap="round"/></svg></button></header><form class="size-conversions__form" data-conversion-form novalidate><input type="hidden" name="id"><input type="hidden" name="action" value="create"><div class="size-conversions__field"><label for="sizeConversionType">Measurement type</label><select id="sizeConversionType" name="measurement_type" required><option value="volume">Liquid volume</option><option value="weight">Product weight</option></select></div><div class="size-conversions__field"><label for="sizeConversionAmount">Amount</label><input id="sizeConversionAmount" name="amount" type="number" step="any" min="0.000001" inputmode="decimal" required></div><div class="size-conversions__field"><label for="sizeConversionUnit">Unit</label><select id="sizeConversionUnit" name="unit" required></select></div><div class="size-conversions__field"><label for="sizeConversionLabel">Size label</label><input id="sizeConversionLabel" name="label" readonly></div><div class="size-conversions__field"><label for="sizeConversionValue">Converted value</label><input id="sizeConversionValue" name="base_value" readonly></div><div class="size-conversions__field"><label for="sizeConversionBaseUnit">Base unit</label><input id="sizeConversionBaseUnit" name="base_unit" readonly></div><p class="size-conversions__field-error" role="alert" data-conversion-error></p><div class="size-conversions__drawer-actions"><button type="button" class="size-conversions__cancel-button" data-conversion-cancel>Cancel</button><button type="submit" class="size-conversions__save-button" data-conversion-save>Save Conversion</button></div></form></aside><div class="size-conversions__toast" role="status" aria-live="polite" hidden data-conversion-toast></div>
<?php }

function cw_render_purchases(bool $reviewOnly=false): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-toolbar"><div><h2><?= $reviewOnly?'Invoice review queue':'Supplier invoice intake' ?></h2><p><?= $reviewOnly?'Review and approve existing drafts for this period.':'Uploads remain drafts until every required value is reviewed.' ?></p></div><?php if(!$reviewOnly): ?><button class="cw-btn cw-primary" data-open-upload>Upload invoice</button><?php endif; ?></div><div class="cw-table-wrap"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Currency</th><th>Total</th><th>Lines</th><th>Extraction</th><th>Review</th><th>Approval</th><th>Uploaded by</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody id="invoiceRows"><tr><td colspan="12" class="cw-empty">Loading purchases…</td></tr></tbody></table></div></div></section>
<?php cw_render_invoice_dialogs(!$reviewOnly); }

function cw_render_invoice_dialogs(bool $includeUpload): void { if($includeUpload): ?>
<dialog id="uploadDialog" class="cw-dialog cw-upload-dialog" aria-labelledby="cwUploadDialogTitle"><div class="cw-upload-dialog__panel"><div class="cw-upload-dialog__header"><div><h2 id="cwUploadDialogTitle">Upload supplier invoices</h2><p>PDF, JPG, JPEG, PNG, XLSX or CSV; up to 15 MB each.</p></div><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form></div><form id="uploadForm" class="cw-upload-dialog__form"><div class="cw-upload-dialog__body"><label class="cw-drop"><input id="invoiceFiles" type="file" name="invoice_files[]" multiple accept=".pdf,.jpg,.jpeg,.png,.xlsx,.csv"><strong>Drop invoices here or choose files</strong><span>Each file becomes its own draft invoice.</span></label><div id="uploadSelection" class="cw-upload-selection" aria-live="polite"><p class="cw-upload-empty">No files selected.</p></div><div id="uploadProgress" class="cw-upload-progress" role="status" hidden></div><div id="uploadResults" aria-live="polite"></div></div><div class="cw-upload-dialog__footer"><button type="button" class="cw-btn cw-upload-dialog__cancel" data-cw-upload-cancel>Cancel</button><button id="cwUploadSelectedFiles" class="cw-btn cw-primary cw-upload-dialog__submit" type="submit" disabled>Upload selected files</button></div></form></div></dialog>
<?php endif; ?>
<dialog id="reviewDialog" class="cw-dialog cw-review"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Review invoice</h2><div id="reviewExtractionNotice" class="cw-manual-review-notice" role="status" hidden><strong>No invoice lines were extracted from this file.</strong><span>Manual line entry is required before approval.</span></div><form id="reviewForm"><input type="hidden" name="id"><div class="cw-form-grid"><label>Supplier<input name="supplier_name" required></label><label>Invoice number<input name="invoice_number" required></label><label>Invoice date<input name="invoice_date" type="date" required></label><label>Currency<input name="currency" maxlength="3" required></label><label>Exchange rate<input name="exchange_rate" type="number" step="0.000001" min="0.000001" required></label><label>VAT treatment<select name="vat_treatment" required><option value="unconfirmed">Confirm treatment</option><option value="inclusive">Inclusive</option><option value="exclusive">Exclusive</option><option value="exempt">Exempt</option><option value="mixed">Mixed</option></select></label><label>Subtotal<input name="subtotal" readonly></label><label>VAT amount<input name="vat_amount" readonly></label><label>Invoice total<input name="invoice_total" readonly></label><label class="wide">Notes<textarea name="notes"></textarea></label></div><div class="cw-toolbar"><h3>Invoice lines</h3><button class="cw-btn" id="addLine" type="button">Add line</button></div><div class="cw-table-wrap"><table><thead><tr><th>Description</th><th>Product</th><th>Qty</th><th>Unit</th><th>Pack size</th><th>Unit cost</th><th>Discount</th><th>Subtotal</th><th>VAT</th><th>Total</th><th>Type</th><th></th></tr></thead><tbody id="reviewLines"></tbody></table></div><div class="cw-dialog-actions"><button class="cw-btn cw-primary" type="submit">Save review</button><button class="cw-btn" id="approveInvoice" type="button">Approve</button></div></form></dialog>
<dialog id="matchDialog" class="cw-dialog"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Match website item</h2><div class="cw-product-filters"><label>Product or variation<input id="matchSearch"></label><label>Category<select id="matchCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><tbody id="matchRows"><tr><td class="cw-empty">Enter a search.</td></tr></tbody></table></div></dialog>
<template id="lineTemplate"><tr><td><input data-k="raw_description"></td><td><input data-k="product_description" required></td><td><input data-k="quantity" type="number" step="0.000001" min="0" required></td><td><select data-k="purchase_unit"><option value="">Confirm</option><option>kg</option><option>g</option><option>L</option><option>ml</option><option>unit</option><option>pack</option></select></td><td><input data-k="pack_size" type="number" step="0.000001" min="0"></td><td><input data-k="unit_price" type="number" step="0.000001" min="0" required></td><td><select data-k="discount_type"><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select><input data-k="discount_value" type="number" step="0.01" min="0" value="0.00"><small data-discount-result></small></td><td><input data-k="line_subtotal" readonly></td><td><select data-k="vat_treatment"><option value="unconfirmed">Invoice treatment</option><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option><option value="exempt">Exempt</option></select><input data-k="calculated_vat_amount" readonly><input data-k="vat_override_amount" type="number" step="0.01" min="0"><input data-k="vat_override_reason" placeholder="Override reason"></td><td><input data-k="line_total" readonly></td><td><select data-k="item_type"><option value="unclassified">Confirm type</option><option value="supplier_raw_material">Raw material</option><option value="website_product">Website product</option><option value="website_variation">Website variation</option><option value="packaging">Packaging</option><option value="additional_cost">Additional cost</option></select><button class="cw-btn" data-match-line type="button">Match</button></td><td><button class="cw-icon" data-remove-line type="button">×</button></td></tr></template>
<?php }

function cw_render_phase2(string $page): void { ?>
<section class="cw-section cw2"><div class="cw-section-body"><div class="cw-toolbar"><div><h2><?= $page==='shipments'?'Shipment workspace':($page==='landed-costs'?'Allocation and reconciliation':'Sale-size product matching') ?></h2><p>Only records required for this page and selected month are loaded.</p></div><?php if($page==='shipments'): ?><button class="cw-btn cw-primary" id="cw2NewShipment" type="button">Create shipment</button><?php endif; ?></div><div class="cw2-grid"><aside class="cw2-list" id="cw2ShipmentList"><p class="cw-empty">Loading shipments…</p></aside><div class="cw2-workspace" id="cw2ShipmentWorkspace"><div class="cw-empty-state"><strong>Select a shipment</strong><p>Opening a shipment never saves data.</p></div></div></div><?php if($page==='landed-costs'): ?><div class="cw-page-calculation"><button class="cw-btn cw-primary" id="cw2Calculate" type="button" disabled>Calculate landed costs</button><button class="cw-btn cw-primary" id="cw2Confirm" type="button" disabled>Confirm calculation</button><div id="cw2Reconciliation" class="cw-empty-state"><strong>No calculation selected</strong></div><div id="cw2LandedLines" class="cw-table-wrap"></div></div><?php elseif($page==='product-matching'): ?><div class="cw-page-calculation"><div id="cw2SaleSizes" class="cw-empty-state"><strong>No landed-cost lines available</strong></div></div><?php endif; ?></div></section>
<?php }

function cw_render_profitability(): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-toolbar"><div><h2>Read-only WooCommerce snapshot</h2><p id="lastSync">No successful sync yet.</p><p id="snapshotStats">No snapshot counts yet.</p><p id="syncStatus">No sync attempt is active.</p></div><div class="cw-actions"><button class="cw-btn cw-primary" id="syncWebsite">Sync Website Data</button><button class="cw-btn" id="recoverSync" hidden>Recover interrupted sync</button></div></div><div class="cw-progress" id="syncProgress" hidden><span></span><p>Starting sync…</p></div><div class="cw-product-filters"><label>Search snapshot<input id="productSearch" placeholder="Product, variation or SKU"></label><label>Category<select id="productCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><thead><tr><th>Product</th><th>Variation</th><th>SKU</th><th>Type</th><th>Category</th><th>Price incl. VAT</th><th>Stock</th><th>Status</th><th>Cost status</th></tr></thead><tbody id="productRows"><tr><td colspan="9" class="cw-empty">No products are available for this period.</td></tr></tbody></table></div></div></section>
<?php }

function cw_render_cogs(): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-empty-state"><strong>WooCommerce Cost of Goods Sold is not enabled. Cost publishing is unavailable.</strong><p>Profitability figures are private Cost Workbook previews and are not published to WooCommerce.</p><p>Future publishing requires an eligible confirmed cost, exact product or variation match, stale-value check, explicit confirmation, audit record and returned-value verification.</p><button class="cw-btn cw-primary" type="button" disabled aria-disabled="true">Publishing unavailable</button></div></div></section>
<?php }

function cw_render_settings(): void { ?>
<section class="cw-section"><div class="cw-section-body"><form id="settingsForm" class="cw-settings"><label>Base currency<input name="base_currency" maxlength="3" value="NAD" required></label><label>VAT rate (%)<input name="vat_rate" type="number" step="0.01" min="0" value="15" required></label><label>Retail target margin (%)<input name="retail_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Wholesale target margin (%)<input name="wholesale_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Reseller target margin (%)<input name="reseller_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Low-margin threshold (%)<input name="low_margin_threshold" type="number" step="0.01" min="0" max="100"></label><div class="cw-help"><p>Settings apply to Cost Workbook calculations only and do not write to WooCommerce.</p></div><button class="cw-btn cw-primary" type="submit">Save settings</button></form></div></section>
<?php }
