<?php
declare(strict_types=1);

function cw_render_overview(array $period): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-overview-grid">
<a href="<?= cw_page_url('purchases.php',$period) ?>"><span>Purchases &amp; Invoices</span><strong id="metricInvoices">—</strong><small id="metricPurchaseNote">Loading selected month…</small></a>
<a href="<?= cw_page_url('shipments.php',$period) ?>"><span>Shipments</span><strong id="metricShipments">—</strong><small>Active in selected month</small></a>
<a href="<?= cw_page_url('landed-costs.php',$period) ?>"><span>Landed Costs</span><strong id="metricLanded">—</strong><small>Confirmed calculations</small></a>
<a href="<?= cw_page_url('product-matching.php',$period) ?>"><span>Product Matching</span><strong id="metricMatches">—</strong><small>Saved product matches</small></a>
<a href="<?= cw_page_url('profitability.php',$period) ?>"><span>Profitability</span><strong id="metricWebsite">—</strong><small>Read-only snapshot items</small></a>
<a href="<?= cw_page_url('cogs-publishing.php',$period) ?>"><span>COGS Publishing</span><strong>Unavailable</strong><small>No WooCommerce write on load</small></a>
<a href="<?= cw_page_url('settings.php',$period) ?>"><span>Settings</span><strong id="metricSettings">—</strong><small>Configured workbook values</small></a>
<a href="<?= cw_page_url('historical-cost-records.php',$period) ?>"><span>Historical Records</span><strong>Read only</strong><small>9 preserved datasets</small></a>
</div></div></section>
<?php }

function cw_render_purchases(bool $reviewOnly=false): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-toolbar"><div><h2><?= $reviewOnly?'Invoice review queue':'Supplier invoice intake' ?></h2><p><?= $reviewOnly?'Review and approve existing drafts for this period.':'Uploads remain drafts until every required value is reviewed.' ?></p></div><?php if(!$reviewOnly): ?><button class="cw-btn cw-primary" data-open-upload>Upload invoice</button><?php endif; ?></div><div class="cw-table-wrap"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Currency</th><th>Total</th><th>Lines</th><th>Extraction</th><th>Review</th><th>Approval</th><th>Uploaded by</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody id="invoiceRows"><tr><td colspan="12" class="cw-empty">Loading purchases…</td></tr></tbody></table></div></div></section>
<?php cw_render_invoice_dialogs(!$reviewOnly); }

function cw_render_invoice_dialogs(bool $includeUpload): void { if($includeUpload): ?>
<dialog id="uploadDialog" class="cw-dialog cw-upload-dialog" aria-labelledby="cwUploadDialogTitle"><div class="cw-upload-dialog__panel"><div class="cw-upload-dialog__header"><div><h2 id="cwUploadDialogTitle">Upload supplier invoices</h2><p>PDF, JPG, JPEG, PNG, XLSX or CSV; up to 15 MB each.</p></div><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form></div><form id="uploadForm" class="cw-upload-dialog__form"><div class="cw-upload-dialog__body"><label class="cw-drop"><input id="invoiceFiles" type="file" name="invoice_files[]" multiple accept=".pdf,.jpg,.jpeg,.png,.xlsx,.csv"><strong>Drop invoices here or choose files</strong><span>Each file becomes its own draft invoice.</span></label><div id="uploadSelection" class="cw-upload-selection" aria-live="polite"><p class="cw-upload-empty">No files selected.</p></div><div id="uploadProgress" class="cw-upload-progress" role="status" hidden></div><div id="uploadResults" aria-live="polite"></div></div><div class="cw-upload-dialog__footer"><button type="button" class="cw-btn cw-upload-dialog__cancel" data-cw-upload-cancel>Cancel</button><button id="cwUploadSelectedFiles" class="cw-btn cw-primary cw-upload-dialog__submit" type="submit" disabled>Upload selected files</button></div></form></div></dialog>
<?php endif; ?>
<dialog id="reviewDialog" class="cw-dialog cw-review"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Review invoice</h2><div id="reviewExtractionNotice" class="cw-manual-review-notice" role="status" hidden><strong>No invoice lines were extracted from this file.</strong><span>Manual line entry is required before approval.</span></div><form id="reviewForm"><input type="hidden" name="id"><div class="cw-form-grid"><label>Supplier<input name="supplier_name" required></label><label>Invoice number<input name="invoice_number" required></label><label>Invoice date<input name="invoice_date" type="date" required></label><label>Currency<input name="currency" maxlength="3" required></label><label>Exchange rate<input name="exchange_rate" type="number" step="0.000001" min="0.000001" required></label><label>VAT treatment<select name="vat_treatment" required><option value="unconfirmed">Confirm treatment</option><option value="inclusive">Inclusive</option><option value="exclusive">Exclusive</option><option value="exempt">Exempt</option><option value="mixed">Mixed</option></select></label><label>Subtotal<input name="subtotal" readonly></label><label>VAT amount<input name="vat_amount" readonly></label><label>Invoice total<input name="invoice_total" readonly></label><label class="wide">Notes<textarea name="notes"></textarea></label></div><div class="cw-toolbar"><h3>Invoice lines</h3><button class="cw-btn" id="addLine" type="button">Add line</button></div><div class="cw-table-wrap"><table><thead><tr><th>Description</th><th>Product</th><th>Qty</th><th>Unit</th><th>Pack size</th><th>Unit cost</th><th>Discount</th><th>Subtotal</th><th>VAT</th><th>Total</th><th>Type</th><th></th></tr></thead><tbody id="reviewLines"></tbody></table></div><div class="cw-dialog-actions"><button class="cw-btn cw-primary" type="submit">Save review</button><button class="cw-btn" id="approveInvoice" type="button">Approve</button></div></form></dialog>
<dialog id="matchDialog" class="cw-dialog"><form method="dialog"><button class="cw-close" aria-label="Close">×</button></form><h2>Match website item</h2><div class="cw-product-filters"><label>Product or variation<input id="matchSearch"></label><label>Category<select id="matchCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><tbody id="matchRows"><tr><td class="cw-empty">Enter a search.</td></tr></tbody></table></div></dialog>
<template id="lineTemplate"><tr><td><input data-k="raw_description"></td><td><input data-k="product_description" required></td><td><input data-k="quantity" type="number" step="0.000001" min="0" required></td><td><select data-k="purchase_unit"><option value="">Confirm</option><option>kg</option><option>g</option><option>L</option><option>ml</option><option>unit</option><option>pack</option></select></td><td><input data-k="pack_size" type="number" step="0.000001" min="0"></td><td><input data-k="unit_price" type="number" step="0.000001" min="0" required></td><td><select data-k="discount_type"><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select><input data-k="discount_value" type="number" step="0.01" min="0" value="0.00"><small data-discount-result></small></td><td><input data-k="line_subtotal" readonly></td><td><select data-k="vat_treatment"><option value="unconfirmed">Invoice treatment</option><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option><option value="exempt">Exempt</option></select><input data-k="calculated_vat_amount" readonly><input data-k="vat_override_amount" type="number" step="0.01" min="0"><input data-k="vat_override_reason" placeholder="Override reason"></td><td><input data-k="line_total" readonly></td><td><select data-k="item_type"><option value="unclassified">Confirm type</option><option value="supplier_raw_material">Raw material</option><option value="website_product">Website product</option><option value="website_variation">Website variation</option><option value="packaging">Packaging</option><option value="additional_cost">Additional cost</option></select><button class="cw-btn" data-match-line type="button">Match</button></td><td><button class="cw-icon" data-remove-line type="button">×</button></td></tr></template>
<?php }

function cw_render_phase2(string $page): void { ?>
<section class="cw-section cw2"><div class="cw-section-body"><div class="cw-toolbar"><div><h2><?= $page==='shipments'?'Shipment workspace':($page==='landed-costs'?'Allocation and reconciliation':'Sale-size product matching') ?></h2><p>Only records required for this page and selected month are loaded.</p></div><?php if($page==='shipments'): ?><button class="cw-btn cw-primary" id="cw2NewShipment" type="button">Create shipment</button><?php endif; ?></div><div class="cw2-grid"><aside class="cw2-list" id="cw2ShipmentList"><p class="cw-empty">Loading shipments…</p></aside><div class="cw2-workspace" id="cw2ShipmentWorkspace"><div class="cw-empty-state"><strong>Select a shipment</strong><p>Opening a shipment never saves data.</p></div></div></div><?php if($page==='landed-costs'): ?><div class="cw-page-calculation"><button class="cw-btn cw-primary" id="cw2Calculate" type="button" disabled>Calculate landed costs</button><button class="cw-btn cw-primary" id="cw2Confirm" type="button" disabled>Confirm calculation</button><div id="cw2Reconciliation" class="cw-empty-state"><strong>No calculation selected</strong></div><div id="cw2LandedLines" class="cw-table-wrap"></div></div><?php elseif($page==='product-matching'): ?><div class="cw-page-calculation"><div id="cw2SaleSizes" class="cw-empty-state"><strong>No landed-cost lines available</strong></div></div><?php endif; ?></div></section>
<?php }

function cw_render_profitability(): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-toolbar"><div><h2>Read-only WooCommerce snapshot</h2><p id="lastSync">No successful sync yet.</p><p id="snapshotStats">No snapshot counts yet.</p><p id="syncStatus">No sync attempt is active.</p></div><div class="cw-actions"><button class="cw-btn cw-primary" id="syncWebsite">Sync Website Data</button><button class="cw-btn" id="recoverSync" hidden>Recover interrupted sync</button></div></div><div class="cw-progress" id="syncProgress" hidden><span></span><p>Starting sync…</p></div><div class="cw-product-filters"><label>Search snapshot<input id="productSearch" placeholder="Product, variation or SKU"></label><label>Category<select id="productCategory"><option value="">All categories</option></select></label></div><div class="cw-table-wrap"><table><thead><tr><th>Product</th><th>Variation</th><th>SKU</th><th>Type</th><th>Category</th><th>Price incl. VAT</th><th>Stock</th><th>Status</th><th>Cost status</th></tr></thead><tbody id="productRows"><tr><td colspan="9" class="cw-empty">No products are available for this period.</td></tr></tbody></table></div></div></section>
<?php }

function cw_render_cogs(): void { ?>
<section class="cw-section"><div class="cw-section-body"><div class="cw-empty-state"><strong>WooCommerce Cost of Goods Sold is not enabled. Cost publishing is unavailable.</strong><p>Profitability figures are private Cost Workbook previews and are not published to WooCommerce.</p><p>Future publishing requires an eligible confirmed cost, exact product or variation match, stale-value check, explicit confirmation, audit record and returned-value verification.</p><button class="cw-btn cw-primary" type="button" disabled aria-disabled="true">Publishing unavailable</button></div></div></section>
<?php }

function cw_render_settings(): void { ?>
<section class="cw-section"><div class="cw-section-body"><form id="settingsForm" class="cw-settings"><label>Base currency<input name="base_currency" maxlength="3" value="NAD" required></label><label>VAT rate (%)<input name="vat_rate" type="number" step="0.01" min="0" value="15" required></label><label>Retail target margin (%)<input name="retail_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Wholesale target margin (%)<input name="wholesale_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Reseller target margin (%)<input name="reseller_target_margin" type="number" step="0.01" min="0" max="99.99"></label><label>Low-margin threshold (%)<input name="low_margin_threshold" type="number" step="0.01" min="0" max="100"></label><div class="cw-help"><p>Settings apply to Cost Workbook calculations only and do not write to WooCommerce.</p></div><button class="cw-btn cw-primary" type="submit">Save settings</button></form></div></section>
<?php }
