<?php
declare(strict_types=1);
function cw_render_landed_product_costs(array $period):void{ ?>
<section class="landed-product-costs" data-lpc-root data-api="landed-product-costs-api-wrapper.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
 <section class="landed-product-costs__summary"><?php foreach([['products','Products'],['suppliers','Suppliers'],['complete','Complete Costs'],['attention','Needs Attention']] as $w):?><article class="landed-product-costs__summary-card"><span class="landed-product-costs__summary-label"><?= $w[1] ?></span><strong class="landed-product-costs__summary-value" data-lpc-summary="<?= $w[0] ?>">0</strong></article><?php endforeach;?></section>
 <form class="landed-product-costs__filters" data-lpc-filters><label>Search<input name="q" type="search" placeholder="Supplier, product, code, SKU or invoice"></label><label>Supplier<select name="supplier"><option value="">All suppliers</option></select></label><label>Category<select name="category"><option value="">All categories</option></select></label><label>Costing Basis<select name="basis"><option value="">All bases</option><option value="weight">Weight</option><option value="volume">Volume</option><option value="count">Count</option><option value="ready_made">Ready-made unit</option></select></label><label>Base Unit<select name="unit"><option value="">All units</option><option>kg</option><option>L</option><option>each</option><option>unit</option></select></label><label>Transport Status<select name="transport"><option value="">All</option><option value="allocated">Allocated</option><option value="missing">Not allocated</option></select></label><label>Packaging Status<select name="packaging"><option value="">All</option><option value="available">Available</option><option value="missing">Missing</option></select></label><label>Cost Status<select name="status"><option value="">All statuses</option><option value="complete">Complete</option><option value="attention">Needs attention</option></select></label><label>From<input name="from" type="date" value="<?= sprintf('%04d-%02d-01',$period['year'],$period['month']) ?>"></label><label>To<input name="to" type="date" value="<?= (new DateTimeImmutable(sprintf('%04d-%02d-01',$period['year'],$period['month'])))->modify('last day of this month')->format('Y-m-d') ?>"></label><button type="reset">Clear Filters</button></form>
 <section class="landed-product-costs__table-card"><div class="landed-product-costs__table-wrap"><table class="landed-product-costs__table"><thead><tr><th>Supplier Name</th><th>Product Name</th><th>Short Code</th><th>Category</th><th>Costing Basis</th><th>Base Unit</th><th>Supplier Cost per Base Unit</th><th>Transport per Base Unit</th><th>Packaging Setups</th><th>Landed Cost per Base Unit</th><th>Supplier Invoice</th><th>Cost Date</th><th>Status</th><th>Actions</th></tr></thead><tbody data-lpc-rows><tr><td colspan="14">Loading product costs…</td></tr></tbody></table></div></section>
 <section class="landed-product-costs__mobile" data-lpc-mobile></section>
</section>
<div class="landed-product-costs__backdrop" data-lpc-backdrop></div><aside class="landed-product-costs__drawer" data-lpc-drawer aria-hidden="true" role="dialog" aria-modal="true"><header><h2>Product cost record</h2><button type="button" data-lpc-close aria-label="Close">×</button></header><form data-lpc-form><input type="hidden" name="id"><div><label>Product name<input name="product_name" required></label><label>Short code<input name="short_code" placeholder="Generated automatically"></label><label>Match WooCommerce product<select name="woo_product_id"><option value="">Not matched</option></select></label><label>Category<select name="product_category" required></select></label><label>Costing basis<select name="costing_basis" required><option value="">Select basis</option><option value="weight">Weight</option><option value="volume">Volume</option><option value="count">Count</option><option value="ready_made">Ready-made unit</option></select></label><label>Base unit<select name="base_unit" required><option value="kg">kg</option><option value="L">L</option><option value="each">each</option><option value="unit">unit</option></select></label><label>Supplier<select name="supplier_id" required></select></label><label>Supplier invoice / reference<input name="manual_reference" required></label><label>Cost date<input name="cost_date" type="date" required></label><label>Total purchased quantity<input name="total_purchased_quantity" type="number" min="0.00000001" step="any" required></label><label>Total supplier cost<input name="total_supplier_cost" type="number" min="0" step="any" required></label><label>VAT treatment<select name="vat_treatment"><option value="recoverable">Recoverable</option><option value="non_recoverable">Non-recoverable</option><option value="exempt">Exempt</option></select></label><label>Transport allocation<input name="transport_allocation" type="number" min="0" step="any" value="0"></label><label>Notes<textarea name="notes"></textarea></label></div><footer><button type="button" data-lpc-close>Cancel</button><button type="submit">Save Manual Product</button></footer></form></aside>
<dialog data-lpc-history><form method="dialog"><button aria-label="Close">×</button></form><h2>Cost history</h2><div data-lpc-history-rows></div></dialog><div class="landed-product-costs__toast" data-lpc-toast hidden></div>
<?php }
