<?php
declare(strict_types=1);

function cw_supplier_types(): array { return ['Raw Materials','Packaging','Equipment & Accessories','Freight & Logistics','Services','Mixed','Uncategorised']; }
function cw_invoice_types(): array { return ['Raw Materials','Packaging','Equipment & Accessories','Freight & Logistics','Services','Mixed']; }
function cw_product_categories(): array { return ['Plant Butters','Carrier Oils','Essential Oils','Hydrosols','Dried Herbs','Powders','Active Ingredients','Preservatives','Emulsifiers','Surfactants','Proteins','Solvents','Waxes','Packaging','Equipment','Accessories','Other']; }
function cw_si_options(array $values,string $first=''): string { $html=$first!==''?'<option value="">'.htmlspecialchars($first,ENT_QUOTES,'UTF-8').'</option>':''; foreach($values as $v)$html.='<option value="'.htmlspecialchars($v,ENT_QUOTES,'UTF-8').'">'.htmlspecialchars($v,ENT_QUOTES,'UTF-8').'</option>'; return $html; }

function cw_render_supplier_invoices(array $period): void { ?>
<section class="supplier-invoices" data-si-root data-api="supplier-invoices-api.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
  <section class="supplier-invoices__upload-panel" data-si-upload-panel>
    <div><h2>Upload supplier invoice</h2><p>Upload a supplier invoice to extract the supplier, invoice details, purchased products, quantities and costs.</p></div>
    <label class="supplier-invoices__upload-zone" data-si-drop><input type="file" data-si-file accept=".pdf,.jpg,.jpeg,.png" hidden><svg class="supplier-invoices__upload-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 15V4m0 0L7.5 8.5M12 4l4.5 4.5M5 14v5h14v-5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg><strong>Drop an invoice here or choose a file</strong><span>PDF, JPG, JPEG or PNG · maximum 15 MB</span><button type="button" class="supplier-invoices__choose" data-si-choose>Choose File</button></label>
    <div class="supplier-invoices__selected" data-si-selected hidden><span data-si-file-name></span><small data-si-file-size></small><button type="button" data-si-remove aria-label="Remove selected file">Remove</button></div>
    <div class="supplier-invoices__upload-actions"><button type="button" class="supplier-invoices__upload-button" data-si-upload disabled>Upload &amp; Extract</button><p role="status" aria-live="polite" data-si-upload-status></p></div>
  </section>
  <section class="supplier-invoices__summary" aria-label="Supplier invoice summary">
    <?php foreach([['Invoices','file-text'],['Extracted Items','list'],['Needs Attention','circle-alert'],['Suppliers','building-2']] as $i=>$w): ?><article class="supplier-invoices__summary-card"><div><i data-lucide="<?= $w[1] ?>" aria-hidden="true"></i><p class="supplier-invoices__summary-label"><?= $w[0] ?></p></div><strong class="supplier-invoices__summary-value" data-si-summary="<?= ['invoices','items','attention','suppliers'][$i] ?>">0</strong></article><?php endforeach; ?>
  </section>
  <form class="supplier-invoices__filters" data-si-filters>
    <label class="supplier-invoices__filter">Date basis<select name="date_basis"><option value="invoice">Invoice date</option><option value="upload">Upload date</option></select></label>
    <label class="supplier-invoices__filter">From date<input type="date" name="from" value="<?= sprintf('%04d-%02d-01',$period['year'],$period['month']) ?>"></label>
    <label class="supplier-invoices__filter">To date<input type="date" name="to" value="<?= (new DateTimeImmutable(sprintf('%04d-%02d-01',$period['year'],$period['month'])))->modify('last day of this month')->format('Y-m-d') ?>"></label>
    <label class="supplier-invoices__filter">Supplier<select name="supplier_id" data-si-supplier-filter><option value="">All suppliers</option></select></label>
    <label class="supplier-invoices__filter">Supplier type<select name="supplier_type"><?= cw_si_options(cw_supplier_types(),'All supplier types') ?></select></label>
    <label class="supplier-invoices__filter">Invoice type<select name="invoice_type"><?= cw_si_options(cw_invoice_types(),'All invoice types') ?></select></label>
    <label class="supplier-invoices__filter">Product category<select name="category"><?= cw_si_options(cw_product_categories(),'All product categories') ?></select></label>
    <label class="supplier-invoices__filter">Status<select name="status"><option value="">All statuses</option><option value="ready">Ready</option><option value="attention">Needs attention</option><option value="extracting">Extracting</option><option value="failed">Failed</option><option value="duplicate">Duplicate</option><option value="archived">Archived</option></select></label>
    <label class="supplier-invoices__filter supplier-invoices__search">Search<input name="q" type="search" placeholder="Supplier, invoice, product or SKU"></label>
    <button type="reset" class="supplier-invoices__clear">Clear Filters</button>
  </form>
  <section class="supplier-invoices__table-card"><div class="supplier-invoices__table-wrap"><table class="supplier-invoices__table"><thead><tr><th>Invoice Date</th><th>Uploaded</th><th>Supplier</th><th>Supplier Type</th><th>Invoice No.</th><th>Product Name</th><th>SKU</th><th>Product Category</th><th class="is-number">Quantity</th><th>Pack Size</th><th class="is-number">Total kg/L</th><th class="is-number">Cost excl. VAT</th><th class="is-number">Cost per kg/L</th><th>Currency</th><th>Status</th><th>Actions</th></tr></thead><tbody data-si-rows><tr><td colspan="16" class="supplier-invoices__empty">Loading supplier invoices…</td></tr></tbody></table></div><footer class="supplier-invoices__pagination"><span data-si-page-info></span><label>Rows <select data-si-page-size><option>25</option><option>50</option><option>100</option></select></label><button type="button" data-si-prev>Previous</button><button type="button" data-si-next>Next</button></footer></section>
</section>
<div class="supplier-invoices__drawer-backdrop" data-si-backdrop></div><aside class="supplier-invoices__drawer" data-si-drawer aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="siDrawerTitle"><header><div><p class="eyebrow">Invoice review</p><h2 id="siDrawerTitle">Review extracted invoice</h2><p>Correct only missing or uncertain fields before saving.</p></div><button type="button" data-si-close aria-label="Close">×</button></header><form data-si-review><input type="hidden" name="id"><div class="supplier-invoices__drawer-scroll"><a data-si-original target="_blank" class="supplier-invoices__original">Open Original File</a><div class="supplier-invoices__warnings" data-si-warnings></div><div class="supplier-invoices__form-grid"><label>Supplier<select name="supplier_id" data-si-review-supplier></select></label><label>Supplier name<input name="supplier_name" required></label><label>Supplier type<select name="supplier_type"><?= cw_si_options(cw_supplier_types()) ?></select></label><label>Invoice type<select name="invoice_type"><?= cw_si_options(cw_invoice_types()) ?></select></label><label>Invoice number<input name="invoice_number" required></label><label>Invoice date<input type="date" name="invoice_date" required></label><label>Currency<input name="currency" maxlength="3" required></label><label>Exchange rate<input name="exchange_rate" type="number" step="0.000001" min="0"></label><label>Subtotal excl. VAT<input name="subtotal" type="number" step="0.01"></label><label>VAT / tax<input name="vat_amount" type="number" step="0.01"></label><label>Invoice total<input name="invoice_total" type="number" step="0.01"></label><label>Shipping / freight<input name="shipping_amount" type="number" step="0.01"></label></div><h3>Extracted items</h3><div class="supplier-invoices__review-lines" data-si-lines></div><button type="button" class="supplier-invoices__add-line" data-si-add-line>Add line item</button></div><footer><button type="button" data-si-cancel>Cancel</button><button type="submit" class="supplier-invoices__upload-button">Save Invoice</button></footer></form></aside>
<template data-si-line-template><article class="supplier-invoices__line"><input type="hidden" data-k="id"><label>Product name<input data-k="product_description" required></label><label>SKU<input data-k="supplier_sku"></label><label>Category<select data-k="product_category"><?= cw_si_options(cw_product_categories()) ?></select></label><label>Quantity<input data-k="quantity" type="number" min="0" step="0.000001"></label><label>Pack size<input data-k="pack_size" type="number" min="0" step="0.000001"></label><label>Unit<select data-k="purchase_unit"><option value="">Confirm unit</option><option>g</option><option>kg</option><option>ml</option><option>L</option><option>unit</option></select></label><label>Cost excl. VAT<input data-k="line_subtotal" type="number" min="0" step="0.01"></label><label>VAT<input data-k="vat_amount" type="number" min="0" step="0.01"></label><label>Notes<input data-k="line_notes"></label><div class="supplier-invoices__calculated"><span data-si-total-base>Needs size</span><strong data-si-cost-base>—</strong></div><button type="button" data-si-remove-line aria-label="Remove line">×</button></article></template>
<?php }
