<?php
declare(strict_types=1);

function cw_render_wholesale_pricing(array $period): void
{ ?>
<section class="wholesale-pricing" data-wp-root data-api="wholesale-pricing-api.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
  <div class="wholesale-pricing__summary">
    <article class="wholesale-pricing__summary-card"><span class="wholesale-pricing__summary-label">Wholesale Products</span><strong class="wholesale-pricing__summary-value" data-wp-products>0</strong></article>
    <article class="wholesale-pricing__summary-card"><span class="wholesale-pricing__summary-label">Active Price Sizes</span><strong class="wholesale-pricing__summary-value" data-wp-active>0</strong></article>
    <article class="wholesale-pricing__summary-card"><span class="wholesale-pricing__summary-label">Below Minimum Margin</span><strong class="wholesale-pricing__summary-value" data-wp-below>0</strong></article>
    <article class="wholesale-pricing__summary-card"><span class="wholesale-pricing__summary-label">Costs Needing Review</span><strong class="wholesale-pricing__summary-value" data-wp-review>0</strong></article>
  </div>
  <form class="wholesale-pricing__filters" data-wp-filters>
    <label>Search<input type="search" name="search" placeholder="Product, code, SKU or size"></label>
    <label>Category<select name="category" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All categories</option></select></label>
    <label>Product type<select name="product_type" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All product types</option><option value="purchased">Purchased product</option><option value="manufactured">Manufactured formulation</option></select></label>
    <label>Wholesale size<select name="size" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All sizes</option></select></label>
    <label>Packaging status<select name="packaging_status" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All packaging</option><option value="setup">Packaging setup</option><option value="manual">Manual packaging</option><option value="none">Not required</option><option value="required">Packaging required</option></select></label>
    <label>Margin status<select name="margin_status" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All margins</option><option value="acceptable">At/above minimum</option><option value="below">Below minimum</option></select></label>
    <label>Price status<select name="status" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All statuses</option><option>Draft</option><option>Ready</option><option>Active</option><option>Future Price</option><option>New Cost Available</option><option>Missing Packaging</option><option>Missing Cost</option><option>Below Minimum Margin</option><option>Expired</option><option>Archived</option></select></label>
    <label>Effective on<input type="date" name="effective_date"></label>
    <label>History<select name="history" data-portal-custom-select data-portal-select-variant="input-vat"><option value="current">Current prices</option><option value="all">Current and historical</option></select></label>
    <button type="reset">Clear Filters</button>
  </form>
  <div class="wholesale-pricing__view-switcher" role="tablist"><button class="wholesale-pricing__view-button" type="button" aria-selected="true" data-wp-view="detail">Detailed Pricing</button><button class="wholesale-pricing__view-button" type="button" aria-selected="false" data-wp-view="matrix">Price Matrix</button></div>
  <section data-wp-detail>
    <div class="wholesale-pricing__table-card"><div class="wholesale-pricing__table-wrap"><table class="wholesale-pricing__table"><thead><tr><th>Product Name</th><th>Short Code</th><th>Category</th><th>Product Type</th><th>Wholesale Size</th><th>Base Cost</th><th>Product Content Cost</th><th>Packaging Source</th><th>Packaging Cost</th><th>Other Costs</th><th>Total Cost excl. VAT</th><th>Pricing Method</th><th>Target Margin</th><th>Price excl. VAT</th><th>VAT</th><th>Price incl. VAT</th><th>Profit</th><th>Margin</th><th>MOQ</th><th>Effective Date</th><th>Status</th><th>Actions</th></tr></thead><tbody data-wp-rows><tr><td colspan="22">Loading wholesale prices…</td></tr></tbody></table></div></div>
    <div class="wholesale-pricing__mobile" data-wp-mobile></div>
  </section>
  <section data-wp-matrix hidden><div class="wholesale-pricing__matrix-tools"><label>Matrix value<select data-wp-matrix-value data-portal-custom-select data-portal-select-variant="input-vat"><option value="price_inc_vat">Price incl. VAT</option><option value="price_ex_vat">Price excl. VAT</option><option value="profit">Profit</option><option value="margin_percent">Margin</option></select></label></div><div class="wholesale-pricing__table-card"><div class="wholesale-pricing__table-wrap"><table class="wholesale-pricing__matrix" data-wp-matrix-table></table></div></div></section>
  <div class="wholesale-pricing__backdrop" data-wp-backdrop hidden></div>
  <aside class="wholesale-pricing__drawer" data-wp-drawer aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="wpDrawerTitle">
    <header><div><p>Wholesale price</p><h2 id="wpDrawerTitle">Add Wholesale Price</h2></div><button type="button" data-wp-close aria-label="Close">×</button></header>
    <form data-wp-form novalidate><input type="hidden" name="id"><input type="hidden" name="new_version" value="0">
      <div class="wholesale-pricing__form-grid">
        <label class="span">Product<select name="product_key" required data-portal-custom-select data-portal-select-variant="input-vat"></select></label><label>Product type<select name="product_type" data-portal-custom-select data-portal-select-variant="input-vat"><option value="purchased">Purchased product</option><option value="manufactured">Manufactured formulation</option></select></label><label>Source cost<input name="base_cost" readonly></label><label>Source-cost date<input name="source_cost_date" readonly></label>
        <label>Wholesale size<select name="size_conversion_id" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">Custom count / pack</option></select></label><label>Size label<input name="wholesale_size_label" required placeholder="Case of 10"></label><label>Quantity<input name="quantity" type="number" min="0.000001" step="any" required></label><label>Unit<select name="unit" data-portal-custom-select data-portal-select-variant="input-vat"><option>kg</option><option>L</option><option>each</option><option>unit</option><option>bottles</option><option>capsules</option></select></label><label>MOQ<input name="moq" type="number" min="1" step="any" value="1"></label>
        <label>Packaging source<select name="packaging_source" data-portal-custom-select data-portal-select-variant="input-vat"><option value="required">Packaging required</option><option value="setup">Packaging setup</option><option value="manual">Manual packaging cost</option><option value="none">No additional packaging</option></select></label><label>Packaging setup<select name="packaging_setup_id" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">Select setup</option></select></label><label>Manual packaging description<input name="packaging_description"></label><label>Packaging cost basis<select name="packaging_cost_basis" data-portal-custom-select data-portal-select-variant="input-vat"><option value="exclusive">Excluding VAT</option><option value="inclusive">Including VAT</option></select></label><label>Packaging VAT treatment<select name="packaging_vat_treatment" data-portal-custom-select data-portal-select-variant="input-vat"><option value="recoverable">Recoverable</option><option value="non_recoverable">Non-recoverable</option><option value="exempt">Exempt</option></select></label><label>Manual packaging amount<input name="manual_packaging_amount" type="number" min="0" step="any" value="0"></label><label class="span">Manual packaging reason or note<input name="packaging_note"></label><label class="span wholesale-pricing__confirm"><input type="checkbox" name="no_packaging_confirmed" value="1"> I confirm no additional packaging is required.</label>
        <fieldset class="span"><legend>Other wholesale costs</legend><label>Repacking labour<input name="repacking_labour" type="number" min="0" step="any" value="0"></label><label>Handling<input name="wholesale_handling" type="number" min="0" step="any" value="0"></label><label>Outer carton<input name="outer_carton" type="number" min="0" step="any" value="0"></label><label>Protective wrapping<input name="protective_wrapping" type="number" min="0" step="any" value="0"></label><label>Pallet contribution<input name="pallet_contribution" type="number" min="0" step="any" value="0"></label><label>Other cost<input name="other_cost" type="number" min="0" step="any" value="0"></label></fieldset>
        <label>Pricing method<select name="pricing_method" data-portal-custom-select data-portal-select-variant="input-vat"><option value="margin">Target Gross Margin %</option><option value="profit">Desired Profit</option><option value="manual">Manual Wholesale Price</option></select></label><label>Target margin %<input name="target_margin" type="number" min="0" max="99.99" step="any"></label><label>Desired profit<input name="desired_profit" type="number" min="0" step="any" value="0"></label><label>Manual price excl VAT<input name="manual_price" type="number" min="0" step="any" value="0"></label><label>Selling VAT rate<input name="selling_vat_rate" readonly></label><label>Price rounding<select name="rounding_rule" data-portal-custom-select data-portal-select-variant="input-vat"><option value="none">No rounding</option><option value="0.50">Nearest N$0.50</option><option value="1">Nearest N$1</option><option value="up1">Round up to N$1</option><option value="up5">Round up to N$5</option><option value="custom">Custom price ending</option></select></label><label>Custom price ending<input name="custom_price_ending" type="number" min="0" max="0.99" step="0.01" value="0.99"></label><label>Effective date<input name="effective_date" type="date" required></label><label>Expiry date<input name="expiry_date" type="date"></label><label>Status<select name="status_key" data-portal-custom-select data-portal-select-variant="input-vat"><option value="draft">Draft</option><option value="ready">Ready</option><option value="active">Active</option><option value="future">Future Price</option></select></label><label class="span">Notes<textarea name="notes"></textarea></label>
        <fieldset class="span wholesale-pricing__tiers"><legend>Optional higher-volume price tiers</legend><p>Each tier is calculated and checked against the configured minimum margin.</p><div data-wp-tiers></div><button type="button" data-wp-add-tier>Add price tier</button></fieldset>
      </div>
      <aside class="wholesale-pricing__calculation" data-wp-calculation></aside><p class="wholesale-pricing__form-error" data-wp-error></p>
      <footer><button type="button" data-wp-cancel>Cancel</button><button type="submit" class="portal-button portal-button--primary">Save Wholesale Price</button></footer>
    </form>
  </aside>
  <div class="wholesale-pricing__toast" data-wp-toast hidden></div>
</section>
<?php }
