<?php
declare(strict_types=1);

function cw_render_formulations(array $period): void
{ ?>
<section class="fc" data-fc-root data-api="formulations-api.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
  <section class="fc-list" data-fc-list-view>
    <div class="fc-summary"><article><span>Formulations</span><strong data-fc-count>0</strong></article><article><span>Active</span><strong data-fc-active>0</strong></article><article><span>Drafts</span><strong data-fc-drafts>0</strong></article></div>
    <div class="fc-filter"><label>Search<input type="search" data-fc-search placeholder="Name, code or category"></label><label>Status<select data-fc-status><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label></div>
    <div class="fc-table-wrap"><table class="fc-table"><thead><tr><th>Formulation</th><th>Code</th><th>Category</th><th>Type</th><th>Version</th><th>Effective</th><th>Status</th><th>Actions</th></tr></thead><tbody data-fc-list><tr><td colspan="8">Loading formulations…</td></tr></tbody></table></div>
  </section>
  <section class="fc-builder" data-fc-builder hidden>
    <div class="fc-builder-bar"><button type="button" data-fc-back>← Formulations</button><span data-fc-version-label>Draft · Version 1</span><div><button type="button" data-fc-duplicate>Duplicate</button><button type="button" data-fc-save>Save Draft</button><button type="button" class="portal-button portal-button--primary" data-fc-new-version>Save New Version</button></div></div>
    <div class="fc-alert" data-fc-alert hidden></div>
    <section class="fc-panel"><h2>Formulation details</h2><div class="fc-grid">
      <label>Formulation name<input name="formulation_name" data-fc-field required></label><label>Code<input name="formulation_code" data-fc-field placeholder="FRM-CB-001"></label><label>Category<input name="category" data-fc-field></label><label>Type<select name="formulation_type" data-fc-field><option value="weight">Weight</option><option value="volume">Volume</option><option value="count">Count</option><option value="mixed">Mixed</option></select></label>
      <label>Reference batch size<input name="reference_batch_size" data-fc-field type="number" min="0.000001" step="any" value="1"></label><label>Batch unit<select name="reference_batch_unit" data-fc-field><option>kg</option><option>g</option><option>L</option><option>ml</option><option>each</option></select></label><label>Expected yield<input name="expected_yield" data-fc-field type="number" min="0.000001" step="any" value="1"></label><label>Yield unit<select name="yield_unit" data-fc-field><option>kg</option><option>g</option><option>L</option><option>ml</option><option>each</option></select></label>
      <label>Loss / waste %<input name="loss_percent" data-fc-field type="number" min="0" max="99.9999" step="any" value="0"></label><label>Status<select name="status_key" data-fc-field><option value="draft">Draft</option><option value="active">Active</option></select></label><label>Effective date<input name="effective_date" data-fc-field type="date"></label><label>Entry mode<select name="mode_key" data-fc-field><option value="quantity">Quantity</option><option value="percentage">Percentage</option></select></label><label class="fc-span">Notes<textarea name="notes" data-fc-field></textarea></label>
    </div></section>
    <section class="fc-panel"><div class="fc-panel-head"><div><h2>Ingredients</h2><p>Costs use the current landed product cost excluding VAT. Mixed weight/volume rows require an explicit density conversion.</p></div><button type="button" data-fc-add-ingredient>Add Ingredient</button></div><div class="fc-table-wrap"><table class="fc-table fc-ingredients"><thead><tr><th>Ingredient</th><th>Code</th><th>Quantity</th><th>Unit</th><th>%</th><th>Converted base quantity</th><th>Landed cost / base</th><th>Source</th><th>Cost contribution</th><th></th></tr></thead><tbody data-fc-ingredients></tbody><tfoot><tr><th colspan="4">Ingredient totals</th><th data-fc-percent-total>0%</th><th></th><th></th><th></th><th data-fc-ingredient-cost>N$0.00</th><th></th></tr></tfoot></table></div></section>
    <div class="fc-two"><section class="fc-panel"><h2>Production costs</h2><div class="fc-grid"><label>Labour<input name="labour" data-fc-production type="number" min="0" step="any" value="0"></label><label>Utilities<input name="utilities" data-fc-production type="number" min="0" step="any" value="0"></label><label>Consumables<input name="consumables" data-fc-production type="number" min="0" step="any" value="0"></label><label>Quality / testing<input name="quality" data-fc-production type="number" min="0" step="any" value="0"></label><label>Other<input name="other" data-fc-production type="number" min="0" step="any" value="0"></label><label>Variable overhead %<input name="variable_overhead_percent" data-fc-production type="number" min="0" step="any" value="0"></label></div></section>
    <section class="fc-panel fc-cost-summary"><h2>Batch cost summary</h2><dl><div><dt>Ingredients</dt><dd data-fc-sum-ingredients>N$0.00</dd></div><div><dt>Production &amp; overhead</dt><dd data-fc-sum-production>N$0.00</dd></div><div><dt>Total batch cost excl VAT</dt><dd data-fc-sum-total>N$0.00</dd></div><div><dt>Cost per yield unit</dt><dd data-fc-sum-unit>N$0.00</dd></div></dl></section></div>
    <section class="fc-panel"><div class="fc-panel-head"><div><h2>Batch scenarios</h2><p>Scale ingredient quantities and apply fixed production costs plus variable overhead.</p></div><button type="button" data-fc-add-batch>Add Scenario</button></div><div class="fc-cards" data-fc-batches></div></section>
    <section class="fc-panel"><div class="fc-panel-head"><div><h2>Selling sizes &amp; pricing</h2><p>Sizes come from Size Conversions; packaging uses the most specific active setup from Packaging Costs.</p></div><button type="button" data-fc-add-size>Add Selling Size</button></div><div class="fc-table-wrap"><table class="fc-table"><thead><tr><th>Selling size</th><th>Packaging setup</th><th>Units / batch</th><th>Product cost</th><th>Packaging cost</th><th>Full unit cost</th><th>Pricing mode</th><th>Margin / profit</th><th>Price excl VAT</th><th>Price incl VAT</th><th></th></tr></thead><tbody data-fc-sizes></tbody></table></div></section>
    <footer class="fc-footer"><small>Formula version 1 · Margin price = full cost ÷ (1 − target margin). Existing versions remain immutable.</small><button type="button" data-fc-archive>Archive formulation</button></footer>
  </section>
  <div class="fc-toast" data-fc-toast hidden></div>
</section>
<?php }
