<?php
declare(strict_types=1);
function cw_render_packaging_costs(array $period):void{ ?>
<section class="packaging-costs" data-pc-root data-api="packaging-costs-api.php" data-csrf="<?= htmlspecialchars(cw_csrf_token(),ENT_QUOTES,'UTF-8') ?>">
 <nav class="packaging-costs__tabs" aria-label="Packaging Costs sections"><a href="?tab=items" data-pc-tab="items">Packaging Items</a><a href="?tab=setups" data-pc-tab="setups">Size Setups</a></nav>
 <section data-pc-panel="items"><form class="packaging-costs__filters" data-pc-item-filters><label>Search<input type="search" name="q" placeholder="Item, supplier or SKU"></label><label>Type<select name="type"><option value="">All types</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="">All</option></select></label></form><div class="packaging-costs__table-wrap"><table><thead><tr><th>Packaging Item</th><th>Type</th><th>Supplier</th><th>Supplier SKU</th><th>Effective Date</th><th>Purchase Quantity</th><th>Cost excl. VAT</th><th>Cost incl. VAT</th><th>Unit Cost excl.</th><th>Unit Cost incl.</th><th>Status</th><th>Actions</th></tr></thead><tbody data-pc-item-rows><tr><td colspan="12">Loading packaging items…</td></tr></tbody></table></div></section>
 <section data-pc-panel="setups" hidden><form class="packaging-costs__filters" data-pc-setup-filters><label>Search<input type="search" name="q" placeholder="Setup, size or scope"></label><label>Scope<select name="scope"><option value="">All scopes</option><option value="product">Product</option><option value="category">Category</option><option value="default">Default</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="">All</option></select></label></form><p class="packaging-costs__priority">Resolution priority: Product-specific → Category default → Global default → No setup.</p><div class="packaging-costs__table-wrap"><table><thead><tr><th>Setup</th><th>Size</th><th>Scope</th><th>Components</th><th>Packaging Cost excl.</th><th>Packaging Cost incl.</th><th>Effective Date</th><th>Status</th><th>Actions</th></tr></thead><tbody data-pc-setup-rows><tr><td colspan="9">Loading size setups…</td></tr></tbody></table></div></section>
</section>
<div class="packaging-costs__backdrop" data-pc-backdrop></div>
<aside class="packaging-costs__drawer" data-pc-item-drawer aria-hidden="true" role="dialog" aria-modal="true"><header><h2>Packaging item</h2><button type="button" data-pc-close aria-label="Close">×</button></header><form data-pc-item-form><input type="hidden" name="id"><div class="packaging-costs__drawer-body"><label>Item name<input name="item_name" required></label><label>Packaging type<select name="packaging_type_id" required></select></label><label>Supplier<input name="supplier_name"></label><label>Supplier SKU<input name="supplier_sku"></label><label>Effective date<input type="date" name="effective_date" required></label><label>Purchase quantity<input type="number" name="purchase_quantity" min="0.000001" step="0.000001" required></label><label>Purchase unit<input name="purchase_unit" placeholder="units, rolls, sheets…" required></label><label>Amount entered (N$)<input type="number" name="amount_entered" min="0" step="0.000001" required></label><label>Cost basis<select name="cost_basis"><option value="inclusive">Including VAT</option><option value="exclusive">Excluding VAT</option></select></label><label>VAT treatment<select name="vat_treatment"><option value="standard">Standard VAT</option><option value="zero_rated">Zero-rated</option><option value="exempt">Exempt</option></select></label><label>VAT rate %<input type="number" name="vat_rate" readonly></label><div class="packaging-costs__calculation" data-pc-item-preview></div><label>Notes<textarea name="notes"></textarea></label><p class="packaging-costs__hint">Saving a changed cost creates a new effective-dated price record; earlier costs remain in history.</p></div><footer><button type="button" data-pc-close>Cancel</button><button type="submit">Save Packaging Item</button></footer></form></aside>
<aside class="packaging-costs__drawer" data-pc-setup-drawer aria-hidden="true" role="dialog" aria-modal="true"><header><h2>Size setup</h2><button type="button" data-pc-close aria-label="Close">×</button></header><form data-pc-setup-form><input type="hidden" name="id"><div class="packaging-costs__drawer-body"><label>Setup name<input name="setup_name" required></label><label>Product size<select name="size_conversion_id" required></select></label><label>Scope<select name="scope_type"><option value="default">Global default</option><option value="category">Category</option><option value="product">Product</option></select></label><label>Scope reference<input name="scope_reference" placeholder="Category or product ID"></label><label>Scope label<input name="scope_label" placeholder="Category or product name"></label><label>Effective date<input type="date" name="effective_date" required></label><h3>Packaging components</h3><div data-pc-components></div><button type="button" data-pc-add-component>Add Component</button><div class="packaging-costs__calculation" data-pc-setup-preview></div></div><footer><button type="button" data-pc-close>Cancel</button><button type="submit">Save Size Setup</button></footer></form></aside>
<template data-pc-component-template><div class="packaging-costs__component"><select data-k="packaging_item_id" required></select><input data-k="quantity" type="number" min="0.000001" step="0.000001" value="1" aria-label="Quantity"><input data-k="waste_percent" type="number" min="0" step="0.01" value="0" aria-label="Waste percent"><button type="button" data-pc-remove-component aria-label="Remove component">×</button></div></template>
<?php }

function cw_render_packaging_summary(): void { ?>
<section class="packaging-costs__summary" aria-label="Packaging summary">
 <?php foreach ([
  ['items','Packaging Items','Materials recorded'],
  ['setups','Active Size Setups','Current packaging setups'],
  ['missing','Missing Size Conversions','Sizes requiring attention'],
  ['average','Average Packaging Cost','Average recorded unit cost'],
 ] as $w): ?><article>
  <div class="packaging-costs__summary-heading">
   <?php if($w[0]==='items'): ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m5 8 7-4 7 4v9l-7 4-7-4V8Zm0 0 7 4m7-4-7 4m0 0v9" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg>
   <?php elseif($w[0]==='setups'): ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 6h14M8 3v6m8-6v6M5 12h14M8 9v6m8-6v6M5 18h14M8 15v6m8-6v6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>
   <?php elseif($w[0]==='missing'): ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 4 3.8 19h16.4L12 4Z" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/><path d="M12 9v4.5M12 16.5h.01" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>
   <?php else: ?><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="5" y="3.5" width="14" height="17" rx="2" stroke="currentColor" stroke-width="1.7"/><path d="M8 7h8M8.5 11h1M12 11h1M15.5 11h1M8.5 14.5h1M12 14.5h1M15.5 14.5h1" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><?php endif; ?>
   <span><?= htmlspecialchars($w[1],ENT_QUOTES,'UTF-8') ?></span>
  </div>
  <strong data-pc-summary="<?= $w[0] ?>">0</strong><small><?= htmlspecialchars($w[2],ENT_QUOTES,'UTF-8') ?></small>
 </article><?php endforeach; ?>
</section>
<?php }
