<?php
declare(strict_types=1);
require_once BASE_PATH.'/shared/database.php';
require_once BASE_PATH.'/shared/auth.php';
require_once BASE_PATH.'/shared/employee-features.php';

function marketing_schema_ready():void{
 static $ready=false;if($ready)return;
 db()->exec("INSERT IGNORE INTO ops_roles(role_key,name,description)VALUES('marketing_sales','Marketing & Sales Assistant','Marketing production, website content and limited sales cover')");
 db()->exec("CREATE TABLE IF NOT EXISTS marketing_work_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,content_type VARCHAR(50) NOT NULL,platform VARCHAR(50) NULL,campaign VARCHAR(190) NULL,product_reference VARCHAR(190) NULL,brief TEXT NULL,objective TEXT NULL,target_audience VARCHAR(190) NULL,owner_notes TEXT NULL,required_dimensions VARCHAR(80) NULL,due_at DATETIME NULL,publish_at DATETIME NULL,priority VARCHAR(20) NOT NULL DEFAULT 'normal',approval_required TINYINT(1) NOT NULL DEFAULT 1,assigned_employee_id INT NULL,status VARCHAR(40) NOT NULL DEFAULT 'brief',caption TEXT NULL,cta VARCHAR(255) NULL,hashtags TEXT NULL,published_url VARCHAR(500) NULL,published_at DATETIME NULL,proof_file VARCHAR(255) NULL,revision_count INT NOT NULL DEFAULT 0,quality_revision_count INT NOT NULL DEFAULT 0,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,cancelled_at DATETIME NULL,KEY idx_marketing_status(status,due_at),KEY idx_marketing_assignee(assigned_employee_id,status),KEY idx_marketing_publish(publish_at,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 db()->exec("CREATE TABLE IF NOT EXISTS marketing_item_versions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,item_id BIGINT UNSIGNED NOT NULL,version_label VARCHAR(40) NOT NULL,file_name VARCHAR(255) NOT NULL,stored_name VARCHAR(255) NOT NULL,mime_type VARCHAR(120) NOT NULL,file_size BIGINT UNSIGNED NOT NULL,asset_status VARCHAR(30) NOT NULL DEFAULT 'draft',uploaded_by INT NOT NULL,uploaded_by_name VARCHAR(190) NOT NULL,uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_marketing_versions(item_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 db()->exec("CREATE TABLE IF NOT EXISTS marketing_item_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,item_id BIGINT UNSIGNED NOT NULL,old_status VARCHAR(40) NULL,new_status VARCHAR(40) NOT NULL,note TEXT NULL,actor_id INT NOT NULL,actor_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_marketing_history(item_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 db()->exec("CREATE TABLE IF NOT EXISTS marketing_product_changes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,woo_product_id BIGINT UNSIGNED NOT NULL,woo_variation_id BIGINT UNSIGNED NOT NULL DEFAULT 0,product_name VARCHAR(255) NOT NULL,change_type VARCHAR(40) NOT NULL DEFAULT 'content',proposed_name VARCHAR(255) NULL,proposed_short_description TEXT NULL,proposed_description MEDIUMTEXT NULL,proposed_seo_title VARCHAR(255) NULL,proposed_meta_description VARCHAR(500) NULL,change_notes TEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'draft',assigned_employee_id INT NULL,submitted_at DATETIME NULL,reviewed_at DATETIME NULL,reviewed_by INT NULL,reviewed_by_name VARCHAR(190) NULL,published_at DATETIME NULL,published_by INT NULL,published_by_name VARCHAR(190) NULL,created_by INT NOT NULL,created_by_name VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_marketing_product_status(status,updated_at),KEY idx_marketing_product(woo_product_id,woo_variation_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 if(marketing_table_exists('cw_product_snapshots')){
  $columns=['description_html'=>'ADD COLUMN description_html MEDIUMTEXT NULL AFTER permalink','short_description_html'=>'ADD COLUMN short_description_html TEXT NULL AFTER description_html','image_count'=>'ADD COLUMN image_count INT NOT NULL DEFAULT 0 AFTER short_description_html','seo_title'=>'ADD COLUMN seo_title VARCHAR(255) NULL AFTER image_count','meta_description'=>'ADD COLUMN meta_description VARCHAR(500) NULL AFTER seo_title'];
  foreach($columns as$name=>$definition)if(!marketing_column_exists('cw_product_snapshots',$name))db()->exec('ALTER TABLE cw_product_snapshots '.$definition);
 }
 $ready=true;
}
function marketing_table_exists(string$table):bool{$q=db()->prepare('SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$table]);return(int)$q->fetchColumn()>0;}
function marketing_column_exists(string$table,string$column):bool{$q=db()->prepare('SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$q->execute([$table,$column]);return(int)$q->fetchColumn()>0;}
function marketing_is_owner():bool{return current_role_key()==='owner_admin';}
function marketing_require_access():void{require_login();if(!portal_user_can_access_feature('marketing')){http_response_code(403);exit('You do not have access to Marketing.');}marketing_schema_ready();}
function marketing_employee_id():int{return(int)(current_user()['id']??0);}
function marketing_scope_sql(array&$params):string{if(marketing_is_owner())return'1=1';$params[]=marketing_employee_id();return'assigned_employee_id=?';}
function marketing_e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function marketing_csrf():string{if(empty($_SESSION['marketing_csrf']))$_SESSION['marketing_csrf']=bin2hex(random_bytes(24));return(string)$_SESSION['marketing_csrf'];}
function marketing_verify():void{if(!hash_equals(marketing_csrf(),(string)($_POST['csrf']??'')))throw new RuntimeException('Your session expired. Refresh and try again.');}
function marketing_statuses():array{return['brief','to_create','in_progress','ready_for_review','changes_requested','approved','scheduled','published','cancelled'];}
function marketing_notify(int$itemId,int$recipient,string$title,string$message):void{if($recipient<=0)return;try{require_once BASE_PATH.'/shared/notifications.php';notifications_create(['title'=>$title,'message'=>$message,'module'=>'marketing','related_type'=>'marketing_item','related_id'=>$itemId,'action_link'=>BASE_URL.'/apps/marketing/index.php?item='.$itemId,'required_delivery'=>1],[$recipient]);}catch(Throwable $e){error_log('Marketing notification failed: '.$e->getMessage());}}
function marketing_notify_owners(int$itemId,string$title,string$message):void{try{require_once BASE_PATH.'/shared/notifications.php';$recipients=notifications_role_recipients(['owner_admin']);if($recipients)notifications_create(['title'=>$title,'message'=>$message,'module'=>'marketing','related_type'=>'marketing_item','related_id'=>$itemId,'action_link'=>BASE_URL.'/apps/marketing/index.php?item='.$itemId,'required_delivery'=>1],$recipients);}catch(Throwable $e){error_log('Marketing owner notification failed: '.$e->getMessage());}}
