<?php
declare(strict_types=1);

function siw_stages(): array {return [
 'reported'=>['label'=>'Reported','employee'=>'reported','step'=>1,'next'=>'AI triage is waiting to start.'],
 'ai_processing'=>['label'=>'AI review in progress','employee'=>'reported','step'=>2,'next'=>'AI is reviewing this report.'],
 'needs_information'=>['label'=>'Needs information','employee'=>'needs_information','step'=>2,'next'=>'The requested employee-observable information is required.'],
 'ai_failed'=>['label'=>'AI review failed','employee'=>'reported','step'=>2,'next'=>'Retry triage or continue with manual engineering review.'],
 'brief_ready'=>['label'=>'Brief ready','employee'=>'under_review','step'=>2,'next'=>'Complete the risk decision.'],
 'awaiting_owner_approval'=>['label'=>'Owner approval required','employee'=>'under_review','step'=>2,'next'=>'Review the technical brief and approve, request information, or defer.'],
 'approved'=>['label'=>'Repair approved','employee'=>'under_review','step'=>3,'next'=>'The durable repair job is waiting to be processed.'],
 'repair_queue_failed'=>['label'=>'Repair queue failed','employee'=>'under_review','step'=>3,'next'=>'Retry the existing queue job or copy the approved Codex brief.'],
 'codex_queued'=>['label'=>'Repair queued','employee'=>'fix_in_progress','step'=>3,'next'=>'The repair will start from the protected queue.'],
 'codex_running'=>['label'=>'Repair in progress','employee'=>'fix_in_progress','step'=>3,'next'=>'The controlled repair is in progress.'],
 'repair_failed'=>['label'=>'Repair failed','employee'=>'fix_in_progress','step'=>3,'next'=>'Review the failure and retry or defer.'],
 'pr_ready'=>['label'=>'Repair ready','employee'=>'fix_in_progress','step'=>3,'next'=>'Start the required test suite.'],
 'testing'=>['label'=>'Testing','employee'=>'testing','step'=>4,'next'=>'Required tests are running.'],
 'tests_failed'=>['label'=>'Tests failed','employee'=>'testing','step'=>4,'next'=>'Repair the failure before deployment.'],
 'ready_to_deploy'=>['label'=>'Ready to deploy','employee'=>'testing','step'=>4,'next'=>'Owner deployment approval is required.'],
 'awaiting_deployment_approval'=>['label'=>'Deployment approval required','employee'=>'testing','step'=>4,'next'=>'Approve deployment or defer.'],
 'deploying'=>['label'=>'Deploying','employee'=>'testing','step'=>4,'next'=>'Deployment is in progress.'],
 'deployment_failed'=>['label'=>'Deployment failed','employee'=>'reopened','step'=>4,'next'=>'Review the failure and retry safely.'],
 'verification_pending'=>['label'=>'Live verification required','employee'=>'testing','step'=>5,'next'=>'Confirm whether the original problem is fixed on the live portal.'],
 'verification_failed'=>['label'=>'Live verification failed','employee'=>'reopened','step'=>5,'next'=>'The issue remains open for further repair.'],
 'done'=>['label'=>'Done','employee'=>'done','step'=>5,'next'=>'The repair passed deployment and live verification.'],
 'deferred'=>['label'=>'Deferred','employee'=>'deferred','step'=>2,'next'=>'Resume review when the issue is ready.'],
 'duplicate'=>['label'=>'Duplicate','employee'=>'under_review','step'=>2,'next'=>'Review the linked issue.'],
 'manual_engineering_required'=>['label'=>'Manual engineering required','employee'=>'deferred','step'=>3,'next'=>'Manual intervention is required.'],
 'reopened'=>['label'=>'Reopened','employee'=>'reopened','step'=>3,'next'=>'Review the new evidence and restart the repair.'],
];}

function siw_normalise_stage(array $issue): string {$raw=(string)($issue['workflow_stage']??'');$map=['awaiting_approval'=>'awaiting_owner_approval','owner_approval_required'=>'awaiting_owner_approval','approved_for_repair'=>'approved','repair_queued'=>'codex_queued','repair_in_progress'=>'codex_running','pr_open'=>'pr_ready','tests_passed'=>'ready_to_deploy','deployed'=>'verification_pending','verified'=>empty($issue['verified_at'])?'verification_pending':'done'];$stage=$map[$raw]??$raw;if(isset(siw_stages()[$stage]))return $stage;$legacy=(string)($issue['internal_status']??'reported');return $map[$legacy]??(isset(siw_stages()[$legacy])?$legacy:'reported');}

function siw_command_registry(): array {return [
 'approve_repair'=>['from'=>['awaiting_owner_approval'],'to'=>'approved','label'=>'Approve Repair','pending'=>'Approving…','event'=>'repair_approved','message'=>'approved the issue for controlled repair.','primary'=>true],
 'request_information'=>['from'=>['awaiting_owner_approval','brief_ready'],'to'=>'needs_information','label'=>'Request Information','pending'=>'Opening request…','event'=>'information_requested','message'=>'requested more employee-observable information.'],
 'defer_issue'=>['from'=>['awaiting_owner_approval','repair_failed','tests_failed','awaiting_deployment_approval','reopened'],'to'=>'deferred','label'=>'Defer Issue','pending'=>'Deferring…','event'=>'issue_deferred','message'=>'deferred the issue.'],
 'resume_review'=>['from'=>['deferred'],'to'=>'awaiting_owner_approval','label'=>'Resume Review','pending'=>'Resuming…','event'=>'review_resumed','message'=>'resumed owner review.','primary'=>true],
 'retry_repair'=>['from'=>['repair_failed','tests_failed','verification_failed','reopened'],'to'=>'codex_queued','label'=>'Retry Repair','pending'=>'Queueing…','event'=>'repair_requeued','message'=>'queued another controlled repair attempt.','primary'=>true,'outbox'=>true],
 'approve_deployment'=>['from'=>['awaiting_deployment_approval'],'to'=>'deploying','label'=>'Approve Deployment','pending'=>'Approving…','event'=>'deployment_approved','message'=>'approved the tested repair for deployment.','primary'=>true,'outbox'=>true],
 'confirm_fixed'=>['from'=>['verification_pending'],'to'=>'done','label'=>'Confirm Fixed on Live Site','pending'=>'Confirming…','event'=>'issue_completed','message'=>'confirmed the repair on the live portal.','primary'=>true,'requires_verification'=>true],
 'still_not_fixed'=>['from'=>['verification_pending'],'to'=>'verification_failed','label'=>'Still Not Fixed','pending'=>'Saving…','event'=>'verification_failed','message'=>'reported that the live issue is still not fixed.'],
 'retry_queue'=>['from'=>['approved','repair_queue_failed'],'to'=>'approved','label'=>'Retry Queue','pending'=>'Retrying…','event'=>'repair_queue_retried','message'=>'retried the existing controlled repair queue job.','primary'=>true],
];}

function siw_permitted_actions(string $stage): array {$result=[];foreach(siw_command_registry() as $command=>$rule)if(in_array($stage,$rule['from'],true))$result[]=['command'=>$command,'label'=>$rule['label'],'pending_label'=>$rule['pending'],'primary'=>(bool)($rule['primary']??false)];return $result;}
function siw_has_blocking_employee_request(array $issue,bool $lock=false): bool {
 if(array_key_exists('blocking_request_count',$issue))return (int)$issue['blocking_request_count']>0;
 $issueId=(int)($issue['id']??0);if($issueId<1)return !empty($issue['has_blocking_employee_request']);
 $suffix=$lock?' FOR UPDATE':'';
 return (bool)ops_rows("SELECT id FROM system_issue_information_requests WHERE issue_id=? AND audience='employee' AND is_blocking=1 AND status='pending' LIMIT 1".$suffix,[$issueId]);
}
function siw_automation_configured(): bool {if(!defined('SYSTEM_ISSUES_WORKER_SECRET')||SYSTEM_ISSUES_WORKER_SECRET==='')return false;try{return (bool)ops_rows("SELECT nonce_hash FROM system_issue_worker_nonces WHERE worker_identifier='github-actions' ORDER BY created_at DESC LIMIT 1");}catch(Throwable $e){return false;}}
function siw_queue_state(array $issue): array {
 $issueId=(int)($issue['id']??0);$job=$issueId>0?(ops_rows('SELECT id,status,attempts,last_error,available_at,created_at,processed_at FROM system_issue_workflow_outbox WHERE issue_id=? ORDER BY id DESC LIMIT 1',[$issueId])[0]??null):null;$configured=siw_automation_configured();$age=$job?max(0,time()-strtotime((string)$job['created_at'])):0;$delayed=$job&&in_array($job['status'],['pending','retry'],true)&&$age>=60;
 return ['automation_configured'=>$configured,'queue_job_id'=>$job?(int)$job['id']:null,'queue_status'=>$job?(string)$job['status']:'missing','queue_attempts'=>$job?(int)$job['attempts']:0,'queue_created_at'=>$job['created_at']??null,'queue_available_at'=>$job['available_at']??null,'queue_processed_at'=>$job['processed_at']??null,'queue_last_error'=>$job&&!empty($job['last_error'])?'The repair integration could not process this job.':null,'queue_delayed'=>(bool)$delayed];
}
function siw_view(array $issue): array {
 $stage=siw_normalise_stage($issue);$blocking=siw_has_blocking_employee_request($issue);
 if($blocking&&in_array($stage,['reported','ai_processing','needs_information','brief_ready','awaiting_owner_approval'],true)){$stage='needs_information';}
 elseif(!$blocking&&$stage==='needs_information'){$stage='awaiting_owner_approval';}
 $definition=siw_stages()[$stage];$actions=$blocking?array_values(array_filter(siw_permitted_actions($stage),fn(array $action):bool=>$action['command']!=='approve_repair')):siw_permitted_actions($stage);
 $result=['issue_id'=>(int)($issue['id']??0),'internal_status'=>$blocking?'needs_information':($stage==='awaiting_owner_approval'?'brief_ready':$stage),'workflow_stage'=>$stage,'workflow_version'=>(int)($issue['workflow_version']??1),'workflow_label'=>$blocking?'Waiting for employee information':$definition['label'],'employee_status'=>$blocking?'needs_information':$definition['employee'],'employee_status_label'=>system_issue_status_label($blocking?'needs_information':$definition['employee']),'approval_allowed'=>!$blocking&&$stage==='awaiting_owner_approval','message'=>'Workflow state loaded.','next_step'=>$blocking?'Approval becomes available after the required information is received.':$definition['next'],'next_required_action'=>$blocking?'Wait for the requested employee information.':$definition['next'],'progress_step'=>$definition['step'],'permitted_actions'=>$actions,'blocking_employee_request'=>$blocking];
 if(in_array($stage,['approved','repair_queue_failed','codex_queued','codex_running'],true)){$result=array_merge($result,siw_queue_state($issue));if(!$result['automation_configured']){$result['next_step']='Repair approved, but automated repair processing has not been configured.';$result['next_required_action']=$result['next_step'];$result['permitted_actions']=[['command'=>'copy_codex_brief','label'=>'Copy Codex Brief','pending_label'=>'Copying…','primary'=>true]];}elseif($result['queue_delayed']){$result['next_step']='The repair was approved, but processing has not started.';$result['next_required_action']=$result['next_step'];$result['permitted_actions']=[['command'=>'retry_queue','label'=>'Retry Queue','pending_label'=>'Retrying…','primary'=>true],['command'=>'copy_codex_brief','label'=>'Copy Codex Brief','pending_label'=>'Copying…','primary'=>false]];}}
 return $result;
}

function siw_execute(int $issueId,string $command,string $expectedStage,int $expectedVersion,string $idempotencyKey,string $note=''): array {
 if(!isset(siw_command_registry()[$command]))throw new DomainException('invalid_command');if(!preg_match('/^[A-Za-z0-9._:-]{16,80}$/',$idempotencyKey))throw new InvalidArgumentException('invalid_idempotency_key');
 $actor=(int)(current_user()['id']??0);$actorName=(string)(current_user()['name']??'Owner');$rule=siw_command_registry()[$command];db()->beginTransaction();try{
  $existing=ops_rows('SELECT response_json FROM system_issue_workflow_actions WHERE issue_id=? AND idempotency_key=? FOR UPDATE',[$issueId,$idempotencyKey])[0]??null;if($existing&&$existing['response_json']){db()->commit();return (array)json_decode((string)$existing['response_json'],true);}
  $issue=ops_rows('SELECT * FROM system_issues WHERE id=? FOR UPDATE',[$issueId])[0]??null;if(!$issue)throw new OutOfBoundsException('issue_not_found');$stage=siw_normalise_stage($issue);$version=(int)($issue['workflow_version']??1);
  if($stage!==$expectedStage||$version!==$expectedVersion)throw new UnexpectedValueException('stale_workflow');if(!in_array($stage,$rule['from'],true))throw new DomainException('invalid_transition');
  if($command==='approve_repair'&&siw_has_blocking_employee_request($issue,true))throw new LogicException('pending_information');
  if($command==='confirm_fixed'){$integration=ops_rows('SELECT * FROM system_issue_integrations WHERE issue_id=? ORDER BY id DESC LIMIT 1 FOR UPDATE',[$issueId])[0]??null;if(!$integration||empty($integration['tests_passed_at'])||empty($integration['deployed_at'])||!empty($integration['rollback_active']))throw new LogicException('verification_prerequisite');}
  if($command==='retry_queue'){$job=ops_rows("SELECT * FROM system_issue_workflow_outbox WHERE issue_id=? AND event_type='approve_repair' ORDER BY id DESC LIMIT 1 FOR UPDATE",[$issueId])[0]??null;if(!$job)throw new LogicException('queue_job_missing');db()->prepare("UPDATE system_issue_workflow_outbox SET status='retry',attempts=attempts+1,available_at=NOW(),last_error=NULL WHERE id=?")->execute([(int)$job['id']]);system_issue_event($issueId,'repair_queue_retried',$stage,$stage,$actorName.' retried the existing controlled repair queue job.',['outbox_id'=>(int)$job['id']]);$result=siw_view($issue);$result['message']='The existing repair queue job was made available for retry.';$result['activity_event']=['title'=>'Repair Queue Retried','message'=>$actorName.' retried the existing controlled repair queue job.','created_at_display'=>date('j M Y · H:i')];$encoded=json_encode($result,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);db()->prepare('INSERT INTO system_issue_workflow_actions(issue_id,idempotency_key,command,response_json) VALUES(?,?,?,?)')->execute([$issueId,$idempotencyKey,$command,$encoded]);db()->commit();return $result;}
  $to=$rule['to'];$target=siw_stages()[$to];$newVersion=$version+1;$now=date('Y-m-d H:i:s');$approvedAt=$command==='approve_repair'?$now:($issue['approved_at']??null);$approvedBy=$command==='approve_repair'?$actor:($issue['approved_by']??null);$verifiedAt=$command==='confirm_fixed'?$now:($issue['verified_at']??null);$verifiedBy=$command==='confirm_fixed'?$actor:($issue['verified_by']??null);$doneAt=$command==='confirm_fixed'?$now:($issue['done_at']??null);
  db()->prepare('UPDATE system_issues SET workflow_stage=?,workflow_version=?,employee_status=?,internal_status=?,approved_at=?,approved_by=?,verified_at=?,verified_by=?,done_at=? WHERE id=?')->execute([$to,$newVersion,$target['employee'],$to,$approvedAt,$approvedBy,$verifiedAt,$verifiedBy,$doneAt,$issueId]);
  $eventMessage=$actorName.' '.$rule['message'];system_issue_event($issueId,$rule['event'],$stage,$to,$eventMessage,['command'=>$command,'workflow_version'=>$newVersion,'authenticated_actor_user_id'=>$actor,'note'=>$note]);
 if($command==='approve_repair'){$brief=ops_rows('SELECT * FROM system_issue_ai_briefs WHERE issue_id=? AND is_current=1 AND ai_brief_json IS NOT NULL ORDER BY version_number DESC,id DESC LIMIT 1',[$issueId])[0]??null;if(!$brief)throw new LogicException('approved_brief_missing');$briefVersion=(int)$brief['version_number'];$dedupe='system_issue:'.$issueId.':approved_brief:'.$briefVersion.':repair_attempt:1';$payload=['issue_id'=>$issueId,'command'=>$command,'workflow_version'=>$newVersion,'approved_brief_version'=>$briefVersion,'immutable_codex_brief'=>system_issue_brief_plain_text($issue,$brief),'base_branch'=>'main','direct_main_write'=>false];db()->prepare("INSERT INTO system_issue_workflow_outbox(issue_id,approved_brief_id,approved_brief_version,event_type,deduplication_key,payload_json,status) VALUES(?,?,?,?,?,?,'pending')")->execute([$issueId,(int)$brief['id'],$briefVersion,$command,$dedupe,json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}elseif(!empty($rule['outbox'])){$payload=['issue_id'=>$issueId,'command'=>$command,'workflow_version'=>$newVersion];db()->prepare("INSERT INTO system_issue_workflow_outbox(issue_id,event_type,payload_json,status) VALUES(?,?,?,'pending')")->execute([$issueId,$command,json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}
  $fresh=$issue;$fresh['workflow_stage']=$to;$fresh['workflow_version']=$newVersion;$result=siw_view($fresh);$result['message']=$command==='approve_repair'?'The repair was approved successfully.':$target['label'].' saved successfully.';$result['activity_event']=['title'=>ucwords(str_replace('_',' ',$rule['event'])),'message'=>$eventMessage,'created_at_display'=>date('j M Y · H:i')];$encoded=json_encode($result,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);db()->prepare('INSERT INTO system_issue_workflow_actions(issue_id,idempotency_key,command,response_json) VALUES(?,?,?,?)')->execute([$issueId,$idempotencyKey,$command,$encoded]);db()->commit();return $result;
 }catch(Throwable $error){if(db()->inTransaction())db()->rollBack();throw $error;}
}
