<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/accounts-amendments.php';amendments_require_access();amendments_schema_ready();
$pageTitle='Accounting Amendments | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/accounts-amendments.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-amendments.css')],['path'=>'assets/css/accounts-amendments-buttons.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-amendments-buttons.css')]];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page amendments-page" id="amendmentsPage" data-api="amendments-api.php">
 <header class="accounts-hero"><div><p class="eyebrow">Finance workspace</p><h1>Amendments</h1><p>Shared accounting correction discussions between the accountant and owner.</p></div><button class="portal-button portal-button--primary" id="newAmendment">New amendment</button></header>
 <section class="amendment-filters"><input id="amendmentSearch" placeholder="Search subject or reference"><select id="amendmentStatus"><option value="">All statuses</option><option value="open">Open</option><option value="accountant_responded">Accountant responded</option><option value="owner_responded">Owner responded</option><option value="needs_more_information">Needs more information</option><option value="resolved">Resolved</option></select></section>
 <div class="amendment-layout"><section class="amendment-list" id="amendmentList" aria-live="polite"></section><section class="amendment-thread" id="amendmentThread"><div class="amendment-empty">Select an amendment to view its audit trail.</div></section></div>
 <dialog id="amendmentDialog"><form id="amendmentForm" enctype="multipart/form-data"><header><div><p class="eyebrow">Accounting correction</p><h2>New amendment</h2></div><button type="button" data-close aria-label="Close">×</button></header><label>Subject<input name="subject" required maxlength="190"></label><label>Application<select name="application_key"><?php foreach(amendments_allowed_applications() as $key=>$label):?><option value="<?=htmlspecialchars($key)?>"><?=htmlspecialchars($label)?></option><?php endforeach;?></select></label><div class="amendment-two"><label>Period<input name="period_key" placeholder="YYYY-MM"></label><label>Reference<input name="related_reference"></label></div><label>Message<textarea name="message" required rows="6"></textarea></label><label>Evidence<input type="file" name="files[]" multiple accept=".pdf,.jpg,.jpeg,.png,.csv,.xls,.xlsx"></label><footer><button type="button" class="portal-button portal-button--secondary" data-close>Cancel</button><button class="portal-button portal-button--primary">Create amendment</button></footer></form></dialog>
</main>
<script src="<?=BASE_URL?>/assets/js/accounts-amendments.js?v=<?=filemtime(BASE_PATH.'/assets/js/accounts-amendments.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
