<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/accounts-amendments.php';amendments_require_access();amendments_schema_ready();
$pageTitle='Accounting Amendments | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/accounts-amendments.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-amendments.css')]];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page amendments-page" id="amendmentsPage" data-api="amendments-api.php">
 <header class="accounts-hero amendments-hero"><div><p class="eyebrow">Finance workspace</p><h1>Amendments</h1><p>Shared accounting correction discussions between the accountant and owner.</p></div><button class="portal-button portal-button--primary amendment-primary-action" id="newAmendment"><i data-lucide="file-pen-line" aria-hidden="true"></i>New amendment</button></header>
 <section class="amendment-filters" aria-label="Amendment filters"><label class="amendment-search"><span>Search</span><span class="amendment-search-field"><i data-lucide="search" aria-hidden="true"></i><input id="amendmentSearch" placeholder="Search subject or reference"></span></label><label><span>Status</span><select id="amendmentStatus" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All statuses</option><option value="open">Open</option><option value="accountant_responded">Accountant responded</option><option value="owner_responded">Owner responded</option><option value="needs_more_information">Needs more information</option><option value="resolved">Resolved</option></select></label></section>
 <div class="amendment-layout"><section class="amendment-list" id="amendmentList" aria-live="polite"></section><section class="amendment-thread" id="amendmentThread"><div class="amendment-empty amendment-empty--thread"><span class="amendment-empty__icon"><i data-lucide="message-square-text" aria-hidden="true"></i></span><strong>Select an amendment</strong><p>Select an amendment to view its conversation and audit trail.</p></div></section></div>
 <dialog id="amendmentDialog" class="amendment-modal"><form id="amendmentForm" enctype="multipart/form-data"><header><div><p class="eyebrow">Accounting correction</p><h2>New amendment</h2></div><button type="button" class="amendment-close" data-close aria-label="Close"><i data-lucide="x" aria-hidden="true"></i></button></header><div class="amendment-modal__body"><label>Subject<input name="subject" required maxlength="190"></label><label>Application<select name="application_key" data-portal-custom-select data-portal-select-variant="input-vat" required><option value="">Select application</option><?php foreach(amendments_allowed_applications() as $key=>$label):?><option value="<?=htmlspecialchars($key)?>"><?=htmlspecialchars($label)?></option><?php endforeach;?></select></label><div class="amendment-two"><label>Period<input name="period_key" placeholder="YYYY-MM"></label><label>Reference<input name="related_reference"></label></div><label>Message<textarea name="message" required rows="6"></textarea></label><div class="amendment-upload"><div class="amendment-upload__top"><div><strong><i data-lucide="paperclip" aria-hidden="true"></i>Evidence</strong><small>PDF, JPG, PNG or supported accounting files</small></div><button type="button" class="amendment-secondary-action" data-amendment-files><i data-lucide="upload" aria-hidden="true"></i>Choose files</button></div><input id="amendmentFiles" type="file" name="files[]" multiple accept=".pdf,.jpg,.jpeg,.png,.csv,.xls,.xlsx" hidden><div class="amendment-files-list" data-amendment-files-list></div><small class="amendment-upload__empty" data-amendment-files-empty>No files selected.</small></div></div><footer><button type="button" class="amendment-secondary-action" data-close>Cancel</button><button class="amendment-primary-action"><i data-lucide="message-square-plus" aria-hidden="true"></i>Create amendment</button></footer></form></dialog>
</main>
<script src="<?=BASE_URL?>/assets/js/accounts-amendments.js?v=<?=filemtime(BASE_PATH.'/assets/js/accounts-amendments.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
