<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/accounts-assets.php';
accounts_assets_require_access(); accounts_assets_schema_ready(); header('Cache-Control: no-store');

function ar_reply(array $data,int $status=200): void { http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit; }
function ar_date(string $value,bool $optional=false): ?string { if($optional&&$value==='')return null;if(!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/',$value,$m)||!checkdate((int)$m[2],(int)$m[3],(int)$m[1]))throw new RuntimeException('Enter a valid date.');return $value; }
function ar_uploads(int $assetId): void {
    if(empty($_FILES['files']['name']))return;$names=(array)$_FILES['files']['name'];if(count($names)>10)throw new RuntimeException('Upload no more than 10 files at once.');
    $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf','text/plain'=>'txt','text/csv'=>'csv','application/csv'=>'csv','application/msword'=>'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx','application/vnd.ms-excel'=>'xls','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'=>'xlsx'];
    $dir=BASE_PATH.'/uploads/assets';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Protected attachment storage is unavailable.');
    foreach($names as $i=>$name){if((int)($_FILES['files']['error'][$i]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('An attachment did not upload successfully.');$tmp=(string)$_FILES['files']['tmp_name'][$i];$size=(int)($_FILES['files']['size'][$i]??0);if(!is_uploaded_file($tmp)||$size<=0||$size>25*1024*1024)throw new RuntimeException('Each attachment must be between 1 byte and 25 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp)?:'';if(!isset($allowed[$mime]))throw new RuntimeException('That attachment type is not allowed.');$stored=bin2hex(random_bytes(24)).'.'.$allowed[$mime];if(!move_uploaded_file($tmp,$dir.'/'.$stored))throw new RuntimeException('An attachment could not be stored.');$main=strpos($mime,'image/')===0?1:0;db()->prepare('INSERT INTO accounts_asset_attachments(asset_id,document_type,original_filename,stored_filename,mime_type,file_size,is_main_photo,uploaded_by) VALUES(?,?,?,?,?,?,?,?)')->execute([$assetId,'evidence',mb_substr(basename(str_replace('\\','/',(string)$name)),0,255),$stored,$mime,$size,$main,(int)(current_user()['id']??0)]);}
}

try{
 $action=(string)($_REQUEST['action']??'list');
 if($action==='export'){
   $rows=db()->query('SELECT asset_name,category,internal_reference,purchase_date,supplier,purchase_price,vat_amount,purchase_price_excl_vat,serial_number,model,brand,location_name,assigned_to,condition_key,asset_status,warranty_expiry,useful_life_months,depreciation_method,accumulated_depreciation,book_value FROM accounts_assets WHERE archived_at IS NULL ORDER BY asset_name')->fetchAll();
   header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="asset-register-'.date('Y-m-d').'.csv"');$out=fopen('php://output','wb');$head=['asset_name','category','internal_reference','purchase_date','supplier','purchase_price','vat_amount','purchase_price_excl_vat','serial_number','model','brand','location_name','assigned_to','condition_key','asset_status','warranty_expiry','useful_life_months','depreciation_method','accumulated_depreciation','book_value'];fputcsv($out,$head);foreach($rows as $row)fputcsv($out,$row);fclose($out);exit;
 }
 if($action==='list'){
   $where='archived_at IS NULL';$params=[];
   foreach(['category','condition_key','location_name','asset_status'] as $field){$value=trim((string)($_GET[$field]??''));if($value!==''){$where.=' AND '.$field.'=?';$params[]=$value;}}
   $search=trim((string)($_GET['search']??''));if($search!==''){$where.=' AND (asset_name LIKE ? OR internal_reference LIKE ? OR serial_number LIKE ? OR supplier LIKE ?)';for($i=0;$i<4;$i++)$params[]='%'.$search.'%';}
   $stmt=db()->prepare('SELECT * FROM accounts_assets WHERE '.$where.' ORDER BY asset_name,id DESC');$stmt->execute($params);$rows=array_map('accounts_asset_payload',$stmt->fetchAll());
   $all=db()->query("SELECT COUNT(*) total,COALESCE(SUM(purchase_price),0) total_value,SUM(asset_status='active') active_count,SUM(condition_key='requires_attention' OR asset_status='in_repair') attention_count FROM accounts_assets WHERE archived_at IS NULL")->fetch();
   $source=db()->query("SELECT id,purchase_date,supplier,description,invoice_reference,amount_incl_vat,vat_amount,amount_excl_vat FROM accounts_input_vat_purchases WHERE deleted_at IS NULL ORDER BY purchase_date DESC,id DESC LIMIT 500")->fetchAll();
   ar_reply(['ok'=>true,'rows'=>$rows,'summary'=>['total'=>(int)$all['total'],'value'=>(float)$all['total_value'],'active'=>(int)$all['active_count'],'attention'=>(int)$all['attention_count']],'options'=>accounts_asset_options(),'source_purchases'=>$source]);
 }
 if($action==='detail'){$id=(int)($_GET['id']??0);$asset=accounts_asset_find($id);if(!$asset)ar_reply(['ok'=>false,'error'=>'Asset not found.'],404);$history=db()->prepare('SELECT action_key,note,actor_name,created_at FROM accounts_asset_history WHERE asset_id=? ORDER BY id DESC');$history->execute([$id]);$maintenance=db()->prepare('SELECT * FROM accounts_asset_maintenance WHERE asset_id=? ORDER BY maintenance_date DESC,id DESC');$maintenance->execute([$id]);ar_reply(['ok'=>true,'asset'=>accounts_asset_payload($asset),'history'=>$history->fetchAll(),'maintenance'=>$maintenance->fetchAll()]);}
 accounts_verify_csrf((string)($_POST['csrf']??''));
 if($action==='save'){
   $id=(int)($_POST['id']??0);$before=$id?accounts_asset_find($id):null;if($id&&!$before)throw new RuntimeException('Asset not found.');
   $name=trim((string)($_POST['asset_name']??''));$category=trim((string)($_POST['category']??''));$location=trim((string)($_POST['location_name']??''));if($name===''||$category===''||$location==='')throw new RuntimeException('Asset name, category and location are required.');
   $purchaseDate=ar_date((string)($_POST['purchase_date']??''));$purchase=max(0,(float)($_POST['purchase_price']??0));$vat=max(0,(float)($_POST['vat_amount']??0));$exclusive=max(0,(float)($_POST['purchase_price_excl_vat']??($purchase-$vat)));$method=trim((string)($_POST['depreciation_method']??''));$life=(int)($_POST['useful_life_months']??0);if($method!==''&&$life<=0)throw new RuntimeException('Useful life is required when a depreciation method is selected.');
   $fields=['asset_name'=>$name,'category'=>$category,'internal_reference'=>trim((string)($_POST['internal_reference']??''))?:null,'source_purchase_id'=>(int)($_POST['source_purchase_id']??0)?:null,'purchase_date'=>$purchaseDate,'supplier'=>trim((string)($_POST['supplier']??''))?:null,'purchase_price'=>$purchase,'vat_amount'=>$vat,'purchase_price_excl_vat'=>$exclusive,'serial_number'=>trim((string)($_POST['serial_number']??''))?:null,'model'=>trim((string)($_POST['model']??''))?:null,'brand'=>trim((string)($_POST['brand']??''))?:null,'location_name'=>$location,'assigned_to'=>trim((string)($_POST['assigned_to']??''))?:null,'assigned_date'=>ar_date((string)($_POST['assigned_date']??''),true),'condition_key'=>(string)($_POST['condition_key']??'good'),'asset_status'=>(string)($_POST['asset_status']??'active'),'warranty_start'=>ar_date((string)($_POST['warranty_start']??''),true),'warranty_expiry'=>ar_date((string)($_POST['warranty_expiry']??''),true),'useful_life_months'=>$life>0?$life:null,'depreciation_method'=>$method?:null,'depreciation_start_date'=>ar_date((string)($_POST['depreciation_start_date']??''),true),'accumulated_depreciation'=>max(0,(float)($_POST['accumulated_depreciation']??0)),'book_value'=>max(0,(float)($_POST['book_value']??$exclusive)),'notes'=>trim((string)($_POST['notes']??''))?:null];
   $user=current_user();if($id){$sets=[];$values=[];foreach($fields as $key=>$value){$sets[]=$key.'=?';$values[]=$value;}$sets[]='updated_by=?';$sets[]='updated_by_name=?';$values[]=(int)($user['id']??0);$values[]=(string)($user['name']??'Portal user');$values[]=$id;db()->prepare('UPDATE accounts_assets SET '.implode(',',$sets).' WHERE id=?')->execute($values);}else{$fields['created_by']=(int)($user['id']??0);$fields['created_by_name']=(string)($user['name']??'Portal user');$columns=array_keys($fields);db()->prepare('INSERT INTO accounts_assets('.implode(',',$columns).') VALUES('.implode(',',array_fill(0,count($columns),'?')).')')->execute(array_values($fields));$id=(int)db()->lastInsertId();}
   ar_uploads($id);$after=accounts_asset_find($id);accounts_asset_audit($id,$before?'updated':'created',$before,$after);ar_reply(['ok'=>true,'message'=>$before?'Asset updated.':'Asset added.','asset'=>accounts_asset_payload($after)]);
 }
 if($action==='maintenance'){$id=(int)($_POST['id']??0);if(!accounts_asset_find($id))throw new RuntimeException('Asset not found.');$date=ar_date((string)($_POST['maintenance_date']??''));$description=trim((string)($_POST['description']??''));if($description==='')throw new RuntimeException('Maintenance description is required.');$u=current_user();db()->prepare('INSERT INTO accounts_asset_maintenance(asset_id,maintenance_date,description,cost,supplier,notes,created_by,created_by_name) VALUES(?,?,?,?,?,?,?,?)')->execute([$id,$date,$description,max(0,(float)($_POST['cost']??0)),trim((string)($_POST['supplier']??''))?:null,trim((string)($_POST['notes']??''))?:null,(int)($u['id']??0),(string)($u['name']??'Portal user')]);accounts_asset_audit($id,'maintenance_added',null,null,$description);ar_reply(['ok'=>true,'message'=>'Maintenance record added.']);}
 if($action==='dispose'){$id=(int)($_POST['id']??0);$before=accounts_asset_find($id);if(!$before)throw new RuntimeException('Asset not found.');$date=ar_date((string)($_POST['disposal_date']??''));$reason=trim((string)($_POST['disposal_reason']??''));if($reason==='')throw new RuntimeException('Disposal reason is required.');db()->prepare("UPDATE accounts_assets SET asset_status='disposed',disposal_date=?,disposal_reason=?,disposal_proceeds=?,disposal_notes=?,updated_by=?,updated_by_name=? WHERE id=?")->execute([$date,$reason,max(0,(float)($_POST['disposal_proceeds']??0)),trim((string)($_POST['disposal_notes']??''))?:null,(int)(current_user()['id']??0),(string)(current_user()['name']??'Portal user'),$id]);$after=accounts_asset_find($id);accounts_asset_audit($id,'disposed',$before,$after,$reason);ar_reply(['ok'=>true,'message'=>'Asset disposal recorded.']);}
 ar_reply(['ok'=>false,'error'=>'Unsupported action.'],400);
}catch(Throwable $e){ar_reply(['ok'=>false,'error'=>$e->getMessage()],422);}
