<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/accounts-assets.php';
accounts_assets_require_access(); accounts_assets_schema_ready();
$pageTitle='Asset Register | '.APP_NAME;$activeApp='accounts';$csrf=accounts_csrf_token();
$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/accounts-hierarchy.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-hierarchy.css')],['path'=>'assets/css/accounts-assets.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-assets.css')]];
include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page input-vat-page asset-register-page" id="assetRegisterPage" data-api="asset-register-api.php" data-csrf="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>" data-source-purchase="<?=htmlspecialchars((string)($_GET['source_purchase_id']??''),ENT_QUOTES,'UTF-8')?>">
 <nav class="accounts-breadcrumb" aria-label="Breadcrumb"><a href="index.php">Accounts</a><span aria-hidden="true">›</span><strong>Asset Register</strong></nav>
 <header class="accounts-page-header"><div><p class="eyebrow">Accounts application</p><h1>Asset Register</h1><p>Record, assign, maintain and audit business assets.</p></div><div class="accounts-actions"><a class="portal-button portal-button--ghost" href="asset-register-api.php?action=export"><i data-lucide="download"></i>Export CSV</a><button class="portal-button portal-button--ghost" type="button" data-print><i data-lucide="printer"></i>Print</button><button class="portal-button portal-button--primary" type="button" data-add><i data-lucide="plus"></i>Add Asset</button></div></header>
 <section class="accounts-summary" aria-label="Asset summary">
  <article><span class="accounts-summary-heading"><i data-lucide="boxes"></i>Total assets</span><strong data-summary-total>0</strong><small>Registered assets</small></article>
  <article><span class="accounts-summary-heading"><i data-lucide="banknote"></i>Purchase value</span><strong data-summary-value>N$ 0.00</strong><small>Recorded acquisition value</small></article>
  <article><span class="accounts-summary-heading"><i data-lucide="circle-check"></i>Active</span><strong data-summary-active>0</strong><small>Assets in active use</small></article>
  <article><span class="accounts-summary-heading"><i data-lucide="triangle-alert"></i>Attention</span><strong data-summary-attention>0</strong><small>Repair or attention required</small></article>
 </section>
 <section class="asset-filter-bar" aria-label="Asset filters"><label class="asset-search"><span>Search</span><span><i data-lucide="search"></i><input data-search type="search" placeholder="Search asset, reference, serial or supplier"></span></label><label><span>Category</span><select data-filter="category" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All categories</option></select></label><label><span>Condition</span><select data-filter="condition_key" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All conditions</option></select></label><label><span>Location</span><select data-filter="location_name" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All locations</option></select></label></section>
 <section class="asset-analysis" aria-label="Asset analysis"><article><h2>Categories</h2><div data-analysis-categories></div></article><article><h2>Conditions</h2><div data-analysis-conditions></div></article><article><h2>Locations</h2><div data-analysis-locations></div></article></section>
 <section class="accounts-table-shell"><header><div><p class="eyebrow">Assets</p><h2>Asset records</h2></div><span data-count>0 records</span></header><div class="accounts-table-wrap"><table><thead><tr><th>Asset</th><th>Category</th><th>Reference</th><th>Location</th><th>Condition</th><th>Purchase date</th><th>Value</th><th>Status</th><th>Actions</th></tr></thead><tbody data-rows></tbody></table></div><div class="asset-empty" data-empty hidden><i data-lucide="boxes"></i><h3>No assets found</h3><p>Add the first asset or adjust the filters.</p><button class="portal-button portal-button--primary" type="button" data-add>Add Asset</button></div></section>

 <dialog class="accounts-dialog asset-dialog" data-asset-dialog><form data-asset-form enctype="multipart/form-data"><header><div><p class="eyebrow">Asset Register</p><h2 data-form-title>Add Asset</h2></div><button type="button" data-close aria-label="Close">&times;</button></header><div class="asset-dialog-body"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id">
  <section><h3>Asset details</h3><div class="asset-form-grid"><label>Asset name<input name="asset_name" required maxlength="190"></label><label>Category<select name="category" required data-portal-custom-select data-portal-select-variant="input-vat"><option value="">Select category</option></select></label><label>Internal reference<input name="internal_reference" maxlength="100"></label><label>Source Input VAT purchase<select name="source_purchase_id" data-portal-custom-select data-portal-select-variant="input-vat"><option value="">No linked purchase</option></select></label><label>Purchase date<input name="purchase_date" type="date" required value="<?=date('Y-m-d')?>"></label><label>Supplier<input name="supplier" maxlength="190"></label><label>Purchase price incl VAT (N$)<input name="purchase_price" type="number" min="0" step="0.01" value="0"></label><label>Input VAT (N$)<input name="vat_amount" type="number" min="0" step="0.01" value="0"></label><label>Purchase price excl VAT (N$)<input name="purchase_price_excl_vat" type="number" min="0" step="0.01" value="0"></label></div></section>
  <section><h3>Identification &amp; use</h3><div class="asset-form-grid"><label>Brand<input name="brand"></label><label>Model<input name="model"></label><label>Serial number<input name="serial_number"></label><label>Location<select name="location_name" required data-portal-custom-select data-portal-select-variant="input-vat"><option value="">Select location</option></select></label><label>Assigned to<input name="assigned_to"></label><label>Assigned date<input name="assigned_date" type="date"></label><label>Condition<select name="condition_key" data-portal-custom-select data-portal-select-variant="input-vat"></select></label><label>Status<select name="asset_status" data-portal-custom-select data-portal-select-variant="input-vat"></select></label></div></section>
  <section><h3>Warranty &amp; depreciation readiness</h3><p class="asset-section-note">No depreciation rate is assumed. Configure these fields only from approved accounting policy.</p><div class="asset-form-grid"><label>Warranty start<input name="warranty_start" type="date"></label><label>Warranty expiry<input name="warranty_expiry" type="date"></label><label>Depreciation method<select name="depreciation_method" data-portal-custom-select data-portal-select-variant="input-vat"></select></label><label>Useful life (months)<input name="useful_life_months" type="number" min="1"></label><label>Depreciation start<input name="depreciation_start_date" type="date"></label><label>Accumulated depreciation (N$)<input name="accumulated_depreciation" type="number" min="0" step="0.01" value="0"></label><label>Current book value (N$)<input name="book_value" type="number" min="0" step="0.01" value="0"></label><label class="span-2">Notes<textarea name="notes" rows="3"></textarea></label></div></section>
  <section><h3>Documents &amp; photo</h3><label class="asset-upload"><input name="files[]" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5M5 14v5h14v-5"/></svg><span><strong>Choose or drop asset files</strong><small>Images, PDF, documents or spreadsheets · max 25 MB each</small></span></label><div class="asset-pending-files" data-pending-files></div></section>
 </div><p class="form-message" data-form-message></p><footer><button type="button" class="portal-button portal-button--ghost" data-close>Cancel</button><button class="portal-button portal-button--primary" type="submit">Save Asset</button></footer></form></dialog>

 <dialog class="accounts-dialog asset-detail-dialog" data-detail-dialog><div><header><div><p class="eyebrow">Asset record</p><h2 data-detail-title>Asset</h2></div><button type="button" data-detail-close aria-label="Close">&times;</button></header><div class="asset-dialog-body" data-detail-body></div><footer><button type="button" class="portal-button portal-button--ghost" data-detail-close>Close</button></footer></div></dialog>
</main>
<script defer src="<?=BASE_URL?>/assets/js/asset-register.js?v=<?=filemtime(BASE_PATH.'/assets/js/asset-register.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
