<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/accounts-import-vat.php';import_vat_require_owner();import_vat_schema_ready();header('Cache-Control:no-store');
function im_reply(array$d,int$s=200):void{http_response_code($s);header('Content-Type:application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES);exit;}
function im_date(string$v):bool{return(bool)preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)&&strtotime($v)!==false;}
function im_upload(int$importId,?int$paymentId=null):void{if(empty($_FILES['files']['name']))return;$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'];$dir=BASE_PATH.'/uploads/import-vat';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Protected document storage is unavailable.');foreach((array)$_FILES['files']['name']as$i=>$name){if((int)$_FILES['files']['error'][$i]!==UPLOAD_ERR_OK)throw new RuntimeException('A document did not upload successfully.');$tmp=(string)$_FILES['files']['tmp_name'][$i];$size=(int)$_FILES['files']['size'][$i];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp)?:'';if(!isset($allowed[$mime])||$size>25*1024*1024)throw new RuntimeException('Documents must be PDF, JPG, PNG or WEBP and no larger than 25 MB.');$stored=bin2hex(random_bytes(24)).'.'.$allowed[$mime];if(!move_uploaded_file($tmp,$dir.'/'.$stored))throw new RuntimeException('A document could not be stored.');db()->prepare('INSERT INTO accounts_import_vat_documents(import_id,payment_id,document_type,original_filename,stored_filename,mime_type,file_size,uploaded_by)VALUES(?,?,?,?,?,?,?,?)')->execute([$importId,$paymentId,(string)($_POST['document_type']??'other'),mb_substr(basename((string)$name),0,255),$stored,$mime,$size,(int)(current_user()['id']??0)]);}}
try{$action=(string)($_REQUEST['action']??'list');$month=import_vat_month((string)($_REQUEST['month']??date('Y-m')));$view=(string)($_REQUEST['view']??'imports');
 if($action==='export'){$d=import_vat_payload($month,$view);header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="import-vat-'.$month.'.csv"');$o=fopen('php://output','w');fputcsv($o,['Import Date','Reference','Supplier','Import VAT','Other Charges','Total Due','Due Date','Paid','Outstanding','Status']);foreach($d['records']as$r)fputcsv($o,[$r['import_date'],$r['reference'],$r['supplier'],$r['import_vat_amount'],(float)$r['duty_amount']+(float)$r['other_charge_amount'],$r['total_due'],$r['due_date'],$r['paid'],$r['outstanding'],$r['status']]);fclose($o);exit;}
 if($_SERVER['REQUEST_METHOD']==='POST'){import_vat_verify((string)($_POST['csrf']??''));
  if($action==='save'){$id=(int)($_POST['id']??0);$date=(string)($_POST['import_date']??'');$due=(string)($_POST['due_date']??'');$supplier=trim((string)($_POST['supplier']??''));$ref=trim((string)($_POST['reference']??''));$description=trim((string)($_POST['description']??''));if(!im_date($date)||!im_date($due)||$supplier===''||$ref===''||$description==='')throw new RuntimeException('Complete the import date, supplier, reference, description and due date.');$vat=round(max(0,(float)($_POST['import_vat_amount']??0)),2);$duty=round(max(0,(float)($_POST['duty_amount']??0)),2);$other=round(max(0,(float)($_POST['other_charge_amount']??0)),2);if($vat<=0)throw new RuntimeException('Enter the NamRA assessed Import VAT amount.');$total=round($vat+$duty+$other,2);$u=current_user();$before=$id?import_vat_record($id):null;if($id){db()->prepare('UPDATE accounts_import_vat_liabilities SET import_date=?,import_month=?,supplier=?,description=?,reference=?,source_system=?,country_origin=?,currency=?,supplier_invoice_value=?,customs_value=?,payment_arrangement=?,import_vat_amount=?,duty_amount=?,other_charge_amount=?,total_due=?,due_date=?,notes=?,updated_by=? WHERE id=?')->execute([$date,substr($date,0,7),$supplier,$description,$ref,$_POST['source_system']??'',$_POST['country_origin']??'',$_POST['currency']??'',$_POST['supplier_invoice_value']?:null,$_POST['customs_value']?:null,$_POST['payment_arrangement']??'other',$vat,$duty,$other,$total,$due,$_POST['notes']??'',(int)$u['id'],$id]);}else{db()->prepare('INSERT INTO accounts_import_vat_liabilities(import_date,import_month,supplier,description,reference,source_system,country_origin,currency,supplier_invoice_value,customs_value,payment_arrangement,import_vat_amount,duty_amount,other_charge_amount,total_due,due_date,notes,created_by,created_by_name)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$date,substr($date,0,7),$supplier,$description,$ref,$_POST['source_system']??'',$_POST['country_origin']??'',$_POST['currency']??'',$_POST['supplier_invoice_value']?:null,$_POST['customs_value']?:null,$_POST['payment_arrangement']??'other',$vat,$duty,$other,$total,$due,$_POST['notes']??'',(int)$u['id'],(string)$u['name']]);$id=(int)db()->lastInsertId();}im_upload($id);import_vat_audit($id,$before?'import_updated':'import_created',$before,import_vat_record($id));im_reply(['ok'=>true,'message'=>'Import liability saved.','data'=>import_vat_payload($month,$view)]);}
  if($action==='payment'){$id=(int)($_POST['import_id']??0);$record=import_vat_record($id);if(!$record)throw new RuntimeException('Import liability not found.');$date=(string)($_POST['payment_date']??'');$amount=round((float)($_POST['amount']??0),2);if(!im_date($date)||$amount<=0)throw new RuntimeException('Enter a valid payment date and amount.');$q=db()->prepare('SELECT COALESCE(SUM(amount),0) FROM accounts_import_vat_payments WHERE import_id=? AND reversed_at IS NULL');$q->execute([$id]);$paid=(float)$q->fetchColumn();if($paid+$amount>(float)$record['total_due']+0.005&&!isset($_POST['confirm_overpayment']))throw new RuntimeException('Payment exceeds the outstanding amount. Confirm the overpayment before recording it.');$u=current_user();db()->prepare('INSERT INTO accounts_import_vat_payments(import_id,payment_date,amount,reference,payment_method,notes,created_by,created_by_name)VALUES(?,?,?,?,?,?,?,?)')->execute([$id,$date,$amount,$_POST['payment_reference']??'',$_POST['payment_method']??'',$_POST['payment_notes']??'',(int)$u['id'],(string)$u['name']]);$pid=(int)db()->lastInsertId();im_upload($id,$pid);import_vat_audit($id,'payment_recorded',null,['payment_id'=>$pid,'amount'=>$amount,'date'=>$date]);im_reply(['ok'=>true,'message'=>'Payment recorded.','data'=>import_vat_payload($month,$view)]);}
  if($action==='delete'){$id=(int)($_POST['id']??0);$r=import_vat_record($id);if(!$r)throw new RuntimeException('Import liability not found.');$q=db()->prepare('SELECT COUNT(*) FROM accounts_import_vat_payments WHERE import_id=? AND reversed_at IS NULL');$q->execute([$id]);if((int)$q->fetchColumn())throw new RuntimeException('Imports with payment history cannot be deleted. Reverse or correct the payment with an audit reason.');db()->prepare('UPDATE accounts_import_vat_liabilities SET deleted_at=NOW(),deleted_by=? WHERE id=?')->execute([(int)(current_user()['id']??0),$id]);import_vat_audit($id,'import_deleted',$r,null);im_reply(['ok'=>true,'message'=>'Import moved to audit history.','data'=>import_vat_payload($month,$view)]);}
 }
 im_reply(['ok'=>true,'data'=>import_vat_payload($month,$view)]);
}catch(Throwable$e){im_reply(['ok'=>false,'message'=>$e->getMessage()],400);}
