<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/config.php';
require_once BASE_PATH . '/shared/auth.php';
require_once BASE_PATH . '/shared/employee-features.php';
require_once BASE_PATH . '/shared/accounts-input-vat.php';
accounts_require_workspace_access();
$pageTitle = 'Accounts | ' . APP_NAME;
$activeApp = 'accounts';
$extraStylesheets = [['path' => 'assets/css/accounts.css', 'version' => (string) filemtime(BASE_PATH . '/assets/css/accounts.css')], ['path' => 'assets/css/accounts-hierarchy.css', 'version' => (string) filemtime(BASE_PATH . '/assets/css/accounts-hierarchy.css')], ['path' => 'assets/css/accounts-dashboard.css', 'version' => (string) filemtime(BASE_PATH . '/assets/css/accounts-dashboard.css')]];
include BASE_PATH . '/shared/header.php';
include BASE_PATH . '/shared/sidebar.php';
?>
<main class="workspace module accounts-page accounts-workspace">
  <header class="accounts-hero"><div><p class="eyebrow">Finance workspace</p><h1>Accounts</h1><p>Accounting and financial administration applications.</p></div></header>
  <section class="accounts-app-section" aria-labelledby="accounting-apps-title">
    <header><div><p class="eyebrow">Applications</p><h2 id="accounting-apps-title">Accounting Apps</h2></div></header>
    <div class="accounts-app-grid">
      <a class="accounts-app-card accounting-app-card accounting-app-card--input-vat" href="input-vat.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="receipt-text"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Input VAT</h3><p>Record local VAT purchases, supporting invoices and monthly Input VAT.</p><strong>Open Input VAT <span aria-hidden="true">&rarr;</span></strong></div></a>
      <a class="accounts-app-card accounting-app-card accounting-app-card--output-vat" href="output-vat.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="chart-no-axes-combined"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Output VAT</h3><p>Automatically reconcile WooCommerce sales and calculate Output VAT by tax period.</p><strong>Open Output VAT <span aria-hidden="true">&rarr;</span></strong></div></a>
      <a class="accounts-app-card accounting-app-card accounting-app-card--import-vat" href="import-vat.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="ship"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Import VAT</h3><p>Track imported goods, NamRA Import VAT amounts, due dates and payments.</p><strong>Open Import VAT <span aria-hidden="true">&rarr;</span></strong></div></a>
      <a class="accounts-app-card accounting-app-card accounting-app-card--vat-reconciliation" href="vat-reconciliation.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="scale"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>VAT Reconciliation</h3><p>Combine Output VAT, Input VAT and reviewed Import VAT into a final return position.</p><strong>Open VAT Reconciliation <span aria-hidden="true">&rarr;</span></strong></div></a>
      <a class="accounts-app-card accounting-app-card accounting-app-card--sage" href="sage-reconciliation.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="book-open-check"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Sage Posting &amp; Reconciliation</h3><p>Prepare monthly Sage postings and reconcile receipts without double-counting sales.</p><strong>Open Sage Posting &amp; Reconciliation <span aria-hidden="true">&rarr;</span></strong></div></a>
      <a class="accounts-app-card accounting-app-card accounting-app-card--asset-register" href="asset-register.php"><span class="accounts-app-icon" aria-hidden="true"><i data-lucide="boxes"></i></span><div class="accounting-app-card__content"><div class="accounting-app-card__status"><small class="accounts-app-status is-available">Available</small><span class="accounts-owner-label"><i data-lucide="shield-lock" aria-hidden="true"></i>Owner only</span><span class="accounting-app-visual" aria-hidden="true"><i></i><i></i><i></i></span></div><h3>Asset Register</h3><p>Record, assign, maintain and audit business assets.</p><strong>Open Asset Register <span aria-hidden="true">&rarr;</span></strong></div></a>
    </div>
  </section>
</main>
<?php include BASE_PATH . '/shared/footer.php'; ?>
