<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/employee-features.php';require_once BASE_PATH.'/shared/accounts-input-vat.php';accounts_require_access();accounts_input_vat_schema_ready();
$pageTitle='Input VAT | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/accounts-hierarchy.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-hierarchy.css')]];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page" id="inputVatPage" data-api="input-vat-api.php" data-csrf="<?=htmlspecialchars(accounts_csrf_token(),ENT_QUOTES,'UTF-8')?>" data-owner="<?=accounts_is_owner()?'1':'0'?>" data-rate="<?=htmlspecialchars((string)accounts_standard_vat_rate(),ENT_QUOTES,'UTF-8')?>">
 <nav class="accounts-breadcrumb" aria-label="Breadcrumb"><a href="index.php">Accounts</a><span aria-hidden="true">&rsaquo;</span><strong>Input VAT</strong></nav>
 <header class="accounts-hero"><div><p class="eyebrow">Accounts application</p><h1>Input VAT</h1><p>Record local VAT purchases and calculate Input VAT for the selected period.</p></div><div class="accounts-actions"><button class="btn-primary" type="button" data-add-purchase>Add Purchase</button><button type="button" class="btn-secondary" data-print>Print</button><a class="btn-secondary" data-export href="input-vat-api.php?action=export">Export CSV</a></div></header>
 <section class="accounts-toolbar" aria-label="Input VAT filters"><button type="button" class="btn-secondary accounts-month-step" data-previous-month aria-label="Previous month">&larr; Previous Month</button><label>Period<select data-period><option value="current">Selected month</option><?php if(accounts_is_owner()):?><option value="all">All periods</option><?php endif;?></select></label><label>Month<input type="month" data-month value="<?=date('Y-m')?>"></label><button type="button" class="btn-secondary accounts-month-step" data-next-month aria-label="Next month">Next Month &rarr;</button><label>Search<input type="search" data-search placeholder="Supplier or description"></label><label>Status<select data-status><option value="">All statuses</option><option value="captured">Captured</option><option value="reviewed">Reviewed</option><option value="needs_correction">Needs Correction</option></select></label><?php if(accounts_is_owner()):?><label>VAT rate (%)<input data-rate-setting type="number" min="0" max="100" step="0.01" value="<?=htmlspecialchars((string)accounts_standard_vat_rate(),ENT_QUOTES,'UTF-8')?>"></label><button class="btn-secondary" data-save-rate>Save rate</button><?php endif;?></section>
 <section class="accounts-summary" data-summary aria-live="polite"></section>
 <section class="accounts-breakdowns"><article><h2>VAT treatment</h2><div data-treatment-summary></div></article><article><h2>Suppliers</h2><div data-supplier-summary></div></article><article><h2>Descriptions</h2><div data-description-summary></div></article></section>
 <section class="accounts-table-card"><div class="accounts-table-wrap" data-portal-horizontal-scroll-source><table><thead><tr><th data-sort="purchase_date">Date</th><th data-sort="supplier">Supplier</th><th>Description</th><th>Incl VAT</th><th>Input VAT</th><th>Excl VAT</th><th>Attachment</th><th>Entered By</th><th>Status</th><th>Actions</th></tr></thead><tbody data-rows></tbody><tfoot data-totals></tfoot></table></div></section>
 <dialog class="accounts-dialog" data-dialog><form method="dialog" data-form enctype="multipart/form-data"><header><div><p class="eyebrow">Input VAT</p><h2 data-form-title>Add Purchase</h2></div><button value="cancel" aria-label="Close">×</button></header><input type="hidden" name="id"><div class="accounts-form-grid"><label>Date<input name="purchase_date" type="date" required></label><label>Supplier<input name="supplier" maxlength="190" required></label><label class="span-2">Description<textarea name="description" required></textarea></label><label>Amount incl VAT (N$)<input name="inclusive" type="number" min="0" step="0.01" required></label><label>VAT treatment<select name="vat_treatment" required><option value="standard">Standard rate</option><option value="zero_rated">Zero Rated</option><option value="no_vat">No VAT / Non-VAT</option><option value="manual_vat">Manual VAT</option><option value="review_required">Review Required</option></select></label><label data-manual-wrap hidden>Manual VAT (N$)<input name="manual_vat" type="number" min="0" step="0.01"></label><div class="vat-preview span-2" data-vat-preview></div><label class="span-2">Evidence files<input name="files[]" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"></label><div class="pending-files span-2" data-pending-files></div></div><p class="form-message" data-form-message></p><footer><button value="cancel" class="btn-secondary">Cancel</button><button type="submit" class="btn-primary" data-save>Save Purchase</button></footer></form></dialog>
 <dialog class="accounts-dialog accounts-review-dialog" data-review-dialog><form method="dialog" data-review-form><header><h2>Review purchase</h2><button value="cancel" aria-label="Close">×</button></header><input type="hidden" name="id"><label>Status<select name="review_status"><option value="reviewed">Reviewed</option><option value="needs_correction">Needs Correction</option><option value="captured">Captured</option></select></label><label>Reason / note<textarea name="review_note"></textarea></label><p data-review-message></p><footer><button value="cancel" class="btn-secondary">Cancel</button><button type="submit" class="btn-primary">Save Review</button></footer></form></dialog>
 <dialog class="accounts-dialog" data-audit-dialog><form method="dialog"><header><h2>Audit history</h2><button value="cancel" aria-label="Close">×</button></header><div data-audit-history></div><footer><button value="cancel" class="btn-secondary">Close</button></footer></form></dialog>
</main><script defer src="<?=BASE_URL?>/assets/js/input-vat.js?v=<?=filemtime(BASE_PATH.'/assets/js/input-vat.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
