<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/employee-features.php';require_once BASE_PATH.'/shared/accounts-input-vat.php';accounts_require_input_vat_access();accounts_input_vat_schema_ready();header('Cache-Control: no-store');
function iv_reply(array $data,int $status=200):void{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function iv_uploads(int $purchaseId):array{
 if(empty($_FILES['files']['name']))return[];$names=(array)$_FILES['files']['name'];if(count($names)>10)throw new RuntimeException('Upload no more than 10 files at once.');
 $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf','text/plain'=>'txt','text/csv'=>'csv','application/csv'=>'csv','application/msword'=>'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx','application/vnd.ms-excel'=>'xls','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'=>'xlsx'];
 $dir=BASE_PATH.'/uploads/input-vat';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Protected attachment storage is unavailable.');$saved=[];
 foreach($names as $i=>$name){if((int)($_FILES['files']['error'][$i]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('An attachment did not upload successfully.');$tmp=(string)$_FILES['files']['tmp_name'][$i];$size=(int)$_FILES['files']['size'][$i];if(!is_uploaded_file($tmp)||$size<=0||$size>25*1024*1024)throw new RuntimeException('Each attachment must be between 1 byte and 25 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp)?:'';if(!isset($allowed[$mime]))throw new RuntimeException('That attachment type is not allowed.');$stored=bin2hex(random_bytes(24)).'.'.$allowed[$mime];if(!move_uploaded_file($tmp,$dir.'/'.$stored))throw new RuntimeException('An attachment could not be stored.');try{$stmt=db()->prepare('INSERT INTO accounts_input_vat_attachments(purchase_id,original_filename,stored_filename,mime_type,file_size,uploaded_by)VALUES(?,?,?,?,?,?)');$stmt->execute([$purchaseId,mb_substr(basename(str_replace('\\','/',(string)$name)),0,255),$stored,$mime,$size,(int)(current_user()['id']??0)]);$saved[]=$stored;}catch(Throwable $e){@unlink($dir.'/'.$stored);throw $e;}}
 return $saved;
}
try{
 $action=(string)($_REQUEST['action']??'list');
 if($action==='export'){
  $month=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['month']??''))?(string)$_GET['month']:date('Y-m');$all=accounts_is_owner()&&($_GET['period']??'')==='all';$where='deleted_at IS NULL';$params=[];if(!$all){$where.=' AND purchase_date>=? AND purchase_date<?';$from=$month.'-01';$params=[$from,date('Y-m-d',strtotime($from.' +1 month'))];}$stmt=db()->prepare('SELECT purchase_date,supplier,description,amount_incl_vat,vat_amount,amount_excl_vat,vat_treatment,review_status,created_by_name FROM accounts_input_vat_purchases WHERE '.$where.' ORDER BY purchase_date,id');$stmt->execute($params);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="input-vat-'.$month.'.csv"');$out=fopen('php://output','wb');fputcsv($out,['Date','Supplier','Description','Incl VAT','Input VAT','Excl VAT','VAT Treatment','Review Status','Entered By']);foreach($stmt->fetchAll() as $r)fputcsv($out,$r);fclose($out);exit;
 }
 if($action==='audit'){if(!accounts_is_owner())throw new RuntimeException('Only the owner can view audit history.');$id=(int)($_GET['id']??0);$stmt=db()->prepare('SELECT action_key,actor_name,created_at,before_json,after_json FROM accounts_input_vat_audit WHERE purchase_id=? ORDER BY id DESC');$stmt->execute([$id]);iv_reply(['ok'=>true,'history'=>$stmt->fetchAll()]);}
 if($action==='list'){
  $month=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['month']??''))?(string)$_GET['month']:date('Y-m');$all=accounts_is_owner()&&($_GET['period']??'')==='all';$where=['deleted_at IS NULL'];$params=[];if(!$all){$where[]='purchase_date>=? AND purchase_date<?';$from=$month.'-01';$params=[$from,date('Y-m-d',strtotime($from.' +1 month'))];}$search=trim((string)($_GET['search']??''));if($search!==''){$where[]='(supplier LIKE ? OR description LIKE ?)';$params[]='%'.$search.'%';$params[]='%'.$search.'%';}$status=trim((string)($_GET['status']??''));if(in_array($status,['captured','reviewed','needs_correction'],true)){$where[]='review_status=?';$params[]=$status;}$sort=in_array($_GET['sort']??'',['supplier','purchase_date'],true)?(string)$_GET['sort']:'purchase_date';$stmt=db()->prepare('SELECT * FROM accounts_input_vat_purchases WHERE '.implode(' AND ',$where).' ORDER BY '.$sort.' '.(($_GET['direction']??'desc')==='asc'?'ASC':'DESC').',id DESC');$stmt->execute($params);$rows=array_map('accounts_purchase_payload',$stmt->fetchAll());$summary=['count'=>count($rows),'inclusive'=>0,'vat'=>0,'exclusive'=>0,'treatments'=>[],'suppliers'=>[],'descriptions'=>[]];foreach($rows as $r){$summary['inclusive']+=$r['inclusive'];$summary['vat']+=$r['vat'];$summary['exclusive']+=$r['exclusive'];$summary['treatments'][$r['vat_treatment']]=($summary['treatments'][$r['vat_treatment']]??0)+$r['vat'];$summary['suppliers'][$r['supplier']]=($summary['suppliers'][$r['supplier']]??0)+$r['inclusive'];$key=mb_substr($r['description'],0,50);$summary['descriptions'][$key]=($summary['descriptions'][$key]??0)+$r['inclusive'];}iv_reply(['ok'=>true,'rows'=>$rows,'summary'=>$summary,'standard_vat_rate'=>accounts_standard_vat_rate(),'refreshed_at'=>date(DATE_ATOM)]);
 }
 if($_SERVER['REQUEST_METHOD']!=='POST')throw new RuntimeException('POST required.');accounts_verify_csrf((string)($_POST['csrf']??''));
 if($action==='save_rate'){if(!accounts_is_owner())throw new RuntimeException('Only the owner can change the VAT rate.');$rate=max(0,min(100,(float)($_POST['rate']??15)));db()->prepare("INSERT INTO accounts_settings(setting_key,setting_value,updated_by)VALUES('standard_vat_rate',?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)")->execute([(string)$rate,(int)(current_user()['id']??0)]);iv_reply(['ok'=>true,'rate'=>$rate,'message'=>'Standard VAT rate saved. Existing records were not recalculated.']);}
 if($action==='save'){$id=(int)($_POST['id']??0);$date=(string)($_POST['purchase_date']??'');$supplier=trim((string)($_POST['supplier']??''));$description=trim((string)($_POST['description']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$supplier===''||$description==='')throw new RuntimeException('Date, supplier and description are required.');$calc=accounts_vat_calculate((float)($_POST['inclusive']??0),(string)($_POST['vat_treatment']??'standard'),isset($_POST['manual_vat'])?(float)$_POST['manual_vat']:null);if($calc['inclusive']<=0)throw new RuntimeException('Amount incl VAT must be greater than zero.');$user=current_user();$before=null;db()->beginTransaction();try{if($id){$before=accounts_purchase($id);if(!$before||!accounts_can_edit_purchase($before))throw new RuntimeException('You cannot edit this purchase.');$stmt=db()->prepare('UPDATE accounts_input_vat_purchases SET purchase_date=?,supplier=?,description=?,amount_incl_vat=?,vat_rate=?,vat_amount=?,amount_excl_vat=?,vat_treatment=?,updated_by=? WHERE id=?');$stmt->execute([$date,$supplier,$description,$calc['inclusive'],$calc['rate'],$calc['vat'],$calc['exclusive'],$calc['treatment'],(int)$user['id'],$id]);}else{$stmt=db()->prepare('INSERT INTO accounts_input_vat_purchases(purchase_date,supplier,description,amount_incl_vat,vat_rate,vat_amount,amount_excl_vat,vat_treatment,created_by,created_by_name)VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$date,$supplier,$description,$calc['inclusive'],$calc['rate'],$calc['vat'],$calc['exclusive'],$calc['treatment'],(int)$user['id'],(string)$user['name']]);$id=(int)db()->lastInsertId();}iv_uploads($id);$after=accounts_purchase($id);accounts_audit($id,$before?'updated':'created',$before,$after);db()->commit();iv_reply(['ok'=>true,'row'=>accounts_purchase_payload($after),'message'=>$before?'Purchase updated.':'Purchase saved.']);}catch(Throwable $e){db()->rollBack();throw $e;}}
 if($action==='review'){if(!accounts_is_owner())throw new RuntimeException('Only the owner can review purchases.');$id=(int)($_POST['id']??0);$before=accounts_purchase($id);$status=(string)($_POST['review_status']??'');$note=trim((string)($_POST['review_note']??''));if(!$before||!in_array($status,['captured','reviewed','needs_correction'],true))throw new RuntimeException('Choose a valid review status.');if($status==='needs_correction'&&$note==='')throw new RuntimeException('A correction reason is required.');db()->prepare('UPDATE accounts_input_vat_purchases SET review_status=?,review_note=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?')->execute([$status,$note,(int)(current_user()['id']??0),$id]);$after=accounts_purchase($id);accounts_audit($id,'reviewed',$before,$after);iv_reply(['ok'=>true,'row'=>accounts_purchase_payload($after),'message'=>'Review saved.']);}
 if($action==='delete'){if(!accounts_is_owner())throw new RuntimeException('Only the owner can delete purchases.');$id=(int)($_POST['id']??0);$before=accounts_purchase($id);if(!$before)throw new RuntimeException('Purchase not found.');db()->prepare('UPDATE accounts_input_vat_purchases SET deleted_at=NOW(),deleted_by=? WHERE id=? AND deleted_at IS NULL')->execute([(int)(current_user()['id']??0),$id]);accounts_audit($id,'deleted',$before,accounts_purchase($id,true));iv_reply(['ok'=>true,'message'=>'Purchase moved to audit history.']);}
 if($action==='delete_attachment'){if(!accounts_is_owner())throw new RuntimeException('Only the owner can remove attachments.');$id=(int)($_POST['attachment_id']??0);$stmt=db()->prepare('SELECT * FROM accounts_input_vat_attachments WHERE id=? AND deleted_at IS NULL');$stmt->execute([$id]);$file=$stmt->fetch();if(!$file)throw new RuntimeException('Attachment not found.');db()->prepare('UPDATE accounts_input_vat_attachments SET deleted_at=NOW(),deleted_by=? WHERE id=?')->execute([(int)(current_user()['id']??0),$id]);accounts_audit((int)$file['purchase_id'],'attachment_deleted',$file,null);iv_reply(['ok'=>true,'message'=>'Attachment removed.']);}
 throw new RuntimeException('Unknown action.');
}catch(Throwable $e){error_log('Input VAT request failed: '.$e->getMessage());iv_reply(['ok'=>false,'error'=>$e->getMessage()],400);}
