<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/accounts-output-vat.php';
output_vat_require_owner(); output_vat_schema_ready();
$pageTitle='Output VAT | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/accounts-hierarchy.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts-hierarchy.css')]];
include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page output-vat-page" id="inputVatPage" data-output-vat data-api="output-vat-api.php" data-csrf="<?=htmlspecialchars(output_vat_csrf_token(),ENT_QUOTES,'UTF-8')?>" data-current-month="<?=htmlspecialchars(date('Y-m'),ENT_QUOTES,'UTF-8')?>">
 <nav class="accounts-breadcrumb" aria-label="Breadcrumb"><a href="index.php">Accounts</a><span aria-hidden="true">&rsaquo;</span><strong>Output VAT</strong></nav>
 <header class="accounts-hero"><div class="accounts-hero-copy"><p class="eyebrow">Accounts application</p><h1>Output VAT</h1><p>Automatically reconcile WooCommerce sales and calculate Output VAT by tax period.</p><p class="input-vat-active-period"><i data-lucide="calendar-days" aria-hidden="true"></i><span class="input-vat-active-period-label">Active period</span><strong data-active-period><?=htmlspecialchars(date('F Y'),ENT_QUOTES,'UTF-8')?></strong></p></div><div class="accounts-actions"><button class="portal-button portal-button--secondary" type="button" data-sync><i data-lucide="refresh-cw" aria-hidden="true"></i><span>Refresh Data</span></button><a class="portal-button portal-button--secondary" data-export href="#"><i data-lucide="download" aria-hidden="true"></i><span>Export</span></a><button class="portal-button portal-button--secondary" type="button" data-print><i data-lucide="printer" aria-hidden="true"></i><span>Print</span></button></div></header>
 <p class="output-vat-source-note"><i data-lucide="shield-check"></i><span><strong>Read-only WooCommerce source.</strong> This application cannot edit orders, prices, stock, refunds or customer records.</span></p>
 <section class="accounts-summary" data-summary aria-live="polite"></section>
 <section class="input-vat-month-workspace" aria-label="Output VAT period"><div class="input-vat-month-nav"><button type="button" class="input-vat-month-arrow" data-prev aria-label="Previous month"><i data-lucide="chevron-left" aria-hidden="true"></i></button><label class="input-vat-year-select"><span>Year</span><select data-year data-portal-custom-select data-portal-select-variant="input-vat" aria-label="Output VAT year"></select></label><nav class="input-vat-month-tabs" data-month-tabs aria-label="Output VAT months"></nav><button type="button" class="input-vat-month-arrow" data-next aria-label="Next month"><i data-lucide="chevron-right" aria-hidden="true"></i></button></div><div class="input-vat-month-status" data-output-period-status></div></section>
 <section class="output-vat-reconciliation" data-reconciliation></section>
 <section class="accounts-breakdowns" data-analysis></section>
 <section class="accounts-toolbar input-vat-history-toolbar output-vat-filters" aria-label="Output VAT filters"><div class="input-vat-history-primary"><label class="accounts-search-control input-vat-history-search"><span>Search</span><span class="input-vat-search-field"><i data-lucide="search" aria-hidden="true"></i><input type="search" data-search placeholder="Search order ID"></span></label><label><span>Order status</span><select data-status data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All statuses</option><option value="completed">Completed</option><option value="processing">Processing</option><option value="on-hold">On hold</option><option value="refunded">Refunded</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select></label><label><span>VAT treatment</span><select data-treatment data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All treatments</option><option value="standard">Standard 15%</option><option value="mixed">Mixed</option><option value="zero_rated">Zero Rated</option><option value="exempt">Exempt / Non-taxable</option><option value="review">Review</option></select></label><label><span>Reconciliation</span><select data-reconcile data-portal-custom-select data-portal-select-variant="input-vat"><option value="">All records</option><option value="included">Included</option><option value="excluded">Excluded</option><option value="difference">VAT difference</option></select></label></div></section>
 <section class="accounts-table-card"><header class="output-vat-table-heading"><div><p class="eyebrow">Accounting audit</p><h2>WooCommerce orders</h2></div><span data-record-count></span></header><p class="accounts-scroll-hint">Scroll horizontally to view all accounting fields.</p><div class="accounts-table-wrap"><table><thead><tr><th>Date</th><th>Order ID</th><th>Status</th><th>Included</th><th>Total incl VAT</th><th>Shipping</th><th>Discount</th><th>Refund</th><th>Standard-rated</th><th>Zero-rated</th><th>Exempt</th><th>Woo VAT</th><th>Expected VAT</th><th>Net excl VAT</th></tr></thead><tbody data-orders><tr><td colspan="14" class="empty-row">Loading WooCommerce accounting data…</td></tr></tbody></table></div></section>
 <dialog class="accounts-dialog" data-adjust-dialog><form data-adjust-form><header><div><p class="eyebrow">Owner adjustment</p><h2>Adjust Output VAT</h2></div><button type="button" data-close aria-label="Close">&times;</button></header><div class="accounts-form-grid"><label>Adjustment amount (N$)<input type="number" name="amount" step="0.01" required></label><label>Reason<input name="reason" maxlength="500" required></label><label class="span-2">Supporting note<textarea name="note"></textarea></label></div><p class="form-message" data-adjust-message></p><footer><button type="button" class="portal-button portal-button--secondary" data-close>Cancel</button><button class="portal-button portal-button--primary">Record adjustment</button></footer></form></dialog>
</main>
<script defer src="<?=BASE_URL?>/assets/js/output-vat.js?v=<?=filemtime(BASE_PATH.'/assets/js/output-vat.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
