<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/accounts-input-vat.php';
require_login();if(!accounts_is_owner()){http_response_code(403);exit('Owner access required.');}
$pageTitle='Payment Reconciliation | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>filemtime(BASE_PATH.'/assets/css/accounts.css')],['path'=>'assets/css/payment-reconciliation.css','version'=>filemtime(BASE_PATH.'/assets/css/payment-reconciliation.css')]];
include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?><main class="workspace module accounts-page payment-reconciliation">
<header class="pr-head"><div><p class="eyebrow">Finance workspace</p><h1>Payment Reconciliation</h1><p>Verify actual receipts against orders, bookkeeping and driver collections.</p></div><div class="pr-actions"><button class="pr-secondary" id="pr-import-open">Import Statement</button><button id="pr-export">Export CSV</button><a class="pr-secondary" href="index.php">Accounts</a></div></header>
<form id="pr-range"><label>From<input name="from" type="date" value="<?=date('Y-m-01')?>" required></label><label>Through<input name="to" type="date" value="<?=date('Y-m-d')?>" required></label><button>Apply date range</button></form>
<p id="pr-message" role="status"></p><section class="pr-kpis" id="pr-kpis"></section><nav id="pr-tabs" aria-label="Transaction views"></nav>
<div class="pr-filters"><label>Search<input id="pr-search" type="search" placeholder="Order number or customer"></label><label>Status<select id="pr-status"><option value="">All statuses</option><option>Recorded</option><option>Awaiting Evidence</option><option>Matched</option><option>Confirmed</option><option>Partially Paid</option><option>Discrepancy</option></select></label><label>Sort<select id="pr-sort"><option value="date">Latest first</option><option value="customer">Customer</option><option value="amount">Highest amount</option></select></label><button class="pr-secondary" id="pr-clear">Clear filters</button></div>
<div id="pr-table"></div><div class="pr-actions"><button id="pr-prev" class="pr-secondary">Previous</button><span id="pr-page"></span><button id="pr-next" class="pr-secondary">Next</button></div>
<section id="pr-unmatched"><h2>Unmatched receipts</h2><button id="pr-export-receipts" class="pr-secondary">Export unmatched receipts</button><div id="pr-receipts"></div></section>
<aside id="pr-bulk" hidden><details open><summary>Selected transactions</summary><span id="pr-bulk-totals"></span></details><button id="pr-confirm-selected">Confirm Selected</button><button class="pr-secondary" id="pr-clear-selected">Clear Selection</button></aside>
<dialog id="pr-drawer"><header><h2>Transaction details</h2><button id="pr-close" class="pr-secondary">Close</button></header><div id="pr-detail"></div><p id="pr-detail-error" role="alert"></p></dialog>
<dialog id="pr-import"><header><h2>Import payment evidence</h2><button id="pr-import-close" class="pr-secondary">Close</button></header><form id="pr-import-form"><p>Use a Sage CSV from the <a href="../operations/bank-statement-processor.php" target="_blank" rel="noopener">existing Bank Statement Processor</a>, or an FNB approved-transactions terminal PDF. Preview before importing. No payment is automatically confirmed.</p><label>Format<select name="kind"><option value="bank">Bank Processor Sage CSV</option><option value="terminal">FNB terminal PDF</option></select></label><label>Bank account identifier<input name="account" maxlength="100" placeholder="Use the same identifier for every statement"></label><label>Bank payment method<select name="method" id="pr-import-method"></select></label><label>Statement<input type="file" name="statement" accept=".csv,.pdf" required></label><button>Preview import</button></form><div id="pr-import-preview"></div><p id="pr-import-message" role="status"></p><button id="pr-import-save" hidden>Import evidence</button></dialog>
</main><script src="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/js/payment-reconciliation.js?v=<?=filemtime(BASE_PATH.'/assets/js/payment-reconciliation.js')?>"></script><?php include BASE_PATH.'/shared/footer.php';?>
