<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/auth.php';require_once BASE_PATH.'/shared/employee-features.php';require_once BASE_PATH.'/shared/accounts-sage.php';sage_require_owner();sage_schema_ready();$month=sage_month((string)($_GET['month']??date('Y-m')));$pageTitle='Sage Posting & Reconciliation | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')]];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';?>
<main class="workspace module accounts-page sage-page" data-sage-app data-api="sage-reconciliation-api.php" data-csrf="<?=htmlspecialchars(sage_csrf(),ENT_QUOTES,'UTF-8')?>" data-month="<?=htmlspecialchars($month,ENT_QUOTES,'UTF-8')?>">
<nav class="accounts-breadcrumb" aria-label="Breadcrumb"><a href="index.php">Accounts</a><span>&rsaquo;</span><strong>Sage Posting &amp; Reconciliation</strong></nav>
<header class="accounts-hero"><div class="accounts-hero-copy"><p class="eyebrow">Accounts application · Owner only</p><h1>Sage Posting &amp; Reconciliation</h1><p>Prepare summary Sage postings, record the manual Sage reference, and reconcile receipts without double-counting sales.</p><p class="input-vat-active-period"><i data-lucide="calendar-days"></i><span>Active period</span><strong data-period-label></strong></p></div><div class="accounts-actions"><a class="portal-button portal-button--secondary" data-export href="#"><i data-lucide="download"></i> Export Pack</a><button class="portal-button portal-button--secondary" type="button" onclick="window.print()"><i data-lucide="printer"></i> Print</button><button class="portal-button portal-button--ghost" type="button" data-settings><i data-lucide="settings"></i> Settings</button></div></header>
<section class="input-vat-month-workspace"><div class="input-vat-month-nav"><button type="button" class="input-vat-month-arrow" data-prev aria-label="Previous month"><i data-lucide="chevron-left"></i></button><label class="input-vat-year-select"><span>Year</span><select data-year></select></label><nav class="input-vat-month-tabs" data-tabs aria-label="Sage accounting months"></nav><button type="button" class="input-vat-month-arrow" data-next aria-label="Next month"><i data-lucide="chevron-right"></i></button></div><div class="input-vat-month-status" data-month-status></div></section>
<section class="accounts-summary" data-summary aria-live="polite"></section>
<section class="sage-progress" data-progress></section>
<section class="sage-grid" data-content><div class="accounts-loading-card"><span class="accounts-loading-spinner"></span><strong>Loading local accounting data…</strong></div></section>
<div class="toast" data-toast hidden></div>
<dialog class="accounts-dialog sage-dialog" data-settings-dialog><form data-settings-form><header><div><p class="eyebrow">Owner configuration</p><h2>Sage Posting Settings</h2></div><button type="button" data-close>&times;</button></header><div class="accounts-form-grid"><label>Sage customer<input name="customer_name" required></label><label>Posting mode<select name="posting_mode"><option value="summary_monthly">Monthly summary</option></select></label><label>Bank statement method<select name="bank_statement_method"><option value="manual_sage_upload">Manual Sage Upload</option><option value="sage_bank_feed">Sage Bank Feed</option></select></label><label>Standard-rated sales account<input name="standard_account" placeholder="Accountant approval required"></label><label>Standard VAT code<input name="standard_vat_code" placeholder="e.g. VAT 15%"></label><label>Zero-rated sales account<input name="zero_account"></label><label>Shipping income account<input name="shipping_account"></label><label>Discounts account<input name="discount_account"></label><label>Refunds / returns account<input name="refund_account"></label></div><p class="form-message" data-settings-message></p><footer><button type="button" class="portal-button portal-button--secondary" data-close>Cancel</button><button class="portal-button portal-button--primary">Save Settings</button></footer></form></dialog>
<dialog class="accounts-dialog sage-dialog" data-posted-dialog><form data-posted-form><header><div><p class="eyebrow">Manual Sage posting</p><h2>Record Sage Posting</h2></div><button type="button" data-close>&times;</button></header><div class="accounts-form-grid"><label>Sage customer<input name="sage_customer" required></label><label>Sage invoice/document number<input name="sage_document_number" required></label><label>Sage posting date<input type="date" name="sage_posting_date" required></label><label>Sage total<input type="number" step="0.01" name="sage_total" required></label><label>Sage VAT<input type="number" step="0.01" name="sage_vat" required></label><label class="span-2">Optional note<textarea name="sage_note"></textarea></label></div><p class="form-message" data-posted-message></p><footer><button type="button" class="portal-button portal-button--secondary" data-close>Cancel</button><button class="portal-button portal-button--primary">Mark Posted to Sage</button></footer></form></dialog>
<dialog class="accounts-dialog sage-dialog" data-receipt-dialog><form data-receipt-form><header><div><p class="eyebrow">Settlement evidence</p><h2>Record Bank/Sage Receipt</h2></div><button type="button" data-close>&times;</button></header><div class="accounts-form-grid"><label>Receipt date<input type="date" name="receipt_date" required></label><label>Amount<input type="number" step="0.01" min="0.01" name="amount" required></label><label>Payment method<input name="payment_method" list="sagePaymentMethods" required><datalist id="sagePaymentMethods"><option>Cash</option><option>EFT</option><option>DPO</option><option>Easywallet</option><option>FNB eWallet</option><option>Nedbank</option><option>Bluewallet</option><option>Pay2Cell</option><option>PayToday</option></datalist></label><label>Bank/clearing account<input name="bank_account"></label><label>Sage reference<input name="sage_reference"></label><label>Allocation<select name="allocated_to_sales"><option value="1">Allocated to Hambelela Sales / clearing</option><option value="0">Not allocated</option></select></label><label><input type="checkbox" name="timing_difference" value="1"> Timing difference</label><label class="span-2">Notes<textarea name="notes"></textarea></label></div><p class="sage-warning">This receipt settles an existing sales posting. It must not be posted as new revenue.</p><footer><button type="button" class="portal-button portal-button--secondary" data-close>Cancel</button><button class="portal-button portal-button--primary">Record Receipt</button></footer></form></dialog>
</main><script src="<?=htmlspecialchars(BASE_URL,ENT_QUOTES,'UTF-8')?>/assets/js/sage-reconciliation.js?v=<?=filemtime(BASE_PATH.'/assets/js/sage-reconciliation.js')?>"></script><?php include BASE_PATH.'/shared/footer.php';?>
