<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';
require_once BASE_PATH.'/shared/accounts-vat-reconciliation.php';
vat_reconciliation_require_owner();vat_reconciliation_schema_ready();header('Cache-Control:no-store');
function vr_reply(array $data,int $status=200):void{http_response_code($status);header('Content-Type:application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_SLASHES);exit;}
try{
 $action=(string)($_REQUEST['action']??'list');$code=vat_reconciliation_period_code((string)($_REQUEST['period']??date('Y-m')));$payload=vat_reconciliation_payload($code);
 if($action==='export'){$s=$payload['sources'];header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="vat-reconciliation-'.$payload['period']['period_code'].'.csv"');$out=fopen('php://output','w');fputcsv($out,['VAT Reconciliation',$payload['period']['label']]);fputcsv($out,['Return due',$payload['period']['due_date']]);fputcsv($out,[]);fputcsv($out,['Sales — Output VAT']);fputcsv($out,['Month','Website sales incl shipping','Shipping / non-taxable','Taxable Incl VAT','Output VAT','Taxable Excl VAT','Zero-rated source classification','Exempt / review source classification','Owner VAT adjustment','Invariant status']);foreach($s['months'] as $m)fputcsv($out,[$m['month'],$m['output_gross'],$m['output_shipping'],$m['output_inclusive'],$m['output_vat'],$m['output_exclusive'],$m['output_zero_rated'],$m['output_exempt'],$m['output_adjustment'],$m['output_reconciliation_status']]);fputcsv($out,[]);fputcsv($out,['Purchases — Input VAT']);fputcsv($out,['Month','Purchases Incl VAT','Input VAT','Purchases Excl VAT','Invariant status']);foreach($s['months'] as $m)fputcsv($out,[$m['month'],$m['input_inclusive'],$m['input_vat'],$m['input_exclusive'],$m['input_reconciliation_status']]);fputcsv($out,[]);fputcsv($out,['Eligible Import VAT',$s['import_vat']]);fputcsv($out,['Owner adjustments',$s['adjustments']]);fputcsv($out,['Final VAT position',$s['final_position']]);fclose($out);exit;}
 if($_SERVER['REQUEST_METHOD']==='POST'){
  vat_reconciliation_verify((string)($_POST['csrf']??''));$period=$payload['period'];$u=current_user();
  if($action==='eligibility'){$id=(int)($_POST['import_id']??0);$status=(string)($_POST['eligibility_status']??'pending_review');$allowed=['pending_review','eligible','excluded','needs_evidence','assigned_to_another_period'];if(!in_array($status,$allowed,true))throw new RuntimeException('Choose a valid Import VAT eligibility decision.');$reason=trim((string)($_POST['reason']??''));if($status!=='pending_review'&&$reason==='')throw new RuntimeException('Enter the reason for this Import VAT decision.');$q=db()->prepare('SELECT import_vat_amount FROM accounts_import_vat_liabilities WHERE id=? AND deleted_at IS NULL');$q->execute([$id]);$assessed=$q->fetchColumn();if($assessed===false)throw new RuntimeException('Import VAT record not found.');$amount=$status==='eligible'?round((float)($_POST['eligible_amount']??$assessed),2):0.0;if($amount<0||(float)$amount>(float)$assessed)throw new RuntimeException('Eligible Import VAT cannot exceed the assessed principal.');$evidence=(string)($_POST['evidence_status']??'evidence_present');$assigned=$status==='eligible'?(int)$period['id']:null;db()->prepare('INSERT INTO accounts_import_vat_credit_eligibility(import_id,eligibility_status,eligible_amount,evidence_status,assigned_period_id,decision_reason,decided_by,decided_by_name,decided_at)VALUES(?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE eligibility_status=VALUES(eligibility_status),eligible_amount=VALUES(eligible_amount),evidence_status=VALUES(evidence_status),assigned_period_id=VALUES(assigned_period_id),decision_reason=VALUES(decision_reason),decided_by=VALUES(decided_by),decided_by_name=VALUES(decided_by_name),decided_at=NOW()')->execute([$id,$status,$amount,$evidence,$assigned,$reason,(int)$u['id'],(string)$u['name']]);vat_reconciliation_audit((int)$period['id'],'import_eligibility',null,['import_id'=>$id,'status'=>$status,'eligible_amount'=>$amount,'reason'=>$reason]);vr_reply(['ok'=>true,'message'=>'Import VAT eligibility decision saved.','data'=>vat_reconciliation_payload($code)]);}
  if($action==='adjustment'){$direction=(string)($_POST['direction']??'increase');$amount=round((float)($_POST['amount']??0),2);$reason=trim((string)($_POST['reason']??''));if(!in_array($direction,['increase','decrease'],true)||$amount<=0||$reason==='')throw new RuntimeException('Enter an adjustment direction, amount and reason.');db()->prepare('INSERT INTO accounts_vat_reconciliation_adjustments(period_id,direction,amount,reason,note,created_by,created_by_name)VALUES(?,?,?,?,?,?,?)')->execute([(int)$period['id'],$direction,$amount,$reason,trim((string)($_POST['note']??'')),(int)$u['id'],(string)$u['name']]);vat_reconciliation_audit((int)$period['id'],'adjustment_created',null,['direction'=>$direction,'amount'=>$amount,'reason'=>$reason]);vr_reply(['ok'=>true,'message'=>'VAT reconciliation adjustment recorded.','data'=>vat_reconciliation_payload($code)]);}
  if($action==='ready'){$latest=vat_reconciliation_payload($code);if(!$latest['ready'])throw new RuntimeException('Complete all Output VAT, Input VAT and Import VAT source reviews before marking this return ready.');if($latest['snapshot'])vr_reply(['ok'=>true,'message'=>'This VAT return period is already frozen and ready to file.','data'=>$latest]);$s=$latest['sources'];db()->prepare('INSERT INTO accounts_vat_reconciliation_snapshots(period_id,source_hash,output_vat,input_vat,import_vat,adjustments,final_position,source_json,created_by,created_by_name)VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([(int)$period['id'],$latest['source_hash'],$s['output_vat'],$s['input_vat'],$s['import_vat'],$s['adjustments'],$s['final_position'],json_encode($s,JSON_UNESCAPED_SLASHES),(int)$u['id'],(string)$u['name']]);db()->prepare("UPDATE accounts_vat_return_periods SET status='ready_to_file' WHERE id=?")->execute([(int)$period['id']]);vat_reconciliation_audit((int)$period['id'],'snapshot_frozen',null,['source_hash'=>$latest['source_hash'],'final_position'=>$s['final_position']]);vr_reply(['ok'=>true,'message'=>'VAT return frozen — ready to file.','data'=>vat_reconciliation_payload($code)]);}
  if($action==='file'){$latest=vat_reconciliation_payload($code);if(!$latest['snapshot'])throw new RuntimeException('Mark this VAT return ready before recording filing.');$date=(string)($_POST['filed_date']??'');$reference=trim((string)($_POST['reference']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$reference==='')throw new RuntimeException('Enter the filing date and NamRA filing reference.');db()->prepare('INSERT INTO accounts_vat_reconciliation_filings(period_id,filed_date,filing_reference,note,created_by,created_by_name)VALUES(?,?,?,?,?,?)')->execute([(int)$period['id'],$date,$reference,trim((string)($_POST['note']??'')),(int)$u['id'],(string)$u['name']]);db()->prepare("UPDATE accounts_vat_return_periods SET status='filed' WHERE id=?")->execute([(int)$period['id']]);vat_reconciliation_audit((int)$period['id'],'return_filed',null,['date'=>$date,'reference'=>$reference]);vr_reply(['ok'=>true,'message'=>'VAT return filing recorded.','data'=>vat_reconciliation_payload($code)]);}
  if($action==='payment'){$latest=vat_reconciliation_payload($code);if(!$latest['filing'])throw new RuntimeException('Record the VAT return filing before adding a return payment.');$date=(string)($_POST['payment_date']??'');$amount=round((float)($_POST['amount']??0),2);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$amount<=0)throw new RuntimeException('Enter a valid payment date and amount.');db()->prepare('INSERT INTO accounts_vat_reconciliation_payments(period_id,payment_date,amount,reference,payment_method,note,created_by,created_by_name)VALUES(?,?,?,?,?,?,?,?)')->execute([(int)$period['id'],$date,$amount,trim((string)($_POST['reference']??'')),trim((string)($_POST['payment_method']??'')),trim((string)($_POST['note']??'')),(int)$u['id'],(string)$u['name']]);vat_reconciliation_audit((int)$period['id'],'return_payment',null,['date'=>$date,'amount'=>$amount]);vr_reply(['ok'=>true,'message'=>'VAT return payment recorded.','data'=>vat_reconciliation_payload($code)]);}
 }
 vr_reply(['ok'=>true,'data'=>$payload]);
}catch(Throwable$e){vr_reply(['ok'=>false,'message'=>$e->getMessage()],400);}
