<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/accounts-vat-reconciliation.php';vat_reconciliation_require_owner();vat_reconciliation_schema_ready();$pageTitle='VAT Reconciliation | '.APP_NAME;$activeApp='accounts';$extraStylesheets=[['path'=>'assets/css/accounts.css','version'=>(string)filemtime(BASE_PATH.'/assets/css/accounts.css')]];include BASE_PATH.'/shared/header.php';include BASE_PATH.'/shared/sidebar.php';
?>
<main class="workspace module accounts-page vat-reconciliation-page" id="inputVatPage" data-vat-reconciliation data-api="vat-reconciliation-api.php">
 <nav class="accounts-breadcrumb" aria-label="Breadcrumb"><a href="index.php">Accounts</a><span aria-hidden="true">&rsaquo;</span><strong>VAT Reconciliation</strong></nav>
 <header class="accounts-hero"><div class="accounts-hero-copy"><p class="eyebrow">Accounts application</p><h1>VAT Reconciliation</h1><p>Automatically combine Output VAT, Input VAT and eligible Import VAT into the final VAT return position.</p><p class="input-vat-active-period"><i data-lucide="calendar-days" aria-hidden="true"></i><span class="input-vat-active-period-label">Active VAT period</span><strong id="vrActivePeriod">Loading…</strong></p></div><div class="accounts-actions" data-portal-header-status-target><button type="button" class="portal-button portal-button--secondary" id="vrRefresh"><i data-lucide="refresh-cw" aria-hidden="true"></i><span>Refresh Sources</span></button><a class="portal-button portal-button--secondary" id="vrExport" href="#"><i data-lucide="download" aria-hidden="true"></i><span>Export</span></a><button type="button" class="portal-button portal-button--secondary" id="vrPrint"><i data-lucide="printer" aria-hidden="true"></i><span>Print</span></button></div></header>
 <section class="input-vat-month-workspace vr-period-workspace"><div class="input-vat-month-nav"><button type="button" class="input-vat-month-arrow" data-period-step="-2" aria-label="Previous VAT period"><i data-lucide="chevron-left" aria-hidden="true"></i></button><label class="input-vat-year-select"><span>Year</span><select id="vrYear" data-portal-custom-select data-portal-select-variant="input-vat" aria-label="VAT return year"></select></label><nav class="input-vat-month-tabs" id="vrPeriodTabs" aria-label="VAT return periods"></nav><button type="button" class="input-vat-month-arrow" data-period-step="2" aria-label="Next VAT period"><i data-lucide="chevron-right" aria-hidden="true"></i></button></div><div class="input-vat-month-status" id="vrPeriodStatus"></div></section>
 <div id="vrNotice" class="vr-notice" role="status" hidden></div><section id="vrContent" aria-live="polite"><p class="accounts-empty">Loading saved VAT sources…</p></section>
</main>
<script defer src="<?=BASE_URL?>/assets/js/vat-reconciliation.js?v=<?=filemtime(BASE_PATH.'/assets/js/vat-reconciliation.js')?>"></script>
<?php include BASE_PATH.'/shared/footer.php'; ?>
