<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/delivery/ReleaseFlags.php';
header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
if(!DELIVERY_ENABLED){http_response_code(503);exit('Delivery is not enabled.');}
require_once BASE_PATH.'/apps/operations/operations.php';require_login();
require_once BASE_PATH.'/shared/delivery/FrontSession.php';require_once BASE_PATH.'/shared/delivery/AccessGrants.php';
use Hambelela\Delivery\AccessGrants;
try{$actor=\Hambelela\Delivery\FrontSession::actor(db(),(int)(current_user()['id']??0));if($actor['role']!=='owner_admin')throw new DomainException();}catch(DomainException $e){http_response_code(403);exit('Owner access required.');}
$_SESSION['delivery_front_csrf']??=bin2hex(random_bytes(32));$message='';$selected=(int)($_POST['employee']??$_GET['employee']??0);
if($_SERVER['REQUEST_METHOD']==='POST')try{
    \Hambelela\Delivery\FrontSession::csrf((string)($_POST['csrf']??''));
    if(($_POST['verified']??'')!=='1')throw new DomainException('Confirm the recipient and access before saving.');
    AccessGrants::save(db(),$actor['id'],$selected,is_array($_POST['grants']??null)?$_POST['grants']:[],(string)($_POST['version']??''),(string)($_POST['reason']??''));$message='Delivery access updated. Staff role and other modules are unchanged.';
}catch(DomainException $e){$message=$e->getMessage();}catch(Throwable $e){http_response_code(503);$message='Access could not be updated. Reload before retrying.';}
$staff=db()->query("SELECT e.id,e.full_name,r.role_key FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id WHERE e.status='active' AND r.role_key NOT IN ('delivery_driver','owner_admin') ORDER BY e.full_name")->fetchAll(PDO::FETCH_ASSOC);
$grants=AccessGrants::current(db(),$selected);$valid=false;foreach($staff as $person)if((int)$person['id']===$selected)$valid=true;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Delivery access · Hambelela</title><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-core.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-core.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-controls.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-controls.css')?>"></head><body data-delivery-ui><main class="delivery-main"><header class="pagehead"><div><div class="eyebrow">OWNER · ACCESS CONTROL</div><h1>Delivery permissions</h1><p>Grant only the Delivery access this employee needs. Existing role permissions remain in place.</p></div><a class="secondary" href="drivers.php">Drivers and partners</a></header><p role="status"><?=htmlspecialchars($message,ENT_QUOTES)?></p><section class="card"><form method="get"><label>Staff member<select name="employee" required><option value="">Choose employee</option><?php foreach($staff as $person):?><option value="<?=(int)$person['id']?>" <?=(int)$person['id']===$selected?'selected':''?>><?=htmlspecialchars($person['full_name'].' · '.$person['role_key'],ENT_QUOTES)?></option><?php endforeach;?></select></label><button class="secondary">Review access</button></form></section><?php if($valid):?><section class="card"><h2>Additional Delivery access</h2><form method="post"><input type="hidden" name="employee" value="<?=$selected?>"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['delivery_front_csrf'],ENT_QUOTES)?>"><input type="hidden" name="version" value="<?=AccessGrants::version($grants)?>"><?php foreach(AccessGrants::ALLOWED as $key=>$label):?><label class="check"><input type="checkbox" name="grants[]" value="<?=$key?>" <?=in_array($key,$grants,true)?'checked':''?>><?=htmlspecialchars($label,ENT_QUOTES)?></label><?php endforeach;?><label>Approval reason<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label class="check"><input type="checkbox" name="verified" value="1" required>I verified this employee and approve the selected access.</label><button class="primary">Save Delivery permissions</button><p>Removing a selection revokes only this explicit grant, not access supplied by the employee's existing role.</p></form></section><?php endif;?></main></body></html>
