<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/delivery/ReleaseFlags.php';header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
if(DELIVERY_ENABLED!==true&&DELIVERY_SETUP_ENABLED!==true){http_response_code(503);exit('Delivery setup is not enabled.');}
require_once BASE_PATH.'/apps/operations/operations.php';require_login();require_once BASE_PATH.'/shared/delivery/FrontSession.php';
try{$actor=\Hambelela\Delivery\FrontSession::actor(db(),(int)(current_user()['id']??0));if($actor['role']!=='owner_admin')throw new DomainException();}catch(DomainException $e){http_response_code(403);exit('Owner access required.');}
$_SESSION['delivery_front_csrf']??=bin2hex(random_bytes(32));$message='';
if($_SERVER['REQUEST_METHOD']==='POST')try{
 \Hambelela\Delivery\FrontSession::csrf((string)($_POST['csrf']??''));$id=(int)($_POST['driver']??0);$reason=trim((string)($_POST['reason']??''));if(strlen($reason)<5||strlen($reason)>500||($_POST['action']??'')!=='disable')throw new DomainException('A reason is required.');
 db()->beginTransaction();$s=db()->prepare("SELECT e.id FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id WHERE e.id=? AND e.status='active' AND r.role_key='owner_admin' FOR UPDATE");$s->execute([$actor['id']]);if(!$s->fetchColumn())throw new DomainException('Owner access changed.');
 $s=db()->prepare("SELECT e.id FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id JOIN delivery_driver_profiles p ON p.employee_id=e.id WHERE e.id=? AND r.role_key='delivery_driver' FOR UPDATE");$s->execute([$id]);if(!$s->fetchColumn())throw new DomainException('Restricted Driver account required.');
 $s=db()->prepare("SELECT COUNT(*) FROM delivery_jobs WHERE driver_employee_id=? AND status NOT IN ('completed','cancelled')");$s->execute([$id]);if((int)$s->fetchColumn())throw new DomainException('Reassign or resolve active deliveries before disabling this Driver.');
 db()->prepare('UPDATE delivery_driver_credentials SET active=0,session_version=session_version+1 WHERE employee_id=?')->execute([$id]);db()->prepare('UPDATE delivery_driver_profiles SET active=0 WHERE employee_id=?')->execute([$id]);db()->prepare('INSERT INTO ops_security_events(event_type,employee_id,metadata_json) VALUES(?,?,?)')->execute(['delivery_driver_disabled',$actor['id'],json_encode(['driver_id'=>$id,'reason'=>$reason],JSON_THROW_ON_ERROR)]);db()->commit();$message='Driver access disabled and sessions revoked. HR employment details were not changed.';
}catch(DomainException $e){if(db()->inTransaction())db()->rollBack();$message=$e->getMessage();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();http_response_code(503);$message='Driver access could not be updated.';}
$drivers=db()->query('SELECT e.id,e.full_name,e.phone,p.active FROM delivery_driver_profiles p JOIN ops_employees e ON e.id=p.employee_id ORDER BY e.full_name')->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Driver management · Hambelela</title><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-core.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-core.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-controls.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-controls.css')?>"></head><body data-delivery-ui><main class="delivery-main"><header class="pagehead"><div><div class="eyebrow">OWNER · DELIVERY ACCESS</div><h1>Drivers</h1><p>Restricted Delivery access only. No salary or employment settings are changed here.</p></div><div class="actions"><a class="primary" href="driver-setup.php">Create / reset Driver</a><a class="secondary" href="partner-setup.php">Partner accounts</a><a class="secondary" href="partner-routing.php">Partner routing</a><a class="secondary" href="index.php">Delivery board</a></div></header><p role="status"><?=htmlspecialchars($message,ENT_QUOTES)?></p><div class="cards"><?php foreach($drivers as $d):?><article class="card"><div class="eyebrow">EMPLOYEE <?=(int)$d['id']?></div><h2><?=htmlspecialchars($d['full_name'],ENT_QUOTES)?></h2><p><?=htmlspecialchars((string)$d['phone'],ENT_QUOTES)?> · <?=(int)$d['active']?'Active':'Disabled'?></p><?php if((int)$d['active']):?><details><summary>Disable Driver access</summary><form method="post"><input name="csrf" type="hidden" value="<?=htmlspecialchars($_SESSION['delivery_front_csrf'],ENT_QUOTES)?>"><input name="action" type="hidden" value="disable"><input name="driver" type="hidden" value="<?=(int)$d['id']?>"><label>Reason<input name="reason" minlength="5" maxlength="500" required></label><button class="danger">Disable and revoke sessions</button></form></details><?php else:?><p>Use the verified account reset form to restore access.</p><?php endif;?></article><?php endforeach;?></div></main></body></html>
