<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/delivery/ReleaseFlags.php';
header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header("Content-Security-Policy: default-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");
if(DELIVERY_ENABLED!==true&&DELIVERY_SETUP_ENABLED!==true){http_response_code(503);exit('Delivery setup is not enabled.');}
if(empty($_SERVER['HTTPS'])||strtolower((string)$_SERVER['HTTPS'])==='off'){http_response_code(403);exit('Secure connection required.');}
require_once BASE_PATH.'/apps/operations/operations.php';require_login();require_once BASE_PATH.'/shared/delivery/FrontSession.php';require_once BASE_PATH.'/shared/delivery/PartnerProvisioning.php';
try{$actor=\Hambelela\Delivery\FrontSession::actor(db(),(int)(current_user()['id']??0));if($actor['role']!=='owner_admin')throw new DomainException();}catch(DomainException $e){http_response_code(403);exit('Owner access required.');}
$_SESSION['delivery_front_csrf']??=bin2hex(random_bytes(32));$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST')try{\Hambelela\Delivery\FrontSession::csrf((string)($_POST['csrf']??''));if(($_POST['verified']??'')!=='yes')throw new DomainException('Verify the partner identity and email ownership.');if(($_POST['secret']??'')!==($_POST['confirmation']??''))throw new DomainException('Secrets must match.');$r=(new \Hambelela\Delivery\PartnerProvisioning(db()))->save($actor['id'],$_POST,(string)($_POST['secret']??''));$message='Partner account saved. Partner ID: '.$r['partner_id'].'. User ID: '.$r['user_id'].'. Previous sessions revoked.';$_SESSION['delivery_front_csrf']=bin2hex(random_bytes(32));}catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){http_response_code(503);$error='Account could not be saved. No partial account was created.';error_log('Partner setup failed: '.get_class($e));}
function delivery_setup_value(string $key):string{return htmlspecialchars((string)($_POST[$key]??''),ENT_QUOTES);}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Partner access · Hambelela</title><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-core.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-core.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-controls.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-controls.css')?>"></head><body data-delivery-ui><main class="delivery-login"><div class="eyebrow">OWNER · PARTNER ACCESS</div><h1>Partner account</h1><p>Restricted to this user's own partner deliveries. This does not create an employee or staff login.</p><p role="status"><?=htmlspecialchars($message,ENT_QUOTES)?></p><p class="form-error" role="alert"><?=htmlspecialchars($error,ENT_QUOTES)?></p><form method="post" autocomplete="off"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['delivery_front_csrf'],ENT_QUOTES)?>"><label>Verified company<input name="company" maxlength="190" required value="<?=delivery_setup_value('company')?>"></label><label>Company code<input name="code" maxlength="30" pattern="[A-Za-z0-9-]{2,30}" required value="<?=delivery_setup_value('code')?>"></label><label>Verified contact name<input name="name" maxlength="190" required value="<?=delivery_setup_value('name')?>"></label><label>Verified email<input name="email" type="email" maxlength="190" required value="<?=delivery_setup_value('email')?>"></label><label>Existing Partner user ID (only for reset)<input name="user_id" type="number" min="1" value="<?=delivery_setup_value('user_id')?>"></label><label>New private secret<input name="secret" type="password" minlength="16" maxlength="72" autocomplete="new-password" required></label><label>Confirm secret<input name="confirmation" type="password" minlength="16" maxlength="72" autocomplete="new-password" required></label><label class="check"><input name="verified" type="checkbox" value="yes" required>I verified this person's identity and email ownership, and approve restricted Partner access.</label><button class="primary">Save Partner account</button></form><p>The Owner must enter and submit the private secret. Never send it in chat.</p><a class="secondary" href="index.php">Delivery workspace</a></main></body></html>
