<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/delivery/ReleaseFlags.php';
header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
if(DELIVERY_ENABLED!==true&&DELIVERY_SETUP_ENABLED!==true){http_response_code(503);exit('Delivery setup is not enabled.');}
require_once BASE_PATH.'/apps/operations/operations.php';require_login();require_once BASE_PATH.'/shared/delivery/FrontSession.php';require_once BASE_PATH.'/shared/delivery/PartnerRouting.php';
try{$actor=\Hambelela\Delivery\FrontSession::actor(db(),(int)(current_user()['id']??0));if($actor['role']!=='owner_admin')throw new DomainException();}catch(DomainException $e){http_response_code(403);exit('Owner access required.');}
$_SESSION['delivery_front_csrf']??=bin2hex(random_bytes(32));$message='';
if($_SERVER['REQUEST_METHOD']==='POST')try{\Hambelela\Delivery\FrontSession::csrf((string)($_POST['csrf']??''));\Hambelela\Delivery\PartnerRouting::save(db(),$actor['id'],(int)($_POST['partner']??0),(int)($_POST['driver']??0),(string)($_POST['reason']??''));$message='Routing saved. New requests will appear on the selected Driver’s queue. Existing assignments are unchanged.';}catch(DomainException $e){$message=$e->getMessage();}catch(Throwable $e){http_response_code(503);$message='Routing could not be saved.';}
$partners=db()->query('SELECT id,name FROM delivery_partners WHERE active=1 ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);
$drivers=db()->query("SELECT e.id,e.full_name FROM ops_employees e JOIN ops_roles r ON r.id=e.role_id JOIN delivery_driver_profiles p ON p.employee_id=e.id WHERE e.status='active' AND r.role_key='delivery_driver' AND p.active=1 ORDER BY e.full_name")->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Partner routing · Hambelela</title><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-core.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-core.css')?>"><link rel="stylesheet" href="<?=htmlspecialchars(BASE_URL,ENT_QUOTES)?>/assets/css/delivery-controls.css?v=<?=filemtime(BASE_PATH.'/assets/css/delivery-controls.css')?>"></head><body data-delivery-ui><main class="delivery-login"><div class="eyebrow">OWNER · DELIVERY ROUTING</div><h1>Partner Driver</h1><p>Explicitly choose the verified Driver for new partner requests. No name-based or automatic employee matching is used.</p><p role="status"><?=htmlspecialchars($message,ENT_QUOTES)?></p><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['delivery_front_csrf'],ENT_QUOTES)?>"><label>Partner<select name="partner" required><option value="">Choose partner</option><?php foreach($partners as $p):?><option value="<?=(int)$p['id']?>"><?=htmlspecialchars($p['name'],ENT_QUOTES)?> · Driver ID <?=\Hambelela\Delivery\PartnerRouting::driver(db(),(int)$p['id'])?:'not configured'?></option><?php endforeach;?></select></label><label>Verified Driver<select name="driver" required><option value="">Choose Driver</option><?php foreach($drivers as $d):?><option value="<?=(int)$d['id']?>"><?=htmlspecialchars($d['full_name'],ENT_QUOTES)?> · <?=(int)$d['id']?></option><?php endforeach;?></select></label><label>Verification / change reason<input name="reason" minlength="5" maxlength="500" required></label><button class="primary">Save routing</button></form><div class="actions"><a class="secondary" href="partner-setup.php">Partner accounts</a><a class="secondary" href="driver-setup.php">Driver accounts</a><a class="secondary" href="index.php">Delivery workspace</a></div></main></body></html>
