<?php
declare(strict_types=1);require_once dirname(__DIR__,2).'/config.php';require_once BASE_PATH.'/shared/delivery/ReleaseFlags.php';
if(!defined('DELIVERY_ENABLED')||DELIVERY_ENABLED!==true){http_response_code(503);exit('Delivery is not enabled.');}
require_once BASE_PATH.'/apps/operations/operations.php';require_login();require_once BASE_PATH.'/shared/delivery/FrontSession.php';require_once BASE_PATH.'/shared/delivery/PartnerAccess.php';
header('Cache-Control: no-store');header('Referrer-Policy: no-referrer');$message='';$setupLink=null;
try{
 $actor=\Hambelela\Delivery\FrontSession::actor(db(),(int)(current_user()['id']??0));$access=new \Hambelela\Delivery\PartnerAccess(db());$access->owner($actor);$access->install();
 $_SESSION['delivery_front_csrf']??=bin2hex(random_bytes(32));
 if($_SERVER['REQUEST_METHOD']==='POST'){
  \Hambelela\Delivery\FrontSession::csrf((string)($_POST['csrf']??''));$result=$access->manage($actor,$_POST);$message='Account updated. Previous sessions revoked.';
  if($result['token'])$setupLink=BASE_URL.'/apps/delivery/partner/password.php#'.$result['token'];
 }
 $accounts=$access->accounts($actor);
}catch(DomainException $e){$message=$e->getMessage();if(!isset($actor)||($actor['role']??'')!=='owner_admin'){http_response_code(403);exit('Owner access required.');}$accounts=isset($access)?$access->accounts($actor):[];}catch(Throwable $e){http_response_code(503);exit('Delivery settings are temporarily unavailable.');}
function ps_escape($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ps_csrf():void{echo '<input type="hidden" name="csrf" value="'.ps_escape($_SESSION['delivery_front_csrf']).'">';}
function ps_permissions(array $a=[]):void{
 ?><label>Role<select name="role"><option value="partner_staff" <?=($a['role_key']??'')==='partner_staff'?'selected':''?>>Tedlaser Staff</option><option value="partner_admin" <?=($a['role_key']??'partner_admin')==='partner_admin'?'selected':''?>>Tedlaser Administrator</option></select></label><?php
 foreach(['create'=>'Create deliveries','edit'=>'Edit instructions before dispatch','driver'=>'View Tedlaser Driver progress (Administrator only)','accounting'=>'View Tedlaser accounting (Administrator only)'] as $key=>$label){?><label class="check"><input type="checkbox" name="can_<?=$key?>" value="1" <?=!empty($a['can_'.$key])||!$a?'checked':''?>><?=ps_escape($label)?></label><?php }
}
require_once BASE_PATH.'/shared/delivery/PortalShell.php';\Hambelela\Delivery\PortalShell::begin(true);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Delivery Settings</title></head><body data-delivery-ui><main class="delivery-main"><header class="pagehead"><div><div class="eyebrow">OWNER · DELIVERY</div><h1>Delivery Settings</h1><p>Manage delivery accounts, partner access, drivers and system preferences.</p></div><a class="secondary" href="index.php">Delivery workspace</a></header><p role="status"><?=ps_escape($message)?></p>
<?php if($setupLink):?><section class="panel"><h2>Password setup link</h2><p>Give this one-time link directly to the account holder. It expires in 60 minutes. No password has been sent or displayed.</p><a href="<?=ps_escape($setupLink)?>">Open secure password setup</a><label>Copy setup link<input readonly value="<?=ps_escape($setupLink)?>"></label></section><?php endif;?>
<section class="panel"><h2>Partner Accounts</h2><p>Tedlaser staff see their own jobs. Administrators can access only Tedlaser data. Permission changes revoke active sessions.</p><details><summary>Create Account</summary><form method="post"><?php ps_csrf();?><input type="hidden" name="action" value="create"><label>Name<input name="name" maxlength="190" required></label><label>Email<input name="email" type="email" maxlength="190" required></label><?php ps_permissions();?><button class="primary">Create account and setup link</button></form></details>
<div class="cards"><?php foreach($accounts as $a):?><article class="card"><h3><?=ps_escape($a['display_name'])?></h3><p><?=ps_escape($a['email'])?></p><p><?=$a['role_key']==='partner_admin'?'Tedlaser Administrator':'Tedlaser Staff'?> · <?=(int)$a['active']?'Active':'Inactive'?></p><p>Last login (UTC): <?=ps_escape($a['last_login_at']?:'Not recorded')?></p><form method="post" class="actions"><?php ps_csrf();?><input type="hidden" name="id" value="<?=(int)$a['id']?>"><button class="secondary" name="action" value="<?=(int)$a['active']?'deactivate':'activate'?>"><?=(int)$a['active']?'Deactivate':'Activate'?></button><button class="secondary" name="action" value="reset">Reset Password</button><button class="secondary" name="action" value="revoke">Revoke Sessions</button></form><details><summary>Edit Permissions</summary><form method="post"><?php ps_csrf();?><input type="hidden" name="action" value="permissions"><input type="hidden" name="id" value="<?=(int)$a['id']?>"><?php ps_permissions($a);?><button class="primary">Save permissions</button></form></details></article><?php endforeach;?></div></section>
<section class="panel"><h2>Driver &amp; Device Settings</h2><div class="actions"><a class="secondary" href="drivers.php">Driver accounts and sessions</a><a class="secondary" href="partner-routing.php">Partner Driver routing</a></div><p>Driver devices continue to use the existing Driver workspace and installation controls.</p></section><section class="panel"><h2>Delivery Preferences</h2><div class="actions"><a class="secondary" href="pricing.php">Delivery Pricing</a><a class="secondary" href="access.php">Delivery access controls</a></div><p>Tracking and delivery notifications continue to use the current configuration.</p></section></main></body></html>
